### ISSUE TITLE
Stove Dissapearing

### ISSUE THREAD

**Issue by OrangeJuiceWSalt** [Uuvana-Studios/longvinter-windows-client#1000]
When I Enter My House Wether its Upgraded or not . after i place my stove first time it doesnot dissapear but when i leave my houst and enter again it disappears

**Comment by OrangeJuiceWSalt** [comment]
![image](https://user-images.githubusercontent.com/104396033/177057638-67b752ee-04cf-4fe8-b966-d55e939ee754.png)
![image](https://user-images.githubusercontent.com/104396033/177057644-11b9b7c3-24c5-448f-8d9c-134a007206d9.png)

**Comment by faketucker** [comment]
Duplicate of #978
