### ISSUE TITLE
Dedicated server issue with port mappings

### ISSUE THREAD

**Issue by lymem** [Uuvana-Studios/longvinter-windows-client#1002]
I run a number of different servers on the same windows server instance, and as such using the default steam ports is problematic. However, I was pointed in the direction of https://forum.uuvana.com/d/53-run-2-servers-behind-same-public-ip to use different ports.
But:
Using the command line:
>LongvinterServer.exe -log -Port=8100 -QueryPort=8150
Results in the server log saying:  
>LogNet: Created socket for bind address: 0.0.0.0 on port 8100
>LogNet: GameNetDriver EOSNetDriver_2147482475 IpNetDriver listening on port 8100
as well as:
>LogEOS: Verbose: [LogEOSP2P] Using Port Range 7777-7876 for P2P traffic
>LogNet: Created socket for bind address: 0.0.0.0 on port 7787

The server will show on the server browser, however using the lan entry will not connect. Entering the direct connection information, with the specified port, does work.

**Comment by faketucker** [comment]
As the log said, you have to use a port in the range of 7777-7876.

**Comment by lymem** [comment]
The thing is, you don't have to use a port in that range. The game works fine using different port ranges, the log and multiplayer connection gui are incorrect.

**Comment by faketucker** [comment]
You can join servers with any port through the server browser, but in LAN, you have to use the direct connect tab and use the local IP. Server browser will not work
