### ISSUE TITLE
New* colored Items losing tint when moving

### ISSUE THREAD

**Issue by orloko** [Uuvana-Studios/longvinter-windows-client#1004]
**Describe the bug**
Picking up an item(colored) that was place down will remove its color.

**To Reproduce**
1. Get any* new colored item
2. Place it down
3. Pick it up
4. Now you have the default item (default color/no tint)

**Expected behavior**
Be able to place it down/pick it up and be the same item (maintain color)

*only tested the `Decorated Round Table`

**Comment by faketucker** [comment]
Seems to only happen with 181: Decorated Round Table (Juniper)

**Comment by Jalsson** [comment]
This was still an issue but should be fixed in 1.0.9c version
