### ISSUE TITLE
Cabinnets with stuff dissapeared from house

### ISSUE THREAD

**Issue by TehMerk** [Uuvana-Studios/longvinter-windows-client#1006]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Current hotfix update have caused some issues when loading the data from server files. Devs are working on a fix to solve the problem and servers will be back up once it's fixed.
