### ISSUE TITLE
unable to place tent anywhere on main island, server number 5

### ISSUE THREAD

**Issue by reportabug121** [Uuvana-Studios/longvinter-windows-client#101]
**Describe the bug**
unable to place tent, lost all will to play

**To Reproduce**
try to place tent

**Expected behavior**
place tent

**Screenshots**

**Desktop (please complete the following information):**
windows 10
**Additional context**
I can place on beaches but not the island, there seems to be plenty of space and I played the past few days with no issues, but on a new character on server 5 it says im either too close to players or monuments even if I am not...if the mainland is full I don't think the map is nearly big enough if it filled in 2 days...

**Comment by sirNugg3ts** [comment]
Server 5 US or EU ?

**Comment by RangoStudio** [comment]
I have the same issue with Server 2 EU.

![Screenshot 2022-03-02 004634](https://user-images.githubusercontent.com/100734206/156267934-1835e098-a110-45c5-8e03-244b872f6a3f.png)

Picture shows a great area for a tent but can't seem to place it. This is by the way over the whole map, I've tried everywhere.

**Comment by Jalsson** [comment]
The collision box for the tent was way bigger than the visible tent model. I resized this and update should be soon in experimental branch of the game
