### ISSUE TITLE
Chest Bug

### ISSUE THREAD

**Issue by shckwve2g** [Uuvana-Studios/longvinter-windows-client#1011]
The Server started to lag and after the crash all chest are gone.
EU WEST Server 2

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #1006
