### ISSUE TITLE
Teleportation bug?

### ISSUE THREAD

**Issue by JayskieJ** [Uuvana-Studios/longvinter-windows-client#1016]
**Describe the bug**
I need to preface with I am brand new and this happened the first time I launched into a server.
I entered a shed looking building slightly northwest of Filemon outpost and upon entering I briefly saw the interior and the other interiors around the shed, and very shortly after I was teleported to Sgt.Lake outpost without fulfilling the steps of the starter quest.

**To Reproduce**
I only suspect this to be a bug as I died after meeting a helpful player around the Sgt.Lake region and I died. I went back to the shed because I thought that was a intended occurence but I cannot reproduce and after spending some time playing concluded that it was a bug.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.8
 - Steam Version v020

**Comment by faketucker** [comment]
The server may have a high ping, which causes issues when loading things, so it assumed you were in the void and teleported you to safe zones. I believe this is the problem with the ping, not the game itself, so it might have no way to prevent this.
