### ISSUE TITLE
Get Shot in Safe Zone

### ISSUE THREAD

**Issue by SalzigerLauch** [Uuvana-Studios/longvinter-windows-client#1019]
I think I found a bug on the Eu-West Uuvana 2 server. If you are in a safe place in the PVP area, enemies can shoot at you by building up and they will not be shot at from the Turrets. It’s really annoying when you’re sitting there and someone is shooting at you

**Comment by faketucker** [comment]
This is not a bug. If you have suggestions, make them on our [Discord](discord.gg/longvinter).
