### ISSUE TITLE
Gun is not able to shoot

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#102]
**Describe the bug**
Sometimes when you walk from the snow to the grass, your gun won't be able to shoot and you have to walk back to the snow so the gun will work properly. Same as when you walk from the grass to the snow. Happened to me many times.

**To Reproduce**
1. try to shoot in the snow zone and then walk to the grass and shoot again

**Expected behavior**
Gun will work properly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by KoalaBoy** [comment]
Maybe it's because the bush or flowers I ran into so it makes the gun not able to shoot

**Comment by Jalsson** [comment]
This was caused by a flower collision on your character, Next update you can shoot through flowers :)
