### ISSUE TITLE
MY BASE IS GONE!

### ISSUE THREAD

**Issue by HelloKashi** [Uuvana-Studios/longvinter-windows-client#1021]
I have been joining the Uuvana 5 server for the longest time and had my base set up PERFECTLY outside of the Filemons  Outpost and now it is all GONE!!!! I am so saddened by this and just want all my loot and my house bacl, I really do not want to start over :( If it was due to being so close to the common area, I can understand that but why even allow us to build there in the first place????. I at least want all my stuff back....HELP

**Comment by faketucker** [comment]
The game is in early access and things can be changed with every update, and we can't bring your stuff back.
