### ISSUE TITLE
Freeze screen in high-fence areas bug

### ISSUE THREAD

**Issue by sgnoodles** [Uuvana-Studios/longvinter-windows-client#1023]
**Describe the bug**
Screen freezing bug

**To Reproduce**
After the recent hotfix, there is a bug where the screen stops when you go to places with many fences.

**Expected behavior**
Freeze screen in high-fence areas

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.8
 - Steam Version 1654574690

**Comment by faketucker** [comment]
It might happen for the same reason as #1036
