### ISSUE TITLE
Duplication Glitch - Equipment

### ISSUE THREAD

**Issue by Cyndergate** [Uuvana-Studios/longvinter-windows-client#1025]
Issue: 
Equipment duplicates if you drop all items during high ping/high turret fire amounts.

Replication:
- High Turret Fire [Atleast 2 Turrets]
- Drop All Items
- Pick Items Back Up
- You can use your equipment, equipment tab is empty, all equipment is in inventory like normal

Possible Causes:
High Ping?

**Comment by Cyndergate** [comment]
This glitch causes your entire inventory to wipe after you relog, apparently.

I relogged in, entire inventory.. empty. I didn't die. I was right where I was.

**Comment by faketucker** [comment]
Duplicate of #961
