### ISSUE TITLE
Can't enter house

### ISSUE THREAD

**Issue by Robin5098** [Uuvana-Studios/longvinter-windows-client#1026]
**Describe the bug**
Hello. I can't enter my house. Please help. I'm on Uuvana 5. I have two houses. One i can enter. one i cannot. Player name Robin5098.

**To Reproduce**
Click on door...

**Expected behavior**
To enter my house

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Game Version [e.g. 1.0] Everything up to date
 - Steam Version [e.g. 1.0] Everything up to date

**Additional context**
Please fix this so i can get into my house.

**Comment by faketucker** [comment]
Do you have things that block your doorway inside the house?

**Comment by Robin5098** [comment]
I might have moved something to the middle of the room the last time i was there. Still.... i can't get in to move it....

**Comment by faketucker** [comment]
Answered in the ticket
