### ISSUE TITLE
Not allowed to click on backpack 

### ISSUE THREAD

**Issue by Agacuate** [Uuvana-Studios/longvinter-windows-client#1027]
I died because of the cold, but died almost behind a house and now that I returned I am not able to click on the backpack to retrieve my loot.
![image](https://user-images.githubusercontent.com/108849479/177682226-47c65068-ba6f-4469-bb77-43b634da1ace.png)
![image](https://user-images.githubusercontent.com/108849479/177682308-dfd66161-e7f1-44ae-9958-027943a45527.png)

**Comment by faketucker** [comment]
Use spacebar
