### ISSUE TITLE
Can't chop down trees in PVE servers

### ISSUE THREAD

**Issue by Hexae** [Uuvana-Studios/longvinter-windows-client#103]
**Describe the bug**
On a PVE server, it's no possible to chop down a tree.

**To Reproduce**
1. Go to Game.ini
2. Add PVP=false
3. Restart

**Expected behavior**
Trees should be able to be chopped down just like PVP servers

**Screenshots**
(https://i.imgur.com/uTJ9YZm.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**
Nope

**Comment by sirNugg3ts** [comment]
Fixed on the latest update
