### ISSUE TITLE
Quest Problem

### ISSUE THREAD

**Issue by guneyarslan** [Uuvana-Studios/longvinter-windows-client#1035]
It does not accept the transactions made before the task arrives when the task is new. For example; Before the "Things are getting serious" task, I put the workbench and upgraded the house. But now it does not accept the task as done. It wants me to do it again. So it would be good if a control mechanism came to it. And as soon as possible.

**Comment by faketucker** [comment]
The point of the quest is to help people get started when it's their first time on the server. That's why it requires you to do it after you get the quest.

**Comment by guneyarslan** [comment]
Yeah but still there is issue on quests. For instance i finished "Advanced Farming" quest (or something like that) but i can't get the reward. And it still showed on quest menu. Also even if you have this quest it still show on vendor quest menu with green accept button. I'm just saying there is a problem about that.
