### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by camarena4** [Uuvana-Studios/longvinter-windows-client#1036]
every so often my game crashes and uses 99% of the RAM 💀  Played on [EU-WEST] Uuvana 1
![Captura de pantalla 2022-07-08 010732](https://user-images.githubusercontent.com/108935541/177988706-7c1635de-2df5-4d19-8ba2-2771c68d6fb0.png)

**Comment by faketucker** [comment]
There have been reports of memory leaks, devs are working on this issue

**Comment by Jalsson** [comment]
This issue was caused by creating too many UI elements. Fixed by creating them only when needed
