### ISSUE TITLE
with RTX 2060 the game uses 93% of the graphics?!

### ISSUE THREAD

**Issue by camarena4** [Uuvana-Studios/longvinter-windows-client#1037]
![Captura de pantalla 2022-07-08 005527](https://user-images.githubusercontent.com/108935541/177989389-36bc6da4-1d68-4b9c-bc56-256e1341bbe0.png)

It is not just a sporadic moment, the use of graphics is continuous.

**Comment by Th4tM4t** [comment]
that most likely isn't a bug, and the game is made with Unreal engine

**Comment by gmbrothers** [comment]
Try turning it off from unlimited FPS to 60 FPS. That should significantly decrease graphics usage @camarena4
