### ISSUE TITLE
my weather station was destroyed with barriers around

### ISSUE THREAD

**Issue by ot21** [Uuvana-Studios/longvinter-windows-client#1039]
**Describe the bug**
my weather station was destroyed with barriers around but my barrier and generator have not been destroyed

**Expected behavior**
would it be possible to shoot at the weather stations through the barriers?

**Screenshots**
![image](https://user-images.githubusercontent.com/93005949/177998704-2324b63d-de1d-46e0-a10b-cc474d13652d.png)

**Desktop (please complete the following information):**
 - OS: window 10
 - Game Version 1.0.8

**Additional context**
there is no entry possible at my base, people just shoot at it

**Comment by faketucker** [comment]
People can stand on a makeshift bench and shoot the weather station

**Comment by ot21** [comment]
how to prevent this from happening again?

**Comment by ducbenho** [comment]
Build higher fences
