### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Liko195** [Uuvana-Studios/longvinter-windows-client#1041]
The game has crashed me with a turret kit in my inventoryand when i went back in i didn´t have it anymore and neither did the money i spent on it.
I have also lost all the progress of my book of discoveries, how i can get it back please?

The turret was transformed into a tent and the telescopic fishing i was equipped with became a normal fishing rod

All my missions have also been restarted and the game has returned from 0 after several days playing, everithing has been restarted and i have lost all my money and the turret that i bought and disappeared when the game crashed.
Please help

**Comment by Liko195** [comment]
All my missions have also been restarted and the game has returned from 0 after several days playing, everithing has been restarted and i have lost all my money and the turret that i bought and disappeared when the game crashed.
Please help

**Comment by Liko195** [comment]
The turret was transformed into a tent and the telescopic fishing i was equipped with became a normal fishing rod

**Comment by faketucker** [comment]
Your save files may become corrupt as a result of the game crash. There is nothing we can do to restore your progress.
