### ISSUE TITLE
Visual Water Glitch

### ISSUE THREAD

**Issue by burritothecat** [Uuvana-Studios/longvinter-windows-client#1044]
When I downloaded the game, instead of the water having the correct texture and seeing the little fishing circles, I only have this flat white texture. I can still fish (although I have to spam-click to find fishing spots), but the water remains like this at all times. I tried deleting and reinstalling the game, no dice. This is the same if I create my own server or if I am in one of the public servers. No idea if this is repeatable, a friend of mine with the same OS and game version has no problems with the water. Makes the game pretty unplayable because I can't get the cash you need in the early game to get started :(

![20220708220834_1](https://user-images.githubusercontent.com/28199112/178093210-3191f01b-b140-4010-9fbd-4b9f42d318b1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.8
 - Steam Version: Whatever the most recent steam version is as of 7/8/22

**Comment by faketucker** [comment]
Toggle DX11 water in the setting
