### ISSUE TITLE
character stuck1

### ISSUE THREAD

**Issue by lydria09** [Uuvana-Studios/longvinter-windows-client#1045]
my character on Eu-West Uuvana 2 is stuck between some rocks and boulders wedged up against a fence not far from the warehouse
![image_2022-07-09_140852533](https://user-images.githubusercontent.com/108985611/178107135-b3969486-1b78-454e-901b-86f144d1146b.png)

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt +F4 but you stuff will drop
