### ISSUE TITLE
A bug that stops the game too often after fixing the bug where the old cabinet diappears players are having a hard time because of this bug i'm korean so i' not good at english thank you.

### ISSUE THREAD

**Issue by ipeepeewhilepoopoo** [Uuvana-Studios/longvinter-windows-client#1047]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #1046
