### ISSUE TITLE
Item Interacting Bug

### ISSUE THREAD

**Issue by ljl2480** [Uuvana-Studios/longvinter-windows-client#105]
**Describe the bug**
Item interacting bug : When i RMB Item, the game go back to lobby.

**Desktop (please complete the following information):**
 - OS Window 10

**Comment by JustDalek** [comment]
Are you on a private server, if so the admin needs to update it #95

**Comment by ljl2480** [comment]
The bug happen at "KR Longvinter sever".

**Comment by sirNugg3ts** [comment]
Server is not updated
