### ISSUE TITLE
Stuck in a 1 by 1 with trees all around

### ISSUE THREAD

**Issue by Simpimpin** [Uuvana-Studios/longvinter-windows-client#1050]
**Describe the bug**
The bug is that i cannont escape this prison that I am in due to the fact i jumped off a ramp chasing a peacock and landed in a 1 by 1 with trees keeping me in. That wouldn't be so bad if I could let myself die but I cannot because i get down to 1 stamina bar and I can't move around enough to generate the energy to die.

![stuck](https://user-images.githubusercontent.com/109005904/178126900-7e24e6f4-011c-4a28-81fc-9054b603c723.png)

 - OS: Windows 10
 - Game Version [e.g. 1.08]
 - Steam Version [e.g. 1.08]

**Comment by RedacheX** [comment]
press Alt+K

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt + K
