### ISSUE TITLE
Cannot click or have to click above buttons

### ISSUE THREAD

**Issue by BritSours18** [Uuvana-Studios/longvinter-windows-client#1051]
**Describe the bug**
I went AFK for a moment and when I came back I couldn't click anything in my inventory etc. Closed out game and it was happening when I came back in except on the home screen I had to click above to click the button (exp in order to click options I had to click the report a bug) Also I couldn't change any game options.

**Expected behavior**
I expect to be able to click the buttons when trying to play i guess

**Desktop (please complete the following information):**
 - OS:Windows 11
  - Game Version 1.0.8
 - Steam Version not sure

**Comment by faketucker** [comment]
Try changing the game resolution

**Comment by faketucker** [comment]
Maybe try Shift + Enter to exit the full screen mode and change the settings

**Comment by Jalsson** [comment]
If this happens to you again you can reset the game settings by going to _username_/AppData/Local and deleting the Longvinter folder
