### ISSUE TITLE
Fences and Turrets are useless

### ISSUE THREAD

**Issue by guneyarslan** [Uuvana-Studios/longvinter-windows-client#1052]
**Describe the bug**
Actually, I don't know if this is a bug. But I can say that it makes the game unplayable. As you can see from the picture, when something high is placed on the outside of the fence, it is entered from there and, worse, fired from there. When fired, they can hit the turret, and of course you, as it has more range than the turret. We put hundreds of fences side by side, now we need to put hundreds on top of it. I just don't want to cut trees for 10 hours.

**To Reproduce**
1. Put a material that you can climb on your fence.
2. Shoot from there.
3. Get in there.
4. Watch how they kill you hundred times.

**Expected behavior**
1- Turrets should be improved.
2- There must be some protection after death, so as not to die again. During this time, we should be able to shoot, but even if they shoot at us, our energy should not decrease.
3- The defense has no advantage, on the contrary, it is at a disadvantage. Therefore, bullets should pass from the inside to the outside of the fence, but not from the outside to the inside. Or turrets bullet has 100% chance to penetrate fences, players' weapons 30%.
4- Right now as people find out about it, many more players will do it. People will not be able to leave their belongings in the garden of their homes.

**Screenshots**
https://prnt.sc/07krWpbzhclS

**Desktop (please complete the following information):**
 - OS: [Windows 11 - insider]
 - Game Version [1.0.8]
 - Steam Version [last one]

**Additional context**
I think it is an important problem and should be solved before the wipe on 17.07.2022. Thank you for everything in advance.

**Comment by ducbenho** [comment]
Just build better defense. What you are asking for is literally "god mode" for defenders. And I don't even like PVP lol!

**Comment by faketucker** [comment]
This is not a bug. People can palce something to climb over fences. That's why you have to use turrets to protect your stuff.

> 1- Turrets should be improved.
> 2- There must be some protection after death, so as not to die again. During this time, we should be able to shoot, but even if they shoot at us, our energy should not decrease.

Devs are already working to find a solution to prevent spawn campers

> 3- The defense has no advantage, on the contrary, it is at a disadvantage. Therefore, bullets should pass from the inside to the outside of the fence, but not from the outside to the inside. Or turrets bullet has 100% chance to penetrate fences, players' weapons 30%.

You can choose to build fences further inside and leave some space inside the house area for turrets.

> 4- Right now as people find out about it, many more players will do it. People will not be able to leave their belongings in the garden of their homes.

The game is PvP and raiding is the point of PvP, so deal with it.

**Comment by guneyarslan** [comment]
> Just build better defense.
It is not possible always. When they find out where your house is, they camp there. They are much more powerful than you and you cannot do anything. You have no choice but to exit the game. It might have PVP protection, at least until it gets to the level of self-defense. It is not fair.

> Devs are already working to find a solution to prevent spawn campers
Yes, that's great that they are working because that's the main problem. It makes the game unplayable. Again, you have no choice but to exit the game. You don't stand a chance when they're two people and you're alone.

> You can choose to build fences further inside and leave some space inside the house area for turrets.
Thank you for that, i didn't know that. And also i don't think many players are knowing that. This game really need a in-game wiki.

> The game is PvP and raiding is the point of PvP, so deal with it.
You are telling a lamb to deal with a lion. You should at least wait for me to turn into a buffalo to deal with it.

Thank you for your all answers.
