### ISSUE TITLE
Lack of privileges

### ISSUE THREAD

**Issue by wamedoarg** [Uuvana-Studios/longvinter-windows-client#1053]
**Describe the bug**
I enter the game for the first time and it gives me this error. Any solution?

**Screenshots**
![long](https://user-images.githubusercontent.com/109087282/178281549-d4e6b5b2-aa43-4426-b391-25fef9065f07.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.8

 - Steam Version v020

**Comment by faketucker** [comment]
Try to run the game as administrator

**Comment by wamedoarg** [comment]
It's the first thing I did when I read the error

**Comment by Liamtay10** [comment]
I am also having the same problem and can't seem to find any solution that works

**Comment by Liamtay10** [comment]
hey so i fiixed the problem its to do with your easy anti cheat. go into another game eith easy anti cheat go into the files go to easy anti cheat and run the file uninstaill it and then re instail it and should fix your problem

**Comment by faketucker** [comment]
You can run the manual install/uninstall script from the game install folder.
![image](https://user-images.githubusercontent.com/28383557/179386522-08b16241-9deb-4682-8545-20743aa26885.png)
