### ISSUE TITLE
The sea looks like white milk

### ISSUE THREAD

**Issue by koreaspinach** [Uuvana-Studios/longvinter-windows-client#1055]
![20220711210515_1](https://user-images.githubusercontent.com/109126235/178407305-b37ffc86-cf59-4fea-99c9-8ccec8bef713.jpg)

It's hard to fish because you can't see the fishing point.

The video settings do not change.

Please help me

**Comment by ducbenho** [comment]
Did you try Toggle DX11 water?

**Comment by faketucker** [comment]
Toggle DX11 water in the settings. If it doesn't work, try following these [steps](https://github.com/Uuvana-Studios/longvinter-windows-client/issues/13#issuecomment-1056012887)

**Comment by koreaspinach** [comment]
Oh, I've been looking for it for a long time, and it's in the bottom right corner of the video setup Thank you. I can finally fish
