### ISSUE TITLE
WHEN I HAVE TWO HOUSES,I HAVE TO USE PASSWORD TO GO IN MY FIRST HOUSE.AND I DO NOT KNOW MY FIRST HOUSE'PASSWORD,SO I CANNOT GO IN MY HOUSE THAT I MADE

### ISSUE THREAD

**Issue by FAGUYGF** [Uuvana-Studios/longvinter-windows-client#1056]

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
