### ISSUE TITLE
Cannot Access Admin Panel

### ISSUE THREAD

**Issue by Mjsmokin24** [Uuvana-Studios/longvinter-windows-client#1059]
Cannot seem to access Admin Panel. I created & got a unoffical server by rockyservers earlier today, & I added my steam ID, & still Admin Panel not working. Also- before I bought into hosting server I- tried the host server tab next to find servers & I cannot seem to find or delete that hosted one I made before I bought into Rockyservers. Please help, thank you.

**Comment by faketucker** [comment]
Use your EOS ID that you can find in the settings
