### ISSUE TITLE
HACKERS with infinite health!!

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#106]
**Describe the bug**
So all day on the US 2 server, hackers have been raiding the big town, SGT whatever its called, and shooting everyone, the turrets AND people have not been able to kill them despite them taking damage constantly. Its become apparent these guys are hacking as i witnessed over 200 damage done to one person who stood there and let the turret hit him.

**To Reproduce**
Cant reproduce, they are hacking somehow.

SEE TOP RIGHT OF SCREEN SHOT - Multiple stacks of 30+ damage to one guy, best i could get sorry.

**Expected behavior**
Expect them to die when theyre hit by 2 turrets for 30 seconds and players with shotguns.. instead they wipe out 10+ players

**Screenshots**
![image](https://user-images.githubusercontent.com/100509746/156113956-89ae3b72-8fe9-4c56-957a-8956052bd842.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 1.0.0
 - 
**Additional context**
Not sure on the player names but thought i should advise this is happening - i cant get close enough or get them to wave for a name.. sorry.

**Comment by ItsKiwi88** [comment]
And for context, im on the southern side of the river below this main base/town and theyre at the entranceway where the turret is shooting them.

**Comment by sirNugg3ts** [comment]
This is not a bug. That's hacking and we are aware of this and are working on anti-cheats. Please do not file bug report when you are not reporting a bug
