### ISSUE TITLE
home spon pot

### ISSUE THREAD

**Issue by jhoya0703** [Uuvana-Studios/longvinter-windows-client#1060]
**Describe the bug**

**To Reproduce**
1. Go to '...' 나는 집에 가고 싶습니다 하지만 집에 들어가면 다시 밖으로 나와집니다. 아마 그위치에 난로가 있어서 그런 것 같습니다
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
![image](https://user-images.githubusercontent.com/109351510/179213165-a7864c9f-dd9a-4e6d-9981-b0d7848edf0c.png)
![image](https://user-images.githubusercontent.com/109351510/179213210-83691eec-f602-4b58-a9ac-80190018f1ca.png)
![image](https://user-images.githubusercontent.com/109351510/179213243-7cc2b35c-b26a-432c-97cf-98c8e14eec83.png)
![image](https://user-images.githubusercontent.com/109351510/179213264-4f5ab32c-074d-4d40-a798-f62f0c407265.png)

**Comment by kbs4674** [comment]
please ask your server owner to remove fireplace.
서버 어드민에게 집 안에 있는 벽난로 오브젝트를 제거해달라고 요청해주세요.

and, please use english.
그리고 전세계 사람들이 보는 채널인 만큼 영어 사용 부탁드립니다.

**Comment by jhoya0703** [comment]
> 메뉴를 선택하세요. 서버에 구현된 객체에 대해 정의합니다.
> 
> 그리고 한국어를 사용했습니다. 모든 사람들이 보고 있습니다.

내가 영어쓸꺼같으면 한국서버를 뭐더러 하겟소

**Comment by kbs4674** [comment]
잼민이는 잠이나 주무세요....
애초에 외국에서 만들어진 게임이고 전세계 사람들이 보는 채널에서 뭔 망신이냐;;

WTF
Be polite.

**Comment by sgnoodles** [comment]
잼민이는 환불받고 겜 지워라

**Comment by MineMy** [comment]
> __**Manner maketh man. / 매너가 사람을 만든다**__

제발 하지 말라면 하지 마세요. 그렇게까지 이 게임이 싫으면 환불 받고 다시는 오지 마세요. 그게 @jhoya0703님이든 이 게임의 모든 플레이어든 모두를 위한 길입니다.
이 게임의 개발자들은 한국인이 아닙니다. 대부분의 개발진들이 모국어가 영어인 국가의 사람일 것입니다. 솔직히 이런 이슈나 코멘트를 볼 때마다 한숨만이 나옵니다.
Please. and PLEASE use English as this game is used by people all over the world.
The developers cannot speak Korean, and they aren't Korean, too. I don't think this is the case even if I look at it.

**Comment by faketucker** [comment]
Duplicate of #943
