### ISSUE TITLE
the water is white and it won't let me fish

### ISSUE THREAD

**Issue by vildeangel** [Uuvana-Studios/longvinter-windows-client#1065]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by MineMy** [comment]
Try [this](https://github.com/Uuvana-Studios/longvinter-windows-client/issues/919#issuecomment-1147638167) one.

**Comment by faketucker** [comment]
Try to toggle DX11 water in the settings. If it doesn’t work, try what the issue https://github.com/Uuvana-Studios/longvinter-windows-client/issues/13 said
