### ISSUE TITLE
Bug: Creating infinite cooked bird meat(s)

### ISSUE THREAD

**Issue by ZehFuge** [Uuvana-Studios/longvinter-windows-client#1068]
**Describe the bug**
If you put your uncooked bird meat in the oven, walk away to cancel the cooking process, open the workbench and click 
on a "Deposit" button, the workbench starts cooking a "Cooked Bird Meat" without using your bird meat from the inventory.
So you can produce infinite "Cooked Bird Meat" with a single piece of "Bird Meat".

**To Reproduce**
1. Have a house with workbench and a stove or oven to cook.
2. Have a piece of "Bird Meat", which you can cook.
3. Put the "Bird Meat" in the stove or oven, so the progressbar for cooking starts loading.
4. Walk away to cancel cooking (also the Cooking-Window disappears).
5. Go to your workbench and click on a "Deposit" button.
6. Your workbench starts to cook a "Cooked Bird Meal" without using your "Bird Meat" from inventory.

**Expected behavior**
A workbench should not cook, also it needs to consume the meat from your inventory.

**Screenshots**
Not available.

**Desktop (please complete the following information):**
 - OS: Win10 Home 21H2
 - Game Version Beta 1.0.8
 - Steam Version 7.30.20.28

**Additional context**
None.

**Comment by faketucker** [comment]
Tested.

**Comment by ZehFuge** [comment]
Edit: This also works with crafting at the workbench.

Preparation: Have a house and a workbench.

1. Put two pieces of wood in the workbench (like you would craft a fence).
2. Walk away (so the window disappears.
3. Open the workbench and click on "Deposit"
4. You got a fence without using ressources.

**Comment by Mikooboy** [comment]
Thank you for the detailed report. This will be fixed in the next update.
