### ISSUE TITLE
Unable to place down fences

### ISSUE THREAD

**Issue by teeatree** [Uuvana-Studios/longvinter-windows-client#1069]
While I was continuing to place down fences, I got the alert "Too Close to Interset Point" randomly and I was unable to finish my build.

**To Reproduce**
4. See an error

**Expected behavior**
I just want to finish the build or know what I'm doing wrong.

**Screenshots**

<img width="173" alt="Screenshot 2022-07-18 221937" src="https://user-images.githubusercontent.com/109566012/179650141-7b473493-6330-4139-ac96-1cdce8bf2ac9.png">
<img width="960" alt="Screenshot 2022-07-18 222114" src="https://user-images.githubusercontent.com/109566012/179650289-28e44447-2776-40b3-9483-1802d07d6653.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Exolight-OG** [comment]
Your mistake is already in the top left of the picture you are building too close to a public place.! :)

**Comment by ducbenho** [comment]
Usually that's a bird spawn point
