### ISSUE TITLE
Limit number of turrets that can be placed around your house

### ISSUE THREAD

**Issue by DylanAG0331** [Uuvana-Studios/longvinter-windows-client#107]
![InkedInked20220228222210_1_LI](https://user-images.githubusercontent.com/100668187/156117584-af0bbb62-07dd-4deb-962d-02a04aa15dde.jpg)
![Inked20220228223125_1_LI](https://user-images.githubusercontent.com/100668187/156117562-1268a8db-71b3-438d-af45-4f336c480a00.jpg)

The amount of turrets someone can put on their house is kind of ridiculous and almost game-breaking, can't really go anywhere without being completely annihilated by a billion and one turrets. Maybe only limit to four turrets? One for each corner? Because for example, this individual has 18 turrets all around his base. Absolutely impossible to do anything against that. 

I mean, after all, this game is a PvP and PvE game. I feel like the devs should at least give us a fighting chance to break into someone's house or something and limit how many turrets there are. I'm just afraid that it'll get to the point where the red blue green and yellow status when you place something will become almost obsolete if someone can just place turrets like this.

-Dylan

**Comment by Dodg-e** [comment]
turrets cost 15k each, they most likely got this many by duping objects to sell them, without duping it would be very unlikely they could afford this many, something to think about

**Comment by ItsKiwi88** [comment]
no not duping at all, i play legitamatly, and with the hat that gives 40% to get extra harvest - i farm lotus flowers all day, i made over 100k legit today and have 7 of my own turrets.. so, yeah.. its not hard at all. Even without duping.

**Comment by aaaaaaaaaaaavm** [comment]
Oh I've been begging for rules regarding how turrets should be handled, they've worked on a couple of my issue but a lot still needs to be addressed.

**Comment by Bunnbunnnn** [comment]
This has been addressed by the new electricity system and work on reducing / eliminating dupes.

**Comment by Sammieyy** [comment]
> This has been addressed by the new electricity system and work on reducing / eliminating dupes.

I don't feel like that will rlly fix anything, cuz you can just make it so that the turrets run 24/7. They should just make the turrets behave the same way as the safe area turrets, only hit those who have weapons.

**Comment by Sammieyy** [comment]
Yup... It's ridiculous. I haven't played in a while cuz of the dupe bug and the amount of turrets ppl got from it. And even if they got it in a legit way by farming etc it's still way to many. In certain areas you can't even walk and have to go through the water around all the houses, which costs way more energy. It's just a bit dumb.
