### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#1070]
Quest completed, but still hanging in the list

![q1](https://user-images.githubusercontent.com/69962198/179799517-878289e0-e232-4910-9c49-6f2a5c73ed69.png)
![q2](https://user-images.githubusercontent.com/69962198/179799528-363b08fc-089b-4ecd-a3c8-cf2164fb7c85.png)

**Comment by Jalsson** [comment]
This has been fixed in some update already so closing this
