### ISSUE TITLE
the water is white i play on a window surface tablet and it works well just the water is white and i cant see where to fish

### ISSUE THREAD

**Issue by magros6969** [Uuvana-Studios/longvinter-windows-client#1071]
**Describe the bug**
 the water is white and cant see where to fish  but the game is play able [otherwise](url)
**To Reproduce**
4. See an error
 you just load it up
**Expected behavior**

**Screenshots**
![20220719184658_1](https://user-images.githubusercontent.com/109632257/179861890-7a8b6a5d-bb47-4e88-ac9a-399e21ce846a.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]
windows 11 on a windows surface pro 8 
**Additional context**

**Comment by biffotmc** [comment]
open the menu in game, click options then click dx 11 water toggle in the bottom right
