### ISSUE TITLE
sofa crafting bug

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#1072]
![cr1](https://user-images.githubusercontent.com/69962198/180002432-6c642e2d-0a06-4e66-8bc2-432b9303dcfd.png)
![cr2](https://user-images.githubusercontent.com/69962198/180002435-ce296d50-40cb-42df-98fb-b6e4295ae0ec.png)

in order to paint the sofa you need **5 items**
BUT
only **4 items** can be added to the workbench

**Comment by faketucker** [comment]
Fixed
