### ISSUE TITLE
crates at arena disappear before anyone can loot them 

### ISSUE THREAD

**Issue by seyless8899** [Uuvana-Studios/longvinter-windows-client#1075]
**Describe the bug**
crates at arena keep disappearing on there own with loot in them mainly the green one 

**To Reproduce**
go to arena and go up to the crates and the top green one will disappear right after spawning in  
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
This happens from time to time. Maybe it's because there's nothing in those crates.

**Comment by Jalsson** [comment]
Chests despawn and respawn after the player has visited them to prevent someone from letting in one item. I belive this was just bad timing so closing this one
