### ISSUE TITLE
Progress Reset Bug

### ISSUE THREAD

**Issue by KenshiCatfish** [Uuvana-Studios/longvinter-windows-client#108]
**Describe the bug**
My game froze while rapidly putting sugar beet into a storage crate in my house, I closed the game and once I reopened it all of my progress was deleted. I found my house again and entered it but once I tried to click on the storage crate that I was placing sugar beet into before my game crashed it says that it is in use and it is unable to be re opened. I also cannot pick up the storage crate.

**To Reproduce**
1. Go to your house with lots of sugar beet in your inventory. Unsure if this but applies to all items or just sugar beet.
2. Click on a storage crate (mine had about 5 sugar beet in it already) and rapidly place items from inventory into storage crate.
3. If game freezes close the game and rejoin server. All progress should be gone and the storage crate being previously used should not be able to be opened and crate should not be able to be picked up.

**Expected behavior**
unsure

**Screenshots**
no screenshots to add

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam API v020

**Additional context**

**Comment by KenshiCatfish** [comment]
figured out cause of issue. Trying to perform many actions while server is glitching/frozen

**Comment by Jalsson** [comment]
Newest update moved all the player information to one file which is loaded on server startup and saved every 6 minutes. This should make joining and loading your character much more reliable. The container bug is also fixed in recent update
