### ISSUE TITLE
Property area shrinking

### ISSUE THREAD

**Issue by myotherheart** [Uuvana-Studios/longvinter-windows-client#1080]
**Describe the bug**
Inside the fence post where it should be green items are red and says to close to an area of interest. If an item is placed it pops back into a bag or can no longer be picker back up. 

**To Reproduce**
4. See an error
IDK how to reproduce this issue
**Expected behavior**
Should be able to place items to the perimeter designated by the four posts.  

**Screenshots**
![image](https://user-images.githubusercontent.com/33080259/180703773-18b7efe4-3230-4183-8976-582a45cc10d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.8
 - Steam Version latest

**Additional context**

**Comment by elow21** [comment]
You can't place items if they are too close to a point of interest. That's a bird spawn point.
