### ISSUE TITLE
[AU] Uuvanna 1 server dissapearing from server list

### ISSUE THREAD

**Issue by elow21** [Uuvana-Studios/longvinter-windows-client#1083]
**Describe the bug**
The AU1 server keeps dissapearing from the server list. It's been happening for 2 days now usually around this time. It was working fine earlier in the morning. It's 6pm at the time of posting so there should be more people online. 
Maybe there's a bug where only 1 person can be online at a given time? 

**To Reproduce**
1. Go to server list
2. Select "Oceania"

**Expected behavior**
AU Uuvanna 1 server shows up on server list. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54529136/180951745-722c7ba3-dfd0-49fd-af20-40b62cc011d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Game Version 1.0.8
 - Steam Version - latest

**Additional context**
The AU1 server also has been experiencing quite a lot of ping spikes this week. This may be related to the issue. 
Others have also informed me of them experiencing this issue.

**Comment by gmbrothers** [comment]
@cherryblossom2020 Any idea what's going on here?
