### ISSUE TITLE
Password hacking hack

### ISSUE THREAD

**Issue by rokmelody** [Uuvana-Studios/longvinter-windows-client#1084]
**Describe the bug**

I think there's a password hack

**To Reproduce**
4. See an error

**Expected behavior**
Daon 1 Mrs. snow's outpost
**Screenshots**
![87654](https://user-images.githubusercontent.com/110050869/181059975-cafe504f-9ee5-46ec-aeb7-094b58da2e88.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7]
 - Game Version [e.g. 1.0.8]
 - Steam Version [e.g. 1.0]

**Additional context**

Please check the log to see if this is nuclear or something else

**Comment by gmbrothers** [comment]
We are aware of the house stealing hack, but the GitHub is not the place to post it. Have a good rest of your day,
gmbrothers

**Comment by rokmelody** [comment]
Can't you restore it? Where do I post it?
