### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by Lenpanpan** [Uuvana-Studios/longvinter-windows-client#1086]
the house and other stuffs wont load fast sometimes other items are not there because of the lag and I cant enter my house due to delay and when u enter the house the stuffs are gone ne
![long](https://user-images.githubusercontent.com/110083864/181171080-62ce10c5-d540-4549-9018-a183ecf8587a.png)
ed to wait before it pop up if its pop I cant leave my house and it will automatically disconnect u to the server because of the lag I have fast internet connection so net is not a problem

**Comment by Hilolen** [comment]
I'm having the same issue in US E6. Houses are taking a long time to load. Gates don't work, and when I try to enter my house I'm disconnected from the game.

**Comment by rx3E** [comment]
Same issue on US E5

**Comment by bugeyeyork** [comment]
Im having the same issue for the past 6 hours in US west Uuvana 2

**Comment by Naert3v** [comment]
Same thing, also the lag results in me getting stuck in the loot buildings because the doors aren't opening, because the lag means i'm not actually standing in front of them. :(
