### ISSUE TITLE
Everything built by everyone is bugged

### ISSUE THREAD

**Issue by 3DDanilo** [Uuvana-Studios/longvinter-windows-client#1087]
**Describe the bug**
Everything built by everyone is bugged, random screens, I can't get into my house and it takes me out of the server.
**To Reproduce**
4. See an error

**Expected behavior**
SOLVE error when kicking me from the server
**Screenshots**

![20220727121034_1](https://user-images.githubusercontent.com/110124803/181344083-eb9b2bcf-b450-42fe-a2d5-a05add5779c5.jpg)
![20220727121052_1](https://user-images.githubusercontent.com/110124803/181344090-b58b1bba-2662-45cf-bf71-3d85472840d2.jpg)
![20220727121106_1](https://user-images.githubusercontent.com/110124803/181344092-113cffd3-c82d-4aab-9f50-5ac6687c3f51.jpg)
![20220727121232_1](https://user-images.githubusercontent.com/110124803/181344093-81798d44-612c-4439-adcd-5393a4304289.jpg)
![20220727120749_1](https://user-images.githubusercontent.com/110124803/181344094-37a94007-800f-469a-a99a-c01e80190328.jpg)
![20220727120835_1](https://user-images.githubusercontent.com/110124803/181344095-acebce4a-0181-42bd-b32f-149aea7f34ad.jpg)
![20220727120901_1](https://user-images.githubusercontent.com/110124803/181344096-a5d32bed-ecf7-469c-a504-6a223f4ee8d9.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [Beta 1.0.8]
 - Steam Version [27/07/2022]

**Additional context**
When walking, it returns me to points without direction, and I have very good internet.

**Comment by faketucker** [comment]
This should be the server problem, not the game bug.
