### ISSUE TITLE
In combat notification

### ISSUE THREAD

**Issue by Callie-esi** [Uuvana-Studios/longvinter-windows-client#1089]
**Describe the bug**
After being in combat even if you die it still continues to say in combat if you leave your stuff will be dropped

**To Reproduce**
Get shot at by someone and die continue playing game

**Expected behavior**
Once you die you are no longer in combat unless combat was started up again. If I am a new person who can't combat the combat and my stuff is dropped because i still have that buff even 2 hours after playing it kind of sucks. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Game Version [e.g. 1.0] 1.0.8
 - Steam Version [e.g. 1.0] I'm not sure.

**Comment by ducbenho** [comment]
The effect will wear out after 30 seconds. Did yours last longer than that?

**Comment by Callie-esi** [comment]
It did not. It is still there about an hour and a half later.. 

Sent from Yahoo Mail on Android 
 
  On Wed, Jul 27, 2022 at 11:40 PM, ***@***.***> wrote:   


The effect will wear out after 30 seconds. Did yours last longer than that?

**Comment by faketucker** [comment]
Have you tried "/kill"?

**Comment by faketucker** [comment]
Fixed in [1.0.9](https://store.steampowered.com/news/app/1635450/view/6074815775727636258)
