### ISSUE TITLE
fishing hat bug

### ISSUE THREAD

**Issue by D0T0LI** [Uuvana-Studios/longvinter-windows-client#109]
**Describe the bug**

I'm wearing a fishing hat, but I can't see it.

**To Reproduce**
1. Go to 'shop'
2. Click on 'fishing hat'
3. can't see him wearing a hat.

**Expected behavior**

I think I can't see it when I wear a hat.

**Screenshots**

[https://steamcommunity.com/sharedfiles/filedetails/?id=2769494483](url)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**

**Comment by Jalsson** [comment]
Fixed in yesterdays update
