### ISSUE TITLE
집 사라짐 아이템 사라짐 복구 해주세요

### ISSUE THREAD

**Issue by rgw6564** [Uuvana-Studios/longvinter-windows-client#1090]
**Describe the bug**

**To Reproduce**
1. Go to '...' 게임 업데이트 하고나서 집과 아이템 울타리 사라짐
2. Click on '....' 복구원함 
3. Scroll down to '....' 복구원함
4. See an error 복구 해주세요

**Expected behavior**
A clear and concise description of what you expected to happen. 업데이트 전으로 복구해주세요

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Game Version [e.g. 1.0.8]
 - Steam Version [e.g. 최신]

**Additional context**

**Comment by rgw6564** [comment]
업데이트를 하고 나서 집 사라짐 아이템과 울타리 등 사라짐 빨리 복구 해주세요

**Comment by biffotmc** [comment]
copy of #1099
