### ISSUE TITLE
trees aint going down when u choop em

### ISSUE THREAD

**Issue by ABOTttr** [Uuvana-Studios/longvinter-windows-client#1091]
trees aint going down when u choop em on 1.0.8b

**Comment by gmbrothers** [comment]
Are you using an axe or a chainsaw? How long are you chopping for? You may not be giving it enough time to chop.

**Comment by ABOTttr** [comment]
lel well on the new patch that came 1.0.8b u can chopp on the same tree for 5 mins and it wont go down , u get drops tho
on the experimental serv last night i wacked that tree like 4 times and u got it down way faster than the normal serv
