### ISSUE TITLE
still a bug , the other houses whent upgraded this aint , and the chest in the other houses is invisible but u can use them

### ISSUE THREAD

**Issue by ABOTttr** [Uuvana-Studios/longvinter-windows-client#1092]
still a bug , the other houses whent upgraded this aint , 
![bild](https://user-images.githubusercontent.com/110172412/181512034-f980b50b-d89d-4497-97a2-672a7e8afba0.png)

**Comment by gmbrothers** [comment]
That's odd, I'll check with some others

**Comment by biffotmc** [comment]
copy of #1099

**Comment by ABOTttr** [comment]
well i was fist lol

> copy of #1099
