### ISSUE TITLE
집 사라짐 아이템 사라짐 울타리 사라짐 복구 원함

### ISSUE THREAD

**Issue by rgw6564** [Uuvana-Studios/longvinter-windows-client#1096]
**Describe the bug**
A clear and concise description of what the bug is. (집, 아이템, 울타리 사라짐)

**To Reproduce**
1. Go to '...'(집, 아이템, 울타리 사라짐)
2. Click on '....'(집, 아이템, 울타리 사라짐)
3. Scroll down to '....'(집, 아이템, 울타리 사라짐)
4. See an error(집, 아이템, 울타리 사라짐)

**Expected behavior**
A clear and concise description of what you expected to happen.(복구 바랍니다)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Game Version [e.g. 1.0.8]
 - Steam Version [e.g. 2.10.91.91]

**Additional context**

**Comment by biffotmc** [comment]
copy of #1094
