### ISSUE TITLE
MISSING HOUSE

### ISSUE THREAD

**Issue by Ksenia2703** [Uuvana-Studios/longvinter-windows-client#1102]
![1111111111111111111111111111](https://user-images.githubusercontent.com/90321080/181544229-5071959d-bf59-4ac2-9ce1-089abff536ca.png)
![22222222222222222222222](https://user-images.githubusercontent.com/90321080/181544368-4f8c3d59-e937-4806-9453-b372495928c7.png)

GIVE ME MY HOUSE AND THINGS BACK!!!

**Comment by biffotmc** [comment]
copy of #1099
