### ISSUE TITLE
Nonupgraded and Upgraded Housing ar both bugged

### ISSUE THREAD

**Issue by Queet256** [Uuvana-Studios/longvinter-windows-client#1107]
These updated should have been added after a wipe because now I cant access most of my storage inside of my houses....
![LV1](https://user-images.githubusercontent.com/108912330/181617061-9ddc65f4-ff93-45cb-bc28-d9790cbab02b.PNG)
![LV2](https://user-images.githubusercontent.com/108912330/181617072-95a71d66-3c6e-496f-9dbe-0fdfb4ec531c.PNG)

**Comment by vEpic7** [comment]
which one is fuel and which is wind power ?

**Comment by Queet256** [comment]
one without the upgrade is fuel, upgraded is solar

**Comment by Queet256** [comment]
also if houses are gonna be that massive there should be an increase added to the property line

**Comment by vEpic7** [comment]
> also if houses are gonna be that massive there should be an increase added to the property line

true

**Comment by vEpic7** [comment]
> one without the upgrade is fuel, upgraded is solar

did u upgraded the fuel one ?

**Comment by Queet256** [comment]
was going to yesterday but the game was unplayable. might try to work on it today if the lag gets fixed soon

**Comment by faketucker** [comment]
Duplicate of #1099
