### ISSUE TITLE
다운서버 어딨어여ㅕ?

### ISSUE THREAD

**Issue by dynkorea** [Uuvana-Studios/longvinter-windows-client#1108]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by kbs4674** [comment]
please, write in english when you issue-up.
제보하실 때 영어사용을 권장드립니다.

and also, what is mean '다온서버' ??
did you mean '다온서버' ??

and if is right, please tell us which number of '다온서버'.
그런데 다운서버가.. 어떤건가요, 다온서버를 말씀하시는건가요?
그리고 다온서가 맞다면, 몇번째 서버를 지칭하시는건지도 말씀 부탁드립니다.

**Comment by playcamping** [comment]
Daon server went to heaven
다온서버는 미국갔어요

**Comment by faketucker** [comment]
The server should be on the list now
