### ISSUE TITLE
All official servers have many network delays.

### ISSUE THREAD

**Issue by playcamping** [Uuvana-Studios/longvinter-windows-client#1110]
**Describe the bug**
All official servers have many network delays.

**To Reproduce**
1. If you type in a chat, a message appears three to four seconds later.
2. If you cut down a tree, it won't fall off.
3. If you walk, you'll do the backstep.

**Expected behavior**
Please test thoroughly before patching. 
Is the experimental server a decoration?

**Screenshots**
Just go online and experience it

**Desktop (please complete the following information):**
 - OS: Windows 10 Latest
 - Game Version: 1.0.8b
 - Steam Version: Package Version 1658944613

**Additional context**
You don't have brain?

**Comment by faketucker** [comment]
Should be better now. And please be polite here
