### ISSUE TITLE
unstable server,movement,lag,high ping after this update.

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#1112]
after this update, all the players r suffering from lagging .

each of things takes much longer than before .everything shows slower too.

ping is so unstable and high too. 

hope it get better soon asap..

**Comment by hawkgamingdev** [comment]
Went from 28ping in Uvanna 5 to 130ping.

**Comment by rx3E** [comment]
Having the same issues

**Comment by faketucker** [comment]
The problem has been [resolved](https://store.steampowered.com/news/app/1635450/view/3376029156932784381).
