### ISSUE TITLE
Can't pick up loot behind houses or trees, basically if there's something infront, i cant pick it up

### ISSUE THREAD

**Issue by jminho9806** [Uuvana-Studios/longvinter-windows-client#1113]
**Can't pick up loot behind trees or houses**
Found this out when I want to pick up a fence behind my house and could not for some reason.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a fence behind your house
2. Camera will zoom out and tilt at an angle so you can place the fence perfectly
3. Unable to tilt the camera so I can remove the placed fence for maybe another colour or anything.
4. Only for fences behind houses or any loot behind certain stuff.

**Expected behaviour**
Make it so I can maybe tilt the camera even just a little so I can pick up loot

**Screenshots**
![image](https://user-images.githubusercontent.com/110243074/181777535-c00b63a5-74dc-4287-bdd0-9d66960499b6.png)
see the corner of the fence behind the house, I can't pick it up, and the hole next to the said fence is where I can right click it into a bag but can't pick up either and after some time it just disappears.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version : 1.0.8b
 - Steam Version : v020

**Comment by Jalsson** [comment]
This issue is nor resolved by new camera angle that can be changed ON by pressing "Q"
