### ISSUE TITLE
 The house is gone after the update

### ISSUE THREAD

**Issue by kimvely** [Uuvana-Studios/longvinter-windows-client#1116]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
There were three-family houses, among which the middle house disappeared after the update. The loot was visible inside the house, but the house itself was gone and the tent could not be rebuilt.

**Screenshots**
![스크린샷(4)](https://user-images.githubusercontent.com/110277198/181877370-b6a61bae-b183-4fd2-a5b9-01059a156596.png)
![스크린샷(5)](https://user-images.githubusercontent.com/110277198/181877378-6d29701e-0b35-4348-8889-8a69afbaa27f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
You need to put a tent in the same spot to get all your stuff back because there's no way to bring your house back. Your house might be lost because of the data lost during the update
