### ISSUE TITLE
Furnaces disappearing / reappearing

### ISSUE THREAD

**Issue by worthij92** [Uuvana-Studios/longvinter-windows-client#1118]
**Describe the bug**
Furnaces are still where I placed them but they go invisible sometimes when going up the stairs, or outside of the home. 

**To Reproduce**
4. See an error

**Expected behavior**
For the furnaces to be present and not to be affected by leaving house or going up and down the stairs :)

**Screenshots**
![image](https://user-images.githubusercontent.com/106206104/181925667-3f48c832-cc77-4f63-bb4f-795e3e3112a6.png)
![image](https://user-images.githubusercontent.com/106206104/181925721-c3b16c42-6616-475f-af0a-d5541ae31e7f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [1.0.8b]
 - Steam Version [never can find this when I need it but it is up to date]

**Additional context**
This was happening in experimental so just informing that the issue is still there sometimes. It seems like it is behaving better in stable but is still randomly happening.

**Comment by faketucker** [comment]
Should be fixed in [1.0.9](https://store.steampowered.com/news/app/1635450/view/6074815775727636258)
