### ISSUE TITLE
Items lost on Vending machine

### ISSUE THREAD

**Issue by mariel4613** [Uuvana-Studios/longvinter-windows-client#1119]
**Describe the bug**
so put back my vending machine on my inventory with the items inside. When I placed it on its new location, all the items were lost.

**To Reproduce**
1. Go to 'your vending machine with items inside'
2. Click on 'right click the vending machine'
3. Scroll down to 'your inventory and place it on new location'
4. See an error

**Expected behavior**
The items should be still be there as its not sold yet.

**Screenshots**

![image](https://user-images.githubusercontent.com/110301300/181933553-3baf73f1-a5df-4f59-be71-e84945f88924.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
The game has a pop-up message telling you that you will lose all the items inside if you pick the vending machine up.
