### ISSUE TITLE
Losing inventory and MK upon reconnecting to a server

### ISSUE THREAD

**Issue by Lyradessa** [Uuvana-Studios/longvinter-windows-client#112]
First time I logged onto the server I've been working on (where I have a house and bunch of stuff) It started me fresh at the starter spawn point. I lost all of the stuff in my inventory and all my MK back down to the starting 100. And after playing for a while, the servers had to update. so I disconnected, updated my game, and reconnected. It did it to me again. Thankfully I do still have access to my house and belongings, but I'm losing all the money I make and everything in my inventory every time I log off.

**Comment by sirNugg3ts** [comment]
Please fill the bug report according to template

**Comment by THESADBOY76** [comment]
When i was logging into the server i lost all of my inventory items and my MK.
But i still have my hous.
Pls fix this bug 
Thx.
