### ISSUE TITLE
Missing Mk, items, and storage issues

### ISSUE THREAD

**Issue by Queet256** [Uuvana-Studios/longvinter-windows-client#1122]
Everything i looted and all my Mk i had before the update is gone... I've relogged several times and still nothing. Still have a box stuck inside the wall of my house, have to spam click to access certain boxes.

**Comment by Queet256** [comment]
also showing i dont have any feathers gathered, fish or plants collected. It's like my whole character got deleted

**Comment by dovo0023** [comment]
me too pls fixed that

**Comment by Queet256** [comment]
Since they ignore all of these posts and the majority of discord messages i'll let you know what i was eventually told. I just got a beta command and another bs command in discord. They're to lazy to resolve the issue so good luck

**Comment by faketucker** [comment]
Your progress may be lost due to multiple server crashes, but the problem has been resolved.

**Comment by Queet256** [comment]
issue was never resolved....
