### ISSUE TITLE
Missing home 3 times

### ISSUE THREAD

**Issue by nadhiim** [Uuvana-Studios/longvinter-windows-client#1123]
**Describe the bug**
I have build my home 3 times but it dissapered. When I enter my friend's house which is located next to my house, I can still see the inside of my house along with my belongings.

**To Reproduce**
1. Go to (TH) BANGKOK 2 OFFICIAL server 
2. Then go to 'Filemon's Outpost then go to the left side. My house should be to the left of the white tent and above the garden firepit.

**Expected behavior**
Please give me back my house and my stuff inside the house. 

**Screenshots**
This is my house location. I marked the location with a red X line.
![map](https://user-images.githubusercontent.com/110315992/182007062-84754ab4-3cc0-4207-b104-9337c1c67938.png)
![me](https://user-images.githubusercontent.com/110315992/182007082-bff73f68-968d-406f-9db4-a1e520db9f57.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Game Version [e.g. 1.0.8b]
 - Steam Version [e.g. 1658944613]

**Additional context**

**Comment by faketucker** [comment]
This happened because the server crashed many times, and the problem has been resolved. There's no way to get your house back unless you build a tent at the same spot to get the stuff inside back.
