### ISSUE TITLE
Setting monitor to portrait exposes a lot of the map

### ISSUE THREAD

**Issue by lmore377** [Uuvana-Studios/longvinter-windows-client#1124]
**Describe the bug**
Setting your monitor to portrait mode in windows settings causes the game to reveal a large amount of the map above you

**To Reproduce**
1. Open the game and load into a server
2. Set in-game video settings to borderless window
3. Set monitor to be portrait orientation in Windows settings

**Expected behavior**
The game should scale properly and not expose a significant amount of the map
**Screenshots**
![image](https://user-images.githubusercontent.com/24685455/182011591-e63cdf15-ca8d-412a-8c26-179807599998.png) this screenshot is a bit zoomed in you can see even more than this

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.8b

**Comment by Jalsson** [comment]
A player cannot be seen that far away because the server does not send information about the player before they are close enough.
