### ISSUE TITLE
Farming Quest

### ISSUE THREAD

**Issue by Roberr7** [Uuvana-Studios/longvinter-windows-client#1129]
I cant claim the reward in the spending machine for no reason

**Comment by Roberr7** [comment]
> I cant claim the reward in the spending machine for no reason

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
