### ISSUE TITLE
The code lock on the doors isn't working and players are also able to destroy fences and enter garden

### ISSUE THREAD

**Issue by KirstennX** [Uuvana-Studios/longvinter-windows-client#113]
**Describe the bug**
The code lock on the houses is not working and other players are able to enter without knowing your code. It may be that any code entered allows you to enter homes therefore players are able to steal items and continue to enter your house, however I have not tried this on anyones house. 
Other players are also able to destroy fences to enter gardens. Not sure how they are doing this however it may be using the chainsaw.

**To Reproduce**
Enter code to enter someones house and this should let you enter despite it not being the correct code. 
Not sure how to replicate the gate bug as I am not sure how it is done. 

**Expected behavior**
Players should not be able to enter house unless they enter the correct code and they should not be able to destroy fences

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows
 - Game Version 1.0.0
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Dodg-e** [comment]
entering houses without code is a bug, destroying fences is part of game, the point of turrets is to protect your garden, if fences are indestructible then there's no point, also if you cant destroy fences then i could surround your house with fences and you would be stuck

**Comment by sirNugg3ts** [comment]
I've just tested and you can't access houses with the incorrect code.
About destroying fences, just like @Dodg-e said

> destroying fences is part of game, the point of turrets is to protect your garden, if fences are indestructible then there's no point, also if you cant destroy fences then i could surround your house with fences and you would be stuck
