### ISSUE TITLE
Cannot upgrade house because of the windmill

### ISSUE THREAD

**Issue by Goro5603** [Uuvana-Studios/longvinter-windows-client#1131]
I keep getting the "Not enough room outside the home to upgrade" even after I removed everything outside of the house.
![longvinter2](https://user-images.githubusercontent.com/110436275/182271755-328ddbef-c9ed-4d68-90a7-62382a97d57b.PNG)
![longvinter](https://user-images.githubusercontent.com/110436275/182271759-b1a2c355-5751-48fb-9930-704a7341f8dc.PNG)
![longvinter3](https://user-images.githubusercontent.com/110436275/182271765-3518281e-5d32-40a5-9c5f-5847cde0c787.PNG)

**Comment by shshady3** [comment]
and what can we do?

**Comment by BonesIsLive** [comment]
Adding to this bug, using the fuel upgrade path when upgrading to the generator (alternative to the windmill) would seem to cause the same issue.

**Comment by aleksalazar** [comment]
![image](https://user-images.githubusercontent.com/33018914/190069459-07d9b4c0-2b79-4ff0-af8c-ace08ada4e75.png)
I have the same issue.
