### ISSUE TITLE
Invisible 2nd floor 

### ISSUE THREAD

**Issue by elow21** [Uuvana-Studios/longvinter-windows-client#1132]
**Describe the bug**
When you spawn in the second floor, the whole floor becomes invisible/transparent including the furniture you placed on the 2nd floor. 

**To Reproduce**
1. Disconnect from server when you are on the 2nd floor
2. Click "Play" and select the server
3. Respawn on 2nd floor
4. Visual bug occurs 

**Expected behavior**

https://user-images.githubusercontent.com/54529136/182317780-2e5f67b5-78c9-4517-9722-a631ba9cb793.mp4

Second floor should not be invisible. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.8b
 - Steam Version latest

**Comment by Jalsson** [comment]
Thank you for the video. This issue will be fixed in next update
