### ISSUE TITLE
the generators are buged, they dont work as intended, if i place a generator near a turrent and fuel it, it wont trigger the closest turrent

### ISSUE THREAD

**Issue by ABOTttr** [Uuvana-Studios/longvinter-windows-client#1133]
![skroep](https://user-images.githubusercontent.com/110172412/182397642-21e69862-3447-4791-83bc-34dd670b5092.jpg)

**Comment by faketucker** [comment]
Other turrets might use that electricity. Try to pick up those that are working until the one you want is working instead.
