### ISSUE TITLE
A bug that cannot delete the cabinet

### ISSUE THREAD

**Issue by Loppy2828** [Uuvana-Studios/longvinter-windows-client#1134]
**Describe the bug**

Unable to delete cabinet. If you install it in your home, it will not play normally.

**To Reproduce**
1. Go to ' cabinet'
2. Click on 'cabinet'
3. See an error

**Expected behavior**

Unable to delete cabinet. It's a serious problem If you use this bug to block the house, you can't delete it and play normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ Windows]
 - Game Version [e.g. 1.0.8b]
 - Steam Version [e.g. 1.0.8b]

**Additional context**

**Comment by faketucker** [comment]
This can happen when the server lags and there might be two cabinets at the same spot.

**Comment by Jalsson** [comment]
All cabinets can now be dismantled correctly so closing this one
