### ISSUE TITLE
"Joining Island" forever

### ISSUE THREAD

**Issue by bagusprawira3** [Uuvana-Studios/longvinter-windows-client#1135]
**Describe the bug**

**To Reproduce**
1. Start Game
2. Choose Server
3. Got "Joining Island" forever 

**Screenshots**
![long time](https://user-images.githubusercontent.com/55121146/182623025-01bf90c5-4594-43fd-8ba2-53e6b088d517.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Newest (Aug 03, 2022)
 - Newest (Aug 03, 2022)

**Additional context**
Just install the game and play for more than 60 Minutes, but when i join to an island, it keep loading until now

**Comment by faketucker** [comment]
Can you join now? Make sure you are not on an experimental branch. But this can also be the problem on the server side.

**Comment by aleksalazar** [comment]
I too have this issue, Windows 11 though.

**Comment by faketucker** [comment]
Close due to no additional information provided.
