### ISSUE TITLE
Volume increases when the "M" key is pressed

### ISSUE THREAD

**Issue by elow21** [Uuvana-Studios/longvinter-windows-client#1137]
**Describe the bug**
Game volume increases to 50ish when the "M" key is pressed. Not sure if this is a feature or bug. 

**To Reproduce**
1. Press the "M" key
2. Volume goes up

**Expected behavior**
Volume should not go up by pressing the M key. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.8b
 - Steam Version Latest

**Additional context**
Volume still increases even when master volume was set to 0.

**Comment by Jalsson** [comment]
This has been fixed in previous update
