### ISSUE TITLE
Sauna OOB Glitch

### ISSUE THREAD

**Issue by AuwrenArt** [Uuvana-Studios/longvinter-windows-client#1138]
When another player was standing just inside the sauna, I glitched on top of the upper wall.
I got scared so I ran back down without testing much initially.

**To Reproduce**
1. One player enters the sauna, and either stands or runs around near the door
2. Another player tries and succeeds at entering
3. The player entering gets forced upwards on top of the sauna wall

**Expected behavior**
Both of us to be inside the Sauna, together, not on the wall.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.8b
 - Steam Version Unsure... windows?

**Additional context**
I got scared so I ran back down without testing much initially.
May test more if I can find someone to test it with me.
I don't remember if the other player was wearing a hat or not, but that might affect it. I also don't know if they were moving back and forth or standing still.

**Comment by faketucker** [comment]
Can you provide us a video?

**Comment by Jalsson** [comment]
Fixed by making players not collide with each other near the sauna entrance to prevent any spawning to a ceiling or not being able to get into the sauna. Fix available in next update
