### ISSUE TITLE
I cant loot backpack in the water

### ISSUE THREAD

**Issue by Ocesguan** [Uuvana-Studios/longvinter-windows-client#1139]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #450
