### ISSUE TITLE
Admin pannel does not open anymore

### ISSUE THREAD

**Issue by Hexae** [Uuvana-Studios/longvinter-windows-client#114]
**Describe the bug**
Admin pannel does not open anymore when interacting with it

**To Reproduce**
1. click on admin panel

**Expected behavior**
When an admin of a server interacts with the ''admin pannel'' button, it should open up an interface.

**Screenshots**
https://user-images.githubusercontent.com/31287772/156200911-35d6079b-7229-493c-b003-9bd48dea0a99.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Game Version 1.0.0 (lastest build of today)
 - Steam Version Lat update was 7 minutes ago.

**Additional context**

**Comment by KillerKazi** [comment]
Same issue for me.  Strange enough, admin panel was working correctly following the latest update however after a bit of play it no longer functions.  Did not do much other than loot a poi and vendor some goods from it.

Reconnecting/Restarting game does not solve this either.

**Comment by sirNugg3ts** [comment]
should be fixed in this patch, just tested and works

**Comment by sirNugg3ts** [comment]
Seems there's still some issues with the panel

**Comment by Bunnbunnnn** [comment]
Hello 

I added my steam ID as explained in the tutorial , restarted the server and seems admin panel not opening

**Comment by Jalsson** [comment]
Admin panel stopped working on servers because it recorded too many events and tried to display them all when clicked on the menu. We limited events so now it should open.
