### ISSUE TITLE
Unstable ping transparent turret,  sudden disconnect

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#1141]
Der r so many problems(from many players)
1.Unstable ping
2.invisible turret, 
3.sudden disconnect
4.sometime can’t click item on the bag so should suicide( if disconnect and reconnect it, all item on the bag gone)

i love this game and i know update is important. But i hope dev fix basic problem first.
New players from youtube or other media will disappoint with basic problem and gone. Pls fix unstable ping .

**Comment by Jalsson** [comment]
Closing this issue since server optimization is an ongoing problem and we are doing things to make game smoother.
