### ISSUE TITLE
Sign Dupe

### ISSUE THREAD

**Issue by AuwrenArt** [Uuvana-Studios/longvinter-windows-client#1143]
**Describe the bug**
Able to dupe signs if I type the message before dying.

**To Reproduce**
1. Take a sign
2. Type what I want to say
3. Enter placement mode
4. Die
5. Respawn still in sign placement mode
6. Place sign for free
7. Pick up my death inventory backpack
8. Sign is still there

**Expected behavior**
If I die, my character isn't still able to place the sign, and the sign stays in my inventory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.8b
 - Steam Version idk.. windows?

**Additional context**
After dying, there's a visual glitch with the sign ui flashing. It didn't go away even after I placed the sign. I had to refresh to the menu.
I died of cold damage. Unsure if its related to the glitch, or if other types of damage would not have the glitch.

**Comment by Mikooboy** [comment]
Sign UI is now removed on death so this should no longer happen in the next update
