### ISSUE TITLE
Equipping a Ammo Pouch removes your Hikers Backpack

### ISSUE THREAD

**Issue by nakLIFTS** [Uuvana-Studios/longvinter-windows-client#1145]
Yeah I purchased an Ammo Pouch from the vendor Filemon
I was wearing my Hikers Backpack
When I equipped the ammo pouch, it took place of the hikers backpack, but the backpack was lost forever
Inventory space was not at max, i think.
In game name is nakLIFTS
US EAST Uuvana 5

**Comment by BonesIsLive** [comment]
Not a proper report.
Having just one of them equiped at once is expected behaviour.

**Comment by Mikooboy** [comment]
Added a check for inventory space when trying to switch out the backpack so this should be fixed in the next update
