### ISSUE TITLE
cannot upgrade 2nd floor

### ISSUE THREAD

**Issue by Kojung08** [Uuvana-Studios/longvinter-windows-client#1147]
**Describe the bug**
I get all the materials that needed for upgrading the second floor.
However, the game don't allow me to do that and the message pop up "not enough room outside the home to upgrade"
even though, I clear everything outside the house.

**Screenshots**
![image](https://user-images.githubusercontent.com/110735968/183257192-aa52d91b-31eb-4b07-8479-6edd810bd9da.png)

**Comment by shshady3** [comment]
we're screwed, it's bc widn tubrbine bug

**Comment by Jalsson** [comment]
Fixed in previous update so closing this one
