### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by t0nyuy** [Uuvana-Studios/longvinter-windows-client#1148]
the game crash
el juego muchas veces  se cierra solo

**Comment by BonesIsLive** [comment]
No es un reporte apropiado, la próxima vez sigue el formato sugerido de reportes.
De momento el juego está teniendo un problema de perdida de memoria, en el cual se sobrecarga la RAM con datos redundantes del juego causando que el mismo se cierre en sistemas con cantidades menores a 8GB luego de determinado tiempo. Los desarrolladores están al tanto del error y será corregido pronto, hasta entonces recomiendo que trates de reiniciar el juego por tu cuenta para evitar que la RAM se siga llenando y todo tu sistema se vuelva inestable.

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
