### ISSUE TITLE
the water is white i cant see any fishes

### ISSUE THREAD

**Issue by p00keyyy** [Uuvana-Studios/longvinter-windows-client#1151]
the water is white i cant see any fishes

**Comment by BonesIsLive** [comment]
Please follow the issue report template next time!
This is a common problem with some dedicated and integrated graphics cards, in short terms, they can't handle the part of the game engine that renders the water. To fix it head to the game options and click the text on the lower right that says "Toggle DX11 Water". Please note at least for the time being you must click this option once you joined a server and you must do it every single time you do so.

**Comment by faketucker** [comment]
Duplicate of #13
