### ISSUE TITLE
Player stucks in a rock

### ISSUE THREAD

**Issue by nikolai-imversed** [Uuvana-Studios/longvinter-windows-client#1152]
**Stuck in rock**
There is a location in a desert where players can stuck in rocks and only way out is suicide.

**To Reproduce**
1. Go to '3S/45W'
2. Get instide the rocks on the beach near water.

**Expected behavior**
Player is not stuck
 
**Desktop (please complete the following information):**
 - Game Version [e.g. 1.0.8]

**Comment by faketucker** [comment]
You can type /kill in the chat for now

**Comment by nikolai-imversed** [comment]
> You can type /kill in the chat for now

yup I am aware of that
