### ISSUE TITLE
[SG] UUVANA 1 is down (can't find it on server list or can't get in)

### ISSUE THREAD

**Issue by zofrente** [Uuvana-Studios/longvinter-windows-client#1154]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Should be up by now.
