### ISSUE TITLE
Modular cabinet

### ISSUE THREAD

**Issue by Diabetesmellitus** [Uuvana-Studios/longvinter-windows-client#1161]
las cajas modulares no las puedo abrir en mi casa, las que se encuentran encima de otras cajas, debo perder mis objetos por esto.

**Comment by BonesIsLive** [comment]
Por favor, la próxima vez sigue el formato adecuado de reporte. 
Es posible poner hasta 2 cajas modulares una sobre la otra y acceder a ambas sin problema, para acceder a una tercera o cuarta tendrás que ayudarte de subir a un taburete o una mesa.
