### ISSUE TITLE
My stuff disapeared

### ISSUE THREAD

**Issue by LilGoldPiggy** [Uuvana-Studios/longvinter-windows-client#1163]
My friend died so ofc he lost his stuff, so i was trying to take it back but many people was there. So ok it's so far. BUT the point is that i've got a bug, all my stuff disapeared. I tried to disconnect and reconnect because I thought it was just a small bug. But then when I reconnected everything was gone. And I was at a safe place the city lake where you can't die from people. 

**Expected behavior**
MY STUFF BACK

 - Steam Version [e.g. 1.0]

**Comment by BonesIsLive** [comment]
this is not a proper report... the servers have been having issues, the stuff might still be there, it could be just failling to load

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
