### ISSUE TITLE
Rollback of my character

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1165]
[](url)Hi.
My character went back in time. I'm shocked
Last night (10.08.22, 01:00) I went out in a tent in a winter biome. The yen had 50000 thousand coins. Today (10.08.22 21:00) I went to the server fond found myself at Mrs snow Outpost from 11000 money and strange inventory. Also i don't have quest. Can we help me?
![2022-08-09 (1)](https://user-images.githubusercontent.com/111048398/184100072-7acee392-65e8-4cc3-b152-1a5d63fbbfc0.png)
![2022-08-09 (3)](https://user-images.githubusercontent.com/111048398/184100104-778387f8-9d13-4be6-99b4-bfaa6ee1f2b8.png)

**Comment by biffotmc** [comment]
we are sorry for the rollback, however we cannot give you back your items since we have no record of what you had. Sometimes this will happen and we are very sorry it happened to you.

**Comment by AJIbPHA** [comment]
i have are compendium too, and now me need make this again? serioslu?
