### ISSUE TITLE
i can't get out from a house :(

### ISSUE THREAD

**Issue by tsankinn** [Uuvana-Studios/longvinter-windows-client#1167]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by gmbrothers** [comment]
The main reason for this would be because you have placed an item in front of the door and it kicks you out every time. Sadly there is not a way to fix this at the moment. Please use the template next time. 
Have a good day, gmbrothers

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
