### ISSUE TITLE
아이템 사라지는 버그가 있어요

### ISSUE THREAD

**Issue by JUHYUN96** [Uuvana-Studios/longvinter-windows-client#1169]
**Describe the bug**

**To Reproduce**
1. 게임플레이를 하고 있읍니다.
2. 길 가다보니 아이템이 사라져있네요.
3. 제 전재산을 잃었읍니다 ㅠ.ㅠ
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by MineMy** [comment]
Duplicate of https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1160

**Comment by faketucker** [comment]
Duplicate of #1160
