### ISSUE TITLE
Turrets can't shoot over fences

### ISSUE THREAD

**Issue by Kusivelho** [Uuvana-Studios/longvinter-windows-client#117]
**Describe the bug**
I placed a turret on my yard and it can't shoot over the fence. I've been killed couple times by turrets that are shooting from fenced yards, why mine are shooting at the fences (and eventually destroy them)?

**To Reproduce**
1. Place a Turret next to your house
2. Turret won't shoot targets behind the fence, they just destroy your own fence

**Expected behavior**
Turrets shooting over the fence, I've seen it happen everywhere else.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by amorrenicole** [comment]
Could it be that theirs were put on something like benches or stools?
They appear higher and eventually shoot over fences too. If you keep them on the ground you rather won't harm people outside but rather who wants to get inside.

**Comment by sirNugg3ts** [comment]
Just tested this and this bug is indeed present

**Comment by Jalsson** [comment]
This is intended

**Comment by cmod31** [comment]
Put the turrets on bushes
