### ISSUE TITLE
why can't I upgrade my house?

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1170]
why can't I upgrade my house?
![2022-08-18 (73)](https://user-images.githubusercontent.com/111048398/185491743-e5f734b3-ed7d-4d6f-8733-55294d8c5d5b.png)
![2022-08-18 (69)](https://user-images.githubusercontent.com/111048398/185491862-43abe0d9-0d43-407f-9d8b-292ee72dc5c7.png)

**Comment by gmbrothers** [comment]
You cannot upgrade your house because of the windmill

**Comment by faketucker** [comment]
Duplicate of #1131
