### ISSUE TITLE
All servers have been reset.

### ISSUE THREAD

**Issue by ethan2ooo** [Uuvana-Studios/longvinter-windows-client#1172]
It was fine until a few hours, but all servers were initialized. I was using a Uuvana 6 server and I had a house and a lot of items, but when I suddenly entered the game, all the servers were reset.

**Comment by ethan2ooo** [comment]
please someone can solve this problem. Help me.

**Comment by biffotmc** [comment]
Servers have just wiped, join our discord [here](https://discord.gg/longvinter) for announcements about wipes, although we are now moving away from wipes as soon as we can.
