### ISSUE TITLE
A message appears stating that the fence cannot be installed

### ISSUE THREAD

**Issue by eorrhd** [Uuvana-Studios/longvinter-windows-client#1175]
![20220820134450_1](https://user-images.githubusercontent.com/111625224/185729319-2c2a06cc-b2a4-4da0-9c25-3b454af114ad.jpg)
![20220820134503_1](https://user-images.githubusercontent.com/111625224/185729320-70465b5c-d670-46ec-8446-eb5ebedf7ebc.jpg)
![20220820134507_1](https://user-images.githubusercontent.com/111625224/185729321-6e5f7e99-6c06-4c52-8b46-9bdeeab1f300.jpg)

[KR] Uuvana 3
This is my house located at satellite 9S/7W.
A message appears stating that the fence cannot be installed as shown in the image at this time.
Please solve the problem.

**Comment by faketucker** [comment]
You try to place things too close to POIs. Maybe there's a bird spawn there or some POIs. That's why you can't place it.
