### ISSUE TITLE
Wrong animation with boat in experimental

### ISSUE THREAD

**Issue by d3dx9** [Uuvana-Studios/longvinter-windows-client#1176]
**Describe the bug**
While traveling by boat, the animation goes through land, see screenshot

**To Reproduce**
1. Go by boat

**Expected behavior**
Seeing water instead of land

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.imgur.com/v3z52KC.jpeg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 11
 - Game Version [e.g. 1.0] 1.0.9
 - Steam Version [e.g. 1.0]

**Comment by faketucker** [comment]
This is for stable version bug tracking only. Check out the #🧪-experimental-longvinter channel on our [Discord](discord.gg/longvinter) to report bugs.
