### ISSUE TITLE
Decrease and randomise loot spawn

### ISSUE THREAD

**Issue by amorrenicole** [Uuvana-Studios/longvinter-windows-client#118]
**Is your feature request related to a problem? Please describe.**
Running around I just noticed that it's really easy to loot or farm things from around your house because the same things keep respawning.
For instance cloudberries and other bushes spawn so often that's it's easy to create seeds and with that farm jam and other things you need for energy drinks or cakes etc.
I would recommend setting the spawn of flowers, bushes and loot more randomly instead of fixed places
I dont know if that's possible but that's what I think based on going on my loot trip right now
Would the surviving aspect increase too since you won't know where berries spawn to feed on them

**Describe the solution you'd like**
I would recommend setting the spawn of flowers, bushes and loot more randomly instead of fixed places.
I dont know if that's possible but that's what I think based on going on my loot trip right now.
Would the surviving aspect increase too since you won't know where berries spawn to feed on them. Plus removing some loot containers to increase the time of a loot expedition. This way people won't have the same things 6x because they are this easy to find.

**Comment by Bunnbunnnn** [comment]
Documented in on forum as 
-Make spawn of bushes, flowers, etc to be more random

Linking for reference
