### ISSUE TITLE
missing items

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1184]
when I put something in my house on the second floor, it breaks. I can pick it up and put it back on but I can't see it...
![2022-08-23 (59)](https://user-images.githubusercontent.com/111048398/186262610-53043641-12d3-4e4f-90f6-2e316ea629ff.png)

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.

**Comment by AJIbPHA** [comment]
but what i need to do?
