### ISSUE TITLE
1. The space bar is not working. 2. The water graphic looks white.

### ISSUE THREAD

**Issue by hotyuri111** [Uuvana-Studios/longvinter-windows-client#1185]
**Describe the bug**
1. ★The space bar is not working. (Pick up items, get out of the tent)
2. The water graphic looks white.
 I can't play the game because of these two things. PLEASE HELP ME play the game.

**To Reproduce**
4. Scroll down to '....'
5. See an error

**Expected behavior**

**Screenshots**
(problem no.2)
<img width="960" alt="화면 캡처 2022-08-24 143433" src="https://user-images.githubusercontent.com/111833883/186337566-6abf339f-b5e5-44be-989e-50ce16ae998d.png">

**Desktop (please complete the following information):**
 - OS:  Window11
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by MineMy** [comment]
I think you have those 2 issue. Why don't you try this way to fix 'em?
* https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1109#issuecomment-1198738999
* https://github.com/Uuvana-Studios/longvinter-windows-client/issues/1109#issuecomment-1198738999
