### ISSUE TITLE
why i can't pick up my staff?

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1186]
why i can't pick up my staff?
![2022-08-24 (1)](https://user-images.githubusercontent.com/111048398/186374729-0d6b9d63-00a8-46ff-b8ba-0cd859a2985e.png)

**Comment by MineMy** [comment]
Sadly, you cannot get items that are deep in the water by game design.
There's nothing todo.

**Comment by faketucker** [comment]
Duplixate of #450
