### ISSUE TITLE
A ton of things in my yard will apparently despawn 

### ISSUE THREAD

**Issue by Lyuvn** [Uuvana-Studios/longvinter-windows-client#1188]
**Describe the bug**
When I hover over all my fences and my planter in the red circle (my fooking weather machines too) it says theyll despawn in 8hrs but everything else is fine. I did have a tent on the x mark but its disappeared. It did overlap my yard so I guess that's why? RIP. But then why would the tent despawn before my items in the yard? 

**To Reproduce**
1.  Have house with a whole yard and a million fences. Put a tent next to the house where the perimeter will overlap the yard 
2. I guess everything that overlapped will despawn 
3.  ????
4.  Profit

**Expected behavior**
My stuff not to despawn because my house is full of wood 

**Screenshots**
![Screenshot 2022-08-25 150947](https://user-images.githubusercontent.com/112097825/186689337-9044e45e-acc7-4039-9743-dafab08be2d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11?
 - Game Version 8b
 - Steam Version idk

**Additional context**
I'm on US east Uvvana 5

**Comment by Mikooboy** [comment]
This should be fixed in the next update
