### ISSUE TITLE
House despawned

### ISSUE THREAD

**Issue by kirito31313** [Uuvana-Studios/longvinter-windows-client#1189]
**Describe the bug**
My house has turned invisible and become non interactable/ showing no border , the house shows up when i enter my building next door but its dark inside, the fence line along with said property disappeared, possible caused by a tent being placed nearby and being near a poitn of interest please resolve this house was oaky for 4 daays before the issue occured.

**Expected behavior**
i expect this to be looked into and fixed and my house replaced with all upgrades
**Screenshots**

![Screenshot 2022-08-25 174024 long vinter inside ](https://user-images.githubusercontent.com/112109837/186722253-40a51764-35df-4fa2-8a96-c0c1f2736aa4.png)
![Screenshot 2022-08-25 174112](https://user-images.githubusercontent.com/112109837/186722255-f7839bbc-e09e-424f-a5f8-a47ec7f4d9bf.png)
![image](https://user-images.githubusercontent.com/112109837/186722572-f135bf94-b097-4082-85f5-79c0cd144aa3.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version [e.g. 1.0.8.b
 - Steam Version upto date version 
**Additional context**

**Comment by faketucker** [comment]
Make sure you put some wood in the workbench to prevent it from decaying, but houses or progress can be lost due to the server crashes or restarts, and there's nothing we can do to bring them back.

**Comment by kirito31313** [comment]
how can this be closed as completed surely if houses and progress is being lost surely this shows the update method needs changing, why are servers no closed for updates so it can be saved then an update rolled out correctly identifying nay issues such as half the server loosing progress for example,

**Comment by kirito31313** [comment]
also, you can see in the image it's not because of wood you can see the house is clearly still there its just invisible however all my items remained inside
