### ISSUE TITLE
BUG - reset my compendium

### ISSUE THREAD

**Issue by san1tap** [Uuvana-Studios/longvinter-windows-client#1193]
![2](https://user-images.githubusercontent.com/112166830/186874576-e8046b63-9df1-4a42-b3e0-780d7978dafc.png)

i had two compendium was finished (fish, plants). Today 0

**Comment by faketucker** [comment]
Progress can be lost due to the server crashes or restarts, and there's nothing we can do to bring them back.

**Comment by faketucker** [comment]
Duplicate of #600
