### ISSUE TITLE
Lost all my equips/ inventory when logging out

### ISSUE THREAD

**Issue by OlManTerrance** [Uuvana-Studios/longvinter-windows-client#1194]
The Bug
Whenever I log out of Uuvana 1 by selecting 'disconnect' I lose all of my inventory and equips (apart from my ammo and Cash).

1. Go to Uuvana 1 server
2. Equip items/ Ammo/ have items in inventory
3. Exit via the disconnect button
4. Log back in via Play instead of Continue to view error

**Expected behavior**
You should see your inventory/ equips missing

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Game Version 1.0.8.b
 - Steam Version same?

**Additional context**
I was being shot at, at the time. Please can I get my stuff back too

**Comment by faketucker** [comment]
Logging off while in combat status will result in the loss of all of your items.
