### ISSUE TITLE
House to close to rocks and won't allow second story upgrade

### ISSUE THREAD

**Issue by OlManTerrance** [Uuvana-Studios/longvinter-windows-client#1197]
**Describe the bug**
I am too close to a pile of rocks and there is no option to move the building at all to allow a second story upgrade after colelcting all the wood and lightbulbs needed

**To Reproduce**
1. Clear all surrounding trees
2. Deposit all needed requirements for building upgrade
3. Select Upgrade
4. See an error 

**Expected behavior**
I expected the building to move slightly to allow for the upgrade or allow a different 'placing' or 'building mode' to place down the new bigger house (within a certain range.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.8.b
 - Steam Version 1.0.8.b

**Additional context**
Just annoying after collecting all that material that I just won't be bale to use this function. Any way to do this would be greatly appreciated, I'm sad and wasted a lot of time on it

**Comment by Jalsson** [comment]
Second story upgrade does check other collisions anymore because it was too hard to get it right. It has been disabled and this issue should no longer appear
