### ISSUE TITLE
Planted Cloudberries Dissapear

### ISSUE THREAD

**Issue by GeraldTheCarrot** [Uuvana-Studios/longvinter-windows-client#12]
**Describe the bug**
After planting a Cloudberry with its seed, the bush disappears after it is fully grown

**To Reproduce**
1. Plant a Cloudberry Bush seed
2. Wait for the bush to grow
4. Bush dissapears

**Expected behavior**
A fully grown Cloudberry bush should appear for me to harvest

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0
 - Steam Version (Latest)

**Additional context**
Lost my cloudberry bush 3 times, thought I kept forgetting so I asked my friends to help me confirm that I'm not going crazy

**Comment by sirNugg3ts** [comment]
If possible, record a video with this happening

**Comment by sirNugg3ts** [comment]
no more information was given. Closing issue
