### ISSUE TITLE
need help from cheaters, eu uuvana 1

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1200]
eu uuvana 1
lina
need help from cheaters
i and my friend fight from two guys in the arena, and kill 2 more times one guys. For this i have agresive...
![2022-08-30 (109)](https://user-images.githubusercontent.com/111048398/187440949-b60be4fe-7892-4a83-bfc2-4e1234c5c707.png)
 but in the moment my all inventory get down to the ground. And in this time my friend and one more guy has die. 
I started to loot everything from the earth that I had time. 
On the screenshots you can see how I still have traces of a backpack even though it was not worn.
![2022-08-30 (112)](https://user-images.githubusercontent.com/111048398/187440732-6e64e352-7080-4999-9d6d-44260b9eebc5.png)
![2022-08-30 (113)](https://user-images.githubusercontent.com/111048398/187440779-8e1a8a2c-4284-40b1-a446-e72a89874fb9.png)
The cheater left the game and then came back in the little time. And later im logg of becouse scared to die.
After I walked back, and ALL MY KLOOT HAS GONE, I didn’t die, nothing, you can see the same amount of ammo. These screenshots were taken after 2 minutes since I left the game.
![2022-08-30 (114)](https://user-images.githubusercontent.com/111048398/187442159-ebe5c27e-6fe1-46d0-85c5-e72a097fcb01.png)
![2022-08-30 (115)](https://user-images.githubusercontent.com/111048398/187442210-f918c570-2163-4c1c-844e-ba2ba29d69a1.png)

**Comment by BonesIsLive** [comment]
This is not the proper way to report hackers, visit contact.uuvana.com and file a report there

**Comment by AJIbPHA** [comment]
im alredy

**Comment by faketucker** [comment]
Will handle this through the ticket
