### ISSUE TITLE
Reporting players and a logging who killed who.

### ISSUE THREAD

**Issue by aaaaaaaaaaaavm** [Uuvana-Studios/longvinter-windows-client#121]
Everyone on the Singaporean server has been menaced by this blue shirt guy who carries an assault gun, kills everyone in sight, loots stuff, and kills people over and over by spawn camping at their bases. Especially to the newbies or the farmers without turrets. Even if you have a turret, he waits for you to come out of its firing range and then kills and loots people.

[This video](https://vimeo.com/683456094) is of him shooting everyone who was trying to access the vending machines or tried crossing the river to the other side by camping over there with his gun and a campfire. The people at the camps cant fire as he is on the other side and isn't visible also they would be killed by the turrets at the vending machine area.

There should be a way to report such players and there should be a log for the server owners to see if someone is truly going wild on the server, also for other players to see on their screen like "xxx was killed by zzz in a gunfight" or something like that the way different battle royales games have it on one side of the screen. 

Also, the way of knowing who is who only if they wave at you makes it impossible to know who is who and a lot of times creates confusion. Especially in our case where we could protect ourselves from this particular guy if we see his name tag. "Yellow shirt guy with a farmers hat is to be avoided" is a really hard way to do things. 

PvP is one thing, it is fun but harassing people online is some fucked up shit.

**Comment by aaaaaaaaaaaavm** [comment]
And now we have a red shirt guy doing the same thing on the same server, official singapore. ffs. I really love this game but shit like this, really makes me have a terrible time over here.

**Comment by Bunnbunnnn** [comment]
> There should be a way to report such players and there should be a log for the server owners to see if someone is truly going wild on the server, also for other players to see on their screen like "xxx was killed by zzz in a gunfight" or something like that the way different battle royales games have it on one side of the screen.

Yup! the devs are working on a more functional admin panel / functionality to help address these concerns.
