### ISSUE TITLE
issues with the entrance of the underground monument 

### ISSUE THREAD

**Issue by SirPoofsAlot** [Uuvana-Studios/longvinter-windows-client#1211]
**Describe the bug**

**To Reproduce**
1. Go to 'the underground monument'
2. hit the ' space bar anywhere inside it and it takes you back to the start of the monument. also hitting space out side of it and in a boat has a chance to break the game. i was under the map 'in a boat' when it finally stopped freaking out'

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 
 - Game Version [e.g. 1.0] 1.0.9

**Comment by BonesIsLive** [comment]
Please remember Experimental Branch reports have to be done in the Experimental channel on Discord, this GitHub is mainly to track main branch bugs.

**Comment by Jalsson** [comment]
Since this was an experimental issue it has been solved already. Closing this issue
