### ISSUE TITLE
invisible guards on the second floor of the monument

### ISSUE THREAD

**Issue by SirPoofsAlot** [Uuvana-Studios/longvinter-windows-client#1212]
title says it all
windows
1.0.9

**Comment by BonesIsLive** [comment]
Please file a proper report so we can track this accordingly. Remember bugs from Experimental Branch should be reported in the Experimental channel on Discord.

**Comment by SirPoofsAlot** [comment]
oh crap sorry sorry

**Comment by Jalsson** [comment]
Since this was an experimental issue it has been solved already. Closing this issue
