### ISSUE TITLE
I'm inquiring for a lawsuit for swearing.

### ISSUE THREAD

**Issue by sjs8655** [Uuvana-Studios/longvinter-windows-client#1213]
I don't know where to ask, so I'm leaving it here.

On 22.9.8 days, from 22:00 to 22.9.900:40, a phrase containing swear words was posted on the sign, and the victim is suffering a lot.

I want to punish the person who installed the sign and ask you to provide Steamid and Gameid.

This case is data and evidence for the accusation of honorary rehabilitation and asks for cooperation.

I would appreciate it if you send me the data by e-mail.

m : sjs8655@gmail.com
![3](https://user-images.githubusercontent.com/113159629/189271814-c2046c40-671f-4dc1-bed9-2d9cc0465fbe.PNG)

**Comment by sjs8655** [comment]
Location is 26E 5S

**Comment by BonesIsLive** [comment]
Hey there.

I'm really sorry about the inconvenience and we would love to help you, but we need you to first fill a proper report so we can track and treat this issue accordingly... You can do so by accessing > https://uuvana.com/contact <

Best regards,
Christian 'Bones' Falbi.
Uuvana Team.
