### ISSUE TITLE
I see the wather white

### ISSUE THREAD

**Issue by nicolasgp03** [Uuvana-Studios/longvinter-windows-client#1214]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by gmbrothers** [comment]
Turn on and off DX11 water in the settings.
