### ISSUE TITLE
집 두개가 붙어 있습니다

### ISSUE THREAD

**Issue by kkkkas** [Uuvana-Studios/longvinter-windows-client#1215]
모르는 사람과 집이 겹쳤다

서버가 사라지고 생긴 이후 내 집과 다른 사람 집이 합쳐져 있다

집 안 상자가 열리지 않는다
집에 벽이 생겼다
**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Game Version1.0.8b
 - Steam Version 1.0.8b

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
