### ISSUE TITLE
Can't place items on sand

### ISSUE THREAD

**Issue by gh0stlyn** [Uuvana-Studios/longvinter-windows-client#1217]
A path of sand appeared through my land after the new update. I cannot place anything on these parts leaving me unable to close off my fence. It says it is overlapping with something.
![7c09649a96cafb1c66280287734928e8](https://user-images.githubusercontent.com/103220758/190828068-ddd17de8-d2f3-4fd0-8372-ae2d83a5ab13.png)

**Comment by Jalsson** [comment]
This issue has been fixed in the current build of the game
