### ISSUE TITLE
Retrieving stuff that's underwater or in a weird place using a fishing rod.

### ISSUE THREAD

**Issue by aaaaaaaaaaaavm** [Uuvana-Studios/longvinter-windows-client#122]
**Is your feature request related to a problem? Please describe.**
If I die trying to swim to someplace, my stuff sinks. They should either be retrievable or just not be shown at all. [Example](https://ibb.co/7t84B0g).

Or a lot of times I die by getting stuck in places from where I can't retrieve my stuff, like when I was stuck between a tree and when I tried to chop it down, I was shot by a turret and I lost my stuff in an unretrievable area because if I try and chop the tree, I get shot again. Or where I died after I was stuck at this place for a long time but couldn't pick the stuff up because it was outside the area of what can be clicked.

**Describe the solution you'd like**
My idea for retrieving stuff, use a telescopic fishing rod and you can fish out the things from underwater or from those sticky places that you cant reach. 

**Additional context**
Also regarding the unclickable things, I cant seem to break and pick up things from behind my house. [Here's ](https://ibb.co/17NZgYn)a picture of a fence placed behind my house and here's a picture of it of me trying to break it and pick it from behind and unable to pick it.

My solution to this is to use a 2D map of the place when placing stuff or picking them up or use an even steeper camera angle. Or maybe just have an option to go 2D which you could toggle on or off when placing things.

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
- Allow to pick loot out of water
- Make building behind the house easier

Linking ticket for more details / reference.
