### ISSUE TITLE
Team invite not working when adding 3rd player

### ISSUE THREAD

**Issue by elow21** [Uuvana-Studios/longvinter-windows-client#1220]
**Describe the bug**
Team invite sent and accepted will show up with an error stating "Team does not exist" for the third player joining. 

**To Reproduce**
1. Have a team with 2 people
2. Invite a 3rd member
3. 3rd member accepts invite
4. Error "team does not exist"

**Expected behavior**
Team invite can be accepted and the 3rd player can join the team without issues. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.9
 - Steam Version latest

**Comment by faketucker** [comment]
Duplicate of #830
