### ISSUE TITLE
Backpacks despawning before returning to point of death.

### ISSUE THREAD

**Issue by StrungUpSystem** [Uuvana-Studios/longvinter-windows-client#1221]
**Describe the bug**
Every time I've died on the PvE server since the 1.0.9 update, I've gone back to the spots I've died to retrieve my backpack, and the backpack despawns, but the items under EQUIPMENT haven't.

**To Reproduce**
1. Have inventory full of items
2. Die to the environment (in my case, cold status effect)
3. Make way back to deathpoint

**Expected behavior**
Backpack will be gone from the spot where your items dropped upon death

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 1.0.9
 - Steam Version: uhhh... most recent?

**Additional context**

**Comment by Jalsson** [comment]
This is fixed in the latest hotfix
