### ISSUE TITLE
Screen stuck on birds eye view of the island

### ISSUE THREAD

**Issue by elow21** [Uuvana-Studios/longvinter-windows-client#1223]
**Describe the bug**
When loading into AU Uvanna 1 server, screen is stuck on a bird's eye view of the island. Occassionally, flickers back to the player and goes back to birds eye view. Can't type /kill or move. 

**To Reproduce**
1. Hop on boat and go to the edge of the map
2. Screen goes black and flickers
3. Disconnect and reconnect 
4. Stuck birds eye view

**Expected behavior**
When out of bounds, teleport player back to dock or house. 

**Screenshots**
https://user-images.githubusercontent.com/54529136/190903910-a80dcd11-6be2-499b-8ce9-d53ab1838d1b.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.9
 - Steam Version latest

**Additional context**
Player can join other servers without this issue occuring. It seems to only happen at AU Uvanna 1 server.

**Comment by Jalsson** [comment]
The cause of this bug is unknown, but you can do /kill it by going to general settings and doing a character reset. This will kill your character and return it to respawn normally
