### ISSUE TITLE
Houses losing fuel immediately that is put in them

### ISSUE THREAD

**Issue by worthij92** [Uuvana-Studios/longvinter-windows-client#1225]
**Describe the bug**
My houses were zeroed out on fuel so I went to stock both of them with fuel, went somewhere else and came back and half of my turrets weren't working due to lack of power. Realized one of my houses said no fuel when I had just put some in, put more fuel in then walked out of house for the other half of my turrets to quit working and then that house said it had no fuel even though I had just replaced it.

**To Reproduce**
4. See an error

**Expected behavior**
For plenty of fuel to not almost immediately get used in my houses. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version 1.0.9]
 - Steam Version [up to date]

**Additional context**

**Comment by Jalsson** [comment]
I belive this issue was caused by the clock that consumes fuel was not reset every time it consumed 1 fuel, this meant the house was consuming 1 fuel every minute.
