### ISSUE TITLE
Can access campfire using the space key after it decays

### ISSUE THREAD

**Issue by zennjamin** [Uuvana-Studios/longvinter-windows-client#1233]
**Describe the bug**
After placeing a campfire and letting it decay, you can walk up to where it was, hit the space key, access it, and make use of it.

**To Reproduce**
1. Place a campfire anywhere you are able to.
2. Wait for the campfire to decay.
3. Hit the space key while next to the area where the campfire was placed and decayed.
4. See that you can still access the campfire and make use of it.

**Expected behavior**
After a campfire decays you should not be able to access and use it.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version: Beta 1.0.9
 - Steam Version: Up to date

**Additional context / info**
The phantom campfire object gets cleaned up after a server restart and can no longer be accessed from where it used to be.

**Comment by Jalsson** [comment]
This is fixed in update 1.0.9b
