### ISSUE TITLE
Safezone turrets shoots you to inside your home.

### ISSUE THREAD

**Issue by mysticmasterfin** [Uuvana-Studios/longvinter-windows-client#1235]
**Describe the bug**
Location Heisala.
Inside of the safe area if you have a home.
and you are inside the home and swing axe or weapon the zone turrets can shoot you. RIP.

**To Reproduce**
1. Go to '...' heisala
2. Click on '....' shoot
3. Scroll down to '....' nope
4. See an error.  get damage

**Expected behavior**
not get shot from the outside.
**Screenshots**
https://youtu.be/xT8CQFLwGkE
https://youtu.be/7HhUhDnPDVE
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Mikooboy** [comment]
Added a check for turrets so that they will not shoot underground in the next update
