### ISSUE TITLE
open server error

### ISSUE THREAD

**Issue by baejhon** [Uuvana-Studios/longvinter-windows-client#1238]
[2022.09.24-11.36.32:008][893]LogEOS: Error: UpdateSession: Successfully updated session 'My server' with ID '80e0d8056635493cab23a676f851452a'
I can't open the server. [2022.09.24-11.36.32:008][893]LogEOS: Error: Update Session: Successfully updated session 'My server' with ID '80e0d8056635493cab23a676f851452a'.
I think the program doesn't recognize 'game.ini'.
The server program cannot read tags, administrators, server names, and server settings.
I set the server name, but it is printed as "My Server". And the manager EOS also comes out differently. Maybe it's the default.

**Comment by faketucker** [comment]
Can you provide your Game.ini file?

> '80e0d8056635493cab23a676f851452a'

This is a server ID, not an administrator ID.
