### ISSUE TITLE
Items floating inside house

### ISSUE THREAD

**Issue by Manofixe** [Uuvana-Studios/longvinter-windows-client#124]
**Describe the bug**
Whenever you try to remove a painting from the wall inside of your house, it goes out of bounds

**To Reproduce**
1. Go to 'inside house'
2. Place painting in a wall
3. try to remove the painting from the wall

**Expected behavior**
i expected the painting to fall onto the ground to pick it up

**Screenshots**
![Floating bag](https://user-images.githubusercontent.com/100613699/156243896-5197bded-a3f8-4293-89ff-10a32473ee4a.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Fixed and pushed to next update
