### ISSUE TITLE
Stuck inside the world

### ISSUE THREAD

**Issue by EvGaming** [Uuvana-Studios/longvinter-windows-client#1248]
**Describe the bug**
I was just paddling along in my boat when i dropped out of the world and cant interact at all. i cant type so i cant /kill, and re logging and verifying files doesnt cause me to spawn either. could someone kill me or get my location changed? 

**To Reproduce**
1. Go to '...' im not really sure, i hit a lag spike when boating
4. See an error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your [problem.](
https://user-images.githubusercontent.com/59549998/192677658-7251f351-8143-4f93-abd1-3c4f4a1a8f44.mp4
)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 11
 - Game Version [e.g. 1.0]  1.0.9
 - Steam Version [e.g. 1.0] v020 steam package versions: 1663887315

**Additional context**

**Comment by honkers8842** [comment]
https://user-images.githubusercontent.com/59549998/192678043-3904e9a2-baa8-4811-9ff5-b64bf9e14e8d.mp4

**Comment by Jalsson** [comment]
If you are experiencing this issue. In the last update, we added a "reset" button in the general settings tab. This will respawn your character normally and you can continue playing.
