### ISSUE TITLE
TImers on how long something can remain un upgraded

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#125]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] There are a lot of tents just laying around taking up space/abandoned, This is killing potential for new players to find new promising land and for more established players to expand on that unused land. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. There should be a timer on how long you can keep something in the unbuilt state maybe even a requirement that needs to be upkept to maintain a home for example, a new craft called "Power generator" you have to build that to keep your house running if your generator is destroyed a player can be given x amount of days to restore the generator before losing the home i think this will force players to commit more to an area rather than spam it with tents it will also lessen the amount of people hovering more elite zones like the arena without putting in the effort to survive and upkeep there, when building a tent you're given a timer prompt of how long it can remain a tent before being deleted, the timer stops when you build a house and now you're given a more extended time to build a generator time/days w/e, if this becomes a thing it can be a craft made at your stable that adds a visable generator to your house which can be attacked and destroyed which leads to the process of "if you don't repair this in x amount of time or days you lose this property" 

**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Tent decay and limit already implemented in game 

House decay documented in forum as 
- Destroy / decay other`s tents / homes / ability to remove
