### ISSUE TITLE
Allow Remapping of [E] key for fishing 

### ISSUE THREAD

**Issue by Bunnbunnnn** [Uuvana-Studios/longvinter-windows-client#126]
**Is your feature request related to a problem? Please describe.**
When I fish, I like to type in the discord or unfocus the game, but this causes problems while fishing because I have to first click into the window before I can push E and the window to catch the fish is normally ending while I LMB back the screen into focus. 

**Describe the solution you'd like**
I would like to be able to remap E to LMB so when I click in the window, its to catch the fish. 
It would greatly increase my exp while fishing. 

**Describe alternatives you've considered**
I have tried to look and see what keys are remap-able but do not see E as an option to change.

EDIT: 

![image](https://user-images.githubusercontent.com/100467604/156261067-3241a448-829f-4408-bec0-d43f11601bf6.png)

Another idea is to make part of the UI where we have to click on the exclamation mark and a fish icon rapidly with LMB to get the fish would be really nice too. 

I also find that I accidently rapidly hit "R" or mash some other key on accident when I thought my finger was on E and I  miss out on my fish and is frustrating (for me at least)

**Comment by 5qu34k99** [comment]
I'd like it if this and other keys were remappable as well.

**Comment by Bunnbunnnn** [comment]
Already documumented on forum and roadmap for passive fishing
