### ISSUE TITLE
Campfire not opening to cooking menu 

### ISSUE THREAD

**Issue by Bunnbunnnn** [Uuvana-Studios/longvinter-windows-client#1261]
**Describe the bug**
Some campfires are not giving the cooking menu open. I'm right up on any campfire near a port and trying to hit space bar to cook. Nothing happens or changes, but I am able to cook at a gas stove in my tent. I tried left and right clicking all around the campfire. As well as having my inventory open and hitting space bar and/or clicking. POI & port campfires have this problem for me. 

The stone fires & campfires from players do work for the menu

**To Reproduce**
1. Go to campfire 
2. Hit space bar and nothing 
3. relogg and try again and nothing 
4. mouse click and nothing 

**Expected behavior**
For the cooking menu to come up so I can cook at POI or port campfires

**Screenshots**
![image](https://user-images.githubusercontent.com/100467604/194787657-9e725686-860a-456c-a8dc-8fcfe37522ac.png)

**Desktop (please complete the following information):**
 - OS:Windows 
 - 1.0.9

**Additional context**
Submitted this ticket on behalf of discord user swiftserpents#3095

**Comment by ryanEnigma** [comment]
haven't done it in a few days, but the fires near the arena allow me to cook, but fires near ports do not allow cooking, eg: the fire near Jax outpost on koilot
