### ISSUE TITLE
dead spot in safe zone

### ISSUE THREAD

**Issue by phloyddd** [Uuvana-Studios/longvinter-windows-client#1265]
**Describe the bug**
i reported this earlier on discord and just dm'd cow about it but there's a dead spot in the safe zone by arena 2.

**To Reproduce**
Just go to arena 2 and go to 23N 63W right near the angled fence.

**Expected behavior**
To be a normal safezone with no gaps in it.

**Screenshots**
![dead spot](https://user-images.githubusercontent.com/101691352/195958377-e02145f5-4cbe-4058-8cae-b1363ff4d593.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Extended the safe zone area to this point. Change will take affect in next update
