### ISSUE TITLE
Bag dropping when waving

### ISSUE THREAD

**Issue by scribbl** [Uuvana-Studios/longvinter-windows-client#1269]
**Describe the bug**
When getting shot, either by a person w/ a gun or a turret and you wave, your bag drops.

**To Reproduce**
1. Get shot by a turret or a person with a gun
2. Wave
3. bag drops

**Expected behavior**
Bag not dropping

**Screenshots**
https://youtu.be/OMtryt6CE1M

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - Game Version 1.0.9
 - Steam Version v020 (package version 1665183764)

**Comment by Jalsson** [comment]
The player dropping the bag has the wrong version of the game which causes them to disconnect when they wave because of the no combat logout feature. Closing since there is no bug present
