### ISSUE TITLE
All crates disappeared

### ISSUE THREAD

**Issue by worthij92** [Uuvana-Studios/longvinter-windows-client#1270]
**Describe the bug**
All crates disappeared in two of my houses. I did /kill to respawn as I am in two different parts of the map with my husband, not sure if that the /kill is relevant but figured I would include it. All of my crates are still "there", but invisible so I have to access by guessing location and pressing spacebar or clicking. Walked in and out of the house and they are still missing

**To Reproduce**
4. See an error

**Expected behavior**
For crates to be visible =)

**Screenshots**
![image](https://user-images.githubusercontent.com/106206104/196054586-5906626b-85e4-4c50-965e-2a82e756799c.png)

and there were crates all over the bottom floor of these houses

**Desktop (please complete the following information):**
 - OS: windows 10]
 - Game Version [1.0.9]
 - Steam Version [up to date]

**Additional context**

**Comment by Jalsson** [comment]
Chest saving system has been changed since this update, closing this for now because this issue has not happened after the new chest saving system change
