### ISSUE TITLE
Vending Machine Buy Order Bugged 

### ISSUE THREAD

**Issue by ghost** [Uuvana-Studios/longvinter-windows-client#1276]
**Describe the bug**
"the new option to buy items via your vending machine is bugged. After about a day the buy order glitches out and looks like this. No clue what causes it. The bought items also don't show up in the item tab."

"I added the buy order for 24 sugar bags, 24 wheat bags in one machine and 24 empty bottles, 24 tea bags and 24 coffee beans in another machine. The next day I checked my machines and the buy order was glitched like in my screenshot. The buy order went down on some items indicating someone sold me something but Items don't show up in the Items tab." 

"I'll leave the machines as they are for now if anyone wants to come and check again. The coordinates for my house are 43°S/23°E on Heisala EU1" 

**To Reproduce**
1. Adding a buy order
2. Log back in after a day 
3. Buy order is bugged for me and players

**Expected behavior**
To have the buy orders to stay on the UI & to properly buy what I want.

**Screenshots**
Player Buyer / Seller view
![image](https://user-images.githubusercontent.com/100467604/197565044-d534fab0-599f-4d10-818d-806ff9508464.png)
![image](https://user-images.githubusercontent.com/100467604/197565072-65493e5a-68d4-4ed6-bd02-b665dc7a0268.png)

Owner View
![image](https://user-images.githubusercontent.com/100467604/197565185-761b40c6-cf77-4cb1-aae2-bc4f6c9b7fb9.png)

Issue ticket created on behalf of discord user Sir Nicolas#8642

**Comment by Jalsson** [comment]
Thank you for detailed report. New item values were not saved correctly and this caused the issues that are presented here. This will be fixed in next update
