### ISSUE TITLE
Black Screen upon logging into Uuvana6

### ISSUE THREAD

**Issue by tsalheiser** [Uuvana-Studios/longvinter-windows-client#128]
**Describe the bug**
Logged out while in my house. Upon Logging back into Uuvana6 I was greeted with a black screen. Could only see the workbench and furnace.

**To Reproduce**
1. Log into Uuvana6

**Screenshots**
![Capture](https://user-images.githubusercontent.com/100736835/156272573-100a84aa-70e1-4cc6-8c1e-976ead73bf0e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.0

**Comment by sirNugg3ts** [comment]
just tried a couple of times and couldnt replicate. if you are stuck, use alt+k or /kill in chat
