### ISSUE TITLE
Achievements still broken

### ISSUE THREAD

**Issue by ClickyCrisp** [Uuvana-Studios/longvinter-windows-client#1287]
### _**Description**_

_Same issue(s) as #1286, #691, #620, #776 and exactly as #421_

- Cannot get 5 broken achievements. (Tested all my remaining locked aside from 10 and 100 kills)
- I was in a team with my better half and every time I cut down a tree they got a steam achievement progress update popup adding +1 to their 100 trees cut achievement, not me.
- Partner achieved 100 trees cut, I never did. Aside from that one, we are missing the same amount of bugged achievements.
- I have tried collecting all plants on EUW Uuvana 2, as well as NA Uuvana 2 and Uuvana 5. No achievement.
- Attempted on "Game Version 1.0.8" **as well as** the current "Game Version 1.0.9b"

![bug1](https://user-images.githubusercontent.com/74375454/199508755-67199538-d940-4b6f-9f7a-8da2dd3e74cd.jpg)
![bug 2](https://user-images.githubusercontent.com/74375454/199509099-314f722c-1243-48bc-99d7-162ab610dc82.png)

### **_To Reproduce_**

1. Get all fish in your first 10 hours of gameplay.
2. Chop down 100 trees, complete all other compendium tabs, heal yourself to full health after having 1 health point.
3. Steam Achievements don't update.

### **_Expected behaviour_**

Able to achieve Steam Achievements.

### _**Desktop:**_

OS: Windows 10 (64 bit)
Game Version: 1.0.9b
Steam Version: Latest (1666144119)
![steam vers](https://user-images.githubusercontent.com/74375454/199513247-f4ce840a-fb68-4e80-88e0-57a37b69d940.png)

### **_Additional Context_**
I've chopped down about 200 trees, completed the fishing compendium tab twice on 2 separate NA servers, completed the plants compendium tab 3 times including an EU server. Tried these all months ago in June, and again this month. Reinstalled, deleted ALL registry items and folders using RevoUninstaller and **THEN** reinstalled yet another time. Still no luck.

If I can give anymore information that might help then please let me know, I know this has been reported as fixed in the past but I still see many reports of this problem coming up again, not sure what else to say because I've tried everything, please help, thank you very much and have a good day! <3

**Comment by Jalsson** [comment]
Thank you for the detailed report.

Looked into this and for some reason, the compendium check was not run on any occasion. Next update the compendium achievements should unlock properly. I looked into the woodcutter achievement as well and I found the mistake that resulted in the achievement being to given the first player that joined the server and not the player that was cutting the wood.

**Comment by ClickyCrisp** [comment]
Thank you very much Jalsson, I'll be sure to hop online immediately after the update is released and give it a go!
I'll reply to this if and when it works.
