### ISSUE TITLE
If you sell things to the vending machine, you won't get any money

### ISSUE THREAD

**Issue by plminseo** [Uuvana-Studios/longvinter-windows-client#1288]
**/Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Found the issue and it is now fixed in today's server hotfix
