### ISSUE TITLE
Full Screen Zoom Locks wrong

### ISSUE THREAD

**Issue by ThisPlatypus291** [Uuvana-Studios/longvinter-windows-client#129]
The auto zoom when entering a house breaks when entering and exiting sometimes. It will zoom in when I exit and then zoom way out when I re-enter the house

**To Reproduce**
1. Go into a house
2. Exit house
3. Screen glitches and zooms out weird

**Expected behavior**
It's supposed to zoom in inside the house and then zoom back out when you leave

**Desktop (please complete the following information):**
 - OS: windows 
 - Game Version beta 1.0
 - Steam Version beta 1.0

**Additional context**
Thought it might have something to do with leaving your inventory or crafting menu open when leaving the house, but it happened without that

**Comment by faketucker** [comment]
Seems like this was fixed
