### ISSUE TITLE
자판기에 버그가 있어요

### ISSUE THREAD

**Issue by byounggwan** [Uuvana-Studios/longvinter-windows-client#1293]
자판기에 ADD ITEM을 누르고 사냥 모자를 누른 후 가격을 최대치로 높이면 갯수 조정이 몇천개든 가능해지는데 그상태에서 자판기 수급을 누르면 마이너스 돈이 됩니다. 지금 제가 -1400만원 이상 으로 바뀌는 버그가 생겼어요..
![제목 없음](https://user-images.githubusercontent.com/118051149/201470051-ff097830-0d61-47bb-ac61-4bfde9c4a5d1.png)

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
