### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by SUNWOO53** [Uuvana-Studios/longvinter-windows-client#1295]
배를 타고 낚시를 하고 있는데 갑자기 배가 날아오르더니 벽을 뛰어넘었어요. 
그래서 배가 가끔 뛰는 걸 반대로 이용해서 다시 원위치로 가려고 하다가 배가 뛰어서 벽에 걸리자, 배에서 내렸는데 갑자기 캐릭터가 사라졌어요.
그 후에 온갖 방법으로 벽 안으로 가려다가 포기하고 죽었는데, 가방이 없어서 문의를 드려요.
해주실수 있다면 잃어버린 Bait Buster,The Reel Of Fortune, 어부모자, 보트를 돌려주세요.

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
