### ISSUE TITLE
Water isn't rendering, even after the hotfix. 

### ISSUE THREAD

**Issue by cojoyan** [Uuvana-Studios/longvinter-windows-client#13]
**Describe the bug**
The same as the title: Water isn't rendering, even after the hotfix. 

**To Reproduce**
There aren't steps to reproduce the problem, it has been happening since the first devlog was uploaded (I'm an old playtester).

**Expected behavior**
Water should look blue, transparent and wavy, not invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/100423371/155755523-2e11dcad-9af3-4f78-8d4f-d03aebf40f5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (21h2)
 - Game Version: Beta 1.0.0 (Last update until 14:05 GMT-3, 25-02-2022)
 - Steam Version: 1642451672 (Last update until 14:05 GMT-3, 25-02-2022)

**Additional context**

Dxdiag screenshots:

![image](https://user-images.githubusercontent.com/100423371/155756504-90bc97f9-1547-4969-894d-582069bd65d1.png)
![image](https://user-images.githubusercontent.com/100423371/155756552-3e0902f8-6103-4de4-bceb-47929fe60971.png)
![image](https://user-images.githubusercontent.com/100423371/155756601-4418aff8-5979-4754-8aa3-299196309fd2.png)

Dxdiag log (In English):

[DxDiag.txt](https://github.com/Uuvana-Studios/longvinter-windows-client/files/8143302/DxDiag.txt)

Any doubt, please contact; cojo#6974 in Discord.

**Comment by sirNugg3ts** [comment]
can you confirm this is still bugged?

**Comment by cojoyan** [comment]
yeah, i updated the game today, tried use the toggle and nothing

**Comment by cojoyan** [comment]
This was fixed with this (at least in my case):

![image](https://user-images.githubusercontent.com/100423371/156272550-c1f1bf96-e1b8-4ce8-8853-4fb964ffe403.png)

Credits to @DjKlzonez#7537
