### ISSUE TITLE
Turrets at Arena Destructable

### ISSUE THREAD

**Issue by Gorysporkman** [Uuvana-Studios/longvinter-windows-client#130]
**Describe the bug**
Turrets at the arena in the north can be destroyed

**To Reproduce**
1. Go to 'the arena'
2. equip gun and ammunition
3. place an object outside of poi range that will raise you high enough to shoot turrets
4. shoot turrets outside of their range

**Expected behavior**
Expected bullets to pass through the npc turrets like they do player turrets

**Screenshots**
![20220301201926_1](https://user-images.githubusercontent.com/69329048/156283647-c12b6b07-8cbf-485a-8653-013c02cc7d2b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0

**Additional context**
allows for indiscriminate killing of players outside of the arena

**Comment by Jalsson** [comment]
Fixed in the recent update
