### ISSUE TITLE
바다가 하얀색이여서 낙시를 못하겠어요

### ISSUE THREAD

**Issue by yuonge** [Uuvana-Studios/longvinter-windows-client#1300]
![KakaoTalk_20221114_231109908](https://user-images.githubusercontent.com/118191364/201681835-502039ee-7cb7-44e0-a5aa-607552ff6402.jpg)
3일째 이래요 좀 고쳐주세요!

**Comment by faketucker** [comment]
Toggle DX11 water in the settings.

**Comment by faketucker** [comment]
Duplicate of #13
