### ISSUE TITLE
게임하다가 집에 안들어가져서 게임 껐다 켰더니

### ISSUE THREAD

**Issue by August2821** [Uuvana-Studios/longvinter-windows-client#1302]
집에 안들어가져서 게임 껐다가 켰더니 아까 낚시하는 곳으로 캐릭터가 다시 생성됐어요.
아이템도 다시 전에 있던 상태로 바뀌었어요

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
