### ISSUE TITLE
Not able to pick up plants

### ISSUE THREAD

**Issue by AmetisRising** [Uuvana-Studios/longvinter-windows-client#132]
**Describe the bug**
Unable to pick up plants, was able to earlier in my playthrough today, and didn't notice anything out the ordinary and now I am unable to pick up the plants.

**Desktop (please complete the following information):**
 - OS: windows
 - Game Version 1.0.0

**Comment by AmetisRising** [comment]
Space picking up seems to be the issue. I can still open chests and interact with other objects with space, but not plants. I can apparently harvest them fine by clicking.

**Comment by AmetisRising** [comment]
I take that back, apparently me tabbing out to write this has taken the ability away to harvest with click now.

**Comment by AmetisRising** [comment]
Clicking is also not working 100&% of the time.

**Comment by KoalaBoy** [comment]
Facing same problem

**Comment by sirNugg3ts** [comment]
have no way to test this out. just logged in and could pick up plants both ways with no issue at all
