### ISSUE TITLE
Players Stuck In Place When Entering House At The Same Time

### ISSUE THREAD

**Issue by Lung314** [Uuvana-Studios/longvinter-windows-client#133]
**Describe the bug**
When people enter the same house at the same time, their character model gets stuck.

**To Reproduce**
1. Multiple people enter the same house at the same time
2. Players that enter the house first must not move upon entering

**Expected behavior**
Everybody is able to enter and move freely inside the house

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Beta 1.0.0
 - Steam Version: Beta 1.0.0

**Comment by Jalsson** [comment]
I changed a teleport function and it now spawns to entering players next to each other instead of on top of each other. It should be fixed in the next update.
