### ISSUE TITLE
Fire pits - Fire disappears and stop heating/regenerating stamina

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#135]
**Describe the bug**
The fire pit update has been good, however after some time or logging out and in [ which includes enduring another full character wipe >:( ] the fire from the pit is no longer visible for some (some can see it some cant) those who cannot see it also do not receive the regeneration from the fire pit.

Can be removed and replaced to fix the issue, however still a bug that will need fixing :)

**To Reproduce**
1. Place pit
2. Log out (get character wiped again)
3. Log in

**Expected behavior**
The fire and regeneration to stay without needing to re-place

**Screenshots**
I missed my chance to take a SS if i get another i will upload.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Ver 1.0.0

**Additional context**
Only happens to some people.

**Comment by Jalsson** [comment]
This was patched in todays update
