### ISSUE TITLE
SAFE ZONES not safe, turrets destroyed.

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#137]
**Describe the bug**
I witnessed a player build multiple bench seats to get to the right height and then shoot and destroy the turret at SGT LAKES base, now its not a safe zone and everyones being mass murdered.
(Server: US #2)

turret doesnt respawn, also shouldnt be destructable!?
please fix ASAP

New players are getting slaughtered.

**To Reproduce**
1. build a few bench seats like stairs to match height of turret
2. shoot and destroy turret

**Expected behavior**
Either invulnerable or respawning turrets in towns to keep players safe - also note that the arena turrets are destroyed too. 

**Screenshots**
![image](https://user-images.githubusercontent.com/100509746/156311267-b94e96a1-6fad-4361-9cda-be2882cd0c82.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 1.0.0
 - Steam Version ?

**Additional context**
this has now happened to ALL nps turrets on US 2 Server.

**Comment by sirNugg3ts** [comment]
Turrets should be fixed in the last patch
