### ISSUE TITLE
People can't shoot when they stay in this line. it should be fixed. 

### ISSUE THREAD

**Issue by atillabulud** [Uuvana-Studios/longvinter-windows-client#1376]
People can't shoot when they stay in this line. it should be fixed. 

![sdfsdfsdfsfd](https://user-images.githubusercontent.com/105663995/213917638-01ab4ed1-dc1c-4d55-bf1a-e32b9e78373d.PNG)
![sssssssssssss](https://user-images.githubusercontent.com/105663995/213917639-cc3267b8-bcf7-4c85-b3e5-db85c3ced7ab.PNG)

 - OS: windows 10
 - Game Version 1.0.9c

**Comment by Jalsson** [comment]
This is intentional to prevent players from getting shot while waiting for chest to spawn

**Comment by ph1oyd** [comment]
The player that submitted the bug report took time to paint an area in a screenshot. It is possible to stand beyond the edge of the platform of this area and out of the safe zone and yet still be the same height as the area with the fires. Then you are able to shoot into the safe zone from this direction. This issue has been in the game for quite some time. You can see where bullets were able to hit into the safe area from the screenshot provided as well.

**Comment by Jalsson** [comment]
This bug will be fixed in 1.10 update.
