### ISSUE TITLE
House upgrade progress isn't working properly (for me)

### ISSUE THREAD

**Issue by junigold** [Uuvana-Studios/longvinter-windows-client#138]
**Describe the bug**
While upgrading my tent, I procured 20 wood in my inventory. Went to the workbench to add 20 to the current 18 progress. Instead of getting 38 on my progress, I got 20.

Went up +2 instead of +20.

**Desktop (please complete the following information):**
 - OS: windows
 - Game Version beta 1.0.0
 - Steam Version I don't know
 
 
**Additional context**
Not sure if relevant, but I have built multiple houses on this server.
Also, wood is mixture of normal and juniper.

**Comment by junigold** [comment]
Oh, and now the progress is 0 after relaunching the game.

**Comment by junigold** [comment]
Ok so. After starting from 0 again, here's what happened.

I took a full bag of 20 and added, got 20 on the progress.
I took a second bag of 20, expecting for 40 total. Progress remained at 20.
I took a single piece of wood after, and progress reset to 1.

**Comment by Jalsson** [comment]
There was a bug in the latest update. Hotfix is rolling out to fix this one
