### ISSUE TITLE
Infinite Harvesting From Garden

### ISSUE THREAD

**Issue by EssenceGFX** [Uuvana-Studios/longvinter-windows-client#14]
Having a single slot open in your inventory allows you to infinitely harvest berries from planted berry bushes for example. It does not convert the original plant into seeds as it normally would, and it doesn't remove the berries from the bush either which allows you to harvest it again immediately. While testing, it seems it doesn't always behave this way, but it's consistent enough that it seems like it may be an issue.

[Video on it in action](https://youtu.be/R2RhZFwLYnY)

**Comment by sirNugg3ts** [comment]
we have tried and couldn't replicate the bug. Please if the issue persists open a new bug report (and this time please fill the template correctly)
thanks for helping the game <3
