### ISSUE TITLE
Server list does not update after leaving a server

### ISSUE THREAD

**Issue by mrccwolf** [Uuvana-Studios/longvinter-windows-client#140]
**Describe the bug**
Server list will not load after leaving a server. The game must be closed entirely and restarted for the server list to populate. This happens every time.

**To Reproduce**
1. Join a server
2. Leave the server from the in game menu
3. Server list will never load.

**Desktop (please complete the following information):**
 - Windows 10
 - Game Version: 1.0.0
 - Steam Version: March 2nd update (player save hot fix)
 - This happened on earlier updates as well

**Comment by sirNugg3ts** [comment]
Tried to replicate this a couple of times with the steps given, but couldn't come to the same result.
Closing issue for now
