### ISSUE TITLE
[US-WEST] Uvana 1 server is strange

### ISSUE THREAD

**Issue by jijeee** [Uuvana-Studios/longvinter-windows-client#1407]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

### ****All items are lost
there is nothing at home
And even if I want to leave the house, I can't

and die for no reason
When will the server be back to normal?****

![20230205132440_1](https://user-images.githubusercontent.com/124482859/216802126-8dd1d177-aebf-45d2-9ad6-a157e8d74646.jpg)

**Comment by cherryblossom2020** [comment]
This is not related to the issue of the game itself. Use below link

https://contact.uuvana.com/
