### ISSUE TITLE
BUGGED WATER

### ISSUE THREAD

**Issue by Mowrena** [Uuvana-Studios/longvinter-windows-client#141]
**Describe the bug**
Water fx can't be found.

**To Reproduce**
When I tried to run my own server and log-on again and tried it, the water couldn't be seen but the fishes are visible looking like a teriyaki chicken drumstick. I tried to restart the game and join another server, and it is still bugged. Tried other methods from the closed case relating to this issue. I also tried to reinstall the application, still doesn't fix it. The toggle render doesn't help either.

**Expected behavior**
Be back to normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/100783458/156384977-bc7874b1-576d-40ee-8a70-0411897f0585.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.0
 - Steam Version: n/a

**Additional context**
...

**Comment by sirNugg3ts** [comment]
Did fix in #13 not work for you?

**Comment by Mowrena** [comment]
Nope. I already fixed it after changing the properties of the game:
- "Run as Admin", then toggled of the "Run as Admin" and it was fixed.
- Deleted all the folder inside the Saved folder.
- And verified the integrity of game files again.
