### ISSUE TITLE
집이 가구를 제외하고 검정색으로 보이지 않아요

### ISSUE THREAD

**Issue by wnsqja0901** [Uuvana-Studios/longvinter-windows-client#1411]
**Describe the bug**
제 집에 들어갔는데 가구를 제외한 집이 검정색으로 보이지 않아요

**To Reproduce**
1. 게임을 킨다.
2. 나의 집에 들어간다.
3. 집이 가구를 제외하고 벽과 바닥이 전부 보이지 않는다.

**Expected behavior**
이유는 전혀 모르겠다. 아무것도 건드리지 않았기 떄문이다.

**Screenshots**

![캡처](https://user-images.githubusercontent.com/125202719/218319493-bc9ab58f-88b3-4d30-b57e-096ce4413d20.JPG)

**Comment by wnsqja0901** [comment]
좀 고쳐주세요.

**Comment by cherryblossom2020** [comment]
Hello. Make sure to restart you game.
