### ISSUE TITLE
My turret shooting me.

### ISSUE THREAD

**Issue by haru44** [Uuvana-Studios/longvinter-windows-client#142]
**Describe the bug**
i place turret in green placeable status. but my turret shooting me, and i can't pick up my turret. but i can pick up fance under the turret.

**To Reproduce**
1. place turret at green placeable status.

**Expected behavior**
turret not shooting me, and i can pick up my turret.

**Screenshots**

![20220302220317_1](https://user-images.githubusercontent.com/100785885/156392837-6e557227-74b4-47c3-9d74-9491ee28ad1a.jpg)

![20220302221614_1](https://user-images.githubusercontent.com/100785885/156392903-1df0f71d-7c66-4694-91cf-0195cf0624ee.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [1.0.0]
 - Steam Version [ API v020 packet version: 1642451672 ]

**Additional context**
singapore server, 7 S/8 W.

**Comment by Jalsson** [comment]
The picture indicates that there might be something to do with the tent next to you. I added more checks that account for multiple homes overlapping each other. Let's see if this fixes it!
