### ISSUE TITLE
List of variables that can be used to cheat/alter the game

### ISSUE THREAD

**Issue by Mikooboy** [Uuvana-Studios/longvinter-windows-client#146]
# List of some variables that can be used to cheat/alter the game

There are a bunch of stuff and I feel like a better solution to fixing these would be to just implement an anti-cheat

All the components have other variables that can be changed but are not listed here since I didn't see them as important as these ones.
For example the `CameraBoom.CameraLagSpeed` and bunch of other variables related to it can be changed.

### ThirdPersonCharacter_C

- `CustomTimeDilation` can be used as a speedhack

- **CameraBoom**
  - `Position`
  - `RelativeRotation`
  - `TargetArmLength`

- **FollowCamera**
  - `Position`
  - `FieldOfView`
  - `ProjectionMode`

- **PlacementCollision**
  - `bGenerateOverlapEvents` can be used to place items pretty much everywhere

- **BuffComponent**
  - `buffsArray`
    - `buffEffect`
    - `remainingDurationInSeconds`
    - etc.

- `InvSize` You can go over the 20 item limit but the inventory resets to 20 when you close the widget

- `PlayerInv` Item IDs can be changed allowing you to drop items you don't have

- `CraftingInv`

- `PlayerGear`

- `FoundItems`

- **ItemToPlace** or the **Items** in general
  - `AllowVerticalSurfaces`, `AllowHorizontalSurfaces`
  - `InsideOnly`, `OutsideOnly`
  - `RestrictedRotation` can be used to rotate tent so that the door is on the back
  - `PlayerReachDistance` can be used to place items far away

- `NameColorSingle.SpecifiedColor` can be used to change the background color of the name when waving

- `NameColorSingle.ColorUseRule` when changed to 1 for example the game will crash for you and others when waving

- `Ammo` can be frozen with CE and therefore allows you to shoot even when out of ammo

- `InWater` can be used to fish while swimming for example

- **CurrentFishspot** or the **Fishspots** in general
  - `DropTable`
    - `ItemIndex` can be used to drop items like the turret for example
    - `DropChanceInPercentage`
  - `MaxDropDelay`

- `HasFishingRod` can be used to fish without having the rod

- `FishingCooldown` can be used to skip the cooldown

- `AllFish`, `AllFeathers` and `AllPlants` can be frozen at 1 and allows you to use the vendors/hats

- `weaponStats` pretty much all of the variables under there lol

- **CurrentWorkbench** or the **Workbenches** in general
  - `WoodToUpgrade`
  - `WoodCurrent` can be used to instantly upgrade the house

### A_Home_C

- `savedSteamID's` the player can change/add his own steamID to the list and get access to the house

#### Like I said at the start there are a bunch of them variables and this is only a part of them. I will be updating this when I find new ones.

**Comment by 5qu34k99** [comment]
Is there a cheat where players can pick up items that are highlighted green when placed so that only the owner should be able to pick up?
