### ISSUE TITLE
light house bugs..

### ISSUE THREAD

**Issue by hams777** [Uuvana-Studios/longvinter-windows-client#1461]
**Describe the bug**

I go the light house upstair where need to use casino access card. I use card key and go inside, and kill AI. Then I try to go out in that place. But at that time the access door already closed... I think the time flow just 1min, but the door already was closed . So i cant go outside because i bring just one key in here.. IS THIS BUG? or new update that the door close quickly or need two card key..
sorry for wrong eng..

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

![Longvinter   2023-04-13 오후 7_08_05](https://user-images.githubusercontent.com/130656281/231730352-864ff3f7-326a-4de9-a17b-9fd9c356cb2d.png)

![Longvinter   2023-04-13 오후 7_08_09](https://user-images.githubusercontent.com/130656281/231730413-1ab58731-c07f-4844-b514-c4a9bed0fb1a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Game Version [e.g. 1.0] beta 1.10b
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Fixed in a hotfix eyesterday
