### ISSUE TITLE
The gun doesn't shoot properly in the bunker

### ISSUE THREAD

**Issue by longvinterbuggame** [Uuvana-Studios/longvinter-windows-client#1462]
**Describe the bug**
The gun doesn't shoot properly in the bunker

**To Reproduce**
The gun doesn't shoot properly in the bunker11111111111111111111

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Fixed in a hotfix eyesterday
