### ISSUE TITLE
Respawn inventory empty bug

### ISSUE THREAD

**Issue by Yzue** [Uuvana-Studios/longvinter-windows-client#147]
Everytime I log back on the server my inventory and money has reset. I also spawn at the start island.Triedn logging off in my base, spawn and wild and it keeps happening.

**Comment by keyg-en** [comment]
Same happening to me right now

**Comment by sirNugg3ts** [comment]
From FAQ on Discord

> We are aware of the time some of you are putting on our game, and we are thankful.
Still we are, as you should be aware, in EA and Beta, which means a lot of updates might delete stuff that might have been done until that point, creating partial or full wipes.

And as Teo said on Announcements

> A couple days after launch we (and players) noticed that some things were not saving, player progress was lost sometimes upon logout, and most often on server restart, where player houses were also being wiped. Problems with logout is mostly fixed now.

> This is caused by the async saving / loading we're using. It would have worked perfectly if we had saved everything from homes, placeables and player progress to a single file, but we don't, we save on multiple files, and sometimes the async saving just won't save if there is already another process going on.

> Why didn't we notice this before release? The system stops working when there are multiple players logging in and out. 

> The latest rollback was just a couple of hours ago which was caused by a failsafe we tried to add, which actually made things worse by not saving at all for a long period of time. We reverted the change now.

> This whole saving/loading thing is quite embarrassing, and we're sorry for wasting your time. We've been working 16 hours a day trying to fix this, and we can fix it, it just takes a little more time. We're trying to get this working this week, and we'll work the whole weekend if that is what it takes.

> Thanks for your patience!
