### ISSUE TITLE
F4 key disables mouse clicks

### ISSUE THREAD

**Issue by keyg-en** [Uuvana-Studios/longvinter-windows-client#148]
**Describe the bug**
Pressing F4 twice will make mouse clicks not register

**To Reproduce**
1. Press F4 once, and it removes the version from top-left
2. When Pressing F4 again it shows game version again
3. Open inventory and hover over an item and you can't click it
4. (However if you hide the version again, the mouse will work again)

**Desktop:**
 - OS: Windows 10
 - Game Version: 1.0
 - Steam Version: 1645539960

**Additional context**
Pretty low priority but annoying if a player doesn't know why their mouse isn't working

**Comment by sirNugg3ts** [comment]
Could replicate, thank you for your bug report <3

**Comment by Jalsson** [comment]
Disabled f4 functionality from running in production build
