### ISSUE TITLE
I placed a turret to defend my house but instead it keeps attacking me + I can't pick it up!

### ISSUE THREAD

**Issue by JipGame** [Uuvana-Studios/longvinter-windows-client#149]
**Describe the bug**
I bought a turret, went to my home, placed the turret ontop of my fence, (it was green). And it was all set! After like 2-3minutes the turret started to target me! I took no damage tho.. I cannot pick the turret up (it gives the warning: cant pick up another property).

**Expected behavior**
Well, I expected the turret to do its job haha :)

**Screenshots**
![Uploading afbeelding.png…]()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Beta 1.0.0
 - Steam Version Beta 1.0.0

**Additional context**
Server: [EU3].

**Comment by sirNugg3ts** [comment]
> Applied a fix where turrets were shooting at the house owner
This should be fixed
