### ISSUE TITLE
롤백되었습니다.

### ISSUE THREAD

**Issue by merling888** [Uuvana-Studios/longvinter-windows-client#1499]
두번 롤백이 되었습니다. 처음엔 괜찮아서 그냥 넘겼는데 두번째는 노력을 해서 집도 최대로 업그레이드 시키고 정원도 예쁘게 꾸며놨습니다. 그리고 2023년 5월 29일 오늘 평화롭게 백어를 잡아서 부자가 될 생각을 하며 낚시를 하던 중 이였습니다. 그치만 그 평화는 오래가지 못했습니다. 갑자기 렉이 걸리기 시작했습니다. 주변들은 제자리 걸음을 하며 어떤 사람은 벽에서 계속 머리를 박고 있었습니다 조금 있으면 풀리겠지라고 생각하고 기다렸습니다. 기다리고 기다리고 기다리고 그리고 15분이 지났습니다. 15분이 지나도 렉이 풀릴 기미가 보이지 않았습니다. 그냥 재접속을 하는게 좋을 것 같아서 재접속을 하려고 연결을 끊고 다시 들어갔습니다. 그치만 저의 집,마당,아이템.돈 모두 사라지고 뒤였습니다. 그치만? 사라진 줄 알았던 저의 첫번째 캐릭터가 있었습니다. 전 매우 충격 충격 충격 충격 충격 전 두번째 캐릭터에 많은 애정과 노력을 쏟아부었습니다. 제 생각으론 서버가 달라서 이런 일이 벌어진 것 같습니다. 둘 다 똑같은 pve서버인데 이상합니다. 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 전 참고로 한국인입니다. 베타 버전인데도 이게 13.93달러인게 말이 안됩니다. 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔

**Comment by merling888** [comment]
> 두번 롤백이 되었습니다. 처음엔 괜찮아서 그냥 넘겼는데 두번째는 노력을 해서 집도 최대로 업그레이드 시키고 정원도 예쁘게 꾸며놨습니다. 그리고 2023년 5월 29일 오늘 평화롭게 백어를 잡아서 부자가 될 생각을 하며 낚시를 하던 중 이였습니다. 그치만 그 평화는 오래가지 못했습니다. 갑자기 렉이 걸리기 시작했습니다. 주변들은 제자리 걸음을 하며 어떤 사람은 벽에서 계속 머리를 박고 있었습니다 조금 있으면 풀리겠지라고 생각하고 기다렸습니다. 기다리고 기다리고 기다리고 그리고 15분이 지났습니다. 15분이 지나도 렉이 풀릴 기미가 보이지 않았습니다. 그냥 재접속을 하는게 좋을 것 같아서 재접속을 하려고 연결을 끊고 다시 들어갔습니다. 그치만 저의 집,마당,아이템.돈 모두 사라지고 뒤였습니다. 그치만? 사라진 줄 알았던 저의 첫번째 캐릭터가 있었습니다. 전 매우 충격 충격 충격 충격 충격 전 두번째 캐릭터에 많은 애정과 노력을 쏟아부었습니다. 제 생각으론 서버가 달라서 이런 일이 벌어진 것 같습니다. 둘 다 똑같은 pve서버인데 이상합니다. 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 전 참고로 한국인입니다. 베타 버전인데도 이게 13.93달러인게 말이 안됩니다. 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔

**Comment by merling888** [comment]
> 두번 롤백이 되었습니다. 처음엔 괜찮아서 그냥 넘겼는데 두번째는 노력을 해서 집도 최대로 업그레이드 시키고 정원도 예쁘게 꾸며놨습니다. 그리고 2023년 5월 29일 오늘 평화롭게 백어를 잡아서 부자가 될 생각을 하며 낚시를 하던 중 이였습니다. 그치만 그 평화는 오래가지 못했습니다. 갑자기 렉이 걸리기 시작했습니다. 주변들은 제자리 걸음을 하며 어떤 사람은 벽에서 계속 머리를 박고 있었습니다 조금 있으면 풀리겠지라고 생각하고 기다렸습니다. 기다리고 기다리고 기다리고 그리고 15분이 지났습니다. 15분이 지나도 렉이 풀릴 기미가 보이지 않았습니다. 그냥 재접속을 하는게 좋을 것 같아서 재접속을 하려고 연결을 끊고 다시 들어갔습니다. 그치만 저의 집,마당,아이템.돈 모두 사라지고 뒤였습니다. 그치만? 사라진 줄 알았던 저의 첫번째 캐릭터가 있었습니다. 전 매우 충격 충격 충격 충격 충격 전 두번째 캐릭터에 많은 애정과 노력을 쏟아부었습니다. 제 생각으론 서버가 달라서 이런 일이 벌어진 것 같습니다. 둘 다 똑같은 pve서버인데 이상합니다. 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 전 참고로 한국인입니다. 베타 버전인데도 이게 13.93달러인게 말이 안됩니다. 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔

**Comment by merling888** [comment]
> 두번 롤백이 되었습니다. 처음엔 괜찮아서 그냥 넘겼는데 두번째는 노력을 해서 집도 최대로 업그레이드 시키고 정원도 예쁘게 꾸며놨습니다. 그리고 2023년 5월 29일 오늘 평화롭게 백어를 잡아서 부자가 될 생각을 하며 낚시를 하던 중 이였습니다. 그치만 그 평화는 오래가지 못했습니다. 갑자기 렉이 걸리기 시작했습니다. 주변들은 제자리 걸음을 하며 어떤 사람은 벽에서 계속 머리를 박고 있었습니다 조금 있으면 풀리겠지라고 생각하고 기다렸습니다. 기다리고 기다리고 기다리고 그리고 15분이 지났습니다. 15분이 지나도 렉이 풀릴 기미가 보이지 않았습니다. 그냥 재접속을 하는게 좋을 것 같아서 재접속을 하려고 연결을 끊고 다시 들어갔습니다. 그치만 저의 집,마당,아이템.돈 모두 사라지고 뒤였습니다. 그치만? 사라진 줄 알았던 저의 첫번째 캐릭터가 있었습니다. 전 매우 충격 충격 충격 충격 충격 전 두번째 캐릭터에 많은 애정과 노력을 쏟아부었습니다. 제 생각으론 서버가 달라서 이런 일이 벌어진 것 같습니다. 둘 다 똑같은 pve서버인데 이상합니다. 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 13.93달러에 값을 해라 전 참고로 한국인입니다. 베타 버전인데도 이게 13.93달러인게 말이 안됩니다. 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔 내 2번째 데이터를 내놔

**Comment by siharyun** [comment]
Hello! I'm not dev but I just wanted to ask you if you are sure you get into same server. there are 2 PvE server in Asia and you looks like you get into two different servers. is your friends and neighbors all there too?

안녕하세요! 저는 개발자는 아니지만 같은 서버가 맞는지 확인해보셨는지 여쭤보고싶어서 댓 남깁니다. 아시아에는 2개의 PVE서버가 있고 기존 데이터가 덮어씌워진게아니라 남아있다면 지금 두 서버에서 플레이하신 것일 확률이 높습니다. 같이 플레이하던 친구나 이웃정보는 그대로 있으신가요?

**Comment by cherryblossom2020** [comment]
Please do not spam on this page. In order to get support, please visit contact.uuvana.com
