### ISSUE TITLE
Able to pick up things placed by other players

### ISSUE THREAD

**Issue by bearlystraight** [Uuvana-Studios/longvinter-windows-client#15]
**Describe the bug**
Everyone can right click fences, lamps, etc. that have been placed outside by others, regardless of the color during placement (green or blue).

**To Reproduce**
1. Go up to a random item placed by someone else.
2. Right click on the item
3. Item is picked up

**Expected behavior**
When the object is green when placing it cannot be picked up by others, when blue it can.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version v020

**Comment by Jalsson** [comment]
We have applied a fix for this. Not sure if there are some cases where they still can be picked up

**Comment by sirNugg3ts** [comment]
please confirm if this still is happening @bearlystraight

**Comment by bearlystraight** [comment]
It's fixed! Thank you
