### ISSUE TITLE
Help, I cant move

### ISSUE THREAD

**Issue by LibbyDough7** [Uuvana-Studios/longvinter-windows-client#1500]
We bought this game on Steam. We are trying to connect but we cant. Also I try to create new server , but I couldnt.

I died in game and reborn in my cabin, but my character borned in a table and I cant move. Also I cant delete server so I cant play this game right now.

My Steam name is Mervemii, please help me.
![resim_2023-05-30_110214853](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/135006871/b853c95c-c590-4ad2-bb99-3e340ff4ced3)

**Comment by siharyun** [comment]
you can use /kill command to escape that!
1. use kill command(in chat box) and spawn in the horbor(not same house)
2. go to the house and take out the table that makes you stuck
there is cool down on /kill command so check system message too!(on left top)
