### ISSUE TITLE
SG공식서버에 제집이 없어졌습니다. 

### ISSUE THREAD

**Issue by calli110800** [Uuvana-Studios/longvinter-windows-client#1503]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by cherryblossom2020** [comment]
Please use contact.uuvana.com to get support for progress loss. This is page for bug report.
