### ISSUE TITLE
FROG HAT ISSUES

### ISSUE THREAD

**Issue by 0002991cfdfb450ab79eff548ba98329** [Uuvana-Studios/longvinter-windows-client#1509]
**Describe the bug**
I reached the frog hat island, but I couldn't get the hat.

**Screenshots**
1. REACHED THE ISLAND
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/138199240/ca6959b3-e8ff-40ec-bd8d-24ad8abffe24)

2. NO HAT IN INVENTORY
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/138199240/acac0c32-ffb1-44c8-b8ca-851eead02617)

**Additional context**
At the same computer, another user got the hat.(There's no problem with computer or update ver.)
THIS IS MY EOS : 0002991cfdfb450ab79eff548ba98329

**Comment by Jalsson** [comment]
Hi, due to technical limitations, we had to limit the number of frog hats given to 1 per device.
