### ISSUE TITLE
Placed Container close to bottom interior of my house, now I can't enter.

### ISSUE THREAD

**Issue by pimpinpeanut** [Uuvana-Studios/longvinter-windows-client#152]
Describe the bug
I was instantly forced outside outside my house after placing down a container, and now I cannot reenter. My house is filled with multiple containers; about 7 containers. I placed down an 8th container near the bottom center of the room. I was instantly forced outside, and now I cannot enter my house. The screen will be black with the "loading wheel" and then it will show me still outside.

To Reproduce Steps to reproduce the behavior:
Possibly cover majority of the floor in a house with containers, and place one where the player spawns

Desktop (please complete the following information):

OS: [Windows]
Game Version [1.0]
Steam Version [1.0]
Additional context Add any other context about the problem here.

**Comment by Jalsson** [comment]
Managed to reproduce this issue and added double-check and raised a spawn point inside a house a bit. Now works much more reliably.
