### ISSUE TITLE
집밖으로 나오니 캐릭터,체력바 이외에 모든 화면이 흰색만 나옵니다

### ISSUE THREAD

**Issue by moolkong2** [Uuvana-Studios/longvinter-windows-client#1530]
**Describe the bug**

**To Reproduce**
1. Go to '...' 친구 집에서 부활했습니다
2. Click on '....' 밖으로 나갔습니다
4. Scroll down to '....'
5. See an error 갑자기 화면이 전부 흰색만 나옵니다. 캐릭터와 체력바는 보였습니다.
![스크린샷(168)](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/142781473/df513233-bad9-47fb-b5c1-bf625837b2fa)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.11
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Try reconnecting. We can't find the exact way to replicate this.
