### ISSUE TITLE
집이 없어졌어요..

### ISSUE THREAD

**Issue by ssssssubin** [Uuvana-Studios/longvinter-windows-client#1537]
**Describe the bug**
- 필몬지역에 있는 나의 첫번째 집이 없어지는 문제가 발생함 어제 접속했을땐 분명 집이 있었음. 

**To Reproduce**
4. See an error

**Expected behavior**
- 어제 필몬에 있는 집으로 들어가면 레이크 광장으로 움직이는 버그가 있었음. 그렇지만 게임 끄기전 정상적으로 집으로 들어가졌음

**Screenshots**
- 어제 있었던 필몬집 
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/143533359/89360dbe-40fb-4408-bc55-92a713429b39)
- 현재 상황
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/143533359/24a0d776-e403-4731-a28c-e0d0f122f51c)

**Desktop (please complete the following information):**
 - Steam Version [e.g. 1.11]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #600
