### ISSUE TITLE
게임을 하다가 게임이 멈추더니 하던 서버도 안보이고 이 서버 저 서버 들어가다가 모든게 초기화 된거같습니다.

### ISSUE THREAD

**Issue by HHHHHHHHH111** [Uuvana-Studios/longvinter-windows-client#1540]
**Describe the bug**

사진을 찍을새도 없이 오늘 세이브파일도 없고 그냥 튕기더니 모든게 사라졌습니다.
최근 세이브파일 원하시면 메일이던 어디로는 보내드릴테니 확인 후 답변주세요.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by siharyun** [comment]
오늘 Monthly Wipe, 월간 초기화 서버들은 모두 초기화 했습니다. 서버 이름 뒤에  Monthly Wipe가 붙는 서버는 한달에 한번 초기화 하는 서버로 플레이에 참고 하시기 바랍니다!

**Comment by faketucker** [comment]
Duplicate of #600
