### ISSUE TITLE
서버가 안들어가지는 버그 고쳐주세요

### ISSUE THREAD

**Issue by cathubopp** [Uuvana-Studios/longvinter-windows-client#1541]
![20230919_170116](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/145449751/ec9f9310-41a0-46a7-afaf-2c98746dcf60)

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
