### ISSUE TITLE
Sauna Placement Bug

### ISSUE THREAD

**Issue by Ashli2P** [Uuvana-Studios/longvinter-windows-client#1549]
**Describe the bug**
When you try to place the sauna inside of your player house, lots of unpredictable stuff happens like getting lifted into the air, speeding around the map, and teleporting to the starting merchant area.

**To Reproduce**
1. Go to player house
2. Open inventory
3. Click on sauna
4. Move your cursor around
5. The game starts FREAKING OUT

**Expected behavior**
Nothing should happen at all when you try to place the sauna where it shouldn't be, and it should not have collision until placed.

**Screenshots**
![Longvinter 2023 11 19 - 18 41 59 01 - frame at 5m25s](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/103918273/41db0404-6eef-458e-bc53-b6146dd1b4d9)
![Longvinter 2023 11 19 - 18 41 59 01 - frame at 5m31s](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/103918273/875d64d0-b337-4fd7-80fb-e568028da5e2)
![Longvinter 2023 11 19 - 18 41 59 01 - frame at 6m20s](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/103918273/29be7b9d-bf52-4065-9fe6-3c60d733d293)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [Beta 1.11]
 - Steam Version [1700160213]

**Additional context**
I don't think this is beneficial to the player, but it is hilarious. Thanks for reading, love the game, have a nice day.

**Comment by Jalsson** [comment]
Thanks for the report. We will be adding this to our fix list. Should be fixed in 1.12 update
