### ISSUE TITLE
Getting Booted

### ISSUE THREAD

**Issue by DaBreadMannB** [Uuvana-Studios/longvinter-windows-client#155]
**Describe the bug**
After logging into the server I can not make any action's in game without getting booted to the title screen. For example: space bar to interact - booted to title screen, mid animation of waving - booted to title screen, even clicking once - booted to title screen.

**To Reproduce**

**Expected behavior**
Being able to even play the game without getting booted to the title screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Windows
 - Game Version [e.g. 1.0]
 - Beta 1.0.0
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Server or client is not updated
