### ISSUE TITLE
한시간전까지 했던 것들이 다 사라지고 처음부터 시작해요

### ISSUE THREAD

**Issue by msje711** [Uuvana-Studios/longvinter-windows-client#1550]
열심히 도감깨고 파밍하고 낚시해서 돈모으고 있는데 업데이트 하고나서 이때까지 했던것들이 다 초기화가 되었어요
SG 우바나 1 초기화 하고나서부터 계속 서버가 여러개로 나뉜거마냥 접속할때마다 바껴요 
겁나 열심히 해놨는데 다시 처음으로 무한반복 돌아가니 할맛이 떨어지네요 의욕이 사라짐
버그좀 제대로 고쳐주세요

**Comment by faketucker** [comment]
Duplicate of #600
