### ISSUE TITLE
(Japanese) display of pricing on the vending machine / vendor / possession currency are broken

### ISSUE THREAD

**Issue by armgadge** [Uuvana-Studios/longvinter-windows-client#1552]
**Describe the bug**
On Japanese, display of pricing on vending machine / vendor, and possession currency I have are broken.
It displays "Game Over" and tiny pricing display so unreadable.
(Please see the red boxed area on the screenshot)
![longvinter-bug](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/152012469/964594a5-4cbb-4f73-b0bd-451c8e7ad574)

**To Reproduce**
1. Select lanuguage settings to Japanese
2. Join the game and go to some vending machine or vending person

**Expected behavior**
Pricing on the vendor and possession currency displays correctly.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.12
 - Steam Version 1700100828

**Comment by faketucker** [comment]
![image](https://github.com/user-attachments/assets/3b4f4cfc-966e-4d66-8e0d-bbddffb90faf)

Should be fixed by now
