### ISSUE TITLE
my hunting is gone 1hour

### ISSUE THREAD

**Issue by zerozerozerozero123** [Uuvana-Studios/longvinter-windows-client#1557]
I did all the missions. It took 1 hour. However, he said that an error had appeared, and when he left and came back in, all the encyclopedia disappeared. I'll send you a picture. I want you to solve it.
![long](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/152474923/c47666ae-cd67-4fd0-a534-43e4360569ef)
![long](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/152474923/3e750c9c-9a74-468c-81f4-1366cd59ff6d)

**Comment by faketucker** [comment]
Duplicate of #600
