### ISSUE TITLE
ゲームにログインしたところ、データがかなり前に戻っていました。

### ISSUE THREAD

**Issue by Nekomura7** [Uuvana-Studios/longvinter-windows-client#1558]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by armgadge** [comment]
こんにちは、横からすみません。
現在、タイトル画面の「続ける（Continue）」ボタンからゲーム再開したときに
進捗がセーブされない不具合があると公式からアナウンスが出ているようですが、
この不具合が起きた時は、その続けるボタンを使っていたのか、サーバーブラウザーを使っていたのかは覚えていますでしょうか？
ここをはっきりさせておいたほうが良いかなと思いました。

Hi, sorry for mentioning you.
Currently there is a issue announced from official about save progression, when used continue button on the main menu.
Do you remember which method used to join the server? from continue button or via server browser?
I think you need to clearify on this.

**Comment by Nekomura7** [comment]
ありがとうございます
その時ちょうどJP PvP 1 サーバーがダウンしていてサーバーブラウザから入りました。

**Comment by faketucker** [comment]
Duplicate of #600
