### ISSUE TITLE
Rollback of save data

### ISSUE THREAD

**Issue by Kuroyuu1195** [Uuvana-Studios/longvinter-windows-client#1561]
**Describe the bug**
Save data is rolled back when restarting the game.

**To Reproduce**
1. Select [JP]Uuvana 1 from the server browser and log in
2. Logout after doing some work
3. Log in to [JP]Uuvana 1 again from the server browser
4. Save data is rolled back

**Expected behavior**
Rollback of save data or save error when exiting

**Screenshots**
![キャプチャ](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/152564771/c71d094d-1a81-446c-b513-b36bc6ac3318)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [Beta 1.12]
 - Steam Version [1698777785]

**Additional context**

**Comment by faketucker** [comment]
Duplicate #600
