### ISSUE TITLE
집합쳐짐 버그 

### ISSUE THREAD

**Issue by themoon0618** [Uuvana-Studios/longvinter-windows-client#1571]
롱빈터 집지어두고 빽섭되서 다시 그위치에 집을지었더니
집이 합쳐져서 없어지지 않은지 일주일이 넘어가는데
버그로 두채가 합쳐진 집좀 없애주세요
원활한 게임플레이가 불가능합니다

**Comment by siharyun** [comment]
서버와 위치가 어떻게 되시나요?

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
