### ISSUE TITLE
템이 사라짐

### ISSUE THREAD

**Issue by wopaeo** [Uuvana-Studios/longvinter-windows-client#1577]
돈이 19000 -> 1000
회색 늑대 -> 늑대
집 안에 있던것들 밖에 있던것들 다 사라지고 
분명 집에서 겜을 껐었으나 바다앞에서 시작함.
텐트 아니고 집이에요.. 작업대도 사라짐
우바나 3 PVE 서버입니다

**Comment by wopaeo** [comment]
작업대, 보관함 4개, 캐비넷? 1개, 벽난로, 울타리 다수, 터렛, 통발, 18000mk, 회색 늑대, 전기 곡괭이 등등 다 사라졌네요. 도감도 어제 채워놓은게 안채워져 있다고 뜨고

**Comment by faketucker** [comment]
Duplicate of #600
