### ISSUE TITLE
집과 아이템과 집 앞에 있는 모든것들이 사라짐

### ISSUE THREAD

**Issue by rtfdew3489** [Uuvana-Studios/longvinter-windows-client#1578]
유바나3섭에서 집짓고 사는데(어제 만듬) 갑자기 오늘 들어오니까 갑자기 시작 항구에서 스폰돼고 아이템이 없고 고작 100mk.... 심지어 집터에는 집만 있고 텐트와 겹쳐 있었습니다

**Comment by faketucker** [comment]
Duplicate of #600
