### ISSUE TITLE
집에서 나갈수가 없음

### ISSUE THREAD

**Issue by kimmoshe** [Uuvana-Studios/longvinter-windows-client#1579]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
There's currently no other way to get out of the place you're stuck other than to type /kill in the chat right now. Unless there's an admin or dev online, they'll be able to teleport you out.
