### ISSUE TITLE
Storage boxes unable to be destroyed/moved

### ISSUE THREAD

**Issue by Rinimiki** [Uuvana-Studios/longvinter-windows-client#158]
**Describe the bug**
Inability to move storage boxes or break down even though boxes are completely empty. 

**To Reproduce**
1. Build storage system. Change storage system by removing boxes to place them somewhere else. 
2. Empty boxes & inventory so you can unbuild them. Bags appear as if the box did break down, but doesn't actually. 
3. Continues to do more boxes and now all my boxes are bugged out. 
4. Doing this doesn't give me access to my storage boxes and I can't reset/disconnect bc then all servers are missing and then I have to force close game. 
5. Resetting game does nothing.

**Expected behavior**
Being able to empty out storage box so that I can move it in a way that better fits my storage needs. 

**Screenshots**
![image](https://user-images.githubusercontent.com/100827109/156509458-3b493c39-7b97-42a2-883d-99414ac9c583.png)
![image](https://user-images.githubusercontent.com/100827109/156509804-3bc0686f-3361-4036-baf6-ebb7b8049534.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.0
 - Steam Version: Newest update 3/2/22

**Additional context**
I never had an issue with this before until I updated the game to the most recent version.

**Comment by sirNugg3ts** [comment]
Containers should have been fixed in this weeks update
