### ISSUE TITLE
HOUSE MISSING

### ISSUE THREAD

**Issue by k8126int** [Uuvana-Studios/longvinter-windows-client#1583]
**Describe the bug**

My house and vending machine were missing today and I found that a new user just built a new house.
Also I checked that my neighbors houses are exactly same with before. 

server info: [kr] Uuvana #PVE 1
 

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

![longvinter](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/155113720/67729298-732b-4692-9484-1309cfc6b8d6)

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Game Version [longvinter beta 1.12b]
 - Steam Version [1702079146]

**Additional context**
I want to get my house back and all the items in my house.

**Comment by Knuffle11** [comment]
the house will despawn if you do not come back within enough time to replenish the resources. A fully stocked house will decay in 180 hours and despawn and all the items will be lost. you have to use the workbench and go to the decay tab and replenish the wood resouce there to upkeep your house, the 180 hours decays and counts down even when you are offline.
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/157875545/03d5cb3c-cf4a-44d7-9f06-fcaf0bf33088)
