### ISSUE TITLE
게임을 들어와 보니 집이 사라졌어요..

### ISSUE THREAD

**Issue by ParkRowoon** [Uuvana-Studios/longvinter-windows-client#1584]
**버그 설명**
어제까지만 해도 잘 있던 집이 오늘 게임에 들어가 보니 딱 제 집만 사라져 있습니다... 같이 플레이 하던 친구 집도 그대로 있고, 친구 집에 들어가니 맵(지도)에는 친구 집이 뜨지만 제 집은 뜨지 않네요...
![Longvinter   2023-12-30 오후 9_44_11](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/155237044/4609aef8-1289-4c16-b0c4-73c5b8f0c838)
![Longvinter   2023-12-30 오후 9_45_40](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/155237044/7fee58cc-1013-4bc5-b956-23ca75d03590)

**Comment by faketucker** [comment]
Duplicate of #600
