### ISSUE TITLE
집에서 나가지지 않음

### ISSUE THREAD

**Issue by dtd0909** [Uuvana-Studios/longvinter-windows-client#1588]
**Describe the bug**
집에서 나가지지 않고 앱을 끄고 다시 키거나 서버에 다시 접속해도 집 밖으로 이동할 수 없는 문제가 생김

**To Reproduce**
재현할 수 있는 방법을 알 수 없음

**Expected behavior**
예상되는 동작을 알 수 없음

**Screenshots**
<img width="960" alt="스크린샷 2024-01-03 154934" src="https://github.com/Uuvana-Studios/longvinter-windows-client/assets/155518144/077b3cc9-dd23-41ca-ae29-6665e2636e91">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: 1.12
 - Steam Version: 1702079146
**Additional context**
없음

**Comment by faketucker** [comment]
There's currently no other way to get out of the place you're stuck other than to type /kill in the chat right now. Unless there's an admin or dev online, they'll be able to teleport you out.
