### ISSUE TITLE
집에서 나갈수 없음

### ISSUE THREAD

**Issue by dtd0909** [Uuvana-Studios/longvinter-windows-client#1589]
<img width="960" alt="스크린샷 2024-01-03 172725" src="https://github.com/Uuvana-Studios/longvinter-windows-client/assets/155518144/bc5caf1b-1c7e-478c-b1a5-2160bad1bc8a">

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
