### ISSUE TITLE
i can't build my tent :(

### ISSUE THREAD

**Issue by tsankinn** [Uuvana-Studios/longvinter-windows-client#159]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Bug report with no information will be ignored
