### ISSUE TITLE
the disappearance of one's home and belongings

### ISSUE THREAD

**Issue by yj030308** [Uuvana-Studios/longvinter-windows-client#1598]
**Describe the bug**
I didn't go home
the disappearance of one's home and belongings
No items in warehouse
the disappearance of one's belongings

**Desktop (please complete the following information):**
 - OS:Windows
 - Game Version 1.12
 - Steam Version 1705108172

[Longvinter   2024-02-06 23-02-33.zip](https://github.com/Uuvana-Studios/longvinter-windows-client/files/14181408/Longvinter.2024-02-06.23-02-33.zip)

**Comment by faketucker** [comment]
Duplicate of #600
