### ISSUE TITLE
항구에서 배를 타고 게임에서 팅겼는데

### ISSUE THREAD

**Issue by 1Darkwraith1** [Uuvana-Studios/longvinter-windows-client#1601]
**Describe the bug**
( 다시 들어와보니 필드밖에 죽어있고 그나마 아이템 챙겨 배 타고 가볼려고 해도 특정 좌표에서 더 이상 가지지를 않내요
서버에 사람이 10만명 이상 있는것도 아니고 확인하면 고작 10명정도 인데 게임 렉으로 게임 진행을 하지를 못하는데 이런 불완전한 게임을 돈 받고 파셨다니 무료 게임이면 무료게임이라 그런가보다하지 유료게임을 이런식으로 운영합니까

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![20240210_223110_롱빈터 렉 좆같네](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/159147752/b11456f7-9680-4ba4-b5bc-d03f05d74ef8)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]  windows 10
 - Game Version [e.g. 1.0] Longvinter Beta 1.12b
 - Steam Version [e.g. 1.0] Longvinter Beta 1.12b

**Additional context**

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
