### ISSUE TITLE
It doesn't move between trees for the second day;;;

### ISSUE THREAD

**Issue by Mangostep88** [Uuvana-Studios/longvinter-windows-client#1602]
**Describe the bug**
◆ It doesn't move between trees for the second day;;;

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

![bug](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/159798056/0bd38d97-c1d5-4a16-bef3-68f8350eedbb)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0] : Longvinter Beta 1.12b
 - Steam Version [e.g. 1.0] : Longvinter Beta 1.12b

**Additional context**

**Comment by faketucker** [comment]
There's currently no other way to get out of the place you're stuck other than to type /kill in the chat right now. Unless there's an admin or dev online, they'll be able to teleport you out.
