### ISSUE TITLE
[plz fix,,,]Trapped in base camp in kyrres for a month

### ISSUE THREAD

**Issue by SOHWII-choi** [Uuvana-Studios/longvinter-windows-client#1607]
**Describe the bug**
(After passing a certain place in Kyrres' Base camp, a bug occurred where I couldn't move for a month and kept returning to that spot. The location on the map is 42N / 3W, and the server is [JP] Uuvana #PVE. It's like there aren't any obstacles around, but my character got stuck and couldn't move for a month. Please fix it.)

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![Bug](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/161925643/6a301189-9542-4ca9-9f80-cb6276a30560)

**Desktop (please complete the following information):**
- OS: [e.g. Windows] windows 10
- Game Version [e.g. 1.0] : Longvinter Beta 1.12b
- Steam Version [e.g. 1.0] : Longvinter Beta 1.12b

**Additional context**

**Comment by faketucker** [comment]
There's currently no other way to get out of the place you're stuck other than to type /kill in the chat right now. Unless there's an admin or dev online, they'll be able to teleport you out.
