### ISSUE TITLE
ALL HOUSES MISSING

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#162]
**Describe the bug**
After update my houses (3) on AU1 and (2) on US2 are gone along with MANY MANY OTHERS
all my stuff is gone that ive worked all week for, cant place tent in old house location as its now "overlapping something"

you guys have offically broken the game, i cant do this anymore after COUNTLESS character wipes and now entire house wipes youve broken it, every update you guys break it more.
FULL SERVER WIPES ARE NOW NEEDED as no where can houses be placed. either do full wipes or just rollback either way its now unplayable for most. 

Good luck

Done.

**To Reproduce**
1. Log on
2. Cry that all your shit is missing and never coming back.

**Expected behavior**
Id like to think (yes i know its a beta) that basic shit like keeping my stuff ive grinded for HOURS to get will be there when i log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/100509746/156529040-1bfa063e-0500-4ee5-ac63-b9ced68f2251.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 1.0.0.broken

**Additional context**
Entire servers are raging over this

**Comment by sirNugg3ts** [comment]
From FAQ on Discord

> We are aware of the time some of you are putting on our game, and we are thankful.
Still we are, as you should be aware, in EA and Beta, which means a lot of updates might delete stuff that might have been done until that point, creating partial or full wipes.

And as Teo said on Announcements

> A couple days after launch we (and players) noticed that some things were not saving, player progress was lost sometimes upon logout, and most often on server restart, where player houses were also being wiped. Problems with logout is mostly fixed now.

> This is caused by the async saving / loading we're using. It would have worked perfectly if we had saved everything from homes, placeables and player progress to a single file, but we don't, we save on multiple files, and sometimes the async saving just won't save if there is already another process going on.

> Why didn't we notice this before release? The system stops working when there are multiple players logging in and out. 

> The latest rollback was just a couple of hours ago which was caused by a failsafe we tried to add, which actually made things worse by not saving at all for a long period of time. We reverted the change now.

> This whole saving/loading thing is quite embarrassing, and we're sorry for wasting your time. We've been working 16 hours a day trying to fix this, and we can fix it, it just takes a little more time. We're trying to get this working this week, and we'll work the whole weekend if that is what it takes.

> Thanks for your patience!
