### ISSUE TITLE
동굴 버그

### ISSUE THREAD

**Issue by dlawlwl** [Uuvana-Studios/longvinter-windows-client#1628]
동굴에서 길을 따라가다가 빈 공간이 있어 출구인줄 알고 갔는데 Movement disabled while loading assets 라고 뜨며 캐릭터가 움직이지 않았습니다. 전투모드라 다시 접속도 불가능합니다 어떡하나요

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
