### ISSUE TITLE
벙커 버그;;

### ISSUE THREAD

**Issue by sibalsaekkideula** [Uuvana-Studios/longvinter-windows-client#1630]
![Longvinter Screenshot 2024 05 23 - 18 00 37 53](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/170615052/0f2a9ca6-3c1d-4f3a-ae80-d45a35973a48)

벙커에 들어갔더니 안 움직여지고 AI가 쏘는 총에 맞아 죽음

버그  망겜이노;;

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
