### ISSUE TITLE
동굴에서 템파밍 하던도중 갑자기 이렇게 멈추게 되었습니다

### ISSUE THREAD

**Issue by jamJalee66** [Uuvana-Studios/longvinter-windows-client#1633]
살려죠
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/171418972/23813f79-892e-4786-87b2-b93558741d75)

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
