### ISSUE TITLE
자판기버그

### ISSUE THREAD

**Issue by heeya326** [Uuvana-Studios/longvinter-windows-client#1639]
자판기 집앞에 설치해서 판매제품 등록하려고하면 창이 그냥 닫깁니다
매입은되는데 판매 등록이 안되요!!

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
