### ISSUE TITLE
Squeezed Password Window // Missing Water

### ISSUE THREAD

**Issue by xiHolly** [Uuvana-Studios/longvinter-windows-client#164]
**1 Bug:** _**Password Window:**_
_Tried to play with a friend of mine and he cannot type in my server password due to some issues with his password window.
His password window is squeezed to a point where it's only a line and you cannot type in a password at all cause you won't be
able to click or press any buttons nor are you able to see or click the text bubble.._

**2 Bug:** _**Missing Water:**_
_While i was waiting for my buddy to maybe figure the issue with the password window out.. another issue came up after i decided to update the game myself. It appeared that the whole water around the island and in general completely turned invisible after pressing the option "**Auto-Detect**" under the Video Settings in Options. I don't really mind but it's worth reporting. Already tried to restart, re-install the game and restart my computer.. i even removed all additional files and configs from the game itself.. so the basic solutions are already not helping at this point.. i also updated my graphics drivers to the latest version._

--------------------------------------------------------------------------------------------
**Steps to reproduce the behavior:**

**_(Password Window:)_**
1. Start the Game via Steam.
2. Look for a Server with password & click it.
3. Squeezed password window with a weird dark line in between..

**_(Missing Water:)_**
1. Join the game/own or random server.
2. Walk to a beach or water source.
3. See missing water.

-------------------------------------------------------
**Screenshots (Password Window Bug:)**
![unknown](https://user-images.githubusercontent.com/45385521/156533076-041f764d-987f-4c47-8317-13d41ec87cc3.png)
**Screenshots (Missing Water Bug:)**
![21af211efb230ec28e81b2e4fad6a263](https://user-images.githubusercontent.com/45385521/156534437-7304cc75-8fbd-4d94-80fe-356ffa30d609.jpg)
-------------------------------------------------------
**Desktop (please complete the following information):**

 - OS: Windows 10
 - Game Version BETA 1.0.0

-------------------------------------------------------
**Additional context**
_Hope this Report is helpful.. and structured to a point where the issue is understandable, sorry if my english isn't that great!_

**Comment by lmore377** [comment]
For the water, go into the game settings and click Toggle DX11 Water

**Comment by xiHolly** [comment]
Yea, already tried that one as well, forgot to mention that, doesn't do anything. :(

**Comment by xiHolly** [comment]
> For the water, go into the game settings and click Toggle DX11 Water

Yea, already tried that one as well, forgot to mention that, doesn't do anything. :(

**Comment by sirNugg3ts** [comment]
On #13 people have come up with a fix for the water please check.
For the Bug 1 of the password window, we haven't seen this happen anytime, please send us details about the specs and setup of the computer that ran this bug with DxDiag screenshots and extra details if possible

One more thing, great bug report <3

**Comment by xiHolly** [comment]
> On #13 people have come up with a fix for the water please check. For the Bug 1 of the password window, we haven't seen this happen anytime, please send us details about the specs and setup of the computer that ran this bug with DxDiag screenshots and extra details if possible
> 
> One more thing, great bug report <3

_You're welcome! And thank you for the water fix, worked!!_

**Comment by faketucker** [comment]
Fixed in the 1.0.7 update

![image](https://user-images.githubusercontent.com/28383557/172582796-25ef8cdd-1292-4ef8-b8e0-f8359012ffb8.png)
