### ISSUE TITLE
가끔식 선물상자에서 아무것도 없는게 나옵니다.

### ISSUE THREAD

**Issue by BrickBLUE-user** [Uuvana-Studios/longvinter-windows-client#1642]
사진은 없지만 진짜로 아무것도 나오지 않습니다. 고쳐주시면 감사하겠습니다.

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
