### ISSUE TITLE
비공식 서버에 집들이 다 사라졌습니다

### ISSUE THREAD

**Issue by EunRuna** [Uuvana-Studios/longvinter-windows-client#1645]
**Describe the bug**

House, money, and items disappeared after update 1.14
1.14 업데이트 후 집과 돈, 아이템들이 사라졌습니다

**To Reproduce**
1. update 1.14
2. go to my server [Server browser > informality > [루나] 즐기는 사람들]

**Expected behavior**

The house, money, and items must remain intact.
집과 돈, 아이템들이 그대로 있어야 함

**Screenshots**
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/131141177/df44c360-bc60-4959-bbf0-d16f54f073d2)

![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/131141177/376a9dc9-1825-476d-95d6-7e9b63428e86)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Game Version [1.14]
 - Steam Version [1718904662]

**Additional context**

After the 1.14 update, the global safe, items, money, and house were reset when connecting to the server.
1.14 업데이트 후 서버 접속 시 글로벌 금고, 아이템, 돈, 집이 초기화 되었습니다.

**Comment by cherryblossom2020** [comment]
Hello. 1.14 update requires you to wipe your servers.

**Comment by kimzuni** [comment]
@cherryblossom2020 

I understand that this is a problem caused by a change in the structure of the save file.
I have a 1.13 save file as a backup. Nevertheless this won't be possible to restore it, will it? :(
