### ISSUE TITLE
Please, please, please, please, please check We're waiting for two months

### ISSUE THREAD

**Issue by kanghaesang** [Uuvana-Studios/longvinter-windows-client#1646]
Need help for unofficial server to update 1.13 :016: 
I guess after Dec 10th update, AllPlaceables.sav file and AllChests.sav file has appeared in SaveGames folder.
and they got much more volume than other files before, The two files are total 1.5GB now.
When I try to open 1.13 server with this SaveGames file, Memory usage goes up to 100% and it crashes due to out of memory.
(even when I have 32GB RAM on my own PC and server's computer has 64GB RAM)
but I can open server with 1.12 version of the game.
if I delete AllPlaceables.sav file and start in 1.13, I can open the server but the date will roll back to December

Can I get help for this issue? I know devs recommanded to wipe for unofficial servers too but I rly want to save the buildings and also, I don't think it's only unofficial's problem. if ppl started to build more and more in official server, It can also happen in official server or any other servers. 🥹
--------------------------------------------------------------------------------------------------------------------------------
It has not been resolved since (1.13 update), and I contacted the developer on April 29 and 'Sven' confirmed it. After that, I contacted #dedicatedserverhelp on June 12th, but there was no answer.
---------------------------------------------------------------------------------------------------------------------------------
This is the first issue.
![KakaoTalk_20240327_193747943](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/147134259/85a5684c-4aba-4b9d-ac01-af346d02f8f4)

This is the second issue.
![image](https://github.com/Uuvana-Studios/longvinter-windows-client/assets/147134259/527e3077-1743-4a7e-b44c-c2b765d22805)

The first problem occurs when the storage file capacity exceeds 1G.
The second issue occurs after the update on June 27.
I don't know the cause of this.

**Comment by cherryblossom2020** [comment]
You have to wipe the server

**Comment by kanghaesang** [comment]
We have kept the server without initialization since June 2022 until now.
I hope this will be resolved without initializing the server.

If there is no way, please let me know
I have to make a choice.

**Comment by kanghaesang** [comment]
We have kept the server without initialization since June 2022 until now.
I hope this will be resolved without initializing the server.
It's so sad to erase the house of 96 people on the server..

I know that the Long Vinter development team members are putting a lot of effort and passion into this game.
I'm happy and grateful that every update always gives me fresh items and fun.
But this issue makes Long Vinter impossible to enjoy, so it's so sad...

If there is no way, please let me know
I have to make a choice.

**Comment by faketucker** [comment]
1.13 update should require a wipe
