### ISSUE TITLE
When I'm in front of a bonfire, I can't fill my stamina

### ISSUE THREAD

**Issue by fallasleeep93** [Uuvana-Studios/longvinter-windows-client#1647]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
When I'm in front of a bonfire, I can't fill my stamina

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version e.g. 1.4
 - Steam Version [e.g. 1718904662]

**Additional context**
The same error appears even if you restart the game

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
