### ISSUE TITLE
텐트가 사라졌습니다.

### ISSUE THREAD

**Issue by mangyo5** [Uuvana-Studios/longvinter-windows-client#1650]
텐트를 설치해뒀는데 내 모든 것이 사라졌다.
내 텐트 자리에 새로운 사람이 있다.

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
