### ISSUE TITLE
Server [TH] BANGKOK 2 (PVE) has disappeared last night !!!

### ISSUE THREAD

**Issue by GPSpring** [Uuvana-Studios/longvinter-windows-client#1653]
Please explain why and when we can get it back ?

**Comment by faketucker** [comment]
Servers may encounter problems and experience downtime from time to time. You can notify our team via [Discord](https://discord.gg/longvinter), and please wait patiently for action. You can always see the server status at https://status.longvinter.com/. Sorry for any inconvenience.
