### ISSUE TITLE
튕겼다가 다시 들어왔는데 아이템이 사라졌어요

### ISSUE THREAD

**Issue by chuuuuuu2** [Uuvana-Studios/longvinter-windows-client#1659]
**Describe the bug**
게임 중에 튕겨서 서버에서 나가졌는데 다시 들어가니까 일부 아이템이 없어졌어요.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
