### ISSUE TITLE
Party/Guild/Group Mode to find friends in your Session.

### ISSUE THREAD

**Issue by xiHolly** [Uuvana-Studios/longvinter-windows-client#166]
**- Is your feature request related to a problem? Please describe:**
_It is kind of related to a problem me and my friends witnessed couple of times now where we were looking for each other at the beginning and we couldn't find each other for hours due to random spawns._

-------------------------------------------------------------------------
**- Describe the solution you'd like:**
_The random spawns ain't the issue, the suggestion i have  for the whole thing is that maybe add something like a party/guild/group option where you can add people to your group and those are shown on the island with a colored arrow above their head/next to their name (if name is shown). So you would be able to see them on the side of your screen once you distance yourself from your friends.. that would make the finding part of each other better and also easier at the same time. Unless the game was meant to be a full blown survival game where you HAVE TO find each other. Than i most likely understand and see where you guys are going with this._

-------------------------------------------------------------------------
**Additional context**
_Sorry if things are hard to read or to understand, english isn't my native language!_

**Comment by Bunnbunnnn** [comment]
Already documented on forum as 
-Guild-like system for teaming with permission sharing
