### ISSUE TITLE
명성초기화 적용 문제 

### ISSUE THREAD

**Issue by pooh9211** [Uuvana-Studios/longvinter-windows-client#1660]
**Describe the bug**
7월 8일날 우바나 1에서 명성초기화 4단계까지 하였으나 7월 16일인 현재까지 명성초기화 2에서 4로 적용이 되지 않고 있습니다. 
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] 97615967659669198
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0] 1196652201

**Additional context**

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
