### ISSUE TITLE
Inventory disappears in mines when I disconnect

### ISSUE THREAD

**Issue by LauraS08** [Uuvana-Studios/longvinter-windows-client#1666]
**Describe the bug**
When I'm mining in the Repouuro Cave, if I disconnect and then reconnect, all the items in my inventory are gone, even my equipped items. I did not die in the cave. I just disconnected.

**To Reproduce**
1. Go to 'Repouuro Cave' with items in inventory
2. Click on 'mineshaft'
3. Disconnect from game
4. Reconnect into game
5. Go to inventory
6. All items, even equipped ones, are gone

**Expected behavior**
When I reconnect, items in inventory should still be there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.14
 - Steam Version 1721173382

**Additional context**

**Comment by faketucker** [comment]
When you are in the mine, you will have the In Combat status, which will drop all your items if you disconnect.
