### ISSUE TITLE
I was stuck and couldn't get out

### ISSUE THREAD

**Issue by dinhbp** [Uuvana-Studios/longvinter-windows-client#1667]
**Describe the bug**
   stuck and unable to get out

**To Reproduce*
   I went to the stairs and fell between two campfires and couldn't get out

**Expected behavior**
   Please help me escape

**Screenshots**
   [Screenshots](https://github.com/user-attachments/assets/76bd13c9-00e4-4597-b889-4cc1228aab67)
   

    https://github.com/user-attachments/assets/9e03567e-a510-49a6-a4ee-8edbd927536b

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro version
          Version 23H2
          Installed on October 22, 2023
          OS build 22631.3880
          Experience Windows Feature Experience Pack 1000.22700.1020.0]
 - Game Version [1.14]
 - Steam Version [1721173382]

**Additional context**
   I'm playing on [JP] Uuvana #PVE server

**Comment by faketucker** [comment]
There's currently no other way to get out of the place you're stuck other than to type /kill in the chat right now. Unless there's an admin or dev online, they'll be able to teleport you out.
