### ISSUE TITLE
과거에 갇혔습니다

### ISSUE THREAD

**Issue by mjkoh76** [Uuvana-Studios/longvinter-windows-client#1669]
(Uuvana 4) 어제 서버가 불안정해진 후 가끔씩 과거로 돌아가지는 버그가 생겼습니다. 돌아가는 그 서버는 8월20일 8시쯤의 서버고, 21일 새벽 3시까지는 그래도 나갔다 들어오면 기존의 서버로 돌아왔었습니다. 하지만 8월 21일 아침에는 다시 과거의 서버로 돌아갔고 돈 또한 사라져있었습니다. (711만원에서 620만원으로) 그 서버의 모든 사람이 똑같은 현상을 겪고 있고 아직까지도 복구가 안 된 상황입니다.

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
