### ISSUE TITLE
Game crashed when i pick something up

### ISSUE THREAD

**Issue by Mik3St3rHVT** [Uuvana-Studios/longvinter-windows-client#167]
**Describe the bug**
When i enterd my friends server. i crash when picking up aanything!

Anyone know what to do?
Other servers i dont have this problem.
Still she can play but not me

**Comment by sirNugg3ts** [comment]
This seems not to be a bug but probably the server being out of date. We have no way to replicate such issue which seems to be more of a glitch than a bug
