### ISSUE TITLE
보관함이 사라졌습니다 (집내부 포함

### ISSUE THREAD

**Issue by asdssddsfwqedqkkj** [Uuvana-Studios/longvinter-windows-client#1672]
안녕하세요. 우바나 1 PVE? PVP ( 전투가 되는 ) 서버를 사용하고 있는데요

비밀번호를 누군가에게 공유한적도 없고 어렵습니다

저희 집 주인 닉네임은 [민댕쓰] 와 [아라공주] 입니다  집은 Heimo 항구에서 오른쪽으로 걸어가면 있습니다.

오늘 불과 새벽 2시까지도 있던 보관함과 집내부 보관함이 아침 6시 반쯤 접속하니까 다사라져있습니다.

누군가가 핵을 쓴것인지. 게임내 오류인지 확인해주시고

핵을 썻다면 제제 후 보관함 복구 요청드립니다.
![롱빈터 보관함 2](https://github.com/user-attachments/assets/7ff1d2e8-cc6b-4fff-817d-95681e588b6d)

**Comment by faketucker** [comment]
Duplicate of #600
