### ISSUE TITLE
집 4개 부패확장을 했는데 집 2개만 부패확장이 되었습니다

### ISSUE THREAD

**Issue by junyoung425** [Uuvana-Studios/longvinter-windows-client#1674]
안녕하세요 KR uuvana pve1 서버 준영입니다 제가 집 부패확장을 4개의 돈을 지불 했는데 2개만 되었습니다. 재접속을 해보았지만 계속해서 돈도 환불이 안되었고 나무도 60이 최대로 표시 되었습니다. 빠른 시일내로 버그좀 고쳐주셨으면 합니다.

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
