### ISSUE TITLE
버그에 대해서

### ISSUE THREAD

**Issue by goldkong** [Uuvana-Studios/longvinter-windows-client#1678]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

안녕하세요 개발자님
시작한지 얼마되지 않는 뉴비유저입니다
요근래 갑작스러운 서버 렉과 오류로 인하여 게임을 원활하게 이용할 수 없는 점 때문에 문의하게 되었습니다  
개발자님의 빠른 대처를 원합니다
읽어주셔서 감사합니다

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
