### ISSUE TITLE
My friends place the container at the exit of the house and we cant remove the container so we stuck in the house

### ISSUE THREAD

**Issue by nics555** [Uuvana-Studios/longvinter-windows-client#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Bug Reports that are not filled accordingly will not be taken in consideration
