### ISSUE TITLE
Point of interest turrets insane range bug

### ISSUE THREAD

**Issue by Fyreblade** [Uuvana-Studios/longvinter-windows-client#169]
**Describe the bug**
Recent patch seems to have increased safe zone "non-buildable" area. But turrets seem to have been coded to have unlimited range with an attack condition based on whether someone does aggressive things within the safe zone? Problem is the safe zone now exceeds the players view of the turrets, so turrets are shooting people from off screen.

**To Reproduce**
1. Stand within enlarged safe zone
2. Shoot gun
3. Get killed by turrets

**Expected behavior**
Only be shot by turrets if within a reasonable distance of them (ie at least within view of them)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0 latest version on public realm

**Additional context**
Something to define the boundary of the safe zone would be good. For example paving, fences, standing stones, etc

**Comment by sirNugg3ts** [comment]
this is not exactly a bug but more of a balanced gameplay issue. I'm gonna keep the issue open but this will not be a priority to fix right now

**Comment by Fyreblade** [comment]
Fair enough, problem is just that it's now harder to know that you're within the safe zone
