### ISSUE TITLE
Compendium resets on death

### ISSUE THREAD

**Issue by Kusivelho** [Uuvana-Studios/longvinter-windows-client#170]
**Describe the bug**
Compendium completely resets when I die. This didn't happen before, only after latest server wipe.

**To Reproduce**
1. Die.
2. See empty compendium. Plants, fish, all wiped.

**Comment by Dodg-e** [comment]
I can confirm my copendium reset after death, then i picked up wheat and tried dying to see if it would reset and this time it didn't, then i grabed a berry and died again and this time, the wheat was still in compendium but the berry was reset from it.

So it seems to be inconsistent not sure what causes it though

**Comment by Narchypoo** [comment]
This has happened to me all along.  I thought that was just what was supposed to happen - die and have to do it all over again lol.  That being said, my is resetting too - Got killed by a shooter and had to go catch all my fish again.

**Comment by sirNugg3ts** [comment]
I just tested this out and couldn't replicate. Either the steps are not accurate enough and it's only in certain types of death or it might just be a glitch
