### ISSUE TITLE
영구 정지 이유 

### ISSUE THREAD

**Issue by pooh9211** [Uuvana-Studios/longvinter-windows-client#1706]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
영구 정지 당한 이유를 알고 싶습니다. 영구 정지 당하기전 텐트 설치밖에 안했는데 다음날 영구정지 당했습니다.. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]  Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
This is not a place to appeal your ban. Please use https://longvinter.channel.io/
