### ISSUE TITLE
영구 정지 당한 이유가 무엇인가요? 

### ISSUE THREAD

**Issue by pooh9211** [Uuvana-Studios/longvinter-windows-client#1707]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
10월 27일 새벽 6시에 접속해서 텐트 설치한거 외에는 한게 없는데 왜 영구 정지 당했는지 모르겠습니다. 영구 정지 당한 이유라도 알고 싶습니다. 

**Screenshots**
![KakaoTalk_20241027_223504108](https://github.com/user-attachments/assets/3383d5d1-4830-4cec-8d26-448a77eacde6)

![KakaoTalk_20241027_224035875](https://github.com/user-attachments/assets/c1a6c34c-2181-480f-9dd1-0f21a9477223)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
This is not a place to appeal your ban. Please use https://longvinter.channel.io/
