### ISSUE TITLE
Spawn trap at tent

### ISSUE THREAD

**Issue by junigold** [Uuvana-Studios/longvinter-windows-client#171]
**Describe the bug**
Someone who killed me left a matchstick fire at my tent entrance. I cannot move, or click the tent to enter. Every time I die, I'm sent to the same location. What happened to the boat spawn failsafe? lol a group of people with nothing better to do is ruining a solo player's night because i can't do anything.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
> bug reports that are not filled correctly will not be taken in consideration, we need steps to replicate the bugs or we have no way to fix them

This is not a bug but a game balance problem. This will be taken care of after fixing major bugs
