### ISSUE TITLE
When killed in James recycle it keeps the menu for selling on your screen

### ISSUE THREAD

**Issue by unworthytr16** [Uuvana-Studios/longvinter-windows-client#173]
**Describe the bug**

**To Reproduce**
1. Go to 'james recycle'
2. Click on 'the vending machine'
3. get killed 

**Expected behavior**
I would of expected it to disappear

**Comment by mynoodlecat** [comment]
I am having the same issue! roooooood!

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
