### ISSUE TITLE
Small dupe for harvestables

### ISSUE THREAD

**Issue by Dodg-e** [Uuvana-Studios/longvinter-windows-client#174]
**Describe the bug**
If you press space fast while picking berries, wheat etc you can get more than one of it, havent tried with cultivated stuff like black lotus

**Expected behavior**
Not being able to dupe

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by ilrathCXV** [comment]
Did you have the Farmer's Hat on? If no, some crops look like they have a chance of giving more than 1 item randomly. Unless that too is not intended.

**Comment by sirNugg3ts** [comment]
Should be fixed in EXPERIMENTAL branch, should go live soon
