### ISSUE TITLE
Mouse click is not registering

### ISSUE THREAD

**Issue by Snowjuice** [Uuvana-Studios/longvinter-windows-client#175]
**Describe the bug**
When my friend launches the game he see's his mouse but the mouse clicks are not registering. Unable to even go past the news screen.

**To Reproduce**
Not sure how to reproduce this issue.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version Longervinter Beta 1.0.0
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
please give us more information, and possibly a recording of this problem

**Comment by sirNugg3ts** [comment]
Since no information was given we are closing this issue
