### ISSUE TITLE
Character Wipe upon login

### ISSUE THREAD

**Issue by CharlesLiRay** [Uuvana-Studios/longvinter-windows-client#176]
**Describe the bug**
Character inventory and achievments erased upon joining Uuvana 6 server.

**To Reproduce**
Collect vood, collect berry; sell item; purchase tent; etc.
log off
log on
inventory gone

**Expected behavior**
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
This issue occured after the March 3rd update

**Comment by sirNugg3ts** [comment]
Just tested this out in Uuvana 6 US and couldn't replicate
