### ISSUE TITLE
People can destroy my fence although my gate is locked!!!!

### ISSUE THREAD

**Issue by Diyzco** [Uuvana-Studios/longvinter-windows-client#177]
me and my friends connected our fence and put a gate to secure our house. Although the gate is locked, strangers can destroy our fence and come inside to our garden. **Please fix the fence issues**!! Please locked the fence when the fences are connected together!!!

**Comment by sirNugg3ts** [comment]
fences are not indestructible, that's why you want to have turrets to defend the property

**Comment by Diyzco** [comment]
> fences are not indestructible, that's why you want to have turrets to defend the property

Then whats the point of having a gate then?. The server that we enter are PVE not PVP, so does the turret still functioning in PVE??  @sirNugg3ts
