### ISSUE TITLE
Stuck in someone else's property

### ISSUE THREAD

**Issue by Renee1967** [Uuvana-Studios/longvinter-windows-client#178]
I started the game and I was inside my house where I was when I left the game last night. Then everything turned black. I restarted the game, still black. I can only see my character. I walked to the right, then I was in my house then boop, I was inside someone else's property and cannot get out.

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
