### ISSUE TITLE
Workbench opens as Cooking upon 1st click

### ISSUE THREAD

**Issue by CharlesLiRay** [Uuvana-Studios/longvinter-windows-client#179]
**Describe the bug**
When entering player tent/house; clicking on the Workbench opens the Furnace menu. The problems doesn't persist beyond initial attempt.

**To Reproduce**
1. Enter House or Tent
2. Click on Workbench for crafting.
3. Menu for Cooking opens.
4. Close Menu
5. Click on Workbench for crafting.
6. Menu for Crafting opens.
7. Leave House or Tent.
8. Repeat.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
Uuvana 6 server; pre-March 3 Wipe and Post Wipe.

**Comment by Jalsson** [comment]
This was caused by a fireplace near the workbench. I managed to reproduce the issue and got it fixed!
