### ISSUE TITLE
More ways to defend your property

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#18]
**Is your feature request related to a problem? Please describe.**
Putting in tons of work to get  your production going around your home just for 1 person with a chainsaw (who's name you won't know) To mow down your wooden fences take your crops and even take an expensive turret -.- several of them, is a huge hit to that sense of progression.
**Describe the solution you'd like**
I would like for their to be more ways to defend your home starting with the turret, allow  the turret to record who attacked you and get their name, the next time you see this player it can appear red and visible, Have the turrets act as home security and notify you of attacks, after someone attacks your property give them a penalty of where they can't just log off until a set amount of time has passed based on the amount of things stolen if they force a log off have it like RuneScape style where the character will still be online i don't expect most of this to be used just ideas.
**Describe alternatives you've considered**
Overall after losing over 100k in bought turrets who just sat their and let me get robbed, i want to see more defensive features like if you can afford it as a player let us build stone walls, forcing whoever wants to loot us to go and find more craft mods to make things like a sledge hammer and so on, not just any random person with a chainsaw can full loot you. 
**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
- Add more ways to defend your yard from raiding 
- Bounty / reputation system for pvp killers / leaderboards
