### ISSUE TITLE
add feature to connect to a local server

### ISSUE THREAD

**Issue by crus-mitsu** [Uuvana-Studios/longvinter-windows-client#182]
**Is your feature request related to a problem? Please describe.**
The general router is the one that does not allow you to access your global IP address from your LAN.
Therefore, these who make own dedicated servers cannot easily join own servers.

**Describe the solution you'd like**
I would like to have the feature to connect to a local server. For example, create a screen for inputing IP address and port for connet to a local server.

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
-Easier way to host a server / single player mode 

Linking ticket for reference
