### ISSUE TITLE
Stuck in the black area when login

### ISSUE THREAD

**Issue by MrMeww** [Uuvana-Studios/longvinter-windows-client#183]
**Describe the bug**
I logged in the game and got stuck in the black area near the house
ref.
https://www.picz.in.th/image/screenshot-2022-03-04-153857.rDWtH8

**To Reproduce**
just logged in the see the error

**Expected behavior**
Make it back to what it should be

**Screenshots**
https://www.picz.in.th/image/screenshot-2022-03-04-153857.rDWtH8

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [1.0]
 - Steam Version [lastest]

**Additional context**
-

**Comment by MrMeww** [comment]
i tried to walk around the area (hope to die and respond in my house) but the game wont let me.. the last thunder wont dry out..

**Comment by sirNugg3ts** [comment]
alt+k or /kill to die, this could have been due to lag or parcial wipe, and this is more of a glitch than bug, since we dont have steps to reproduce
