### ISSUE TITLE
make items out of air

### ISSUE THREAD

**Issue by The13east** [Uuvana-Studios/longvinter-windows-client#184]
**Describe the bug**
you can put an item on the ground and 2 people can pick it up
**To Reproduce**
1. anywhere
2. drop an Item
3. Have your friend pick up the item at the same time with a count down
4. both of them get the item and can use it ! It's easier with higher ping

**Expected behavior**
only one of the item exist ? IDK 
**Screenshots**
I can replicate it on any servers if you need ! contact me on discord The.13east#9528
**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version I'm on latest version but IDK what version it is 
 - Steam Version Also the latest version

**Additional context**
People can multiply turets like rabbits ! i saw bases with 20 turrets soon after the wipe

**Comment by Jalsson** [comment]
Thanks for informing me about this. will be fixed in the next update!
