### ISSUE TITLE
Edge of map possible glitch? Swimming far out to sea.

### ISSUE THREAD

**Issue by feedmeimstoned** [Uuvana-Studios/longvinter-windows-client#185]
**Describe the bug**
I was in the North East in uvanna 4 and started swimming more East with cooked fish and energy drinks. I swam for over 280 seconds before I went "under the water" and then the game crashed. Every time I log in, it now just intermittently puts me in the loading screen where I can see an arial view of the map. Sometimes for a half a second it will show me spawned at an outpost, but keeps flashing back and forth. I think I found the edge of the map? I have no idea, but now it won't let me log in to my server.

In order to get out of the game entirely, I need to ALT CTRL DEL END TASK in order to get out. 
![swimglitchrelogin](https://user-images.githubusercontent.com/100816131/156803633-47c1639a-8c8f-42c0-8c75-760c07444687.jpg)

**Comment by faketucker** [comment]
Tried. Seems like you'll get teleported back to the island when you reach the edge of the map now.
