### ISSUE TITLE
Fence disappear

### ISSUE THREAD

**Issue by Theromsio** [Uuvana-Studios/longvinter-windows-client#187]
**Describe the bug**
Putting a fence on the land disappears after a while, being in a specific point, it does not happen elsewhere, and it remains open

**To Reproduce**
1. Go to te rest of my fence
2. Click on a new fence
3. Put the fence with the rest of it
4. After a 10 or 15 secons disappear the fence

6. **Expected behavior**
Do not disappear the fence, like the rest of the other fences

**Screenshots**
You can see the part of the fence that disappear 
![image](https://user-images.githubusercontent.com/88055863/156859362-394e4aa1-4e98-491d-a4e0-a126a3b605ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version Beta 1.0.0
 - Steam Version API Steam v020

**Additional context**
Nothing to add here

**Comment by sirNugg3ts** [comment]
This bug was fixed with the new save system
