### ISSUE TITLE
Vendor UI stuck on screen

### ISSUE THREAD

**Issue by tamayo831** [Uuvana-Studios/longvinter-windows-client#188]
Vendor UI stuck on screen
![Longvinter   3_4_2022 6_55_49 PM](https://user-images.githubusercontent.com/59874080/156860634-1280e63e-e01a-45ad-99e7-48b1e19d54fd.png)

**Comment by sirNugg3ts** [comment]
> Bug reports that are not filled correctly will not be taken in consideration, we need steps to replicate the bugs or we have no way to fix them

**Comment by tamayo831** [comment]
Pretty hard to replicate when it’s an occasional bug, plus I had to restart
my game. So almost impossible to replicate but the bug is there.

**Comment by sirNugg3ts** [comment]
Occasional bugs are not bugs, they are called glitches, and its impossible to fix a glitch because we have no way to replicate them. Even so bug report was not filled correctly even if its occasional

**Comment by tamayo831** [comment]
Well either way it needs to be fixed. I’ve seen some people buy and items
from their base with this vendor UI stuck on screen. All I can really say
is I probably was spamming sell par dark lotus plant from my inventory.

**Comment by Mowrena** [comment]
is this issue fixed? I always get this most of the time and need to restart the game again and again. It occurs everytime I open up the vendo about 2-3 times, and it stays there.

**Comment by sirNugg3ts** [comment]
This issue was logged in #410  and this is the most up to date bug report
