### ISSUE TITLE
NO ITEMS PLACE GREEN

### ISSUE THREAD

**Issue by pizzadreams6** [Uuvana-Studios/longvinter-windows-client#189]
**Describe the bug**
After I place my tent down any item I place is blue before placement. Nothing is green.

I have tried multiple tents and multiple items, in multiple spots. Nothing will go down green. Only blue, meaning someone can take my items

**Comment by OkWetcat** [comment]
You have to upgrade to a house. A tent doesn't give you property to place green

**Comment by pizzadreams6** [comment]
Thank you. That is very helpful.
