### ISSUE TITLE
Walking off the map makes the game unresponsive even after rejoining the game server

### ISSUE THREAD

**Issue by itsN3WT** [Uuvana-Studios/longvinter-windows-client#19]
**Describe the bug**
![unknown-6](https://user-images.githubusercontent.com/100468399/155839026-cfb7869a-a561-4ab9-9616-a311022d0183.png)
If you walk off the map at around N51 or any coordinates after 51, the game becomes unresponsive. None of the UIs in game will work, including chat, ESC, inventory etc.

**To Reproduce**
1. Go to anywhere with the coordinates above 51
2. Bug occurs

**Expected behavior**
There's no indicator on where the map ends. A lot of players got stuck this way too thinking there's more to the map than just 100x100.

**Screenshots**
Screenshot was attached above.

**Desktop (please complete the following information):**
 - OS: Latest
 - Game Version: 1.0 Beta/Latest
 - Steam Version: Latest

**Additional context**
If you try to join another server, it works fine, but the specific one that you were in before is completrly corrupted.

**Comment by sirNugg3ts** [comment]
if you fall off the map, just use alt+k or /kill to go back
we are aware that the map is not big and we should put invisible walls.
thanks for the bug report <3
