### ISSUE TITLE
ISSUE WITH VENDING MACHINE

### ISSUE THREAD

**Issue by pizzadreams6** [Uuvana-Studios/longvinter-windows-client#191]
**Describe the bug**
16 N/ 14W the vending machine sells your items, or sometimes all of the items the machine has bought. if you go to purchase someone elses sold item, it will take your money, but not issue the item. 

**To Reproduce**
1. Go to 16 n/ 14w
2. Click on Vending machine
3. scroll over to buying tab

**Expected behavior**
I would love to be able to buy others sold items. Not sure which way is correct, or which way is wrong

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
