### ISSUE TITLE
17 digit code to connect gives no password prompt

### ISSUE THREAD

**Issue by KillerKazi** [Uuvana-Studios/longvinter-windows-client#192]
**Describe the bug**
When you use the 17 digit code to connect to a server, if that server is password protected there is no prompt to input a password.  The server disconnects you automatically with an incorrect password.

This makes it more so difficult for server hosts that must use this to connect to a local server that they are unable to see in the server browser.

**To Reproduce**
1. Go to Connect to Address
2. Insert Session ID
3. See error

**Expected behavior**
Enter code, prompted with password input to connect.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Comment by KoalaBoy** [comment]
Maybe the next update you'll able to do that
https://discord.com/channels/846308806870695967/873486241482559508/948975566353203201

**Comment by Jalsson** [comment]
We have added password field to direct connection!
