### ISSUE TITLE
Unable to enter house

### ISSUE THREAD

**Issue by flooopy** [Uuvana-Studios/longvinter-windows-client#193]
**Describe the bug**
Unable to enter house. I think I placed a row of chests/storage containers too close to the door, so now when I try to enter, I immediately appear back outside. After attempting to enter the house, black screen with loading wheel along with shuffling sound prompt, then appear outside of the house. 

**To Reproduce**
1. In an upgraded house
2. Place a row of chests/storage containers roughly one player model width from the entrance of the door
3. Exit the house
4. Try to reenter the house

**Expected behavior**
To be able to enter and be inside of the house

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Beta 1.0.0
 

![longvinter snip](https://user-images.githubusercontent.com/100990944/156885651-796c1f47-a57b-43f9-970c-b0e3ba2f1a61.PNG)
View from a new tent into my house in the top right of the screenshot. I believe the single high chest is blocking me from entering the house.

**Comment by Jalsson** [comment]
New update should make entering a house more reliable. Please comment back if the problem still continues.
