### ISSUE TITLE
fences disappear overnight

### ISSUE THREAD

**Issue by mrccwolf** [Uuvana-Studios/longvinter-windows-client#194]
**Describe the bug**
Fences which were placed hours before logging over disappeared overnight and people entered my property and stole all my plants. This happened to 3-4 people that lived nearby. Everyone placed their fences within the protected "green" zone. We further tested this by replacing the random missing fences and other people could not remove them. I don't know if the servers restarted at any point.

If this was related to someone walking up and removing the fence... it may be notable that the fence was in most cases very "close" to the edge of the protected zone. Typically within 1-3 gaps of the "blue zone". We could not replicate though. 

**Screenshots**
Image of missing fence section discovered upon log-in
![image](https://user-images.githubusercontent.com/53386742/156879183-82ad1b39-d366-4a4c-9d17-63e695ab7aee.png)

Image confirming the exact position of the fence piece was protected. This happened to multiple people and everyone confirmed they were in the safe zone. 
![image](https://user-images.githubusercontent.com/53386742/156879214-078674e6-c0e7-4c2c-b9ed-b4e5ee4af49e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 3/4/2022 latest steam update

**Comment by Jalsson** [comment]
Fences can be broken down with weapons. Because there was just single fence missing I think some player destroyed the fence.
