### ISSUE TITLE
maybe a dupe glitch? or maybe someone added too many zeros on 30%

### ISSUE THREAD

**Issue by PocketDragon108** [Uuvana-Studios/longvinter-windows-client#198]
If you press space fast as well as click fast while picking berries/flowers you can get more than one of it, i have the farmer hat one and in some cases have got a full bag from 1 flower. i believe only works with hat from testing. is hat plays part this is a little more then 30% increase on harvesting! 

**To Reproduce**
Steps to reproduce the behaviour:
1. plant harvestable
2.  once harvestable grown equip farmers hat! 
3. go ahead and harvest but spawn space and click to make sure you are actioning the pickup/harvest as fast as possible! 
4. reap the rewards. feel free to sell this to merchants then break economy! - disclaimer, please dont break economy i like the game and its fun but need good economy <3 

**Expected behaviour**
id hope to only get a 30% increase and not have economy broken by a few clicks :( 

**Screenshots**
i cant really screen shot but i have clips of my testing - 
WITH FARMING HAT TEST 1- https://youtu.be/W_eBUD7zfS0
WITH FARMING HAT TEST 2 - https://youtu.be/kMAl-h2kTUk
WITHOUT FARMING HAT TEST 1 - https://youtu.be/9bpQ2Q7KkGA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0
 - Steam Version (sorry unsure how to check) 

**Additional context**
i love you guys! <3 keep up the good work! you have a gem of a game here! 
for the other dupe glitch's - https://youtu.be/iik25wqIuFo

**Comment by Jalsson** [comment]
There was a error when calculating the farming hat buff effect on harvest. The 30% reduction was actually calculated for nearly 300% buff. Fix will be included in next experimental update
