### ISSUE TITLE
Stuck behind a container

### ISSUE THREAD

**Issue by Alexel01** [Uuvana-Studios/longvinter-windows-client#200]
On one of the shed (5°N 9°E), you can climb on the smaller box and on the biger box, but if you go behind the contanainer, you j ust get stuck in this area with no way to get out. 

**To Reproduce**
1. Go to (5°N 9°E)
2. Climb on the small boxes and try to bo behind the blue container
3. You're stuck. 

**Expected behavior**
A way to jump above the boxes, to teleport back to your house or to the nearest harbor when stuck would be nice. 

**Screenshots**
![Bug report1](https://user-images.githubusercontent.com/101010838/156891015-5d8bf339-362a-49d6-bf5f-c4cf6477bf45.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Game Version : Beta 1.0.0
 - Steam Version : Mar 4 2022

**Comment by Jalsson** [comment]
Added blocking volume to prevent anybody from going there
