### ISSUE TITLE
Can't join my own server when people are connected.

### ISSUE THREAD

**Issue by Mr6D9** [Uuvana-Studios/longvinter-windows-client#201]
( Windows 11 Pro, Version: 21H2, OS Build: 22000.527, System Type: 64-bit operating system, x64-based processor, Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz )
I'm self-hosting on my PC and have my Firewalls Open.
![image](https://user-images.githubusercontent.com/97693528/156891333-9978170a-ad22-4699-b5b3-90079b2a0e5e.png)
![image](https://user-images.githubusercontent.com/97693528/156891202-186b12db-242c-41e6-be75-b4b6c1e4434b.png)
I also have the common issue where I can't see the server on the Server List

The only fix I had for getting back on to the server when people are connected is to restart the server. (then I can connect when people are connected)

**Comment by sirNugg3ts** [comment]
please put this issue in https://github.com/Uuvana-Studios/longvinter-windows-server/issues
