### ISSUE TITLE
can't enter house

### ISSUE THREAD

**Issue by TamaraDuinhouwer** [Uuvana-Studios/longvinter-windows-client#204]
**Describe the bug**
i connot enter my house, i think becouse i place a banch at the entrance at the inside of my house ..

**Expected behavior**
maybe if it is the bench, you could do something that u cannot place items at the entrance of your house

 - Steam Version [e.g. 1.0]

**Comment by rossleeef** [comment]
I had this happen too, I placed a sign at the entrance of my tent and now I can't enter. Added bonus, the sign accidentally placed on top of my head so it's too high to remove... my tent is stuck inaccessible

**Comment by AloeAline** [comment]
I got this problem also.

**Comment by isaacneworld** [comment]
i got too.

**Comment by PocketDragon108** [comment]
I help some in the discord with this one, what we did was constantly keep entering the house and right clicking it pick up the item blocking after about 3 mins of trying he got it! Just if you place a crate or something with items in it you'd damm out of luck :(

**Comment by TamaraDuinhouwer** [comment]
> I help some in the discord with this one, what we did was constantly keep entering the house and right clicking it pick up the item blocking after about 3 mins of trying he got it! Just if you place a crate or something with items in it you'd damm out of luck :(




> i tried but it doesn't work. i dont see the inside of my house, it sounds like the others did? i get a black screen with the looding sign buttom right. i tried clicking my spacebar fast but nothing works. sucks.. :(

**Comment by PocketDragon108** [comment]
That's because spacebar won't pick up a placed item. You need to right click!

**Comment by Jalsson** [comment]
New update should make entering a house more reliable.
