### ISSUE TITLE
Default fishing keybind 'E' prevents 'ESDF' movement

### ISSUE THREAD

**Issue by hexparrot** [Uuvana-Studios/longvinter-windows-client#205]
**Describe the bug**
Due to 'E' being unconfigurable for 'reel in fish', my preferred movement keys ESDF are non-viable.  When fishing, I therefore am forced to move up at the same time as 'reel', resulting in it cancelling the fishing.

**To Reproduce**
1. Bind ESDF to movement keys
2. Equip fishing pole and go fishing
3. Press the 'E' key from onscreen to attempt to reel in
4. Can't reel in due to simultaneous movement

**Expected behavior**
The key 'E' (Use, Reel?) should be user configurable in keybinds.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: EA 1.0

**Additional context**
Eventually, showing the user-configured keys rather than the default keybinds in loading/help screens would be preferred.

**Comment by Balthaxair** [comment]
fix your keyboard don't waste their time with this kind of thing

**Comment by Jalsson** [comment]
Keys can now be changed in the input menu so this is no longer a problem
