### ISSUE TITLE
The sea is white and theres no fishing spots

### ISSUE THREAD

**Issue by mimoe12** [Uuvana-Studios/longvinter-windows-client#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by PocketDragon108** [comment]
Bumping to let you know your big report is blank

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
