### ISSUE TITLE
Container status is not updated for a while when you walk away after opening it

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#210]
**Describe the bug**
It'll say the container is in use by someone else when you open it and walk away, and try to re-open it again

**To Reproduce**
1. Go to 'a container'
2. Open it and walk away
3. Try to re-open it
4. Container status is not updated for a while

**Expected behavior**
Container status is updated in real-time

**Desktop (please complete the following information):**
 - OS: Windows: 11
 - Game Version: 1.0.0
 - Steam Version: Lastest

**Additional context**
I don't know if this is a bug or it's a delay of client-server thing

**Comment by sirNugg3ts** [comment]
From last update

> Fixed a bug where chest stays locked when player logouts when using it
