### ISSUE TITLE
Chainsaw's and Arena Fixes.

### ISSUE THREAD

**Issue by catnapstv** [Uuvana-Studios/longvinter-windows-client#213]
So for Chainsaws I thought it would be cool if you guys fixed up the animation and sound,

lower the sound of chainsaws and the distance they travel, make the effect a little different, maybe drop the tree down rather then glitch it? 

Then in Arena i thought it would be cool if you guys  put the  2 random crates spawning randomly in the  arena zzone, this allows players to never know where it is and duel for it in the arena.

want more info? check out my stream, im the leading twitch streamer for the game currently.

catnapstv

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
- balance chainsaw volume / sound range
- make loot crates in the areana locations more random
