### ISSUE TITLE
if you're building and you die you instant glitch and inventory gets stuck.

### ISSUE THREAD

**Issue by catnapstv** [Uuvana-Studios/longvinter-windows-client#214]
There is a huge glitch where if you die while placing something you then have the item floating and your inventory is stuck and unusable. you can still retrieve your dropped items but have to always restart the game in order to fix the inventory glitch. happens 100% of the time and im sure others have experienced it.

**Comment by sirNugg3ts** [comment]
Please do the bug report following the template
