### ISSUE TITLE
I accidentally placed a sign on top of my head, now it's too high to remove

### ISSUE THREAD

**Issue by rossleeef** [Uuvana-Studios/longvinter-windows-client#215]
**Describe the bug**
I was placing a sign and when it went blue i placed it, now it's above head height and i don't know how to remove it. It's also close to the entrance of my tent so now I can't enter my tent. (I can reach the door of my tent, but it glitches out)

**To Reproduce**
1. stand outside a dwelling
2. place sign just in front of the character
3. it should place on top of the characters head

**Expected behavior**
The sign or whatever item will not be able to be removed

**Screenshot**
![longvinter sign glitch](https://user-images.githubusercontent.com/101029731/156907605-9182ed78-8dc5-4dba-80ea-9dfb7acd131a.jpg)

**Comment by faketucker** [comment]
You can place it on the character's head, but it's still removable. Try to unequip your equipment and right-click on the item you want to remove.
