### ISSUE TITLE
Small Dupe

### ISSUE THREAD

**Issue by freshtaken** [Uuvana-Studios/longvinter-windows-client#216]
**Describe the bug**
A dupe that allows wood to be duped (for the house upgrade)

**To Reproduce**
1. go to workbench inside tent
2.  get 1 piece of wood only in your inventory
3.  click deposit wood and quickly click the wood to put it in the crafting section 
4.  it adds one to the total wood and the wood is still fully usable in the crafting section (its not a ghost item i tried it multiple times)
5. 

**Expected behavior**
I was just messing around and i clicked on one of the pieces of wood after depositing all and then it was still in the crafting section so i clicked again and it wasnt a ghost item

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0
 - Steam Version: API v020

Additional context
N/A

**Comment by sirNugg3ts** [comment]
I tested this out, couldn't replicate, can you check if this dupe only works in laggy servers?

**Comment by freshtaken** [comment]
yeah shoulda mentioned i was on a full server with 110 ping so that might have helped that happen

**Comment by sirNugg3ts** [comment]
Ok that's actually very usefull information, thank you for your input <3

**Comment by Jalsson** [comment]
Fix for this will be included in next update
