### ISSUE TITLE
Sgt. Lake's Travel Outpost Glitch

### ISSUE THREAD

**Issue by Maeday2o6** [Uuvana-Studios/longvinter-windows-client#219]
I traveled from NE map to Sgt Lake's outpost, it started with the boat screen traveling through the ocean, then just had ocean without anything around it. Could not see any structures or character model. I could walk around and it would still drain energy. When I walked more east I fell through the map, going to what seemed like "underground" but probably someone's house (I just started playing so I don't know what inside houses look like). When I tried to leave the house it was a player's base surrounded by turrets so I automatically died and lost everything.

**Comment by sirNugg3ts** [comment]
Please fill the bug report according to the template. If you don't give us the info to replicate we have no way to fix it
