### ISSUE TITLE
House Collapse and Can not enter a house

### ISSUE THREAD

**Issue by AloeAline** [Uuvana-Studios/longvinter-windows-client#220]
HI, I got this problem about the house collapse and also my friends house, 
![lvt_bug02](https://user-images.githubusercontent.com/101035476/156912187-aeb75521-5899-463c-bfe4-b9664febb944.png)
he suddenly place the box near the door and he can not go inside his house any suggestion for this.
![lvt_bug01](https://user-images.githubusercontent.com/101035476/156912190-56874f10-0a06-4fdc-ab1a-db19540bdc3d.png)

Thank you.
AloeAline.

**Comment by Jalsson** [comment]
New update fixed some spawning problems. Please comment back when you have installed update. And updated the server if you are playing on unofficial server

**Comment by sirNugg3ts** [comment]
No more information was given, closing issue
