### ISSUE TITLE
Did not spawn at house and all mk is gone

### ISSUE THREAD

**Issue by DerpaDerp125** [Uuvana-Studios/longvinter-windows-client#221]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by PocketDragon108** [comment]
Helping to remind you your big report is not filled out. Please attached more information to help the Devs! Wheres where you when your logged off/died and what server? Stuff like this helps then find and patch the bug

**Comment by sirNugg3ts** [comment]
Completing what @PocketDragon108 said:

Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
