### ISSUE TITLE
Ocean bug

### ISSUE THREAD

**Issue by Kito0o0o** [Uuvana-Studios/longvinter-windows-client#222]
**Describe the bug**
Spawned in and the ocean just disappeared.

**To Reproduce**
Unsure how to reproduce. Attempting to full restart
**Expected behavior**

**Screenshots**
https://gyazo.com/cab351c9d0cae4a0eb936379d9bbaab6

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Game Version [e.g. 1.0]1.0.0 
 - Steam Version [e.g. 1.0]

**Additional context**
Add any other context about the problem here. no other context
thank you for your time

**Comment by Kito0o0o** [comment]
The water still isnt showing up after restarting the game

**Comment by sirNugg3ts** [comment]
Duplicate of #13
