### ISSUE TITLE
Longvinter stops running apps in the background

### ISSUE THREAD

**Issue by naSlash26** [Uuvana-Studios/longvinter-windows-client#224]
**Describe the bug**
Hello, yesterday I wanted to stream the game but the problem is that the game when I go to it in the foreground, it stops running my other apps in the background except the streaming software and so it's quite problematic for me who uses software to make my vtuber work ^^ 

**Expected behavior**
Normally the game should be able to run in the foreground and not block my other apps behind to work. 

**Screenshots**
https://www.twitch.tv/videos/1416482506
At 15:58 for example, you will see me playing but my 2D avatar et my Stream avatar app are frozen.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
I just run the game and nothing freezes, background or foreground, this seems to be an issue with the other programs and not with game

**Comment by naSlash26** [comment]
But if I do the same with other games, I don't have this problem..

**Comment by naSlash26** [comment]
I have seen an other stream of a vtuber and he has exactly the same problem as me. So I think it's a problem from the game and not mine ^^
