### ISSUE TITLE
Outside of the Map

### ISSUE THREAD

**Issue by Dixonnnnn** [Uuvana-Studios/longvinter-windows-client#227]
You can get out of the map by closing the game (or possibly leaving a lobby) at the right time and become stuck

**To Reproduce**
1. Go on the boat to the outpost
2. Close the game at some point throughout the transition
3. Reload the game
4. Rejoin the server
5. Run around in the under ocean section and you get out of bounds

**Expected behavior**
This wasn't found on purpose so I expected that when I rejoined I would either be at the outpost or at the place where I took the boat

**Screenshots**
![image](https://user-images.githubusercontent.com/101045981/156921202-a4f9f877-4504-431f-b834-c3157f3fc971.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
I believe this was fixed. You will be teleported to the safe zones instead of the void if you get out of ocean bounds
