### ISSUE TITLE
Crashing when logging in to server 

### ISSUE THREAD

**Issue by natemcd01** [Uuvana-Studios/longvinter-windows-client#229]
**Describe the bug**Once I click the Play Button on the Home Screen and select the server EU UUVANA 1,2 or 3 It disconnects me from the server either right away or a minute or two later. 

**To Reproduce**
1. Go to: play 
2. Click on: {EU} Server 
3. Wait to get Disconnected 
4. no error message 

**Expected behavior**
To be able to log in and play the game.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Game Version Beta 1.0.0
 - Steam Version: 8307790

**Additional context**

**Comment by sirNugg3ts** [comment]
> Once I click the Play Button on the Home Screen and select the server EU UUVANA 1,2 or 3 It disconnects me from the server

That's not a crash, that's simply disconnecting, please don't mix both terms.

Are you sure you are not in the experimental branch? Also be sure to have your game updated

**Comment by natemcd01** [comment]
The Reason I added crashing because when I was able Play and collect items they were lost after my (disconnect or crash) and I would have to restart my progress. I should Have added that to the original message. It appears to loose everything and money after the 2nd or 3rd Disconnect.

**Comment by sirNugg3ts** [comment]
Got into EU 3 just fine, servers are laggy because there's a lot of people playing, you probably got disconnected for that reason
