### ISSUE TITLE
Fishing rod disappears when opening settings

### ISSUE THREAD

**Issue by adynt8** [Uuvana-Studios/longvinter-windows-client#23]
**Describe the bug**
Fishing rod disappears when opening settings. 

**To Reproduce**
1. Go to fishing spot
2. Throw out rod
3. Open settings

**Expected behavior**
Not cause fishing rod to disappear.

**Desktop (please complete the following information):**
 - OS: [Windows 10
 - Game Version 1.0.0
 - Steam Version 1642451672

**Comment by sirNugg3ts** [comment]
if possible, attach screenshots or record a video of this issue happening

**Comment by adynt8** [comment]
Couldn’t get it to reproduce again.
