### ISSUE TITLE
Last message shows up after boat travel

### ISSUE THREAD

**Issue by Mikooboy** [Uuvana-Studios/longvinter-windows-client#230]
**Describe the bug**
Last sent text message shows up again after using a boat to travel.

**To Reproduce**
1. Send a message using the chat
2. Go to a boat
3. Use the boat to travel somewhere

**Expected behavior**
After having the message disappear, I would expect that it would show up again after using the boat.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [Experimental]

**Comment by Mikooboy** [comment]
Also, the damage numbers will not disappear if you travel to somewhere with a boat while taking damage.
The numbers will just stay there until you die.

![image](https://user-images.githubusercontent.com/73204452/156940815-62f6c634-b887-45f0-9fc3-e724b8718be0.png)

**Comment by sirNugg3ts** [comment]
Still happens in the last update

**Comment by Mikooboy** [comment]
Changed the chat bubble to delete correctly so this should be fixed in the next update
