### ISSUE TITLE
Unmovable Infinite Storage Bug

### ISSUE THREAD

**Issue by MrVilo** [Uuvana-Studios/longvinter-windows-client#233]
The Infinite Storage Bug when picked up will drop around 4-9 maybe more storage before disappearing leaving stacks of chests on the floor creating basically an infinite amount of storage chests.

The Unmovable Storage Bug when collecting or picking an empty storage it would do the same with the Infinite Storage Bug but the Storage itself will not disappear and no matter how many times you click to pick up it would still drop infinite amounts of storage but as the storage box itself wont disappear you wont be able to collect this so called infinite amount of Storage only if it were to disappear but since the storage itself wont disappear you are able to access the storage itself.

I hope the Devs take notice of this.

Thank You for all your Hard Work!
-MrVilo

**Comment by sirNugg3ts** [comment]
Okay so fancy names, but you haven't exactly explained how the bug works or give steps? 

> The Infinite Storage Bug when picked up will drop around 4-9 maybe more storage

I can't really understand what you mean. What do you pick up? What is droped? By storage do you mean containers?

**Comment by MrVilo** [comment]
its common sense as there's only one storage item in game but yes its the containers, picking the container up would leave a sack (which would be the item you tried picking up or dropping, but in this case the picked up item)

**Comment by sirNugg3ts** [comment]
This seems a bug with laggy servers, can you test on a low ping and almost empty server please?

**Comment by MrVilo** [comment]
yes this is tested, the server ping I am currently on is at 28 with only 1 player in which is me

**Comment by MrVilo** [comment]
this maybe due to stacked containers on top of each other, rendering it unmovable (the top container, bottom container is fine but leaves the other container floating)

**Comment by MrVilo** [comment]
never mind, its the same even if the container is by itself on the ground

**Comment by faketucker** [comment]
This occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.
