### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by L0574u5513** [Uuvana-Studios/longvinter-windows-client#236]
Haven't been able to play for longer than 15 minutes before the game crashes to the main screen loosing all progress. Very frustrating.

**Comment by sirNugg3ts** [comment]
Please give more information, like setup, error messages, etc.

**Comment by stuntrunt** [comment]
same here

**Comment by ixDmnd** [comment]
i can play for a little and then the game lags and then i get put back to the start screen with the news tab on my screen. when i get back to the game i lose everything in my inventory. no error code nothing just get disconnected.

**Comment by L0574u5513** [comment]
Hi
I play for 10-15 minutes and it just stops. Returns to the main screen. Same as other comment on my post, no error, no lag.
Just stops.


Asus tuf gaming laptop
11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
8gb ram

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ixDmnd** [comment]
https://user-images.githubusercontent.com/101069816/156945002-63430667-d853-438d-9e24-ddfb0b80b114.mp4

**Comment by ixDmnd** [comment]
that is a clip of it happening to me

**Comment by ixDmnd** [comment]
last comment from 30 minutes ago was the time it crashed last

**Comment by Morgoth1310** [comment]
geez.... need more info label then when given more info absolutely no follow up lol

**Comment by sirNugg3ts** [comment]
> geez.... need more info label then when given more info absolutely no follow up lol

I also sleep tho xD

That seems to be a version missmatch between server and client. Game was just updated so please update and check if this still happens

**Comment by Morgoth1310** [comment]
> > geez.... need more info label then when given more info absolutely no follow up lol
> 
> I also sleep tho xD
> 
> That seems to be a version missmatch between server and client. Game was just updated so please update and check if this still happens

That's fair mb mb just want to play the game 😭

**Comment by L0574u5513** [comment]
I did the update, tried the official (Aus) server. Started with a black screen, I quit to the menu, restarted. I was in a tent (not mine as I haven't been able to make it that far) Easily caught 80 fish by now with the number of restarts. 5 minutes tops, crashed to the main screen. Why did I pay $20 for a game that cant be played for more than 5 minutes?? I want to support new games but this is really disappointing.
