### ISSUE TITLE
MY invotory has reset ....

### ISSUE THREAD

**Issue by Sneeazy** [Uuvana-Studios/longvinter-windows-client#237]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Duplicate of #120
