### ISSUE TITLE
Server browser empty

### ISSUE THREAD

**Issue by Mikooboy** [Uuvana-Studios/longvinter-windows-client#238]
**Describe the bug**
The server browser takes an incredibly long time to display/load the server list (+10 minutes).
The servers will still be loaded, but it takes so much time that you don't even expect the servers to appear anymore. This means that restarting the game is way faster than waiting for the servers to load.

**To Reproduce**
1. Join any of the experimental servers (normal servers seemed to be fine)
2. Spend a little time on the server and do something that affects the world/save
3. Disconnect from the server 
    (There should be a noticeable delay when pressing the button. Maybe because of the new saving?)
5. Navigate to the server browser again
6. No servers

**Expected behavior**
I would expect the server browser to work like it did before visiting the experimental server i.e. servers showing up in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/73204452/156944275-be4d590c-9db5-4f2d-b354-6c7ed5128508.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [Experimental 1.0.0]

**Comment by Mikooboy** [comment]
After further testing it seems like this does not happen on the [US] experimental server, only on the [EU] experimental

**Comment by bryan-swang** [comment]
This happens for me too while waiting for a server list to appear. It is essentially an empty screen.

**Comment by SebastianMaj** [comment]
I have someone on my server who experiences this but all the time so they never see any servers on the server list. Can only join via session id.

**Comment by Mongulusus** [comment]
Just bought the game , and now i cant play because of that. I restarted it and istalled it new . Nothing happend. Even if i wait for like 20 Minutes. Thats pretty sad. Does somebody know how to change to us Server ?

**Comment by Bunnbunnnn** [comment]
Player had similar problems and found these similar threads in discord: 
https://discord.com/channels/846308806870695967/846308807386464268/954221364821241886
https://discord.com/channels/846308806870695967/934069436216918017/953762740978216971
https://discord.com/channels/846308806870695967/846308807386464268/954348348788342874
https://discord.com/channels/846308806870695967/934077368610488340/954693153846358066

This peson cannot either and just had to opt to connect only via session id 
https://discord.com/channels/846308806870695967/934069436216918017/953139544641925150

**Comment by jar53** [comment]
I'm currently having this problem & can't seem to get past this. I've just bought the game, uninstalled, disabled firewall, closed & relaunched game. I see 0 servers at all times. Just released on steam & still not able to resolve this...
