### ISSUE TITLE
Fishing spots teleport character a few feet away

### ISSUE THREAD

**Issue by adynt8** [Uuvana-Studios/longvinter-windows-client#24]
**Describe the bug**
Standing still on certain fishing spots cause the character to be teleported a short distance away while still keeping the rod in the water.

**To Reproduce**
1. Go to fishing spot
2. Cast reel
3. Stand still
4. Bug happens (doesn’t everytime)

**Expected behavior**
Character does not get teleported while standing still during fishing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1642451672

**Comment by sirNugg3ts** [comment]
that seems like only rubberbanding from the server. Please confirm if this only happens when the server has a high number of players

**Comment by sirNugg3ts** [comment]
Rubberbanding has been fixed
