### ISSUE TITLE
Unable to place tent

### ISSUE THREAD

**Issue by hexparrot** [Uuvana-Studios/longvinter-windows-client#241]
**Describe the bug**
No amount of available room will allow placement of tent.  Can not progress in game.

**To Reproduce**
1. Buy research tent
2. Find available space
3. Try to place tent
4. See picture

**Expected behavior**
I expect to be able to place a tent in longvinter.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Game Version: EA 1.0

**Additional context**
Uuvana 7. Taken 3/5/2022.
![placement](https://user-images.githubusercontent.com/4994619/156957968-710706a1-7129-4b3d-be26-45535d21672e.jpg)

**Comment by sirNugg3ts** [comment]
that could be the issue we had that houses disappeared, which does not happen anymore, or there is a plot right below the visible screen, which we can't see form the screenshot
Will close this issue for now

**Comment by hexparrot** [comment]
So, I've now played for 4 hours and have not successfully gotten a tent down.

It's possible there's a plot right below--but then again, I know there wasn't.  The next question is:

having never been able to successfully place a tent, and placing it in over probably 300 different attempted locations, can something be done so that I know that even off-screen is preventing my ability to play?

There _wasn't_ any plot below, but if there even was--can you include boundaries in the tent-placement system?  If I knew the plots were bigger than the screen, I'd be less surprised when it tells me I can't place it because of another plot.

**Comment by sirNugg3ts** [comment]
We have a fix in EXPERIMENTAL where the model and the space of the tent is better represented, update tomorrow might help
