### ISSUE TITLE
Harry Potter Housing Glitch

### ISSUE THREAD

**Issue by Witteborn** [Uuvana-Studios/longvinter-windows-client#242]
**Describe the bug**

[15s video showing the bug](https://i.imgur.com/mCHKFpS.mp4)

**To Reproduce**

First you need to set up two tents directly behind each other, or houses, it works with both.
<img src="https://user-images.githubusercontent.com/27786664/156955684-36b147f8-a065-463d-a33c-3f3456ec892a.png" width="200" />

It works best when these are as close and parallel to each other as possible

When the tents are set up you can walk in the lower tent from the bottom and out again from the top.

<img src="https://user-images.githubusercontent.com/27786664/156955890-e88f8b86-0b57-40cc-baa8-2bc473e6022b.png" width="300" />

**Expected behavior**
The behavior of the wall should not change because one is so close to the entrance of another tent.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Beta 1.0.0
 - Steam Version
 
![image](https://user-images.githubusercontent.com/27786664/156956142-de0dc913-b6de-4916-89bd-62990b707c20.png)

**Comment by sirNugg3ts** [comment]
Next update should fix this, if not please reopen the bug report
