### ISSUE TITLE
Fast Click Dupe

### ISSUE THREAD

**Issue by GrooovyCat** [Uuvana-Studios/longvinter-windows-client#243]
**Describe the bug**
you can dupe stuff in i think all menus that you can store stuff in

**To Reproduce**
1. open menu that you can store stuff
2. then click on the item fast then it will dupe 
3only happens when laggy like the sever 
**Expected behavior**
the item some times disappears then clicking the item slot it reappears  
adn happens not often/only when its laggy on the sever side 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows]
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**

**Comment by Jalsson** [comment]
Reworked the transfer process. It is now a bit slower when the ping is high. I will have to improve responsiveness later
