### ISSUE TITLE
Spawn Point Reset 

### ISSUE THREAD

**Issue by Oldbourbon413** [Uuvana-Studios/longvinter-windows-client#244]
**Describe the bug**
Spawn point is reset as well as MK is reset on my character if I log off and don't immediately log back into game.

**To Reproduce**
1. Play game
2. Close game for a few hours
3. Relaunch game
4. End up at initial spawn point instead of tent/house

**Expected behavior**
I should be starting off at my house, not at the starting pier

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1646446125

**Additional context**

**Comment by Jalsson** [comment]
The latest changes in the new update should now have fixed all the saving issues. Make sure you update your game and server files is you play on unofficial server
