### ISSUE TITLE
Unraidable base with containers

### ISSUE THREAD

**Issue by Dodg-e** [Uuvana-Studios/longvinter-windows-client#245]
**Describe the bug**
Containers cant be destroyed so you can use them as walls to make an unraidable base

**To Reproduce**
1. Use containers around your house
4. Unraidable base

**Expected behavior**
Being able to destroy the containers or some other fix

**Screenshots**
https://ibb.co/RCLL4DT

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
