### ISSUE TITLE
Nowhere to place a tent

### ISSUE THREAD

**Issue by REZSO45** [Uuvana-Studios/longvinter-windows-client#246]
**Is your feature request related to a problem? Please describe.**
There is nowhere for me and some others to place our tent on the map and spent over a half hour trying to find a spot.
**Describe the solution you'd like**
I'd like some way of placing my tent so i can play.
**Describe alternatives you've considered**
Maybe keep the limits of other homes to their allotted space rather than extending out a few more inches.
**Additional context**
i tried this on server 6 right after the update.

**Comment by maxgrfx** [comment]
i can't place a tent anywhere, i've tried in different servers and in different places but nothing

**Comment by sirNugg3ts** [comment]
The map is going to be constantly updating, if one server is full, try another one
