### ISSUE TITLE
Character Reset

### ISSUE THREAD

**Issue by MaruLow** [Uuvana-Studios/longvinter-windows-client#248]
**Describe the bug**
Login back into the game , and im stuck in underworld " where your character supposed to be in house , but mine stuck and can walk around to see inside other player house"  and yes my character have been reset again. Now it has been 3rd time. 

**To Reproduce**
1. Sometimes when you login back again into the server , your character will be reset. The bug haven't been fixed . And my character stuck in the underworld this time when i login back to the server. I see no points for me to keep grinding because my character will be reset all over again.

**Expected behavior**
My character won't be reset.

**Screenshots**
lost the screenshot.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
What server did you play on?

**Comment by MaruLow** [comment]
> What server did you play on?

Singapore TPG. My ping is between 50 - 80

**Comment by grodish** [comment]
Same happens to me 3 times...
[EU] Uuvana 1 
If you disconnect several times in a row you lose all your progress and money

**Comment by Ekhalal** [comment]
Same on [EU] uuvana 3

**Comment by sirNugg3ts** [comment]
Duplicate of #257
