### ISSUE TITLE
Chest Organization 

### ISSUE THREAD

**Issue by 3Four** [Uuvana-Studios/longvinter-windows-client#25]
It would be a neat addition if Chests could change colors (Like Stardew Valley) so we can have better chest organization or just a different look for Chests  :D

**Comment by Bunnbunnnn** [comment]
#22 Issue is also along the lines of this - leaving this comment as a reference

**Comment by sirNugg3ts** [comment]
@3Four please add this idea as a comment to #22 since that one is more complete and in the same subject
