### ISSUE TITLE
Can't pickup my firepit after placing it

### ISSUE THREAD

**Issue by Roast3dChicken** [Uuvana-Studios/longvinter-windows-client#250]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:,
1. Go to ' the snow area, place a firepit and try to pick it up. It says you can't cause it is on someone else's property, event tho it is mine and it was in a blue area'
2. Click on 'the firepit'

**Expected behavior**
Would be nice that it you place something that's yours, you are able to pick it back up.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![20220307052029_1](https://user-images.githubusercontent.com/101105928/157015290-d2401a21-e893-41d2-9f86-d087bc306dae.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Should be fixed in the last EXPERIMENTAL branch
