### ISSUE TITLE
Fast swim speed

### ISSUE THREAD

**Issue by TwinkieShip** [Uuvana-Studios/longvinter-windows-client#252]
**Describe the bug**
Drinking a speed drink increases speed but also makes u not slow when drunk while swimming.

**To Reproduce**
1. Swim into water.
2. Drink a speed increasing energy drink.
3. Now your speed hacking without the hacks.

**Expected behavior**
Slow swim speed

**Screenshots**
NaN

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.0
 - Steam Version: 1.0.0? Build ID: 8326426

**Additional context**

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
