### ISSUE TITLE
Progress Reset US 6

### ISSUE THREAD

**Issue by pizzadreams6** [Uuvana-Studios/longvinter-windows-client#257]
**Describe the bug**
When I log off, all of my stats and money are gone. My house is still there, but money and stats are all wiped.

**To Reproduce**
1. Log off of game
2. Log onto game
3. You are back on the beginning island. You have no items, no stats and 100 dollars
4. I go through all of the trouble of fishing for money. Travel all the way up north, my house is still there. I am in US uvanna6 18n/18w. 

**Expected behavior**
Log in, Im at my house. My money that I had last night is gone. The items that I had last night, gone. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
I love your game, but this really is exhausting. This happened to me yesterday as well. BETA or not, its still exhausting playing your game. Its not fun anymore.

**Comment by sikkidu** [comment]
i got same problem like u that all the quest fishing, chicken, flower is all gone and my money 30k is gone and also stuff

**Comment by vmensikova** [comment]
I have same problem. I lost money and experiences ...

**Comment by sirNugg3ts** [comment]
Gonna close this issue.

>  My money that I had last night is gone.

As Sven told on discord: 

> Please note that saving should start working AFTER PLAYING first time. There might be still missing progress when loggin in first time after update
