### ISSUE TITLE
Peacock respawning immediately when you start fishing

### ISSUE THREAD

**Issue by zutomayo1234** [Uuvana-Studios/longvinter-windows-client#26]
**Describe the bug**
If you kill the peacock and then go to fish it will immediately respawn.

**To Reproduce**
1. Kill peacock
2. Use fishing rod (I was using the telescopic one, in case that makes a difference)
3. Should happen immediately. I tested it for about 10 minutes last night and it happened every time. 

**Expected behavior**
The bird should respawn on its own timer probably

**Desktop (please complete the following information):**
OS: Windows 10
Game Version 1.0.0
Steam Version 1642451672

**Comment by sirNugg3ts** [comment]
This should be fixed by now
