### ISSUE TITLE
object and kick

### ISSUE THREAD

**Issue by Ch33s3y** [Uuvana-Studios/longvinter-windows-client#260]
**Describe the bug**

**To Reproduce**
1. load up previous game
2. place item from inventory 
3. as soon as its placed your kicked to the title screen
4. rinse and repeat, note that the item is placed but your inventory has item still

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by J2HPHIRE** [comment]
Same thing is happening to me. I can walk around but when I select anything in my inventory or try to pick something up it kicks me to main screen

**Comment by Ch33s3y** [comment]
exactly that, i can select and draw placement but as soon as i click poof back i go

**Comment by RabitzUxW** [comment]
same here put in hours on a server and cant access it cause i keep getting kicked out lost all my money too
