### ISSUE TITLE
Unable to play due to crash from inventory

### ISSUE THREAD

**Issue by Hazzarrd** [Uuvana-Studios/longvinter-windows-client#262]
**Describe the bug**
A clear and concise description of what the bug is.  I come into th3e game and pick a flower open inventory and try to drop it and game ends.  anything i do and the game crashes. even tried on updated server and its pretty much every server.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Please provide us information about what server were you on, and maybe a screen recording of this issue

**Comment by xzxProofxzx** [comment]
Official seems to work fine. Custom servers are bugging.

**Comment by sirNugg3ts** [comment]
then the custom server is not updated correctly, there have been some problems with the script that @lisbonjoker is working on, please check the gameserver channel on discord

**Comment by xzxProofxzx** [comment]
IM not sure i am on the correct discord
