### ISSUE TITLE
1 wood per tree

### ISSUE THREAD

**Issue by GreenySunny** [Uuvana-Studios/longvinter-windows-client#263]
When i cut a tree on a PVE server, it gives me only one wood even 2 when im lucky and it's so looooong to upgrade my tent.

**To Reproduce**
1. Chainsaw
2. cut a tree

**Expected behavior**
More woods

 - OS: WINDOWS 10
 - Game Version 1.0
 - Steam Version 1.0

Thks a lot !

**Comment by sirNugg3ts** [comment]
thats not a bug, its gameplay balance issues. Please only file a bug report if you find bugs
