### ISSUE TITLE
Taking Items from containers

### ISSUE THREAD

**Issue by JFSFlash** [Uuvana-Studios/longvinter-windows-client#264]
When trying to take an item from a container I have to rejoin the server on Blue Storm 3 - PVE

**To Reproduce**
1. Go to a container
2. Open the continer
3. Taker an item

**Expected behavior**
When the error occurs i get the main screen again where i need to rejoin the server

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Beta 1.0.0
 - Steam Version: 1646446125

**Comment by sirNugg3ts** [comment]
Server is not updated

**Comment by JFSFlash** [comment]
Ahhhh. I thought that may be the case but they have no site to contact them.

Thank you!!!
