### ISSUE TITLE
Get kicked when opening inventory

### ISSUE THREAD

**Issue by mikeyBev** [Uuvana-Studios/longvinter-windows-client#266]
**Describe the bug**
Get kicked when opening inventory

**To Reproduce**
1. log on to any server
2. open inventory
3. get kicked from server

**Expected behavior**
Be able to open inventory and grab stuff from containers 

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Comment by sirNugg3ts** [comment]
from discord:
I get disconnected after doing something in the server
1 - Be sure not to be on experimental
2 - If the server is not official, 99% of the times the server is not updated
3 - If the server is official, post a bug report on github
