### ISSUE TITLE
gets kicked from server when I press on my items in inventory 

### ISSUE THREAD

**Issue by CharmaineSantos** [Uuvana-Studios/longvinter-windows-client#269]
i get kicked from the server when i press and try to equip items from inventory 

**To Reproduce**
1. go into inventory 
2. Click on any item in inventory .e.g fishing pole, food 
3. gets kicked out from server

**Expected behavior**
expected to equip item but then get kicked out 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
from discord:
I get disconnected after doing something in the server
1 - Be sure not to be on experimental
2 - If the server is not official, 99% of the times the server is not updated
3 - If the server is official, post a bug report on github
