### ISSUE TITLE
cant enter server after update

### ISSUE THREAD

**Issue by jenlee13** [Uuvana-Studios/longvinter-windows-client#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Official servers are updated. If you are playing on unofficial server it may take a while before they update their server
