### ISSUE TITLE
Server (items & interactive items) Unresponsive after 5-10 minutes of joining

### ISSUE THREAD

**Issue by PandaFleet** [Uuvana-Studios/longvinter-windows-client#270]
**Describe the bug**
When I connect, I have no issues with ping, lag, disconnecting, etc. However, after approx 5-10 minutes, things such as entering houses, shooting, dropping items, etc. become unresponsive. The server does not automatically boot you but you will not be able to do anything until you disconnect and reconnect. As a result of this bug, I respawn between someone's tents and lose the items in my inventory.

**To Reproduce**
1. Go to 'US 2 Uuvanna'
2. Connect and stay connected for approximately 5-10 minutes (Maybe longer)
3. Attempt to interact with your surroundings after short period (boxes, houses, etc.)
4. See unresponsive server that will make you reconnect and lose all progress (It reset my compendium as well as my money and inventory). The one new thing is that it won't auto disconnect/boot you.

**Expected behavior**

No lag and no disconnects and no wipe of my inventory

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version Beta 1.0.0
 - Steam Version N/A
![Screenshot 2022-03-07 150517](https://user-images.githubusercontent.com/101141317/157109555-9f0137c7-963a-4f1f-a1ef-0a7b53dd06b3.png)

**Additional context**

**Comment by sirNugg3ts** [comment]
Are you sure you are not runniing the experimental branch?

**Comment by PandaFleet** [comment]
100%, I can send a screenshot if needed of that. A few others spawned with me between the houses about 15-20mins ago.

**Comment by PandaFleet** [comment]
I just relogged and it did this to me again. Thought I'd provide 1 more pic. Inv is wiped, etc. Also neither of the tents I spawned next to are mine, it's all random.

![image](https://user-images.githubusercontent.com/101141317/157307263-1329f70a-6bc2-4baf-8bfd-52c7dc8398cb.png)

**Comment by Ultimodrew** [comment]
> I just relogged and it did this to me again. Thought I'd provide 1 more pic. Inv is wiped, etc. Also neither of the tents I spawned next to are mine, it's all random.
> 
> ![image](https://user-images.githubusercontent.com/101141317/157307263-1329f70a-6bc2-4baf-8bfd-52c7dc8398cb.png)

I saw this issue a few hours ago when I tried logging into one of their servers. All my progress did not save on one of the servers I played on a day or so ago.

**Comment by sirNugg3ts** [comment]
EXPERIMENTAL has a fix for this, hopefully. If saturday this bug still happens on official servers please report
