### ISSUE TITLE
Planter boxes

### ISSUE THREAD

**Issue by noahfrusha** [Uuvana-Studios/longvinter-windows-client#271]
**Describe the bug**
when i plant cloudberry seeds in planters the planters themselves turn into their bag form

i believe the way to reproduce this is just to have many planters stacked next to each other
and fit all 9 seeds within it

the berries should still grow in the air but the planter box with drop itself

 - windows 10 version 2004 (os build 19041.1415)
 - build id: 8326426
 - steam package version 1642451672

the planting is working as normal but i just have to replace the planter box to plant more seeds

**Comment by noahfrusha** [comment]
side comment this is my first time ever doing something like this, please inform me if i made any mistakes on the info required

**Comment by noahfrusha** [comment]
issue found, you can actually just pick up the planter from under the plants when trying to harvest

**Comment by sirNugg3ts** [comment]
> issue found, you can actually just pick up the planter from under the plants when trying to harvest

this is a duplicate of #67 

The other one seems new

**Comment by faketucker** [comment]
I've faced this problem many times before. But now I'm able to plant everything and it's not turned into a bag (except in the snow area where you have to plant things in a planter box). So I believe this has already been fixed.
