### ISSUE TITLE
Clicking items in inventory disconnects me from game 

### ISSUE THREAD

**Issue by OleBrick** [Uuvana-Studios/longvinter-windows-client#273]
Spawn in 
Open inventory
Clicks on any items more than once 
Disconnects from game back to title menu 
Stupid me (repeat 7+ times)
Report bug 

*windows 10
*Steam

**Comment by ItsXavien** [comment]
i get the same problem, just made a support ticket too so that it gets rectified sooner hopefully

**Comment by sirNugg3ts** [comment]
From FAQ:

> I get disconnected after doing something in the server
>1 - Be sure not to be on experimental
>2 - If the server is not official, 99% of the times the server is not updated
>3 - If the server is official, post a bug report on github

Please open a bug report following the template and specify in which server this is
