### ISSUE TITLE
Disconnected from server without error message

### ISSUE THREAD

**Issue by liltaraud** [Uuvana-Studios/longvinter-windows-client#274]
Was disconnected from the server after playing for ~5 min without warning or error message. I don't remember doing anything particular other than walking around. Server was Uuvana EU 1 and I had ~34ms of ping

**Comment by DarthVaughn** [comment]
same issue. on US uuvana 4.

**Comment by Ketsy13** [comment]
Same issue on all servers

**Comment by longshot326** [comment]
Same issue on US Uuvana 6. unable to reconnect also

**Comment by faketucker** [comment]
This might be a problem with the servers and should be better by now
