### ISSUE TITLE
SAVES? 

### ISSUE THREAD

**Issue by Balthaxair** [Uuvana-Studios/longvinter-windows-client#275]
I seem to have to restart every time I log off still. I had decent amount of stuff and was just starting to really get into the game almost had enough pieces to craft a gun. I would rather lose my stuff to a player or other in game event but to log out and be reset... let me know when that is fixed and ill start playing again because I already put 9 hours in so being able to keep my stuff when I go to bed would be a step up. and since I started playing today I get kicked from servers (even yours) with the same restart play time between kicks varies. never longer then 30 mins.

**Comment by Krowins** [comment]
Same problem here, a friends get kicked from server and has seen all its progress rebooted !

**Comment by sirNugg3ts** [comment]
Thats not an enhancement, that would be a bug report
