### ISSUE TITLE
Cant play the game! Keep getting kicked when I use inventories

### ISSUE THREAD

**Issue by ItsXavien** [Uuvana-Studios/longvinter-windows-client#276]
**Describe the bug**
Game is not playable! Whenever I loot anything from a container, or try to use anything from my inventory, the game kicks me to main menu.

**To Reproduce**
1. Load into server (any and all servers have same issue)
1. Go to 'inventory or a container)'
2. Click on 'any item'
3. Game kicks me to menu
4. NO ERROR comes up

**Expected behavior**
I expect the game to not kick me from the servers. I can't play

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version e.g. 1.0.0
 

**Additional context**

**Comment by PLAGUE-29** [comment]
SAME HERE! tried using fishing pole, crash. tried picking up berries, crash. very frustrating

**Comment by Dylanlimes** [comment]
SAME AND ITS GETING ME MAD IT NEEDS TO BE FIXED

**Comment by LadyGiggles** [comment]
This is also happening to me. 

Purchased fishing rod. Went to pull it from inventory to fish, booted to main menu. Tried 3 times on 3 different servers, same outcome each time.

**Comment by sirNugg3ts** [comment]
From FAQ

> I get disconnected after doing something in the server
>1 - Be sure not to be on experimental
>2 - If the server is not official, 99% of the times the server is not updated
>3 - If the server is official, post a bug report on github with full details

The way you described it doesnt seem to be all in official servers
