### ISSUE TITLE
Not letting me remove items from property

### ISSUE THREAD

**Issue by derekwebb73** [Uuvana-Studios/longvinter-windows-client#278]
**Describe the bug**
When I am placing items around my tent my items will not turn green, they will stay blue and I can't pick up items like my planter box because it says it is on someone else's property but I can go into my tent.

**To Reproduce**
I have no idea how to reproduce, I put my tent away from other people.

**Expected behavior**
I should be able to place items down and not have anyone able to pick it up and it should allow me to pick up items I put down

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
this bug should be fixed in the last EXPERIMENTAL branch. If after the next main update this bug still happens, please reopen the issue
