### ISSUE TITLE
Hat bug

### ISSUE THREAD

**Issue by Waliwz** [Uuvana-Studios/longvinter-windows-client#28]
After I unlock the vendor 

**To Reproduce**
1. Buy Hat 600
2. Wear Hat
3. Disconnect the server 
4. When I try to join server in 1 Minute , I've kick out from server

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Game Version 1.0.0

**Comment by Waliwz** [comment]
So this happen after update

**Comment by sirNugg3ts** [comment]
please record a video of this happening if possible, we are going to look into the problem
