### ISSUE TITLE
(US) Uuvana 1 Server

### ISSUE THREAD

**Issue by EmmaaSpencer** [Uuvana-Studios/longvinter-windows-client#280]
The past 6 hours of playing its been really rocky. I understand its still in beta, but i keep getting kicked out of (us) Uuvana 1 server and i keep losing my progress. NOW i cant even find the server anymore on the server list and no one in discord chat will help me! i just want to know if its down and yall are working on it to make it better or if there is something wrong with my game and it  wont show up!

**Comment by sirNugg3ts** [comment]
The fixes on EXPERIMENTAL should patch this issue. If after the next wipe coming friday this still repeats. please open a new issue
