### ISSUE TITLE
Game progress keeps on resetting

### ISSUE THREAD

**Issue by TriskelionJones** [Uuvana-Studios/longvinter-windows-client#281]
when i downloaded the game it works fine , there is some minor glitches such as missing items in inventory or items getting replaced by a blank icon, but so far the worst one is resseting the game progression. us players put in several hours to play the game even to the point of featuring the game in our contents and gameplay videos.

i've played it the whole day yesterday, and to my surprised when i tried to login this morning i started all the way back to the beginning.
I am very dissapointed since i spent money to buy the game. i understand that it is in early stage but bare in mind this is a paid game .
this issue would be understandable if it is a free game.  It's like buying a half-cooked food.

if this keeps on going people will lose interest to the game specially grinding for how many hours and be sent back to replay the game again without safety of customer support.

My question is how are you guys gonna compensate the people who lost there game progression/time playing this half-baked game
this is another case of CYBERPUNK 2077

**Comment by JuaanP** [comment]
"this is another case of CYBERPUNK 2077" ... this isn't a multi millionaire company that officially releases a game after nine years of development. You bought the game on pre-release state, these things happen, that's why they need player feedback.

**Comment by sirNugg3ts** [comment]
> "this is another case of CYBERPUNK 2077" ... this isn't a multi millionaire company that officially releases a game after nine years of development. You bought the game on pre-release state, these things happen, that's why they need player feedback.

Exactly, this a 2 people dev team, and it definitly didn't took 9 years to release. And that's why we have github, so we can see what is happening. There only so much we can test out with like 70 playtesters.

In another note, please read the FAQ and Announcements on discord since the game was updated and we gave a few warnings


> I get disconnected after doing something in the server
>1 - Be sure not to be on experimental
>2 - If the server is not official, 99% of the times the server is not updated
>3 - If the server is official, post a bug report on github with full details 

> Finally, the new player save system has been on experimental and seems to work perfectly. Please note that saving should start working AFTER PLAYING first time. There might be still missing progress when loggin in first time after update
