### ISSUE TITLE
Storage Bins are Missing

### ISSUE THREAD

**Issue by TheJudeAbides** [Uuvana-Studios/longvinter-windows-client#283]
**Describe the bug**
A few of my storage boxes are just gone. Some that are missing were on the bottom, leaving one just sort of floating. 

**To Reproduce**
Cannot reproduce, they are just gone?

**Expected behavior**
I expected my containers to not vaporize into thin air.
![20220307203318_1](https://user-images.githubusercontent.com/101113668/157148201-1877c477-82a0-4853-a3ba-ab11b5d2c199.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0
 - Steam Version  unk

**Additional context**

**Comment by RedMoyo** [comment]
https://www.youtube.com/watch?v=imyDqhPYEuw

**Comment by TheJudeAbides** [comment]
Can someone translate that? I have no idea what hes saying. i saw spacebar. it just happened again, and I am losing tons of loot because of it

**Comment by sirNugg3ts** [comment]
Please update your game as the update should have fixed this issue
