### ISSUE TITLE
world crash from grabbing objects in boxes

### ISSUE THREAD

**Issue by EpicAirless22** [Uuvana-Studios/longvinter-windows-client#284]
**Describe the bug**
I went into a hanger like building to check for loot and when I go to get something I get put back to the main menu 
**To Reproduce**
1. Go to '...' go to buildings towards middle of spawn area
2. Click on '....' click on boxes  and click an item 
4. See error. no error pops up

**Expected behavior**
item goes to inventory
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10 pro
 - Game Version [e.g. 1.0] 1.0.0
 - Steam Version [e.g. 1.0]

**Additional context**
I also got an alert of someone is using boxes I don't know if that's important or not but they are world spawn boxes

**Comment by KoalaBoy** [comment]
I get disconnected after doing something in the server
1 - Be sure not to be on experimental
2 - If the server is not official, 99% of the times the server is not updated
3 - If the server is official, post a bug report on github with full details

**Comment by sirNugg3ts** [comment]
as @KoalaBoy said, follow those steps. If you still have a bug open a new bug report with Server information and evidence
