### ISSUE TITLE
Not being able to pick items up due to perspective

### ISSUE THREAD

**Issue by TheJudeAbides** [Uuvana-Studios/longvinter-windows-client#285]
I collapsed a gun turret with the intention of moving it, and due to where it ended up behind my house, I am unable to pick it up, effectively losing it permanently. 

this, to me, is game breaking =/

**Comment by hoak** [comment]
This also happened to me. I could not pick up a garden plot that I destroyed in front of my house but that was slightly behind a hill. The top of the item bag was just visible over the hill. I also could not reach//click/destroy a fence that was behind my house that I placed and had to have a friend come shoot it down. I think it would be helpful to have a modifier key when destroying items to let you go into overhead mode, or have a key you press to have those hidden items that you won appear through the object in front of them and let you interact with them.

**Comment by sirNugg3ts** [comment]
you can just use space if you dont see them
