### ISSUE TITLE
Loading into the middle of nowhere

### ISSUE THREAD

**Issue by Jellybubble18** [Uuvana-Studios/longvinter-windows-client#288]
**Describe the bug**
When I loaded into the Australian server for the first time today, it has loaded me into a random place on the map. Initially I was loaded into a black area. With a little movement, I was then moved into someone's tent with access to their crate. 

**To Reproduce**
Unsure if able to reproduce as this happened on loading into server for the first time today. Has not been this way on other days. 

**Expected behavior**
Should be loaded into my last position, boat ramp or my house/tent

**Screenshots**
![image](https://user-images.githubusercontent.com/101162674/157165254-daf3b321-a3bc-4f23-a147-19bb7a897152.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g. 1.0]: Beta 1.0.0
 - Steam Version [e.g. 1.0] App ID 1635450 Build ID 8326426

**Additional context**

**Comment by sirNugg3ts** [comment]
Due to the update, some stuff just dissapeared, after this login it should be fixed. Alt+k to suicide and respawn

**Comment by Jellybubble18** [comment]
> Due to the update, some stuff just dissapeared, after this login it should be fixed. Alt+k to suicide and respawn

This is continuing to happen even after the update./
