### ISSUE TITLE
AU Uuvana Server 1 

### ISSUE THREAD

**Issue by Jellybubble18** [Uuvana-Studios/longvinter-windows-client#289]
**Describe the bug**
Each time the server kicks me or crashes, I load back into the server with none of my inventory and all of my money has reset to 100. Last time this happened, I had 3500+ 

**To Reproduce**
1. Server kicks or crashes
2. Loads back into same server
3. Empty inventory and no money

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Game Version [e.g. 1.0] Beta 1.0.0
 - Steam Version [e.g. 1.0] App ID 1635450 Build ID 8326426

**Additional context**
This happens every single time the server crashes - usually 3-5 times in a few hours

**Comment by Jellybubble18** [comment]
This also completely wipes any progress I have made in the compedium

**Comment by sirNugg3ts** [comment]
The fixes on EXPERIMENTAL should patch this issue. If after the next wipe coming friday this still repeats. please open a new issue
