### ISSUE TITLE
Don't get a feather after kill birds

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#292]
**Describe the bug**
When you kill a bird and spam a spacebar it will only give you a bird meat

**To Reproduce**
1. Find a bird
2. Kill it
3. Spam a spacebar to pick up the items it will pick up two times but you'll only get a bird meat

**Expected behavior**
Spam a spacebar and still can get feathers

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by Jalsson** [comment]
Item picking acts a bit weird if there is 2 items exactly at the same location. Added a bit of offset to bird meat so there is a bit of space between them
