### ISSUE TITLE
Fishing Road bug

### ISSUE THREAD

**Issue by sudokunym** [Uuvana-Studios/longvinter-windows-client#295]
**Describe the bug**
Game disconnects from server after selecting the the fishing road tool.

**To Reproduce**
1. Go to your server choice
2. Click on the 'fishing road' icon to use the tool.
3. See error

**Expected behavior**
It was expected to collect fishes with the tool.

**Screenshots**
No screenshot applicable.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0
 - Steam Version Latest as of 03/08/2022

**Comment by sirNugg3ts** [comment]
From FAQ on discord 

I get disconnected after doing something in the server
1 - Be sure not to be on experimental
2 - If the server is not official, 99% of the times the server is not updated
3 - If the server is official, post a bug report on github with full details
