### ISSUE TITLE
Uuana 2 - any free place to place a tent

### ISSUE THREAD

**Issue by JJAUT** [Uuvana-Studios/longvinter-windows-client#296]
**Describe the bug**
Spent hours to find a free place to place a tent - either it's overlapping with a POI or too close to a player model.

**To Reproduce**
1. Go to any place on the map...

**Expected behavior**
Ability to place a tent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 1.0.0

**Comment by ElectricGhosty** [comment]
Same issue here. Just bought the game and was fun until now.

**Comment by sirNugg3ts** [comment]
this is not a bug and yes a problem with spacing, please play on a different server for now while we don't wipe the servers or wait for a new Map / new Servers
