### ISSUE TITLE
ideas that in my opinion could improve the game

### ISSUE THREAD

**Issue by Hanz001** [Uuvana-Studios/longvinter-windows-client#297]
the ability to customize your avatar and its gender.
the ability to directly create a server in the game.
then it would be cool to have your own farm like Stardew Valley.
and as in animal crossing the possibility of having specialized shops.
it would be nice to change the outfit of your character too

**Comment by Bunnbunnnn** [comment]
Documented already on forum as 
-Player customization, clothing, faction swag, in-game cosmetics
-Easier way to host a server / single player mode
-more veggies to farm with
-player created vendor / trade post to sell/buy things
