### ISSUE TITLE
House Problem

### ISSUE THREAD

**Issue by Nilles24** [Uuvana-Studios/longvinter-windows-client#298]
**Describe the bug**

On [us] Uvvana 1 I had a house made with tons of crates a furnace and other stuff inside, it disapeared so I assumed all my loot was gone so I bought a tent and placed it in almost the same spot. When I went into my tent I could see the inside of half my house and interact with the furnace and workbench from my old house however my crates were blocked from view so I could not acsess those. Is there a way to delete my tent and get my old house to reapear?

**To Reproduce**
1. Go to '...' Uvvana 1 on US servers, go to Mt. snow and head to the island off the the left of the dock my tent is on the shore right by the start of the island.
2. Click on '....' the tent, shows my old house but cant see it when not in tent

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
EXPERIMENTAL has a fix for this, hopefully. If saturday this bug still happens on official servers please report
