### ISSUE TITLE
Tent Placement

### ISSUE THREAD

**Issue by P0P1NTAGS** [Uuvana-Studios/longvinter-windows-client#299]
I have been playing for about 2 days now and I cannot find any place to place down my tent. It says every spot on the map is taken by someone else. Is any else having this problem? I can have no tents on my screen, and it still says that it is claimed by someone else. Am I missing something?

**Comment by Jalsson** [comment]
We will be limiting tents players can have setupped to 2 active tents. We hope this will reduce amount of tent spam. Also, we will be adding another island so there will be more play area.
