### ISSUE TITLE
Flushing Meadows PVP server

### ISSUE THREAD

**Issue by Adantzer-2158** [Uuvana-Studios/longvinter-windows-client#301]
Played on the Flushing Meadows server last night and everything was fine. Logged on today and one of my containers inside my house has disappeared along with all of its contents. The container was placed stacked in between two containers.

**Comment by tzd13** [comment]
I just logged into the same server... I am missing 5 containers that were full. Everything is gone. Hours of work just gone.

**Comment by sirNugg3ts** [comment]
Bugs on non-official servers are not taken into account since those servers might be out of date, please try to replicate this in official servers
