### ISSUE TITLE
Container Disappearing in the Arena

### ISSUE THREAD

**Issue by MrVilo** [Uuvana-Studios/longvinter-windows-client#302]
**Describe the bug**
Some or All of the Containers (The Yellow Container mainly) in the arena disappear when you jump off the ledge to loot it.

**To Reproduce**
Enter the arena in game if the Containers have spawned by jumping off the ledge towards it

**Expected behavior**
Some or all of the Containers will disappear, especially if a Yellow Container spawn in, that will disappear as soon as you enter the arena by jumping off the ledge towards it

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: 19043.1566
 - Game Version 1.0.0
 - Steam Version v020

**Additional context**
n/a

**Comment by freshtaken** [comment]
this was happening to me aswell

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
