### ISSUE TITLE
Turret abusing and how to fix it

### ISSUE THREAD

**Issue by Golatas1** [Uuvana-Studios/longvinter-windows-client#303]
The Feature is considered with a huge Problem we have. i tried to do the endgame stuff, like getting all Fishes etc. The Problem i had is that a guy placed one Fish spot ful with Turrets, so u couldnt catch all and dont get the Vendor available. We had this problem also with some Farming spots, People placed their Home into an Area with loot or connect it with that Area so turrets make it impossible to loot there. 

In my opinion its the best idea to make every Turret wound when they get hit. This would solve the problem very easy, so u need like 150 too 200 Bullets to get them down.

U could also implement that Turrets cant be placed in special spots, in the near from those fishing spots or from areas with lootsbags.

I hope u understand my issue, im playing on Uevana 3 EU, if u want to have a look at the Problem, the fishing spot is in Northeast where u can get the Archtic Char and the cod. I know my English is not the best so i apologize if its not that easy to read or understand

**Comment by sirNugg3ts** [comment]
Turrets have been balanced
