### ISSUE TITLE
I lost all my inventory and mk(money) on US uuvana 2

### ISSUE THREAD

**Issue by SilverYTC** [Uuvana-Studios/longvinter-windows-client#304]
**Describe the bug**
I logged into the US uuvana 2 server where I have played for multiple hours before, and when I logged in I was in someone else's house and my inventory and mk were completely earsed. I had 1700mk, a tent, and a lot of food.
**To Reproduce**
1. Logged in 
2. Lost stuff
3. That's it.

**Expected behavior**
I did not expect to lose all inventory and mk.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0
 - Steam Version API v020

**Additional context**
As you can see from the screenshots, I have a house with a workbench and a furnace. I also have the pristine peacock feather in my chest, but not in the photo that shows my progress of the compendium. How could I have the feather in my chest, but have 0/29 progress? I want my money and tent back.
![inside_house](https://user-images.githubusercontent.com/101232111/157360152-f1de156d-b0bb-4624-8ef8-59b51c1183fb.png)

![chest_with_feather](https://user-images.githubusercontent.com/101232111/157360160-9436e953-0c6d-4bdb-819a-70309e1782b0.png)
![blank_progress](https://user-images.githubusercontent.com/101232111/157360164-8092c8ff-0c4f-470f-b37f-047ba7cbc5ff.png)

**Comment by sirNugg3ts** [comment]
The fixes on EXPERIMENTAL should patch this issue. If after the next wipe coming friday this still repeats. please open a new issue
