### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by ILoveAdderall** [Uuvana-Studios/longvinter-windows-client#305]
**Duplication*

**To Reproduce**
1. find a friend 
2. drop something
3. both pick up items at the same time
4. now both of you have the item 
**Expected behavior**
duplicates an item
**Screenshots**
![dup](https://user-images.githubusercontent.com/101235384/157368518-ef7184e0-a800-4fab-9099-30a005d55b72.png)

**Desktop (please complete the following information):**
 - OS: Version	10.0.19044 Build 19044
 - Game Version [e.g. 1.0.0]
 - Steam Version 2.10.91.91

**Additional context**

**Comment by cmod31** [comment]
Oh man please leave this in its the only thing i can do after i made everything else in the game xD

**Comment by sirNugg3ts** [comment]
New update on experimental branch fixed this
> - Fixed duplication glitch where people could pick up the same item twice
If after the update that is coming this still happens please open a new bug report
