### ISSUE TITLE
Death on fence placement leaves a frozen placement image

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#306]
**Describe the bug**
When you die from cold while placing a wooden fence, on respawn the placement animation is frozen (in red or green).  You are then unable to place it. Relogging fixes the issue and you do not lose anything.

**To Reproduce**
1. Craft a fence from two logs.
2. Find a place to place it on your property.
3. Get to very low health and have it tick down from cold so eventually you will die in ten seconds or so.
4. Start to position the fence but do not actually place it, just rotate or start to position it. 
5. Let yourself die from cold while still orienting the fence.
6. Respawn.
7. When you respawn you can loot your bag, but cannot place the fence and the placement image is still on screen,
8. Disconnect from the game, quite the game entirely, start it again, and you can now log in and place the fence to correct the issue.

**Expected behavior**
After I die from cold and respawn I expected to be able to place the fence but cannot.

**Screenshots**
![bug1_LVfence](https://user-images.githubusercontent.com/14806514/157376973-9bf3b620-6e08-4dce-b90d-683af4ceb3e2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0 as fully updated at 7 pm EST on 3/8
 - Steam Version 1.0.0

**Additional context**
This happened twice and both times I was placing a fence panel. It happened also on 3/6 I believe. The screenshot shows me after I respawned, looted my bag, and walked over to the fire to warm up. I am not trying to place anything at this time and it still shows the placement image.

**Comment by faketucker** [comment]
Fixed
