### ISSUE TITLE
Issue #288 closed but not resolved

### ISSUE THREAD

**Issue by Jellybubble18** [Uuvana-Studios/longvinter-windows-client#307]
Please refer to Issue #288 - SirNuggets has closed this issue however it is still occuring frequently even after the update and I have again lost all items and 15000 in money. This is game breaking and starting to get very frustrating

**Comment by sirNugg3ts** [comment]
This issue has been patched on Experimental branch, the update should fix this issue. If after the next update this still happens please re-open the bug report <3
