### ISSUE TITLE
Multiple server feature requests

### ISSUE THREAD

**Issue by cmod31** [Uuvana-Studios/longvinter-windows-client#308]
💻 **Server suggestions** 💻

> 📣 1. Public live anouncements (i want to warn people that i restart the server so they'll come back later)

> 💬 2. Global chat (you could put the 1. anouncements there)

> 📰 3. Gui news on login (with text formatting support and links)

> 🔧 4. Better server modding support that could send custom content to players

> 💾 5. Saves everything when server shuts down

> 👤 6. Get the player count with a server console command(so i can embed it somehow on a website and discord bots)

> 🔨 7. Bans shouldn't require a server restart

> 📎 8. Make the website link more present (i want everyone to join my Discord for the server) and the motd visible in the loading screen

> ⚒️ 9. More admin tools like inventorysee, kick players, item /give command, remove/open/enter stuff as a admin thats not their property etc.

**Comment by TyeJM** [comment]
Banning isn't even working even when i restart server so it definitely needs looked at again

**Comment by cmod31** [comment]
News gui could also be made through mails that admins can make for all players for free in a separate menu. but then you would need a mailbox first so maybe a extra button in inventory https://github.com/Uuvana-Studios/longvinter-windows-client/issues/310

**Comment by cmod31** [comment]
i added point 8 lol

**Comment by cmod31** [comment]
Now i added point 9

**Comment by Bunnbunnnn** [comment]
> 📣 1. Public live anouncements (i want to warn people that i restart the server so they'll come back later)

Already implemented via admin panel 

Ticket linked to forum for details / reference
