### ISSUE TITLE
Mailboxes

### ISSUE THREAD

**Issue by catnapstv** [Uuvana-Studios/longvinter-windows-client#310]
How cool would it be if you guys made a mailbox that functioned like a crate, it can be placed by the home and opened like a inventory that others can put things in or even yourself! you could make it where you could have a flag up as a joke or whatnot for a mailman and you can also make it where theres a passcode on it so if you make a little neighborhood with your friends they can drop things off in your mailbox.

**Comment by Hanz001** [comment]
it wouldn't be a bad idea, in fact I'd love to and hope they implement it

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
- ingame mail w/ notification system for it or crate/placable item ingame
