### ISSUE TITLE
Can't click anything after do /spectate1108

### ISSUE THREAD

**Issue by faketucker** [Uuvana-Studios/longvinter-windows-client#313]
**Describe the bug**
Can't click anything after do /spectate1108 even the disconnect button or exit

**To Reproduce**
1. Join any server
2. Do /spectate1108
3. Do /spectate1108 again
4. Can't click anything

**Expected behavior**
Able to click again

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by sirNugg3ts** [comment]
I just tested this out with the steps given and was not able to replicate, everything worked fine. Be sure to be on the main branch and not on experimental

**Comment by sirNugg3ts** [comment]
I tried again and was able to do this

**Comment by Mikooboy** [comment]
Should be fixed in the next update
