### ISSUE TITLE
Chosen language doesn't save

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#314]
**Describe the bug**
Chosen language doesn't save after you re-open the game

**To Reproduce**
1. Open the game
2. Choose any language
3. Close the game and re-open it
4. Your chosen language doesn't save

**Expected behavior**
The game saves the language you chose

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by Jalsson** [comment]
I like fixing all the low priority stuff first :D Will be included in next experimental update
