### ISSUE TITLE
Progress Permanently Wiped During Server Malfunction 

### ISSUE THREAD

**Issue by M1pp** [Uuvana-Studios/longvinter-windows-client#315]
**Describe the bug**
When the servers were malfunctioning last night I was stuck in a black void. I knew others were experiencing this as well so I just closed the game to come back later. When I opened the game around 30 minutes after this, I found that the void was still there but my entire inventory, money, and compendium were completely reset. It's been about 12 hours since and I still don't have anything back. I think this problem might have happened because I picked up items moments after the wipe. I ended up somehow teleporting outside of someone's house and ever since my progress hasn't gone back.

**To Reproduce**
Just an issue with the server. I haven't figured out a way to trigger this on my own.

**Expected behavior**
My progress has been temporarily wiped before but I got it back after around 30 seconds. I'm pretty sure I've never picked up other items during these temporary wipes which might be why this time it worked differently.

**Screenshots**
I don't have any screenshots

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
My progress has been temporarily wiped before and I'm pretty sure it's just an issue with the server lag. Good luck with all the bug fixes and updates to come. I really enjoy longvinter and I think you have dont a great job on it.

**Comment by sirNugg3ts** [comment]
The spawn in the void bug is being fixed, a patch has been issued in experimental branch, so it should take too long to get on main branch. If after the new update this issue is still up, please open a new bug report <3
