### ISSUE TITLE
how can you improve the economy ?

### ISSUE THREAD

**Issue by Kacper1244** [Uuvana-Studios/longvinter-windows-client#316]
I find that in this game there is no real economy. Each player can farm huge amounts of money, in particular thanks to specific techniques. This is why players do not use mk but exchange their objects. I suggest that when many people sell the same object and its price goes down. for example all the players fish for white fish because they give a lot of money so their prices will drop and they will fish less. Thus the player farms all the resources.

**Comment by Bunnbunnnn** [comment]
This was implemented in the game now
