### ISSUE TITLE
Unable to Join any server

### ISSUE THREAD

**Issue by cmegan91** [Uuvana-Studios/longvinter-windows-client#317]
Hello,

I have been unable to join any servers all day. I have tried many public servers and after loading for about 20 seconds it brings me back to the home screen.

Are there any fixes for this

**Comment by sirNugg3ts** [comment]
Is this happening on official servers?

**Comment by Ketsy13** [comment]
Same thing happens to me, officials included. I have tried for 2 days now and I normally get kicked off 2 steps off the spawn dock.

**Comment by sirNugg3ts** [comment]
are you sure you are not in experimental beta?

**Comment by Cdrix** [comment]
same problem and I'm in experimental beta with latest update !

**Comment by sirNugg3ts** [comment]
> same problem and I'm in experimental beta with latest update !

In that case the only server you could get in is the experimental

**Comment by sirNugg3ts** [comment]
Please update game in stable and try again. OP never gave any info back so im closing the issue
