### ISSUE TITLE
My placed items disappear 

### ISSUE THREAD

**Issue by lisabei** [Uuvana-Studios/longvinter-windows-client#318]
A lot of items just disappear the next time i logon. 

for example 2 full chests with expensive loot were gone yesterday. 

Today I logged in for the 2nd time an ALL my placements around my house disappeared. 
4 planters, fireplaces, benches, fences... all things i bought and looted in hours and hours of playtime... pretty dissapointing tbh...

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
