### ISSUE TITLE
Glitched 25th Item in Chest

### ISSUE THREAD

**Issue by asianmess** [Uuvana-Studios/longvinter-windows-client#319]
**Describe the bug**
When putting items in or opening a chest, sometimes there will be a 25th item in the chest, but there are only 24 available slots in a chest.

**To Reproduce**
I'm not entirely sure, however when I checked the chest I saw it.

**Expected behavior**
All the 24 slots of chest space will be taken up however there will be a glitched 25th slot with an item in it.

**Screenshots**
![image](https://user-images.githubusercontent.com/81714869/157528702-286b1e77-b5a9-4d7a-84ea-35a2a138718b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0

**Additional context**
You're able to put that 25th item in your inventory

**Comment by TwinkieShip** [comment]
it seems to happen when u spam click items from your inventory into the storage

**Comment by TophC7** [comment]
> it seems to happen when u spam click items from your inventory into the storage

can second this if you move your items from inventory to chest really quick sometimes a 25th will appear this might have to do with dupes(?)

**Comment by faketucker** [comment]
Tested. This happens both ways, either putting in or taking out, but you have to be on high ping.

**Comment by faketucker** [comment]
Should be more reliable with stable ping
