### ISSUE TITLE
CHARACTER WIPED AFTER EVERY UPDATE

### ISSUE THREAD

**Issue by ItsKiwi88** [Uuvana-Studios/longvinter-windows-client#32]
**Describe the bug**
Me and some players ive met (some not all) experience COMPLETE player/item loss after every update, this ALSO includes the compendium 

**To Reproduce**
Update happens
Log In
Character, inventory and compendium Gone/reset

**Expected behavior**
We should be keeping our characters after every update, re filling the compendium is a bi***

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1.0

**Comment by Jalsson** [comment]
This was due the server not saving player progression when exiting. I added player savings every 2 minutes so now player progression should no longer be wiped when update is rolled out
