### ISSUE TITLE
DC when take/equip Item

### ISSUE THREAD

**Issue by Sunakoh** [Uuvana-Studios/longvinter-windows-client#320]
**DC upon taking an item out of a chest or equipping one**
While trying to fish, I go to equip my fishing rod and am kicked upon it's animation coming starting. 
I also continuously get kicked when trying to remove items from chest. 

**To Reproduce**
1. Go to Inventory
2. Click on the Fishing Rod
3. Kicked // See error

**Expected behavior**
Idk, to have my rod in hand.. and be able to fish.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0
 - Steam Version 1.0
 
 I just wanna fish and be able to play :) thnx

**Comment by sirNugg3ts** [comment]
From FAQ

I get disconnected after doing something in the server
1 - Be sure not to be on experimental
2 - If the server is not official, 99% of the times the server is not updated
3 - If the server is official, post a bug report on github with full details
