### ISSUE TITLE
Trapped in the Void

### ISSUE THREAD

**Issue by CharlesLiRay** [Uuvana-Studios/longvinter-windows-client#321]
**Describe the bug**
When I log into the server; with an established character, the Character's acheivments and inventory were "like new". I played this reset character for several hours; with previously acquired house and assets. After loggin off and returning; the character became stuck in a blank environment; assuming the player house is unable to load. The issue is persistent.

**To Reproduce**
1. Log on to server with an established character.
2. Wait for game to load;  although adjacent house interiors do load.
3. Player house interior does not load.
4. Log off

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
this bug is getting fixed in the next patch, for now use alt + k to suicide
