### ISSUE TITLE
Cannot play game

### ISSUE THREAD

**Issue by Ketsy13** [Uuvana-Studios/longvinter-windows-client#323]
**Describe the bug**
I load into the main menu and click play, when I select a server (official or not) i load for approximately 5 s3econds before it brings me back to the main menu. I am able to hear game audio for a split second before I get kicked. I get no error or warnings when sent back to the main menu. There have been been 5 times where I have loaded into the game and only 2 of which I have been able to play for over 2 minutes.

**To Reproduce**
Click on play and load server then I get kicked. I have tried at least 100 times and re installed twice

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Game Version 1.0.0
 - Steam Version 

**Additional context**

**Comment by Cdrix** [comment]
same here !

**Comment by sirNugg3ts** [comment]
are you sure on are not on beta experimental?

**Comment by Ketsy13** [comment]
yes 100%

**Comment by sirNugg3ts** [comment]
Please update your game as the update should have fixed this issue
