### ISSUE TITLE
Water Don't Appear anymore after using the graphics settings

### ISSUE THREAD

**Issue by Samuel8668** [Uuvana-Studios/longvinter-windows-client#324]
**Describe the bug**
i first launched the game all working fine but later when i try to low the graphics settings i clicked desactivate and reactivate dx11 water and the water gone completly
**To Reproduce**
just click activate and desactivate and play with the graphics settings its the last thing i ever do before the water disappear.
**Expected behavior**
the water should be there!
**Screenshots**
![Water Glitch](https://user-images.githubusercontent.com/94412439/157578462-03dc66f0-5001-4289-a375-ddca45f30a15.PNG)

**Desktop (please complete the following information):**
Windows 10
Game Version 1.0.0 Beta
Steam Version

**Comment by KoalaBoy** [comment]
There's a temporary fix in #13

**Comment by Samuel8668** [comment]
thanks you very much :)
