### ISSUE TITLE
Textures not loading in after a while of exploring all black ground texture and can only see inside of other players homes/tents

### ISSUE THREAD

**Issue by akaJerms** [Uuvana-Studios/longvinter-windows-client#325]
**Describe the bug**
After exploring for a while all ground textures appear black and I can only view inside of other players tents/homes, also while this is happening my inventory has been reset.

**To Reproduce**
1.Explore
2. Try to place a tent
**Expected behavior**
Being able to see and have my stuff.

**Screenshots**

![image](https://user-images.githubusercontent.com/101309064/157588818-d023ad42-8a03-42b0-9734-0a7eca9ec16b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
EXPERIMENTAL has a fix for this, hopefully. If saturday this bug still happens on official servers please report
