### ISSUE TITLE
Small Campfire Addition

### ISSUE THREAD

**Issue by M1pp** [Uuvana-Studios/longvinter-windows-client#326]
**Is your feature request related to a problem? Please describe.**
There's no urgency to this or anything. The feature is just a fun touch that I think would be cool to see if you ever find the time for it.

**Describe the solution you'd like**
I think that campfires that are placed in the winter/snow biome should melt the snow around them. I know the biome has different qualities involving health/energy and I don't think that the melted area around the fire needs to actually change any function. Just think this would be a fun touch

Here is a very crude image I made 

![longvinter feature](https://user-images.githubusercontent.com/101278468/157603764-c26a8a3e-02e3-4c5b-9655-139f5cc4c84e.png)

**Comment by Bunnbunnnn** [comment]
Added to forum
