### ISSUE TITLE
Server issues and items gone

### ISSUE THREAD

**Issue by Gothicturtle** [Uuvana-Studios/longvinter-windows-client#327]
**Describe the bug**
Spent hours on one server as it was the only working server the rest would kick us out or not let us pick up items. After spending hours on the game we came off went on the next day and it was back to the beginning. So disheartened
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
The latest fixes on EXPERIMENTAL should patch this, if after tomorrow this issues still happen please open a new bug report
