### ISSUE TITLE
Ammo Disappears After Death

### ISSUE THREAD

**Issue by Hidden-Knight** [Uuvana-Studios/longvinter-windows-client#328]
**Describe the bug**
After unpacking ammo from a box and storing it directly in your backpack and dying, you are not able to retrieve ammo that was previously stored. If ammo is less than 25 bullets, you are unable to remove from the bag.

After death, respawn, and traveling back to said old bag drop on death location, you are able to obtain all prior items dropped. However, you do not obtain any ammo that was stored in the bag directly. 

**To Reproduce**
1. Unpack ammo from box.
2. Die
3. Return to dropped back, and pick up all equipment from old bag
4. Ammo does not return to player. 

**Expected behavior**
After picking up old bag, I would assume any ammo stored directly in the bag would carry over. This would also be a very good feature for looting when a person walks up to take items from the bag, they are able to loot ammo stored in the bag. 

**Screenshots**
Before Death
![Screenshot_10](https://user-images.githubusercontent.com/101325456/157636234-ba374a34-6d51-4c4a-999e-b565bc402858.png)

After death
![Screenshot_12](https://user-images.githubusercontent.com/101325456/157636291-3f237bc3-58a5-4b92-aae0-c545af31df02.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: Beta 1.0.0
 - Steam Version: 
![Screenshot_13](https://user-images.githubusercontent.com/101325456/157636602-dc75582f-223b-43d2-9ae4-f8e001bb3329.png)
 - Server: [US] Experimental 
 - 

**Additional context**

**Comment by RedShirtRyto** [comment]
Can confirm bug is fixed in the experimental server

**Comment by StupidSlime45** [comment]
its supposed to drop but if its disappearing that's a problem I think

**Comment by faketucker** [comment]
Tested.

**Comment by faketucker** [comment]
Fixed in [1.0.9](https://store.steampowered.com/news/app/1635450/view/6074815775727636258)
