### ISSUE TITLE
Keep "crashing"(forced to restart game) and stuck outside the map

### ISSUE THREAD

**Issue by CocoNna** [Uuvana-Studios/longvinter-windows-client#329]
![image](https://user-images.githubusercontent.com/101327958/157643494-f839484a-f172-41c2-a21d-ee783e8bfad0.png)

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
