### ISSUE TITLE
The item is missing when you spam to pick it up

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#331]
**Describe the bug**
The same two items at the same spot are missing when you spam a click or spacebar to pick them up.

**To Reproduce**
1. Drop the same two items at the same spot
2. Spam a click or spacebar
3. One of them is gone

**Expected behavior**
Can pick up items correctly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by sirNugg3ts** [comment]
this bug is fixed in the EXPERIMENTAL branch. If tomorrow after the update this still happens please open a new bug report
