### ISSUE TITLE
getting disconnected from the server when trying to equip, unequip, drop, and put/get items on containers. Uuvanna 1

### ISSUE THREAD

**Issue by SaeSHD** [Uuvana-Studios/longvinter-windows-client#332]
**Describe the bug**

**To Reproduce**
1. Go to container
2. Click on item in the container to get it
4. it kicks me out as soon as I equip, unequip, drop, and put/get items on containers

**Expected behavior**
when I equip, unequip, drop, and put/get items on containers. it should allow me to equip, unequip, drop, and put/get items on containers.

**Screenshots**
NA, cause it would kick me out after doing it.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version Longvinter beta 1.0.0
 - Steam Version: 1646806235

**Additional context**
I can still move around and sell items. it disconnects me when I do any of those actions.

**Comment by sirNugg3ts** [comment]
Please update your game as the update should have fixed this issue

**Comment by SaeSHD** [comment]
I'm unable to connect to the server after updating it.

**Comment by sirNugg3ts** [comment]
To uuvana 1? and you are sure your client is updated

**Comment by sirNugg3ts** [comment]
I just tried to connect and the server is fine

**Comment by SaeSHD** [comment]
Yes, basically all uuvana 1 servers. As soon as I select the server, it
loads then brings me back to the main screen.

**Comment by sirNugg3ts** [comment]
Please give me information about your setup and your steam ID to check if you were banned for some reason. But from what I can see it seems an issue with your network rather than the game, since the servers are working fine and people can get in the game no issue

**Comment by SaeSHD** [comment]
Hmm.. i'll try reinstalling the game since i haven't tried that yet.

**Comment by SaeSHD** [comment]
Steam ID 76561198181387490
SaeSHD

Setup

I'm using a lan cable with a 300mbps internet connection. I'm from the
philippines.

Computer specs:

i5 4th gen
Gtx 1650  oc
16 gb ram
Windows 10

**Comment by SaeSHD** [comment]
Ok just a sec
