### ISSUE TITLE
too many bugs to play 

### ISSUE THREAD

**Issue by aarlotto** [Uuvana-Studios/longvinter-windows-client#335]
I think this game is such an awesome idea, BUT the servers crashing after only 20min of playtime is really frustrating and makes me want to not start all over again. 

I've tried other servers and the same issue persists. 

The number of servers is fine, but whats the point if the game is just going to crash and force you to start all over?

**Comment by flesur** [comment]
True

**Comment by sirNugg3ts** [comment]
Hello, we understand your concerns, but this not the place to make comments. Please use discord , reddit or the steam forums
