### ISSUE TITLE
The water doesn't appear

### ISSUE THREAD

**Issue by misooow** [Uuvana-Studios/longvinter-windows-client#336]
**Describe the bug**

the water don't appear, it's all white. I can't see the places where i can get fishes, its embarssing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Check #13 for fix
