### ISSUE TITLE
Unlockable skills or features via gameplay and progression

### ISSUE THREAD

**Issue by TophC7** [Uuvana-Studios/longvinter-windows-client#338]
**Is your feature request related to a problem? Please describe.**
No its not related to a problem perse.

**Describe the solution you'd like**
A skill tree of some sorts for the game.  The game as it stands has a lot of room for new features or mechanics and I think some of those should be unlockable via gameplay. For example a feature like item stacks enabling to stack up flowers, berries, etc. in your inventory could be unlocked via an NPC with money or some sort of achievement; or via the menu with some sort of skill tree. 

**Describe alternatives you've considered**
The first idea with an NPC could work as follows:
Right now we unlock NPCs via exploring and finding different items. Each of these NPCs could have different items for each features  and the players buys them. The problem with this however is that it affects the economy of the game and it might backfire making these features or skills too easy to get.

The second idea was something akin to a skill tree:
The skill tree could be part of the menu like the compendium for example. And it could work with achievements. Lets say the player manages to farm 100 berries. then they can go to the menu and as a reward they get the ability to stack up berries. Or lets say the players finds all the different crates in the game and theyll get a mini map or smth. This would be harder to get and gives the game a lot more content to do and a satisfactory reward. 

**Additional context**
Nothing else to add but i love the game!

**Comment by Bunnbunnnn** [comment]
documented and linked for reference
