### ISSUE TITLE
Getting disconnected or server crashing then rejoining and losing all items and money

### ISSUE THREAD

**Issue by ForeverSmolBean** [Uuvana-Studios/longvinter-windows-client#339]
**Describe the bug**
I couldnt fish or interact with items then noticed the server was crashing or would get kicked from the server. Then when rejoining all my items and money would be gone. But I spawned into a house then outside a house and benches and other items would be floating. Then I looked at my inventory and it was all gone.

**To Reproduce**
I just was playing this same thing happened to my friend. I was running around and she was fishing

**Expected behavior**
For me to get kicked and have my items still be there. I have left and joined a server and had my items. Its only when it suddenly stops working and doesn't kick you out.

**Screenshots**
I do not have screenshots I'm sorry

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.0
 -  - Steam Version I couldn't find the version I have but I checked that it was up to date and it was up to date on 3/10/2022

**Additional context**

**Comment by itsclaudizzle** [comment]
Same! It's so annoying, its happened 3 times already!!!
Makes me want to stop playing the game honestly and try and get a refund

**Comment by s7010390** [comment]
Me too!! I lose every thing 2 time already and lose connecting every 20 minutes. It's so annoying.
Please fix these problems.

**Comment by Golatas1** [comment]
Ye me too its really annoying i guess they will fix that soon

**Comment by sirNugg3ts** [comment]
Please update your game as the update should have fixed this issue
