### ISSUE TITLE
Character Wiped After Recent Update

### ISSUE THREAD

**Issue by JonnyTwoTimez** [Uuvana-Studios/longvinter-windows-client#34]
My character on (US) Uuvana 1 was wiped after the update, will my character come back? its going to be hard to keep playing the game if my character can possibly get wiped at any time.

**Comment by Jalsson** [comment]
This was due the server not saving player progression when exiting. I added player savings every 2 minutes so now player progression should no longer be wiped when update is rolled out

**Comment by JonnyTwoTimez** [comment]
I had my character after the update but i kept getting disconnected after i loaded in the map, after so many attempts my character was wiped and all my money gone

**Comment by JonnyTwoTimez** [comment]
will i get my character back?
