### ISSUE TITLE
getting to see the inside of people's houses for a solid second

### ISSUE THREAD

**Issue by tgslacking** [Uuvana-Studios/longvinter-windows-client#340]
https://user-images.githubusercontent.com/46545385/157795032-ed49330c-5c97-4b6f-b8d0-bfdeeecf67f2.mp4

**Comment by Golatas1** [comment]
Ye i had that issue too, but i had that bug always when my Account got suddenly resettet idk why

**Comment by sirNugg3ts** [comment]
This bug was fixed a couple of updates ago
