### ISSUE TITLE
Entering the server Glitch

### ISSUE THREAD

**Issue by RyanEbanks** [Uuvana-Studios/longvinter-windows-client#341]
**Describe the bug**
When I enter the game sometimes it doesn't matter if I have a house, tent or nothing set-up I will spawn either inside someone's house with the freedom to move into other peoples houses, or I spawn in-between the UI of all houses in darkness and I'm not really able to move.

**To Reproduce**
Not sure, all I do is enter the game after the server freezes. Has happened in [US] uuvana1 & [US] uuvana6.

**Expected behavior**
I expected to log in and load up where I previously was.

**Screenshots**
![image](https://user-images.githubusercontent.com/43324378/157802065-fdc702e1-8fe4-4dc2-ae84-d75d790ed7f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.0 
 - Steam Package Version 1646806235

**Additional context**

https://user-images.githubusercontent.com/43324378/157802003-9ffa6003-5372-4338-9c38-87b2c982b56f.mp4

**Comment by sirNugg3ts** [comment]
Please update your game as the latest update fixed this issue
