### ISSUE TITLE
Raiding and how it would help in this game

### ISSUE THREAD

**Issue by Golatas1** [Uuvana-Studios/longvinter-windows-client#342]
We have some Major Issues in the Game that arent compared to Bugs or something like this, its more the gameplay itsself. First we dont have that much content in the Game and on different Servers isnt much place to build on,even for one Tent.In my opinion it would help if raiding like in Rust would be a thing. Because it would give more Space for players to build on, it would help against people who dont play on these Servers anymore and it would give us more content. Because we can lose our Stuff so we have to grind it back and we can Raid others so we have a new Task to do. Although we get more Space and Area for our Village. Plus it would help against the People who Siege different looting spots, like the islands where u can get Rare feathers or something like this.

A Solution could be that Players could buy something to destroy houses and make the House to their own.

Another way could be that u can destroy a House and lootbags are dropping with all the stuff in them. In both ways could be a spezial and really expensive item that does that or u can do it with normal ammo but then maybe a high amount. Although the Players that get raided should get a little bit of Money so its not that frustrating and hard to come back.

This little mechanic could turn the game and bring way more fun and at the same time more content.People who dont play anymore get kicked out so a new Area is free and different farming locations cant get claimed with a house and 10 Turrets around it.Also people like me could have more than maybe just one House because their server has no space to build on. I hope u could understand my idea and thanks for listening.

**Comment by faketucker** [comment]
> In my opinion it would help if raiding like in Rust would be a thing. Because it would give more Space for players to build on, it would help against people who dont play on these Servers anymore and it would give us more content.

There's a tent decay now for inactivated tents. The default is 2 days on an official servers.
"Break into houses / raid" is already documented on the [forum.](https://forum.uuvana.com/d/21-previously-mentioned-suggestions)
