### ISSUE TITLE
"How to Play?" always pops up when you join a server

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#343]
**Describe the bug**
"How to Play?" always pops up when you join a server

**To Reproduce**
1. Join any server
2. "How to Play?" pops up

**Expected behavior**
"How to Play?" only appears the first time you join the server.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Latest

**Comment by sirNugg3ts** [comment]
not a bug but more of a suggestion

**Comment by KoalaBoy** [comment]
> not a bug but more of a suggestion

I think they already did this som imma close this issue
