### ISSUE TITLE
chest duplication bug

### ISSUE THREAD

**Issue by goldrabbitkr** [Uuvana-Studios/longvinter-windows-client#344]
When I try to pick a empty container(chest) up, I can't take the container into my inventory. It just keeps duplicating itself again and again.

**Comment by sirNugg3ts** [comment]
Please update your game as the update should have fixed this issue

**Comment by KoalaBoy** [comment]
> Please update your game as the update should have fixed this issue

Still occurring after the update
https://discord.com/channels/846308806870695967/880859106989178880/952056596052209684
