### ISSUE TITLE
server reconnect does not work after internet crashed mid swim

### ISSUE THREAD

**Issue by sn1ps** [Uuvana-Studios/longvinter-windows-client#347]
**server reconnect does not work after internet crashed mid swim**
My internet crashed while I was swimming across a small river. When my internet reconnect and there was an update for the game. After the update, I cannot reconnect to the same server but any other random server will let me connect. Reconnecting to that specific server kick me immediately back to the server list with no explanation. My friend on that same server does not have the same issue.

**Comment by sirNugg3ts** [comment]
can you please give us your steam ID? and server

**Comment by sn1ps** [comment]
https://steamcommunity.com/profiles/76561198215867391/
server is: [US][FL] Fiber - Cloud Server - NEW GAME

**Comment by sn1ps** [comment]
i have been having some internet issues for the past few hours so im not sure if that has contributed

**Comment by sirNugg3ts** [comment]
We cannot offer support on non-official servers unfortunatly

**Comment by sn1ps** [comment]
okay. ill just keep testing later then. sorry for the issue.

**Comment by sirNugg3ts** [comment]
no problem!
