### ISSUE TITLE
latest update broke game?

### ISSUE THREAD

**Issue by Tanman69** [Uuvana-Studios/longvinter-windows-client#349]
since the latest update on march 11th i have not been able to play. I can load up the game and go to play and I try connecting to any server it brings me back to home screen anyone else having this problem?

**Comment by Jalsson** [comment]
Usually, loading problems are caused by version errors. Make sure you have the latest update and try joining the official server with blue checkmark. If you are having trouble joining unofficial servers this means that the server is not updated yet
