### ISSUE TITLE
Achievements not Triggering

### ISSUE THREAD

**Issue by Narchypoo** [Uuvana-Studios/longvinter-windows-client#35]
**Describe the bug**
Yesterday, I completed the hunter, kill capercallie and equip a hat achievements and none of them have triggered in my Steam record.

**To Reproduce**
n/a

**Expected behavior**
I expected the achievements to have been unlocked like the other ones had.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 1.0
 - Steam Version: unsure, just updated yesterday

**Additional context**
Sorry, was killed and lost my hat, but purchased from the plant/farming vendor when I unlocked that category.  Can repurchase if I need to, but it was still equipped for several hours without triggering achievement.  
![achievements](https://user-images.githubusercontent.com/100515134/155879651-48a9a33d-6136-414e-99a1-0a3f519b125e.jpg)
![ingameshot](https://user-images.githubusercontent.com/100515134/155879654-8e24bc2a-5a15-48f5-9e4f-78b4c521f093.jpg)

**Comment by Narchypoo** [comment]
Just an update, it is still occurring.  Unlocked the fishing one today - so, to date, it's the fishing, feather and kill a wild capercaillie ones that aren't triggering.  Enclosed another picture since recollecting after the server wipe.
![fishing](https://user-images.githubusercontent.com/100515134/156673381-ec2a0b94-c764-47f2-a51b-0bf7f2a79808.jpg)

**Comment by Narchypoo** [comment]
![achievements3 3](https://user-images.githubusercontent.com/100515134/156673800-73d4f9ec-b861-462d-a3da-009fe56a2eab.jpg)

**Comment by sirNugg3ts** [comment]
a fix has been issued in EXPERIMENTAL, this should work next update
