### ISSUE TITLE
Duplication on Longvinter !

### ISSUE THREAD

**Issue by Cequatra** [Uuvana-Studios/longvinter-windows-client#350]
**To Reproduce**
1. try to have green color place
2. place this item (for me box)
3. pick up your item
4. See duplication

**Screenshot**
![image](https://user-images.githubusercontent.com/101416635/157904252-c688bfae-0c6e-456f-b07b-e1c0be615cd0.png)

**Comment by KoalaBoy** [comment]
https://discord.com/channels/846308806870695967/846308807386464268/951983716383727616

Video

**Comment by faketucker** [comment]
Already fixed.
