### ISSUE TITLE
Can we get a fix for spawn camping??

### ISSUE THREAD

**Issue by CorceTV** [Uuvana-Studios/longvinter-windows-client#351]
**Is your feature request related to a problem? Please describe.**
We spawn outside our houses so people can literally stand there with a chainsaw, gun, etc and kill you before you can move.

**Describe the solution you'd like**
Was farming wood to upgrade my tent and a player is holding me in place killing me repeatedly with his chainsaw. Will be IMPOSSIBLE for new players to advance if this isn't fixed. I get it's a PvP game but this is a level of toxicity that will ruin a playerbase.

**Describe alternatives you've considered**
Spawn inside your own home rather than outside of it? Maybe add a "bed" we can spawn on so you don't have to worry about players placing objects where they would spawn and getting stuck.

**Additional context**
Link for video in the Longvinter Discord:
https://discord.com/channels/846308806870695967/880859106989178880/951876380264656896

**Comment by faketucker** [comment]
Now the player respawn point has moved to the inside of the house to prevent spawn killing.
