### ISSUE TITLE
Stuck on ledge on southern island - only way off 

### ISSUE THREAD

**Issue by galpalkal** [Uuvana-Studios/longvinter-windows-client#353]
Whenever you go from left to right on this part of the island in the south, you get stuck on the ledge and have to be killed to get off of it.

The game will continuously disconnect you, so you aren't losing energy and can't die on your own. 

![2022-03-11](https://user-images.githubusercontent.com/101424143/157928957-1cc7b8e2-ebb2-4fa7-9db3-d0f827b10dda.png)

**Comment by faketucker** [comment]
You can type "/kill" in the chat or use Alt+K
