### ISSUE TITLE
Fireplace stuck in house after move

### ISSUE THREAD

**Issue by CrayCray95** [Uuvana-Studios/longvinter-windows-client#354]
**Describe the bug**
I dismanteled my house, but didnt read the explanation as well as i should have maybe... anyway i dismanteled the house with all the furniture still in it. some stools, a rug, 4 boxes, the workbench AND a fireplace. Everything was lost, except the tent and the workbench, but when i replaced my tent; the fireplace was still there but i cant pick it up, i have upgraded to a house again and i still cant pick up the fireplace. 

**To Reproduce**
1. Go to the workbench while you still have a fireplace in your house,
2. Click on dismantle and yes
3. replace your tent a few spaces over,
4. Enter tent and fireplace is still there and unmovable / cant pick it up.

**Expected behavior**
I expected the tent to be empty or to be able to pick up the fireplace. 

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/101428035/157948786-d8cee929-caeb-4173-a3fe-f7aa1d2ed32e.png)

its the first fireplace that is stuck, not the one in the corner.

**Comment by faketucker** [comment]
Tested. When you dismantle the house while the fireplace is still in there and place a tent in the same space, you'll see the fireplace is unusable and can't pick it up.

**Comment by faketucker** [comment]
> ![Longvinter_3_27_2022_10_16_19_PM](https://user-images.githubusercontent.com/28383557/160317109-606b7dfb-5fdb-40a8-ba7b-2c0e9378e129.png)
> From: [Chasey#0942](https://discord.com/channels/846308806870695967/880859106989178880/957826399736061953)

It appears that tent decay also causes placeable items to become stuck in the void and unusable, and you are unable to pick them up.
