### ISSUE TITLE
Possible Dupe Bug - Turret Spamming

### ISSUE THREAD

**Issue by N3stgaming** [Uuvana-Studios/longvinter-windows-client#355]
**Describe the bug**
Possible duplication bug for turrets, with the amount of the turret this guy has is this even possible?
Is it possible to do a quick check on the house owner below Sgt. Lake?

Please see image below, exact location.

![image](https://user-images.githubusercontent.com/101428803/157953235-0721df4c-6dce-422e-b727-ccbf1d17b8de.png)

**Comment by Matavatar** [comment]
This is definitely doable after 3 to 4 days of playing.

**Comment by faketucker** [comment]
You can't duplicate items by spamming placing or picking placeable things up anymore.

And if you have any suspicions about some players' duplicating items or hacking, Please use the ticket system we have on our Discord server! To open one, follow the instructions:
1. Go to ☎-contact;
2. React to 👮 which is referent to Bot Reporting;
3. Inform which server you were playing on (Official only);
4. Post all images/videos and any information you have on the hacker.
https://i.imgur.com/NvIrIHX.png
