### ISSUE TITLE
Unknown item I picked up

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#356]
**Describe the bug**
I have an unknown item I got from a loot chest in the NW large snow base. 

**To Reproduce**
1. Find an unknown item
2. Try to figure out what it is
3. Submit a bug report with tips on what it is not

**Expected behavior**
I would expect too see the image of the item and the hover text.

**Screenshots**
![bugitem1](https://user-images.githubusercontent.com/14806514/157954289-c2fc79eb-91b7-4872-ba68-124b8cf98ecf.PNG)

**Desktop (please complete the following information):**
 - OS: Window s10
 - Game Version v1.0.0 after patch on 3//11
 -  v1.0.0

**Additional context**
I dont know what this item it. as there is no hover text or image for it. I can drop it on the ground pick it up, place it in chests. I cant consume it. It I try to put it in a crafting bench or furnace it turns into a bag. It I try to place it nothing happens.

**Comment by faketucker** [comment]
Fixed. You can no longer find this in the loot chests.
