### ISSUE TITLE
Cant craft AK

### ISSUE THREAD

**Issue by ThetruD** [Uuvana-Studios/longvinter-windows-client#357]
The bug is fairly simple. A majority of the time I am unable to craft AKs in my workbench. When I started the game it wasnt an issue but sometime this week the ak will not show up in my workbench when i put the martials in it.

**Comment by JiHounHuh** [comment]
Just to confirm, are you using the short barrel or long barrel? I believe the icons are the same but only the long barrel works for AK or Semi Auto rifle crafting.

**Comment by faketucker** [comment]
Make sure you are using the right barrel
