### ISSUE TITLE
When Opening chests, cooked fish looses its energy symbol

### ISSUE THREAD

**Issue by knicnax** [Uuvana-Studios/longvinter-windows-client#359]
**Describe the bug**
In the open chest menu, the symbol for cooked fish and raw fish is the same. The energy symbol added on the cooked fish disappears. You need to hover over the fish to find out if it;'s cooked or not

**To Reproduce**
1. Have cooked fish in inventory'
2. Open a chest
3. the inventory menu for both character bag and chest does not show the energy symbol for cooked fish

**Expected behavior**
the energy symbol for cooked fish should be retained when opening chests to easily differentiate between cooked and raw

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version Beta 1.0.0
 - Steam Version v020

**Additional context**

**Comment by faketucker** [comment]
Tested.

**Comment by Mikooboy** [comment]
This should be fixed in the next update
