### ISSUE TITLE
My base disappeared

### ISSUE THREAD

**Issue by levzz** [Uuvana-Studios/longvinter-windows-client#360]
i grinded to upgrade a tent and then my base disapered
i got some items in inventory back but OOOOOOOMMMMMGGGG

**Comment by BrotherBill123** [comment]
Same thing happened to me 
https://streamable.com/jadqga

**Comment by August-vint** [comment]
same all my items and chest are gone

**Comment by heyspaceman** [comment]
Happened to me too. I dismantled my home last night and when I placed my tent down again it already had a stove inside. The stove would heal me but I couldn't pick it up or use it to cook. 

Finally grinded to upgrade my tent again and when I come on to play this morning, while exploring, it randomly glitched and respawned me at my house location but my house was gone and back in my bag. Placed the tent, glitchy stove inside again. 

Lost all my items :(

**Comment by faketucker** [comment]
This should already be [fixed](https://discord.com/channels/846308806870695967/946785267984003072/952160722467557376)
