### ISSUE TITLE
Clearing up tent-space

### ISSUE THREAD

**Issue by drawesometoons** [Uuvana-Studios/longvinter-windows-client#363]
Hello!

A simple fix to the current Tent-space problem would be to give the tents a decay timer of for example 2 days.
2 days without interaction, the tent will be destroyed. This keeps players from just placing down a tent never to return again.
Wasting the space. 
Option B would be to make tents destroyable. If the house stays invincible its fine, but tents should not be a permanent thing.
I think either of those would make real estate much more accessible on the island.

I love the game so far!

**Comment by Bunnbunnnn** [comment]
This was implemented with 2 tent per person & decay timer for tents
