### ISSUE TITLE
Spawning in other players base!

### ISSUE THREAD

**Issue by tamayo831** [Uuvana-Studios/longvinter-windows-client#364]
After I died, I am constantly responding in someones else base. Ive tried restarting and logging out.

https://user-images.githubusercontent.com/59874080/157996689-55b3f7e9-b222-44f6-a3c9-591e2ca02b61.mp4

**Comment by RedReaper2017** [comment]
I am having this issue as well! Has happened to me twice now >=(

**Comment by youhavehowie** [comment]
same

**Comment by KITTENWHO** [comment]
That was my base, not sure what was goin on

**Comment by faketucker** [comment]
Since the latest stable version update, players should no longer respawn in other people's houses.
