### ISSUE TITLE
i dont take fire dmg

### ISSUE THREAD

**Issue by undyingdemon** [Uuvana-Studios/longvinter-windows-client#365]
**Describe the bug**
whenever i stand in fire i dont take dmg but when others or freinds stand in it they take dmg and possibly die
**To Reproduce**
i dont know how to reproduce it
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem
![unknown](https://user-images.githubusercontent.com/96261412/157998257-85980142-366d-4a7f-b3de-b7b34b4663b4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Game Version [e.g. 1.0] 1.0
 - Steam Version [e.g. 1.0] unkown

**Additional context**

**Comment by faketucker** [comment]
I believe you're not standing in the right spot, so you don't take any damage. Try to move a bit and you will take the damage as normal.
