### ISSUE TITLE
Fluctuating Market Prices

### ISSUE THREAD

**Issue by CorceTV** [Uuvana-Studios/longvinter-windows-client#366]
**Is your feature request related to a problem? Please describe.**
Not a problem per se - i like the dynamic market system in theory, but within the first 12 hours of the wipe I'm seeing a lot of high value items bottoming out, and a lot of items which newer players may need skyrocketing.

**Describe the solution you'd like**
A fluctuating market may be an interesting solution. Maybe keep the dynamic market but occasionally maybe a certain item goes really cheap or crazy expensive randomly. This could even be a server event thing - maybe make a specific vendor in a PvP zone do this so there's some conflict over greed.

**Describe alternatives you've considered**
Alternately, maybe a cap on certain items growth - storage chests, for example, are something a lot of new players need, and to have them jump 50% as soon as a server launches is a little rough

**Additional context**

**Comment by faketucker** [comment]
Following the March 15th update, vendor prices are now stabilizing at a 100% faster rate.
