### ISSUE TITLE
running in circles

### ISSUE THREAD

**Issue by mexicandoge** [Uuvana-Studios/longvinter-windows-client#369]
**Describe the bug**
joined a server i was on for 2 days and made me run in circles in the last place i was before logging off
**To Reproduce**
i dont know how it started in the first place, i restarted the game and joined the same server with the same results. 
joining any other server would place me in the lake at the beginning location and makes me swim in circles

**Expected behavior**
not running in circles for now reason
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0] longvinter beta 1.0.0
 - Steam Version [e.g. 1.0]  
 steam api v020
steam package 1646806235

**Additional context**
i close my game after playing it for the past week

**Comment by mexicandoge** [comment]
how do i attach a video of more than 10mb

**Comment by KoalaBoy** [comment]
> how do i attach a video of more than 10mb

Post it on YouTube and paste a link here

**Comment by mexicandoge** [comment]
https://www.youtube.com/watch?v=a5FPaqKW8II
video might be shaky

**Comment by sirNugg3ts** [comment]
We have absolutely no way to replicate this. The odds of this being a problem with your PC are magnitudes bigger than a bug with the game, since you are the first to ever report an issue of this kind. Check for software that might try to emulate input like DS4Windows for example
