### ISSUE TITLE
I think the chainsaw completely destroys the ticrate of the servers

### ISSUE THREAD

**Issue by VisibleIBananaI** [Uuvana-Studios/longvinter-windows-client#37]
Whenever my friend or I use the chainsaw it completely destroys our gameplay

**Comment by Jalsson** [comment]
Does the lag go away after stopping the chainsaw?

**Comment by VisibleIBananaI** [comment]
The lag doesn't completely go away but it is reduced

**Comment by sirNugg3ts** [comment]
please check if this happens when there are around 20 players in the server, that seems just the serve rubberbanding as usual

**Comment by VisibleIBananaI** [comment]
It was around 14-15 players I believe but I'll do some testing again tomorrow.

**Comment by sirNugg3ts** [comment]
netcode has been fixed
