### ISSUE TITLE
Hella Crates

### ISSUE THREAD

**Issue by Zusken** [Uuvana-Studios/longvinter-windows-client#372]
**Describe the bug**

When someone dies their bag becomes crates

**To Reproduce**
 
DIE

**Expected behavior**

Crates Spawn

**Screenshots**

https://steamuserimages-a.akamaihd.net/ugc/1842541072333669124/AD05AF8D39FD801D82CF45718C1147DED9FC3962/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Already fixed

**Comment by Jalsson** [comment]
I think the server version is old if this still happens
