### ISSUE TITLE
Entered someone’s tent and Delted my house

### ISSUE THREAD

**Issue by luvopium** [Uuvana-Studios/longvinter-windows-client#373]
I was right clicking this person farm collecting roots they had a stable box? (the grey colored plant box) while right clicking i somehow entered their tent but once i entered I was teleported to my house but it was gone and it went back to a tent in my inventory and lost everything in containers that was in my house. I wish i clipped it to show proof but i turned it off earlier. Mega F 

Version 1.0.0

**Comment by faketucker** [comment]
Duplicate of #360
