### ISSUE TITLE
2 Houses bug

### ISSUE THREAD

**Issue by Mentolao** [Uuvana-Studios/longvinter-windows-client#376]
When placing my second house in front of the first (since it doesn't let me put it anywhere else nearby), when I bring it too close it bugs and doesn't let me get out of it.

 - OS: Windows 10
 - Game Version Beta 1.0.
![unknown (1)](https://user-images.githubusercontent.com/101456901/158015755-015e66ce-993a-4f8e-9596-58fef9729294.png)
0

**Comment by sirNugg3ts** [comment]
this was fixed on the update
