### ISSUE TITLE
Turrets can't shoot to some angles when being put on heights

### ISSUE THREAD

**Issue by Matavatar** [Uuvana-Studios/longvinter-windows-client#377]
**Describe the bug**
Turrets can't shoot to some angles when being put on heights. Mostly on diagonals from any heights starting to +1 chest.

**To Reproduce**
Put a turret on chests or any heights and run around (with enough food hehe)

**Expected behavior**
Turrets should be able to shoot to any angles from any heights (or not be able to be placed on heights if it's the better design choice to you)

**Video**
https://youtu.be/_FYn1UAsfpw

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0
 - Steam Version 1.0

**Additional context**
Maybe we shouldn't be able to put turrets on heights.

**Comment by faketucker** [comment]
Tested. It seems like there are many blind spots for turrets when you put them up high.

**Comment by faketucker** [comment]
Tested #428. Turrets are not reliably shooting on the ground either.

**Comment by faketucker** [comment]
This seems to still happen somehow
