### ISSUE TITLE
Container Visually Disappearing After Server Restart

### ISSUE THREAD

**Issue by ricjonsu-impact360** [Uuvana-Studios/longvinter-windows-client#378]
**Describe the bug**
As the title says, some container might disappear visually when the server is restarted. It won't be fixed unless you pickup the container, then place it again

**To Reproduce**
1. Place a some containers
2. Restart the server
3. Login to see that some containers are "missing" visually, but they are in fact, there

**Expected behavior**
The container must not disappear.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Stable Beta 1.0
 - Steam Version: Stable Beta 1.0

**Comment by faketucker** [comment]
Do you still face this problem?

**Comment by Ardyey** [comment]
Haven't encountered the issue since the last update. (Thread starter is also my account)

**Comment by faketucker** [comment]
Thanks for the info!
