### ISSUE TITLE
Currency in the negative

### ISSUE THREAD

**Issue by GoochPanooch** [Uuvana-Studios/longvinter-windows-client#380]
When opening the inventory and accessing traders the currency is reading -207654. Because it's in the negative purchasing objects is impossible and any sold object only seems to reduce the overall amount

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
