### ISSUE TITLE
Currency in the negative

### ISSUE THREAD

**Issue by GoochPanooch** [Uuvana-Studios/longvinter-windows-client#381]
After buying an auto defense kit my currency shot down into the negative and I am now unable to purchase anything

1. Bought AutoDefense Kit
2. Currency shot into the negative

**Expected behavior**
Have the currency in the positive

 - Windows
 - 1.0.0
 - Steam Version 1647024114
 
![Screenshot 2022-03-12 104311](https://user-images.githubusercontent.com/101466718/158024770-623a313d-83da-4499-ad31-f89e92fd72b7.png)

**Comment by Matavatar** [comment]
Dudes broke af

**Comment by faketucker** [comment]
I can't find a way to replicate this. Not sure what caused it. If you find an exact way to replicate this, feel free to reopen this issue again or file a new bug report.
