### ISSUE TITLE
My turrets are missing after logging back in several hours later.

### ISSUE THREAD

**Issue by taeowyn** [Uuvana-Studios/longvinter-windows-client#383]
![Longvinter-Win64-Shipping_bzGZbzrQNf](https://user-images.githubusercontent.com/34247151/158029958-7104fdb3-9395-44be-97e3-c8f62dae1472.jpg)
![Longvinter-Win64-Shipping_OGZiRlqtZL](https://user-images.githubusercontent.com/34247151/158029962-c309ffbc-a6bd-49df-a83a-2044937310c0.jpg)

**Comment by faketucker** [comment]
We need more info and steps to replicate the bug or we have no way to fix them. Please use the appropriate bug reporting template that we provided.
