### ISSUE TITLE
An big enhancement ''issue''

### ISSUE THREAD

**Issue by Mcdonaldsis** [Uuvana-Studios/longvinter-windows-client#384]
An npc of some sorts that attacks the animals and players near it. 
Would be a great consideration to make an apple arcade port. this game would be grade a apple arcade material
More transportation like trams or trains
More animals may i suggest wolfs or otter
player owned animals that can help the player out like dogs or cats
long distance player owned communication like an CB radio or walkie talkie 
the ability for the player to make his or hers own clothing
using an sewing machine or just thread and needle
more kinds of turrets
bigger and better houses may i suggest two story buildings
the ability for the player to hide in bushes from enemy npc or otherwise
or to hide in grain fields as well
the ability to use the old movie trope of an bookcase hiding spot in the game
Bigger and better expansion of lootable areas in the  map not just storage places but laboratory's abandoned stores etc
More food and snack items
More weapons
Traps such as rat traps and hunting gear
brick and rock fences

**Comment by Bunnbunnnn** [comment]
documented and linked for reference
