### ISSUE TITLE
Stuck in the Rocks 

### ISSUE THREAD

**Issue by isnowcloud** [Uuvana-Studios/longvinter-windows-client#385]
**Describe the bug**
Character seems to be stuck in between the rocks and does not have a way to escape. 
Logging in and out of the game does not appear to work nor is there a reset/escape button 
**To Reproduce**
1. Go to a woodsy area with rocks and trees
2. Enter through the gap between the rocks
3. Hopefully, you should be stuck with no way to exit :)
Temp. Solution:  Wait for someone to kill you. For now it will be the only way to leave the trapped area 

**Expected behavior**

**Screenshots**
screenshot attached below

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
![Screenshot (7)](https://user-images.githubusercontent.com/101480909/158036468-de41c1eb-4684-4c07-a669-510d7367e856.png)

**Comment by faketucker** [comment]
You can chop down the tree or use /kill to get out of there
