### ISSUE TITLE
Game Crashed After Dismantling Tent

### ISSUE THREAD

**Issue by jehoshua02** [Uuvana-Studios/longvinter-windows-client#386]
**Describe the bug**
Game crashed after dismantling tent.

**To Reproduce**
1. Place tent
2. Enter tent
3. Place workbench
4. Use workbench
5. Click dismantle

**Expected behavior**
Return outside with tent and workbench in inventory without game crashing.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version Beta 1.0.0
 - Steam Version Unsure, but says up to date. Steam API v020 in help about steam?

**Additional context**
Was able to reproduce the issue consistently.

**Comment by GingeNToxic** [comment]
I have this same issue with the house.

**Comment by jehoshua02** [comment]
Fixed for me!
