### ISSUE TITLE
Ammo disappears after being put in a container.

### ISSUE THREAD

**Issue by xdDirti** [Uuvana-Studios/longvinter-windows-client#387]
**Describe the bug**
Ammo disappears after being put inside a container.

**To Reproduce**
Steps to reproduce the behaviour:
1. put ammo in container
2. wait
3. boom

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0
 - Steam Version - Latest at time of this post

**Comment by faketucker** [comment]
Tried. Can't find a way to replicate this
