### ISSUE TITLE
Infrequent camera zoom out on house when entering

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#389]
**Describe the bug**
About 3% of the time when I enter my house the camera is zoomed really far out.

**To Reproduce**
1. Enter house.
2. The camera might be really zoomed out.

**Expected behavior**
I expect to enter the house and have a nice view of my house not from really far away (see screeenshot).

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/14806514/158039087-203a46f3-c1a4-4c2a-8fe8-fa0e35d6fa75.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**
The house to the right is also mine, and the one I am entering is the one on the left. No one else has the code to my houses.

**Comment by faketucker** [comment]
I tried many times but couldn't replicate this. If this happens, try using the mouse scroll wheel to zoom in and out.
