### ISSUE TITLE
Change the icon for the autodefender kit so it isnt the same as the one for the battery

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#390]
**Is your feature request related to a problem? Please describe.**
I am trying to make a turret and I cant tell the difference between the battery and the autodefender kit because the icon is the same.

**Describe the solution you'd like**
It would be nice if they were different. Ideally the battery would look like a battery and the autodefender would look like a tripod base mount.

**Describe alternatives you've considered**
A quick alternative is just to put an upside Y on the current icon for the autodefender and defer the artwork to later.

**Additional context**
I have nothing else to add. This is a really minor issue though.

**Comment by faketucker** [comment]
The game now has the battery icon
