### ISSUE TITLE
Player Vending Machines

### ISSUE THREAD

**Issue by GoochPanooch** [Uuvana-Studios/longvinter-windows-client#391]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Vending machines that can be bought and placed outside homes, where the player controls the price of objects and can sell looted items. Could also be used as a trading terminal for safer trades between players.

**Describe alternatives you've considered**
drop boxes for trades where you have to approve the trade and can only retrieve the items when both parties accept

**Comment by mpurple77** [comment]
We've had several convos with other players suggesting that these would be helpful, especially for light bulbs (at least in this version)

**Comment by Bunnbunnnn** [comment]
Documented and linked for reference
