### ISSUE TITLE
Property line moved after server restart

### ISSUE THREAD

**Issue by Reidiology** [Uuvana-Studios/longvinter-windows-client#394]
**Describe the bug**
After a server restart, one of our gates began saying it was not near a house and anyone could use it. I quickly discovered that a large section of our fencing was now blue in the area it had used to be green. After messing around with the fencing we were able to build a new fence that was all considered green, but it was significantly less space than before, and an odd shape, like the houses weren't providing the correct ownership boundaries anymore. I've attached a photo with a red dotted line showing the old fence line, and you can see the makeshift replacement fence line. I also show a piece of fence showing as blue placement in an area it should be green.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101512465/158064175-fbc22a4e-f0e5-40e2-9c08-7493f5188400.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
I'm unable to recreate this on my own, as I can't restart the server. I do believe the server restarted due to a crash though, so perhaps that is what caused this issue.

**Comment by sirNugg3ts** [comment]
Did you update the server ? If so this is most likely because of the new house / tent hitbox,  then the line just adapted as it was supposed to

**Comment by Reidiology** [comment]
The server was wiped and updated Friday, and the house was placed then.
Also the other side of the fence (south west) has not changed or been moved
at all, and seems fine. If it were a hit box adjustment, shouldnt it occur
eveningly on both sides?

**Comment by faketucker** [comment]
Do you still face this problem or does it work correctly now?

**Comment by Reidiology** [comment]
We have wiped the server since then and I have not experienced it this go
around.

**Comment by faketucker** [comment]
Just want to mention this is might be the same bug as #493
