### ISSUE TITLE
Moveable Blank Item *Experimental Server

### ISSUE THREAD

**Issue by asianmess** [Uuvana-Studios/longvinter-windows-client#395]
**Describe the bug**
A item that is a white blank square, it can be moved around in your inventory, put in chests, and dropped on the ground and picked back up.

**To Reproduce**
I don't know I was walking around and found a chest with a fence, seeds, and this blank item in it, then I tried to move it to my inventory and it worked.

*Playing on Experimental Server*

**Screenshots**
![image](https://user-images.githubusercontent.com/81714869/158071510-1048565c-96f6-4a3f-baf8-febfac70dfaa.png)
![image](https://user-images.githubusercontent.com/81714869/158071516-5a3d9bf3-5061-4641-b48a-ea4920bacdf8.png)
![image](https://user-images.githubusercontent.com/81714869/158071521-741435ee-91a2-4614-8ae3-dadee9c75746.png)
*I have a video but it was over 10MB*

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0

**Additional context**
You are able to move it around in chests and your inventory, as well as drop it on the ground and pick it back it. I tried to use the item but nothing happened when I clicked it

**Comment by mysticmasterfin** [comment]
This can be found also in official servers. and it's value is poor 0mk.
https://cdn.discordapp.com/attachments/846308807386464268/953124267883651092/Capture_2022-03-12_at_16.png

**Comment by sirNugg3ts** [comment]
This is a null item, it doesn't exist and its due to the server lag

**Comment by faketucker** [comment]
I believe this was already fixed.
