### ISSUE TITLE
h

### ISSUE THREAD

**Issue by RollinDoobs** [Uuvana-Studios/longvinter-windows-client#397]
**Describe the bug**
Hacker
**To Reproduce**

**Expected behavior**
Hacker
**Screenshots**
![Longvinter Screenshot 2022 03 13 - 17 38 10 75](https://user-images.githubusercontent.com/101529069/158080412-e8b39458-d039-4e49-8529-bb90b5698c66.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0] -

**Additional context**

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

**Comment by RollinDoobs** [comment]
Idk what he did, some dude was flashing and spamming what the screen shot had in it
