### ISSUE TITLE
Game crashes to main menu when trying to 'dismantle' house

### ISSUE THREAD

**Issue by GingeNToxic** [Uuvana-Studios/longvinter-windows-client#398]
**Describe the bug**
I get booted back to the main menu after clicking 'Dismantle' on my house in the workbench.

**To Reproduce**
1. Go to workbench in empty house
2. Click on dismantle
3. Click continue after warning message about losing house upgrade and wood.
4. Get booted to main menu

**Expected behavior**
House is dismantled and tent in put in inventory to be placed.

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: [Windows
 - Game Version Longvinter Beta 1.0.0
 - Steam Version, Unsure.  Everything is up to date though.

**Additional context**

**Comment by sirNugg3ts** [comment]
This should have been fixed in the latest patch
