### ISSUE TITLE
Cannot place my tent...

### ISSUE THREAD

**Issue by KITTENWHO** [Uuvana-Studios/longvinter-windows-client#399]
**Describe the bug**
Tent appears red, with the error message "Cannot place in someone elses property", however, there are 0 houses in sight. I can place other things like fences, just not the tent... I tried moving to other areas of the map, but the entire map is glitched. I also tried relogging into the server, relaunching the game, and reinstalling the game.

**To Reproduce**
No idea, my friends are not having this issue, and could even place a tent exactly where i was trying to, after i showed them my issue.
**Expected behavior**
The tent places and progression continues as usual.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
This should have been fixed, try to place a new tent
