### ISSUE TITLE
Stucked inside house

### ISSUE THREAD

**Issue by salemggs** [Uuvana-Studios/longvinter-windows-client#40]
I cant leave the house i was just organizing the loot and i cant leave, to solve it i have to close the game and open it again.

**Comment by sirNugg3ts** [comment]
please file the bug correctly according to the template we deliver when you open an issue. If possible attach screenshots or a recording of the issue

**Comment by Plant2** [comment]
recreate bug:
1. enter house
2. place deployable (chest, workbench)
3. attempt to leave
4. stuck inside

player should be able to exit house

game version 1.0
Windows 10

**Comment by sirNugg3ts** [comment]
we haven't seen this happening yet, please give us some screenshots and try to recreate the bug in another server. Else it might be a one time glitch

**Comment by sirNugg3ts** [comment]
No answer was given. If stuck use alt+k or /kill
Closing issue
