### ISSUE TITLE
Unable to Rotate Placeable Objects

### ISSUE THREAD

**Issue by KingofClimb** [Uuvana-Studios/longvinter-windows-client#401]
**Describe the bug**
Since purchase of the game last week, I've been unable to rotate any objects using the "R" key, and have tried all other key combinations as well to no avail.

**To Reproduce**
1. I don't believe it can be reproduced

**Expected behavior**
Objects can be rotated at will.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Longvinter Beta 1.0.0
 - Steam Version: Steam API - v020 (not sure if this is the correct version needed)

**Additional context**
Not sure if the problem could be resolved by adding the option for a user to select the key input to rotate objects in settings?

**Comment by sirNugg3ts** [comment]
I've tried a couple of times and had no issue rotating, that seems to be a problem with your setup
