### ISSUE TITLE
Issues when you die while trying to write something and when you are trying to place something.

### ISSUE THREAD

**Issue by Kimusuko** [Uuvana-Studios/longvinter-windows-client#402]
**Describe the bug**
When you die writing something, when you respawn you can not move anymore, or pause or do anything, the game get locked. 

When you die trying to place something, when you respawn the windown with the indications can not be closed, and you can not use anything from your inventory.

**To Reproduce**
1. Open chat box
2. Die with the box open
3. Same thing while trying to place something.

**Expected behavior**
Respawn normally with everything reseted.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windos 10 pro 21h2 64bits 
 - Game Version Beta 1.0.0
 - Steam Version 

**Additional context**
I was killed by someone and with a turret in both cases

**Comment by faketucker** [comment]
Tested. I can reproduce the chatting but not the placing.

**Comment by Mikooboy** [comment]
Widgets get removed properly when dying so this should be more reliable in the next update.
