### ISSUE TITLE
Unable to remove storage box from my yard

### ISSUE THREAD

**Issue by xzxProofxzx** [Uuvana-Studios/longvinter-windows-client#406]
When trying to remove this box, it will place it into a bag but the box does not disappear. Need it gone, its in the way!!!

Official Server Uvanna 7
Windows 10

*

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
