### ISSUE TITLE
Can't upgrade tent to house

### ISSUE THREAD

**Issue by Bellala333** [Uuvana-Studios/longvinter-windows-client#407]
**Describe the bug**
Can't upgrade tent to house

**To Reproduce**
1. Go to the workbench
2. Deposit 100 wood
3. Click on upgrade
4. Set door code
5. Pick a color

**Expected behavior**
the upgrade should have been highlighted again but it doesn't and the upgrade does not take place, it's still a tent. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1,0
 - Steam Version [e.g. 1.0]

**Additional context**
I got another tent and placed it in a different spot and I'm still having the same problem.

**Comment by Bellala333** [comment]
![20220314135413_1](https://user-images.githubusercontent.com/101591656/158393506-50860b3c-8688-4041-ae97-5607a30ae701.jpg)
![20220314135423_1](https://user-images.githubusercontent.com/101591656/158393530-6283f068-6415-4152-9f53-d160b05cec0e.jpg)

**Comment by sirNugg3ts** [comment]
It has to be a 5 number pin number
