### ISSUE TITLE
Vendor UI stuck on screen

### ISSUE THREAD

**Issue by doyle404** [Uuvana-Studios/longvinter-windows-client#410]
**Describe the bug**
Whenever entering and exiting menus, if you do it to quick or exit by walking away and then quickly opening new dialogue, it locks you in the menu and when you try to exit out of the menu it locks the window or pulls up the disconnect screen without pressing "esc"

**To Reproduce**
1. Go to a vending machine 
2. Click away
3. Click back
4. If it doesn't work repeat 2 and 3
5. See error

**Expected behavior**
Locking you out of the game through the UI menus locking you in them, forcing you to disconnect and reconnect. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Steam Version [e.g. 1.0]

**Comment by sirNugg3ts** [comment]
If you spam the menu it will show up twice

**Comment by Nepre** [comment]
Same here, I have to disconnect and reconnect as I am not sure how to close some menus that are bugged

**Comment by SteamNinjaLord** [comment]
yeah seems like a repeating issue that really hinders from playing especially when you are frequent in opening the shop menu.

**Comment by MollyTeaaa** [comment]
Vendors not closing

**Comment by faketucker** [comment]
Fixed
