### ISSUE TITLE
Cheater Spamming Tents EU2

### ISSUE THREAD

**Issue by VonACYT** [Uuvana-Studios/longvinter-windows-client#412]
Describe the bug

Someone is putting hundreds of tents around the river and for some parts of the map on the EU2 server, it's the first time I'm on github, I don't know if I'm creating the post right or not, but this problem is definitely very annoying
 - OS: Windows 10
 - Game Version 1.0

![yee](https://user-images.githubusercontent.com/101602837/158265878-acf0e3ec-4fe3-4921-83cb-05ca9cbb7fea.PNG)
.

**Comment by sirNugg3ts** [comment]
This is not a bug, its hacking and we are working on it, for this use discord
