### ISSUE TITLE
Cant enter my own house

### ISSUE THREAD

**Issue by xvphoebe** [Uuvana-Studios/longvinter-windows-client#415]
**Describe the bug**
I placed to container near my door (in front of the doorway) but it is color blue and I was able to go out of my own but when I tried entering my house, i can't. It keeps getting me out. 

**To Reproduce**
1. Go to the my house
2. Placed a container near the door
3. Went out my house
4. TTried to enter the house but it keeps pushing me outside

**Expected behavior**
If it is not applicable to place objects near the door change the color placement of the object to red. Fixed this please so I can enter my house again. 

**Screenshots**

https://user-images.githubusercontent.com/85151835/158285252-e08e960b-6585-41c4-837d-b4dc764706f5.mov

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version v020

**Additional context**

**Comment by faketucker** [comment]
I believe this is fixed. You can still enter the house even if there's something blocking the doorway.
