### ISSUE TITLE
Guns stop shooting randomly and take up to 30sec to start shooting again

### ISSUE THREAD

**Issue by BongWaterBilly** [Uuvana-Studios/longvinter-windows-client#416]
**Describe the bug**
Guns stop shooting randomly and takes from 5sec up to 30sec to start shooting again even though the guns loaded.

**To Reproduce**
During gun fights/spam shooting the gun will randomly stop shooting. Could be after 1 shot or after 200 shots, it just seems random.

**Expected behavior**
The gun should shoot when left mouse is clicked but sometimes it doesn't shoot even when loaded.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version v020

**Additional context**
Cannot pvp with this happening :(

**Comment by faketucker** [comment]
Can't replicate this. This might be caused by your gun colliding with an object like bushes, rocks, or trees and you will not able to shoot
