### ISSUE TITLE
When upgrading tent while items inside.

### ISSUE THREAD

**Issue by mysticmasterfin** [Uuvana-Studios/longvinter-windows-client#417]
**Describe the bug**
if you have them in your tent and upgrade to house, they will get stuck and be unusable also can't remove.

**To Reproduce**
1. Go to buy and place indoor heating.
2. Click on upgrade house
3. Scroll down to ----
4. See error stuff are stuck and in the wall.

**Expected behavior**
spawn in the character inventory or if full then turn to bags inside the home.
**Screenshots**

![image](https://user-images.githubusercontent.com/100821214/158300258-9e1a409c-fdf0-4469-bd1f-70c326bef829.png)

**Additional context**
destroying a house will lose all the wood and hard work to make new.

**Comment by faketucker** [comment]
Tried. Can't replicate this. Maybe this might happen because of something like #354
