### ISSUE TITLE
floating tent 

### ISSUE THREAD

**Issue by uwulucci** [Uuvana-Studios/longvinter-windows-client#418]
Tent is floating on top of flowers.

**To Reproduce**
place tent on flowers

![image](https://user-images.githubusercontent.com/101615527/158300686-2e4f7a9f-a603-4dfc-907f-243bea55d638.png)

**Comment by faketucker** [comment]
Tested. Tents can be placed on flowers

**Comment by Mikooboy** [comment]
Added a check for foliage when placing stuff. Should be fixed in the next update
