### ISSUE TITLE
what the is going on

### ISSUE THREAD

**Issue by Golden0of** [Uuvana-Studios/longvinter-windows-client#420]
**Describe the bug**
Some how Someone or People are able to do this on US 6 server right at the lake when you take your 199km boat trip

**To Reproduce**
1. Go to 'US 6'
2. Click on 'Boat trip to lake'

**Expected behavior**
unfair 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
![20220314235837_1](https://user-images.githubusercontent.com/101616677/158304265-2ac154c2-3d89-4a4a-9407-3def4e161933.jpg)
![20220314235843_1](https://user-images.githubusercontent.com/101616677/158304276-a1880d62-6029-4be2-b062-aeccb96649c8.jpg)

**Comment by sirNugg3ts** [comment]
This is hacking and it's being worked on
