### ISSUE TITLE
a safe spot... some people just want to play and trollers just keep killing you.... cant even build because they gonna kill you. Create a safe server maybe? 

### ISSUE THREAD

**Issue by cece653** [Uuvana-Studios/longvinter-windows-client#423]
Needs a safe server. 

I just want to play and build but trollers get on and just kill you when you walk out of your tent door....

**Comment by KoalaBoy** [comment]
There are already non-official PvE servers, but none of the official ones.

**Comment by megane0724** [comment]
I feel like this would be really useful, especially for new players just trying to figure things out.

**Comment by Bunnbunnnn** [comment]
documented and linked for reference
