### ISSUE TITLE
Admin Menu "Show names"

### ISSUE THREAD

**Issue by Dantwire** [Uuvana-Studios/longvinter-windows-client#426]
**Describe the bug**
When you click on Show names, all Players winking but it is running endless

**To Reproduce**
1. Go to 'Admin Menu'
2. Click on 'Show names'
5. See error

**Expected behavior**
Stop winking after some seconds

**Screenshots**
No Screenshot

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.1
 - Steam Version 1.0.1

**Comment by moatib** [comment]
yes , tested on my server and same behavior

**Comment by Dantwire** [comment]
you can resolve the Problem when you click c on your Keyboard

**Comment by moatib** [comment]
yes it stop winking but i haven't the name show

**Comment by sirNugg3ts** [comment]
show names is not working as intended, we are going to fix it

**Comment by faketucker** [comment]
[Fixed.](https://discord.com/channels/846308806870695967/946785267984003072/974562814171693116)
