### ISSUE TITLE
Stuck above a tree

### ISSUE THREAD

**Issue by Lucieher** [Uuvana-Studios/longvinter-windows-client#429]
**Describe the bug**
My character is stuck above a small tree in the island with the peacocks, in the south.

**To Reproduce**
1. Go to the island with the peacock, the one on the west on the EU experimental server
2. Move to the platform
3. Go down while going on top of the small tree

**Expected behavior**
You should'nt be able to go on top of tree or if you can, you should be able to go back on land

**Screenshots**
![stuck](https://user-images.githubusercontent.com/38586091/158443404-215139f1-b177-456a-bb97-044ee356b800.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.1
 - Steam Version last version 15 march 2022

**Additional context**
I'm in the experimental EU Server

**Comment by sirNugg3ts** [comment]
bugs in experimental are not takken into account since we change a lot of stuff regularly there. If you get stuck use alt+k to suicide and respawn
