### ISSUE TITLE
Duping items from crafting and fire stations

### ISSUE THREAD

**Issue by Dodg-e** [Uuvana-Studios/longvinter-windows-client#43]
**Describe the bug**
Duping items from crafting and fire stations

**To Reproduce**
1. Craft or cook something
2. Click multiple times fast on the crafted object to take it to your inventory (works even better if you turn off internet connection, click multiple times on the crafted object to get it, turn internet back on, object get duped.)
3. Inventory full of duped objects

**Expected behavior**
Getting one item and not inventory full

**Screenshots**
https://discord.com/channels/846308806870695967/880859106989178880/947409497201188904

**Comment by Jalsson** [comment]
Added server-side check that prevents multiple requests from coming in before the current one has been processed.
