### ISSUE TITLE
You need to collect all plants ? Bug - Plants Customer

### ISSUE THREAD

**Issue by hugosui** [Uuvana-Studios/longvinter-windows-client#430]
**Describe the bug**

**To Reproduce**
1. Go to 'Plants collectionner'
2. Click on 'him'
3. Be sure to have complete your plants collections

**Expected behavior**
I should be able to have discussion with plants customer
**Screenshots**
![image](https://user-images.githubusercontent.com/70572025/158443875-0addf876-feac-4baa-b294-c4bf64ad91bc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0.1]
 - Steam Version [Mar 8 2022 - 21h50:39]

**Additional context**
I disasambled my tent before the bug, before the "disasembling" i could talk with the plant customer.

**Comment by sirNugg3ts** [comment]
Update your game, the plants have changed
