### ISSUE TITLE
Official Server Uuvana South america , can't find it in Browse Islands. 

### ISSUE THREAD

**Issue by CptMarveLL** [Uuvana-Studios/longvinter-windows-client#432]
Official Server Uuvana South america , can't find it in Browse Islands. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Servers are being updated, use discord to notify this.
