### ISSUE TITLE
Going back onto server

### ISSUE THREAD

**Issue by gabithaa** [Uuvana-Studios/longvinter-windows-client#433]
**Describe the bug**
Randomly not being able to go back onto servers I've been playing on for days, it just takes me straight back to the title screen.
**To Reproduce**
1. Go to 'the title screen.' 
2. Click on 'play' 
3. Scroll down to 'any server you've been playing on (mine I've been playing on is Gronkvinter)' 
4. See error - doesnt let me even go on the server just takes me straight back to the title screen. Can't even access it. 

**Expected behavior**
Being able to go back onto the server that I've been playing on for days.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0] 1.0.1

**Additional context**
This has been happening since I started playing, I have to keep starting on new servers basically every week now or even less than that. I've been on about 5 or six new servers. I really love the game, but this bug has been the most annoying thing that I've had to deal with on a new game.

**Comment by sirNugg3ts** [comment]
Server is not updated for sure. Only issue bugs if this is happening on official servers

**Comment by gabithaa** [comment]
@sirNugg3ts good to know, thank you! So once updated, the problem will fix itself?

**Comment by sirNugg3ts** [comment]
yep

**Comment by jehoshua02** [comment]
Ollo neighbor @gabithaa! Sorry for the down time. Server is updated, but now I'm seeing some concerning bugs (fences disappearing) and decided to leave the server down for maintenance. I can imagine how disappointed you feel right now. I was really excited to play some tonight. I'll post in the [Grokenvinter Discord](https://discord.gg/tCMNAhQzrb) when the server is back up.
