### ISSUE TITLE
New update problems...

### ISSUE THREAD

**Issue by chaiisiing** [Uuvana-Studios/longvinter-windows-client#434]
I just started the game after the update. When I came into the server I always play in I've lost most of my money, some progress when it comes to my Compendium collection. And also some things that I was wearing.

**Comment by chaiisiing** [comment]
The server is EU uuvana 2 btw

**Comment by sirNugg3ts** [comment]
From FAQ on Discord

I just lost my progress / my inventory (or house) disappeared, I want my stuff back!
- We are aware of the time some of you are putting on our game, and we are thankful.
Still we are, as you should be aware, in EA and Beta, which means a lot of updates might delete stuff that might have been done until that point, creating partial or full wipes.
At the moment there's nothing we can do until the game is somewhat stable, we ask for your comprehension and patience while we work on your next favorite game ❤️

**Comment by chaiisiing** [comment]
Oh I see. Thank you.
