### ISSUE TITLE
Garden Tile Bug

### ISSUE THREAD

**Issue by RAILSSS** [Uuvana-Studios/longvinter-windows-client#435]
Placing a garden tile inside my home in front of the door like a doormat causes a bug where you can no longer enter your home. attempting to enter home results in a black screen and then you are back in front of your house again. Also placed a fence next to the door when placing the garden tile just to see if you could place it indoors. Not sure if the garden tile or the fence is creating this issue.

**Comment by RAILSSS** [comment]
not sure if it matters, but this happened in an upgraded tent, not the base tent.

**Comment by faketucker** [comment]
You can still enter the house even if there's something blocking the doorway.

**Comment by faketucker** [comment]
Duplicate of #415
