### ISSUE TITLE
Gate disappearing

### ISSUE THREAD

**Issue by Naert3v** [Uuvana-Studios/longvinter-windows-client#436]
**Describe the bug**
My gate disappears as soon as I place it.

**To Reproduce**
1. Place gate
2. Wait 3 seconds

**Expected behavior**
It should just stay? Like it did before. It is green before placing, on my property.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0] 1.0.1
 - Steam Version [e.g. 1.0] 

**Additional context**

**Comment by KoalaBoy** [comment]
I think it's the same as mine #404

**Comment by sirNugg3ts** [comment]
Duplicate of #404
