### ISSUE TITLE
Ship ticket bug

### ISSUE THREAD

**Issue by Carpetess** [Uuvana-Studios/longvinter-windows-client#439]
**Describe the bug**
I was lagging and was buying ship tickets. The requests werent coming through though, so i boutght more, and more, and more. When the request finally went through i had lost 1000 mk for a trip, therefor having bought 5, which makes no sense

**To Reproduce**
1. Go to any ship while lagging
2. Click on the buy ticket thing multiple times
4. not stonks

**Expected behavior**
buying more tickets than u can afford

**Screenshots**
No Screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version Beta 1.0.1
 - Steam Version i dont know, the most updated version at the time of this report.
**Additional context**
No addtional context.

**Comment by faketucker** [comment]
Tested. You can spam click to travel by boat multiple times, and it'll cost you as much as the time you clicked.

**Comment by Jalsson** [comment]
This action is now prevented.
