### ISSUE TITLE
i logged in today and my house gone and ive noticed a couple other player houses that were there yesterday are gone too. how do i get it back?

### ISSUE THREAD

**Issue by shaggy859** [Uuvana-Studios/longvinter-windows-client#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
There's no method to get stuff back at the moment. And please fill out the template when submitting a bug
