### ISSUE TITLE
Plant Seed Duplikation

### ISSUE THREAD

**Issue by pokakoW** [Uuvana-Studios/longvinter-windows-client#440]
When you spamm left klick while standing on a 3X3 planterbox and you plant your seed (every seed works) the seed your holding is planted  but also drops on the planterbox for you to pick up (you are able to duplikate the seed up to 3 times from what i tried) 

 - OS: e.g. Windows

**Comment by hoak** [comment]
can confirm, I just placed one planter box and with one black lotus seed I could seed the entire thing easily uising this method. Click twice fast when placing it down and your seed get picked back up. So you only need one black lotus seed to seed the entire garden of X plots.

**Comment by faketucker** [comment]
Fixed. You can no longer spam left click to place items at the same spot
