### ISSUE TITLE
Ability to report players for hacking

### ISSUE THREAD

**Issue by Selventis** [Uuvana-Studios/longvinter-windows-client#442]
Have experienced players hacking and griefing my base and taking damage well over the health limit and still not dying by my turrets. They keep flooding my base with endless bullets and never running out. Got to get some anti cheat or something going to prevent this.

**Comment by Selventis** [comment]
Or a way to report and get players disabled for doing so.

**Comment by ZELDACHIK64** [comment]
this has happened to me too and now my entire house and storage units filled up are all gone.

**Comment by Bunnbunnnn** [comment]
@Selventis @ZELDACHIK64  You can always report hackers in the official discord if it took place on the official forum - there is a ticket system in contact channel 

however, adding this suggestion as a way to do it via ingame. Linked for reference
