### ISSUE TITLE
Ability to change house code lock

### ISSUE THREAD

**Issue by Selventis** [Uuvana-Studios/longvinter-windows-client#444]
Would be beneficial to change you house lock code so you don't have to deal with it being one code people can guess then have access to your house by guessing it. Would also be good that when you change it it blocks all players who had the old code until thy have the new one too.

**Comment by hoak** [comment]
I would Expand on this and say that we need three codes: House, gate, and turrets, in that order of trust. As Selventis says you can change a code if you feel it has been shared without your knowledge, which invalidates the old code. My additional idea is that you can share out a code(s) for you yard area but prevent people entering your house. I know we can pop a tent up and that is always locked out, but that prevents you from haveing two houses side by side which is the ideal setup for inventory maximum capacity.

**Comment by Bunnbunnnn** [comment]
documented and linked
