### ISSUE TITLE
Turrets near fishing spots make it impossible to get specific fish

### ISSUE THREAD

**Issue by Spaicat** [Uuvana-Studios/longvinter-windows-client#445]
**Is your feature request related to a problem? Please describe.**
Some people put houses near interest spot such as fishing spots, thus we can't access them. I think it's a really big problem that break the game for other players.

**Describe the solution you'd like**
We should not be capable to put houses and turrets near fishing spots in the same way we can't put house too close to points of interest.

**Additional context**
For example, I can't get the last fish to complete the compendium tab which is located on top of the arena :
![images of turrets blocking fishing spots](https://user-images.githubusercontent.com/55053185/158707890-5ca0b865-2aec-4c16-8f7a-5d63148e10fd.png)

**Comment by Bunnbunnnn** [comment]
documented and linked
