### ISSUE TITLE
Dynamic Building and Cooking

### ISSUE THREAD

**Issue by Fulkrem** [Uuvana-Studios/longvinter-windows-client#45]
Currently in the game we are forced to stand at the stove and workbench if we want to cook and or build anything. In times of making several fence pieces or trying to cook multiple things at once, I find myself standing there for an extended period of time. Yes it keeps the player playing the game more, but at what cost? Boredom. 

Suggestion: We make it so players are able to place the ingredients into the stove and as the it beings to cook, walk away to complete other tasks. This would allow for players to either 

A) Have multiple stoves and cook more food at once, making farming a little more efficient. 
B) We come up with another item that allows players to cook more items at once with the above idea in mind as well. 

I think this will create more dynamic game play for not only players who prefer to live the PVE life, especially pvpers who will be able to push out more buff foods in a timely manner and get back out there into the fight. If there is one.

A little bit of QoL

**Comment by Bunnbunnnn** [comment]
Documented on forum
