### ISSUE TITLE
Server isn't connecting.

### ISSUE THREAD

**Issue by lolkds** [Uuvana-Studios/longvinter-windows-client#452]
**Describe the bug**

**To Reproduce**
1. Go to main menu
2. Click on play
3. then you click on the Singapore Server or any actually
4.The screen acts like its loading me into the server
5. Then I am back to the Play screen. 
6. It won't let me into the server. 

**Expected behavior**
Once I hit play

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.1
 - Steam Version Last update March 16th

**Additional context**
Been going on since yesterday night. Worked fine around 11am but around 8pm when i got on, it wouldnt allow me into any servers, just acts like it will then crashes.

**Comment by ZaiS3** [comment]
i just bought the game and testing the beta and i could only play for few minutes.
The server i have picked, kicked  me and now i cant get in. i'm trying and waiting as the message in the screen says but after a minute maybe a little more i'm back to the main screen.

**Comment by lolkds** [comment]
> 
Yeah thats what mine is doing too!

**Comment by feedmeimstoned** [comment]
this is happening to me too on US uuvana 4

**Comment by PikachusaNus** [comment]
I just downloaded this game a few hours ago and am having the same issue. I cannot load into public servers as it kicks me back to the main menu. I cannot even manually join servers through finding a server in the steam server list and typing in the steam id in game. It starts to load then just kicks me back to the main game. Very unmotivating to buy a game for 20$ and not even be able to play it AT ALL.

**Comment by PikachusaNus** [comment]
To add on to my above comment, I have allowed longvinter through both windows firewall AND my router. So the issue shouldn't with my network connection.

**Comment by faketucker** [comment]
Do you guys still encounter this problem after the new server browser update?

**Comment by faketucker** [comment]
I’m going to close this issue since the update should fix this.
