### ISSUE TITLE
bait disappeared

### ISSUE THREAD

**Issue by ZaiS3** [Uuvana-Studios/longvinter-windows-client#454]
The first time i tried to fish i could see the bait floating on the water. Then i tried to take the fishes but nothig happened. empty inventory and i tried to fish again. then the bait disappeared and it was very difficult or impossible guess when the fishes were eating the bait because ther was nothing floating but the character was there fishing. So it's weird.

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
