### ISSUE TITLE
Experiemental Server: Fish not showing in inventory after catching it 

### ISSUE THREAD

**Issue by Bunnbunnnn** [Uuvana-Studios/longvinter-windows-client#456]
Opening this ticket on behalf of discord player ebeyshiy#4179

**Describe the bug**
On the EU experimental server: Fish does not show in inventory after being caught. Have tried to catch fish in 4-5 times and they wont show up - moved spots and still no fish show up. I can catch plants and other stuff, but not fish. 

**To Reproduce**
1. Catch fish with telescopic reel & normal reel 
2. Have banner that you caught it 
3. open inventory and see no fish

**Expected behavior**
To catch fish when the banner says I caught one. 

**Screenshots**
Link goes to video of bug in discord - file was too large to attach
https://discord.com/channels/846308806870695967/846308807386464268/954048947381489724

**Desktop (please complete the following information):**
1.0.1 beta , Experimental branch 
PC is windows

**Comment by feedmeimstoned** [comment]
this happened to me too on experimental server US

**Comment by iwannamustache** [comment]
hey just by the way fish are currently unobtainable in (us) experimental server me and two friends tested it.

**Comment by Bunnbunnnn** [comment]
Pretty sure it is fixed: Svens message about pushing a fix https://discord.com/channels/846308806870695967/880859106989178880/954402361051340841

**Comment by iwannamustache** [comment]
thanks ily <3
