### ISSUE TITLE
Chainsaw action not working regularly. 

### ISSUE THREAD

**Issue by Plurbaybee** [Uuvana-Studios/longvinter-windows-client#459]
**Describe the bug**
When I am going to to use the chainsaw in a bunch of trees they wont cut it down. I do want to add that I am disabled and used to xbox controller with the steam config 

**To Reproduce**
1. Go to '...' use 
Use the chainshaw 
On the left trigger on xbox controller, the action button will freeze when there are still trees to chop. Walk to a different section with trees and it will would fine. 

**Expected behavior**
We wanted to be able to chop the trees. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]  Windows Stream Version 1.01 
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
If the chainsaw won't work with the left trigger, try pressing the right stick button while holding the left trigger. It should work again.
