### ISSUE TITLE
Inventory and Container Stacking

### ISSUE THREAD

**Issue by Plurbaybee** [Uuvana-Studios/longvinter-windows-client#461]
**Is your feature request related to a problem? Please describe.**
No, not really. 
**Describe the solution you'd like**
We'd like to be able to stack the same item into the same section of the inventory or in the containers. Similar to the way you can have a stack of nook miles tickets in pockets on Animal Crossing. 
**Describe alternatives you've considered**
Only letting stacking happen in the inventory but making the container be something that has to be separated? 
**Additional context**

**Comment by Bunnbunnnn** [comment]
documented already
