### ISSUE TITLE
Controller Options!!

### ISSUE THREAD

**Issue by Plurbaybee** [Uuvana-Studios/longvinter-windows-client#462]
**Is your feature request related to a problem? Please describe.**

I am a disabled person, and I LOVE this game, I would love to be able to play this game in a way that works for my body. Currently with just the steam configs the controller does things like make the character walk in circles. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented and linked for reference
