### ISSUE TITLE
Turret: Despawn on placement/ Player Death while placing

### ISSUE THREAD

**Issue by mpurple77** [Uuvana-Studios/longvinter-windows-client#464]
**Describe the bug**
When placing the turret on to a fence the turret de-spawned.
--It also despawns if you die from freezing while trying to place it.

**To Reproduce**
--see above.

**Expected behavior**
--to spawn in and see it as a drop/loot bag

**Screenshots**
sorry, not much to SS

**Desktop (please complete the following information):**
 - OS:Windows
 - Game Version experimental server (US)
 - Steam Version [1.0.1]

**Additional context**
It happened to a neighbor on the server shortly before it happened to us.

**Comment by faketucker** [comment]
Tested. Any placeable thing will be lost if you die while trying to place it.

**Comment by faketucker** [comment]
[Fixed.](https://discord.com/channels/846308806870695967/946785267984003072/974562814171693116)
