### ISSUE TITLE
Stuck at Point of Interest near Tims Outpost

### ISSUE THREAD

**Issue by FistyDotMe** [Uuvana-Studios/longvinter-windows-client#465]
**Describe the bug**
I'm stuck between the door and shelves at the outpost.

**To Reproduce**
1. Go to point
2. walk
3. Stuck 

**Expected behavior**
Getting out

**Screenshots**
https://imgur.com/qv4t8S4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.1
 - Steam Version 1.0.1

**Comment by faketucker** [comment]
You can type /kill in the chat or use Alt +K
