### ISSUE TITLE
after the update i lost everything

### ISSUE THREAD

**Issue by DKAres901** [Uuvana-Studios/longvinter-windows-client#466]
**Describe the bug**
i lost money item and house why? fix it please

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Jalsson** [comment]
Which server did you play on?

**Comment by fhillipgcastillo** [comment]
I was on server: [US] uuvana 6 and I lost 2 or 3 containers, they just disappear from by house, which had the most important items there. This issue happened after the update

**Comment by faketucker** [comment]
Duplicate of #600
