### ISSUE TITLE
Kick from the server if I interact with anything

### ISSUE THREAD

**Issue by lkid73** [Uuvana-Studios/longvinter-windows-client#467]
Describe the bug
I'm kick, me and my friend form my personnal server Iif I collect flower or open a vending machine

To Reproduce

    Go to anything that you can interact with
    Click

Expected behavior
Kicked form the server

Desktop (please complete the following information):

    OS: Windows 10
    Game Version 1.0.1
    Steam Version 1.0.1

**Comment by sirNugg3ts** [comment]
Server or client is not updated
