### ISSUE TITLE
Can no longer catch fish 

### ISSUE THREAD

**Issue by Slygirl1156** [Uuvana-Studios/longvinter-windows-client#469]
**Describe the bug**

**To Reproduce**
1. Go to any fishing spot
2. Click on to fish
3. Catch a fish and then check your inventory
4. See error: no fish in your inventory 

**Expected behavior**
I expect to be able to fish and get easy money lol
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version Beta 1.0.1
 - Steam Version newsest??

**Additional context**

**Comment by faketucker** [comment]
[Fixed](https://discord.com/channels/846308806870695967/945406152378826812/954401409971920936)
