### ISSUE TITLE
Grid toggle option when building.

### ISSUE THREAD

**Issue by zank-z** [Uuvana-Studios/longvinter-windows-client#47]
I really enjoy the aspect of building in the game but it's kinda hard to measure stuff or place items to look symmetrically without a grid, so a toggle option to turn a soft grid on or off would be nice. It doesn't take away anything from the player who doesn't care about building but it helps a lot of those who wanna create builds/towns/etc. in the game 

I made this edit to see what I mean by saying "a grid option", obviously is not that well made cause I used an online website to do it, but I hope is good enough for you to understand what I mean <3
![-Gr](https://user-images.githubusercontent.com/100526197/155889476-5617e8c1-7c7e-42b2-8cc7-d48137e37025.png)

**Comment by Bunnbunnnn** [comment]
Documented on forum
