### ISSUE TITLE
Right after fishing, got some fishes but doesn't appear in backpack.

### ISSUE THREAD

**Issue by poonuood** [Uuvana-Studios/longvinter-windows-client#472]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by GreenySunny** [comment]
This bug is solved

**Comment by faketucker** [comment]
Duplicate of #469
