### ISSUE TITLE
All my belongings are gone...

### ISSUE THREAD

**Issue by alexhelbig27** [Uuvana-Studios/longvinter-windows-client#473]
**Describe the bug**
After the update, my house and all of the items inside are gone. I had at least 7 different storage containers full of food, guns & ammo, wood, etc. Spent at least 10-20 hours on all that loot unfortunately. 

**To Reproduce**
1. Server: [US] uuvana 6
2. Current session ID: 90157250418322434
3. Location: East Beach on the small island south of Filemon's and east of Artur's.

**Screenshots**
![longvinterHouse](https://user-images.githubusercontent.com/99288500/159045028-9da82ad3-22bb-45a6-937b-e911f57620fa.PNG)

**Comment by alexhelbig27** [comment]
Username is FunkyMonk27

**Comment by sirNugg3ts** [comment]
From FAQ
