### ISSUE TITLE
vending machine menu

### ISSUE THREAD

**Issue by havster100** [Uuvana-Studios/longvinter-windows-client#474]
**Describe the bug**
A when i click on the vending machines around the map every now and then it wont let me close the vending machine menu of the screen and i have to leave the server and come back on two get it two go away 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Duplicate of #410
