### ISSUE TITLE
items disapper

### ISSUE THREAD

**Issue by Leesa2594** [Uuvana-Studios/longvinter-windows-client#476]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Leesa2594** [comment]
I plated a lotus seed, and when I walked away from the screen for just a moment, it disappeared.   There were no other player and my husband was in the area guarding it.  My two planters and lamp post did the same thing

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
