### ISSUE TITLE
i can't pick-up the items i left behind the house

### ISSUE THREAD

**Issue by DKAres901** [Uuvana-Studios/longvinter-windows-client#478]
**Describe the bug**
i can't pick-up the items i left behind the house

**To Reproduce**
1. Go to 'near the house'
2. Click on 'pleace a item or die'
3. Scroll down to 'try to pick-up the item'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
You can pick up placeable things behind your house, but it has to be at the right angle. And try to pick up items with a spacebar if they are behind your house.
