### ISSUE TITLE
Not letting me join the servers I have been playing on

### ISSUE THREAD

**Issue by ZyloIsFaded** [Uuvana-Studios/longvinter-windows-client#480]
**Describe the bug**
When I attempt to join either of the servers, it continuously sends me back to the title screen. 

**To Reproduce**
1. Go to 'Play'
2. Click on 'History'
3. Click the server I want to play on
5. *Sent back to title screen*

 - Steam Version [1.0.1]

**Additional context**
Please figure out what's going on! <3

**Comment by zImaGe1** [comment]
Having this same issue. I can join other servers just fine, but the one I had spent time in, can't play there.

**Comment by sirNugg3ts** [comment]
Servers are out of date most likely. Please only issue bug reports on official servers
