### ISSUE TITLE
empty containers duplicate 

### ISSUE THREAD

**Issue by jashuwalee** [Uuvana-Studios/longvinter-windows-client#482]
**Describe the bug**
Whenever i try to pick up an empty container the item appears but the container stays behind.

**To Reproduce**
1. Go to any container.
2. Right click to turn it into an item
3. container should stay but the item also appears inside

**Screenshots**
![bug](https://user-images.githubusercontent.com/51843335/159086457-ab819b02-8d0a-41d6-9875-253d7dd1a50d.png)

**Comment by johanrdz11** [comment]
I have the same problem i cant pick up my containers

**Comment by hoak** [comment]
same issue was about to submit bug for this too - screnshot looks the same. Rt click on empty contgainer and the oriignal conainer stays there so yuo cant pick up the bag. Worse, the now containers allows you to put items in it but it will go away later.

**Comment by GreenySunny** [comment]
I have exatly the same problem

**Comment by faketucker** [comment]
This occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.
