### ISSUE TITLE
Lots more crashes since 3/18 update

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#484]
**Describe the bug**
I played for hours, 10 hours even before with no crashes and now there is a random crash every 20- 30 min or so.

**To Reproduce**
1. Play
2. So something the latest thing was to open an outpost loot crate for example
3. Cant loot, game health bar stops going down, I know i got disconnected somehow
4. Get booted out to main menu

**Expected behavior**I
I wouild expect to continue playing and not get crashed/booted out/frozen

**Screenshots**
self explanatory

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Game Version Martch 18t update
 -  - Steam Version March 18th update

**Additional context**

**Comment by Leesa2594** [comment]
My husband and I are getting the same thing.

**Comment by faketucker** [comment]
Duplicate pf #600
