### ISSUE TITLE
I can't go in my house anymore and I lost my character

### ISSUE THREAD

**Issue by LysianeCroissant** [Uuvana-Studios/longvinter-windows-client#486]
I had a bug when entering my house, I had to leave the game, when I came back I can no longer enter my house, I lost my money and my progress, even the color of my character changed, can you please help me

ID Session : 90157250423280646
Nam Steam : Ðelicious Łady

**Comment by sirNugg3ts** [comment]
Was this on an official server?

**Comment by LysianeCroissant** [comment]
Server EU uuvana 2

**Comment by LysianeCroissant** [comment]
Problem solved

**Comment by LysianeCroissant** [comment]
The server did the necessary
