### ISSUE TITLE
Vanishing golden chest in the Arena Server Uvana 4

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#49]
**Describe the bug**
Whenever the golden chest spawns it will despawn before you reach it and when you do actually manage to reach it, it's empty and will vanish as you're checking the inside, the only time it had loot in it was on an update it would be the first chest there. 
**To Reproduce**
1. Go to '...' Arena
2. Click on '....' Golden Chest
4. See error It vanishes

**Expected behavior**
I expected to find the hat inside like during the fresh update. 
**Screenshots**
![image](https://user-images.githubusercontent.com/100467609/155891392-d1dc60cb-528d-424d-bd06-27d9137bd545.png)
It was here but it vanished as i got closer.
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
We have tried to replicate this issue and didn't find any problem with the chest

**Comment by xekken** [comment]
Somthing in USA uuvana 4 is causing that chest to vanish before being touched me and 2 other people confirmed this and watched, they also claim to have tried to obtain it multiple times, when you open it it's empty.

**Comment by xekken** [comment]
the only time it works is only once after an update to the game.

**Comment by sirNugg3ts** [comment]
Fixed in the last EXPERIMENTAL branch
