### ISSUE TITLE
vending machine window wont close if double clicked 

### ISSUE THREAD

**Issue by ryhoquist44** [Uuvana-Studios/longvinter-windows-client#490]
**Describe the bug**
every time you double click the vender you can interact but it wont let you close out of it.

**To Reproduce**
1. double click any vending machine

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version latest
 - Steam Version latest

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #410
