### ISSUE TITLE
Game lag, get kick out of server and have to close and open client

### ISSUE THREAD

**Issue by fhillipgcastillo** [Uuvana-Studios/longvinter-windows-client#491]
**Describe the bug**
The game lag, everything freeze except by my character, energy bar freeze, enemies/other players freeze and them I get kick out of the server and for me being able to find and re-join the server I have to close the client and re open it again. 

By the way, My pin goes from 70ms to 110ms which may be some of the cause. (I'm from latan)

**To Reproduce**
1. Join Server: [US] uuvana 6
2. Play until the game elements freeze (by verifying the environment around the player)

**Expected behavior**
If the game lags, I should receive something that let me know I'm lagging at least or to verify my internet connection, and I shouldn't get kick out of the server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Game Version 1.0.1
 - Steam Version 1647446817

**Additional context**

**Comment by faketucker** [comment]
Duplication of #600
