### ISSUE TITLE
Diagonal Home Save Zone reset

### ISSUE THREAD

**Issue by drawesometoons** [Uuvana-Studios/longvinter-windows-client#493]
**Describe the bug**
The save zone of diagonal placed homes reverts to the save zone of a normally placed home when server restarts. Everything that is outside of the save zone can be picked up by everyone.

**To Reproduce**
1. Place Home diagonally
2. Build fence within the save zone
3. Restart server
4. The save zone will have reverted to normal instead of diagonal

**Expected behavior**
Well, obviously one would expect the save zone to stay in the place it is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
Might be more of a problem for server owners, but should be fixed still.

Thank you, love the game!

**Comment by faketucker** [comment]
I placed my house on the diagonal and tried to restart the server many times but couldn't replicate this, so I'm going to close this for now.
