### ISSUE TITLE
Unable to equip/unequip tools.

### ISSUE THREAD

**Issue by ElRosee** [Uuvana-Studios/longvinter-windows-client#494]
**Describe the bug**
Chainsaws/Guns/Fishing Rods, all were unable to be equipped, although the sound notification were there. I were able to interact with everything else normally. I am able to equip/unequip hats, interact with gates, etc. Just no way of equipping tools. I've tried DC, restarting the game. All does not work. 

**To Reproduce**
I have no idea why this happens.

**Expected behavior**
When i left click on the tools on my backpack, that very tool do be equipped, in the equipment tab.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Longvinter Beta 1.0.1
 - Steam Version 
![unknown](https://user-images.githubusercontent.com/101872046/159113316-998783b2-0fc3-49bc-aae6-92d6670775d8.png)
![1](https://user-images.githubusercontent.com/101872046/159113312-b2cb8a85-2a0e-440d-bbb4-0240fb51fdef.png)

**Additional context**
This happens on official servers SG. Started happening around 5 hours ago, before this report was made.

**Comment by e4Nf3Bb5** [comment]
Same from me today on us uuvana 1

**Comment by faketucker** [comment]
Does this still happen? I can't find a way to replicate this

**Comment by faketucker** [comment]
This might happen randomly, and I can't find a way to replicate this. If you face this problem again and have a way to replicate it, feel free to reopen this issue or file a new bug report. But till then, I'ma close this for now.
