### ISSUE TITLE
Arena Loot not spawning in

### ISSUE THREAD

**Issue by annaleejones02** [Uuvana-Studios/longvinter-windows-client#497]
The loot spot in the snow "arena" does not load all loot in. Missing and glitching box

**Comment by sirNugg3ts** [comment]
Is this on an official server?

**Comment by annaleejones02** [comment]
Is an official AUS server

**Comment by faketucker** [comment]
Arena loot is now spawning normally in the AUS server. When the server restarted, any missing or glitching boxes should have been fixed.

**Comment by annaleejones02** [comment]
Yes the AUS server
