### ISSUE TITLE
Autumn Biome Turret bug

### ISSUE THREAD

**Issue by FlukyLemon** [Uuvana-Studios/longvinter-windows-client#498]
when you try to place a turret they disapear or placed somewhere 

[https://i.imgur.com/e8K07Wu.mp4](url)

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

**Comment by cmod31** [comment]
I already made an issue for it
