### ISSUE TITLE
Can't pick up container

### ISSUE THREAD

**Issue by GreenySunny** [Uuvana-Studios/longvinter-windows-client#499]
**Describe the bug**
When i try to pick up with right click a container inside or outside my house, nothing happen and i can't pick up the container. I can stock things inside and take it back but i can't move the containers.

**To Reproduce**
1. Try to pick up an empty container with right click.
2. A noise happens but nothing else.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.1

Thks a lot !

**Comment by sirNugg3ts** [comment]
Is this on an official server?

**Comment by GreenySunny** [comment]
No, its on FR Beginner Vinter

**Comment by sirNugg3ts** [comment]
Unfortunatly we can't offer support on unofficial servers since we dont know the circumstances of the host. Please only issue bug reports on official servers

**Comment by Sammieyy** [comment]
This is happening on the official server as well. My chests just keep being duped and unable to pick those or the original one up

**Comment by GreenySunny** [comment]
So how i can resolve my problem ?
