### ISSUE TITLE
Character Customization

### ISSUE THREAD

**Issue by sirNugg3ts** [Uuvana-Studios/longvinter-windows-client#5]
"A chance to differentiate from one another and would give the world a bit more personality. Plus in-game cosmetics would add another system players could dive into and spend time working towards for a more diverse gameplay loop."

[Discord message](https://discord.com/channels/846308806870695967/873486241482559508/946752911701069844)

**Comment by Bunnbunnnn** [comment]
Documented already on forum as - Player customization, clothing, faction swag, in-game cosmetics
