### ISSUE TITLE
My friend can't open fence gates

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#503]
**Describe the bug**
My friends can't open fence gates even I gave him a house code

**To Reproduce**
1. Place a fence gate in your house area
2. Give your friends a house code and let them enter your house
3. Let your friends open the gate
4. They can't open it

**Expected behavior**
Friends able to open a fence gate in your house area when they can enter your house

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Latest

**Comment by WarpWing** [comment]
Just because you give your friend the house code doesn't mean your friend has access to ALL of your property. If you had a code lock on your fence, then you can share the code with your friend and THEN your friend can access the gate. Otherwise, the fence is only hardcoded to the owner.

**Comment by cmod31** [comment]
There are special codelock fences for this you can craft them i think
