### ISSUE TITLE
Can't dismantle tent

### ISSUE THREAD

**Issue by Sammieyy** [Uuvana-Studios/longvinter-windows-client#505]
**Describe the bug**
I placed a tent and wanted to replace it so i dismantled it. I get kicked out of the tent but the tent stays there and I get a new tent + workbench in my inventory. 

I tried to replace it as i noticed the old stuff from my deleted house (other bug report) was suddenly still there so i tried to replace the tent to grab my stuff. 

**To Reproduce**
1. Go into your tent 
2. Click on dismantle in the workbench 
3. Get kicked out of the house with a new tent and workbench 
4. Old tent is still standing there with the workbench. I can enter the tent and interact with the workbench. I can't place a new tent somewhere else as it says i now have two tents (i have one house and this bugged tent) 

**Expected behavior**
Being able to dismantle and replace the tent.

**Desktop (please complete the following information):**
 - OS: windows 
 - Game Version 1.0.1
 - Steam Version most recent, idk which version 

![IMG-20220319-WA0004](https://user-images.githubusercontent.com/101938031/159128443-3714cecd-e188-4963-a452-2acb61f77a0c.jpeg)

**Comment by Sammieyy** [comment]
Also i placed a new workbench and it suddenly got duped.

**Comment by xZephlin** [comment]
Same here

**Comment by faketucker** [comment]
Can't find what caused this, but it seems like many people are facing this bug.
