### ISSUE TITLE
It automatically turns off within 10 seconds of starting the game. Please solve this problem. I have reinstalled and checked the integrity.

### ISSUE THREAD

**Issue by GuiltyRoach** [Uuvana-Studios/longvinter-windows-client#506]
**Describe the bug**
It automatically turns off within 10 seconds of starting the game. Please solve this problem. I have reinstalled and checked the integrity.

**To Reproduce**
1. Go to Steam
2. Click on Longvinter
3. Wait for 10 second(or do anything)
4. Game crash and automatically left the game

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window
 - Game Version 1.0.1
 - Steam Version newest version

**Additional context**
It automatically turns off within 10 seconds of starting the game. Please solve this problem. I have reinstalled and checked the integrity.

**Comment by Jalsson** [comment]
Does the show any messages after the crash?

**Comment by GuiltyRoach** [comment]
No, It's just that the game is forced to end.

**Comment by faketucker** [comment]
Have you tried updating DirectX and graphics drivers?

**Comment by faketucker** [comment]
We can't look into it since we don't have enough info. Feel free to reopen this issue if you still encounter this problem.
