### ISSUE TITLE
Jumping with touch input

### ISSUE THREAD

**Issue by ZacAttackk** [Uuvana-Studios/longvinter-windows-client#51]
I am playing the game on my laptop as I am away which has a touch screen, and I noticed when taking dust off the screen, the character hops. I tried every other keyboard button and I cannot jump, nor is it listed in the controls. So with that and the fact there is no jump animation yet, I am going to bug report it.

TL;DR:
- Tapping the screen while playing on a touch-screen device causes the player to jump

This may allow players to get into areas they are not supposed to
![jumpbug](https://user-images.githubusercontent.com/13535866/155892826-dd2e1b1a-83af-4e03-8e1c-9ae3b530b9e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Game Version Beta 1.0.0

**Comment by Jalsson** [comment]
Removed the action mapping from game files. Will be fixed in next update later today
