### ISSUE TITLE
Everyone kicked from US Uuvana 4 just 5 min ago, lost most money, in house items, and compendium progress

### ISSUE THREAD

**Issue by feedmeimstoned** [Uuvana-Studios/longvinter-windows-client#512]
**Describe the bug**
US uuvana 4 kicked everyone out of the game. Upon going back in, over half the money I had was gone, and the progress I made with the compendium items were reset to an earlier time. I had new containers full of things as of last night, which are now gone.

**Comment by sirNugg3ts** [comment]
This is not a bug, the server might just have crashed. Please only issue bugs with the game itself and not the servers. For server issues please go to our Discord
