### ISSUE TITLE
More In-Depth Tutorial?

### ISSUE THREAD

**Issue by megane0724** [Uuvana-Studios/longvinter-windows-client#516]
I feel as though the "How to Play" section in the menu is detailed, but it lacks a connection with people who are "hands-on" learners. I am struggling to figure out key mechanics such as establishing a base, weapon crafting, etc.

A way to make the game's controls/objectives easier to understand is if players are entered into an AI server, where they complete a basic tutorial (EX: Begin with basic controls, then have them place a tent, craft weapons using the kits, combat, etc.). That way they are prepared and aren't instantly killed right off the bat by more experienced players (which causes frustration).

As far as alternatives, maybe just having a system of suggested notes for controls/activities pop up in the top corner as the player moves about the world, triggering those notes to appear (EX: When a player comes across a weapon kit, have a note pop up directing them how to craft it and what might be needed).

**Comment by Bunnbunnnn** [comment]
Documented and linked for reference
