### ISSUE TITLE
Plants are not visible

### ISSUE THREAD

**Issue by pizzadreams6** [Uuvana-Studios/longvinter-windows-client#52]
I was disconnected from uuvana6. When I came back my plants were gone. They are not visible, but will not let me plant.

**Comment by sirNugg3ts** [comment]
Please log the bug with steps that we can replicate to fix and follow the template to give us the info to fix

**Comment by pizzadreams6** [comment]
When you view the planter box, it shows nothing in it. Nothing is clickable. Nothing can be planted either. I am in US uuvana6 at 14N 15W

**Comment by sirNugg3ts** [comment]
This issue was not reported correctly.

> Please log the bug with steps that we can replicate to fix and follow the template to give us the info to fix

Open a new bug report with the appropriate steps
