### ISSUE TITLE
DUPING - SELL SAME ITEM INFINITE TIMES

### ISSUE THREAD

**Issue by theB1NaRy** [Uuvana-Studios/longvinter-windows-client#520]
**Describe the bug**
You can use the James Vendor selling screen to sell the same item over and over for infinite profit.

**To Reproduce**
1. Go to James Vendor
2. Place item you wish to sell in the menu
3. Click on Sell and at the SAME time press TAB to close the window
4. Your item will have sold, but remains in your inventory.

**Expected behavior**
You can use the James Vendor selling screen to sell the same item over and over for infinite profit.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.1
 - Steam Version ?

**Additional context**
Unfair and just as game breaking as duplicating items.

**Comment by SebastianMaj** [comment]
I can confirm this works, I tested it on my server and if you time it correctly it will sell and return the item as well.

**Comment by faketucker** [comment]
Fixed in experimental

https://discord.com/channels/846308806870695967/946785267984003072/956178913330098196
