### ISSUE TITLE
Can't place a painting and rug inside the house

### ISSUE THREAD

**Issue by hoak** [Uuvana-Studios/longvinter-windows-client#522]
**Describe the bug**
Complete the Interior upgrade for the fuel powered upgrade path. The room enlarges, but you cant place a painting on the wall.

**To Reproduce**
1. Complete the Interior upgrade for the fuel powered upgrade path
2. You cant place a painting on the wall.

**Expected behavior**
I would expect the paintings to know the increased room dimentiosn size.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
After the house upgrading update, it seems to be bugged with placing a painting or rug inside the houses.

**Comment by Mikooboy** [comment]
Adjusted collisions of the interior so this should be fixed in the next update
