### ISSUE TITLE
 **I can't wear a hat, and the item won't be thrown away.**

### ISSUE THREAD

**Issue by dohansol** [Uuvana-Studios/longvinter-windows-client#523]
**Describe the bug**

**Expected behavior**

**I can't wear a hat, and the item won't be thrown away.**
I couldn't pick up the item.

**Comment by faketucker** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
