### ISSUE TITLE
Containers multiply and cannot be removed.

### ISSUE THREAD

**Issue by kopi311** [Uuvana-Studios/longvinter-windows-client#525]
**Describe the bug**
I wanted to place a container but couldn't, so I clicked on it and the container multiplied and I couldn't move it.

**To Reproduce**
sry It occurs randomly and we do not know the criteria for occurrence.

**Expected behavior**
I would like to be able to move proliferated containers.

**Screenshots**
https://gyazo.com/777a0f46724893ed33886f3181c780b1

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.1
 - Steam Version Latest

**Additional context**
If you try to move a buggy container by right-clicking, the container will multiply.

**Comment by faketucker** [comment]
This occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.

**Comment by kopi311** [comment]
thanks!!
