### ISSUE TITLE
All of my storage containers (in house) are gone!

### ISSUE THREAD

**Issue by NIZKDEE** [Uuvana-Studios/longvinter-windows-client#526]
**MISSING CONTAINERS**
The containers in my house are missing and all of the items I have collected disappeared with them.

**To Reproduce**
Just loaded in to game.

**Expected behavior**
I expected to load into the game at my house and see that nothing was missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 - Game Version Beta 1.01

**Additional context**
I've lost everything I owned. Please fix this.

**Comment by sirNugg3ts** [comment]
Duplicate of #527
