### ISSUE TITLE
Uuvana 6 is down

### ISSUE THREAD

**Issue by Chasedoesstuff** [Uuvana-Studios/longvinter-windows-client#530]
I cant open uuvaana 6. whenever I attempt to open it. it loads like normal and boots me back to the home screen. i tried uuvaana 7 and its functional but uvaana 6 isn't. 

To repeat this error simply open uuvaana 6.

 - OS: Windows
 - Game Version beta 1.01
 - Steam Version I can not figure out how to submit my steam version but I believe it is the most recent.

**Comment by sirNugg3ts** [comment]
This is not a bug, the server might just have crashed. Please only issue bugs with the game itself and not the servers. For server issues please go to our Discord
