### ISSUE TITLE
Very minor. When fishing it states "Tab E" rather than "Tap E" :))

### ISSUE THREAD

**Issue by snip3troug3** [Uuvana-Studios/longvinter-windows-client#532]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Moved out of enhancement since its not a suggestion

**Comment by Jalsson** [comment]
Hint text has been changed so im closing this
