### ISSUE TITLE
Movement is jerky and rubber banding a problem. The higher the ping the worse the problem. Have to log out then back in to bring down the ping. 

### ISSUE THREAD

**Issue by Scorpogee** [Uuvana-Studios/longvinter-windows-client#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
We are aware that the servers are laggy, we are working on network otimization
