### ISSUE TITLE
Baking overhaul

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#541]
**Is your feature request related to a problem? Please describe.**
I always felt baking to be extremely underwhelming currently a cake require a few things that are homegrown all for just a 75 hp heal and the cake goes on cooldown unable to eat another while fish heal 60+ and can be eaten anytime. 
**Describe the solution you'd like**
I feel baking should receive a lot more buffs for example the Cake could increase your stamina bars by maybe 4 that last until the cake buff is gone then the cooldown and fullness would make sense because it's like a topoff, Baking could be the Centerstone to all foods that give you buffs such as a baked food that gives you increased fishing speed and chance at rare fish, A food buff that increases mining speed and chance at rarer ores, a food buff that regens hp overtime but a very small amount but it last for a good duration could be a nice dish for when you are out and about exploring but don't want to eat an entire fish for hp. Add unique Baking recipes that can be bought from the secret shop, fish globally could probably be nerfed on how much hp they give in their base form but provide more when baked with a combination of things so that your means of survival have to be more earned and adds incentive to cooking as a whole. 
**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented and linked to forum
