### ISSUE TITLE
BluePrint Idea 2 Bakery 

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#543]
**Is your feature request related to a problem? Please describe.**
This idea will be quite a simple one which serves as buff to the other post i made about baking overhaul. 
**Describe the solution you'd like**
Make a bakery blueprint, after crafted it will have it's own unique list of recipes when you open it the bakey allows you to put up  to 1000 mats inside of it each such as 1000 wheat, berry types e.t.c, it will bake and produce a recipe of your choice overtime similar to my machinery idea it will show the words "baking" above the station light up and make noises if a player disables it they can steal the cooked items but unlike the machinery (because weapon production will take longer) The bakery will only yield items that were actually done being crafted when turned off. This will be the station requirement to make unique new baking items such as dishes that increase speed of fishing and fish rarity and dishes that increase mining speed and ore rarity followed with cake being moved exclusively to the baking station craft only and instead of 75 hp and with a lengthy cooldown you gain 4 stamina bars/ heart pieces while under the effects of being full. 
**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented and linked to forum
