### ISSUE TITLE
Pvp Rewards

### ISSUE THREAD

**Issue by xekken** [Uuvana-Studios/longvinter-windows-client#544]
**Is your feature request related to a problem? Please describe.**
I have an idea to expand on pvp outside of just raiding. 
**Describe the solution you'd like**
Make a unique island "Island of thieves" or "Skull Island" on this island are npcs that record your pvp records based on rank you gain acess to unique cosmetics, placeable blueprints for the outside of your housing area, cool weapons and titles with visual effects maybe even emotes sorta like the waving one,  Either the npcs could record progress but if thats too hard my back up ideas was players drop pvp coins which are next to your Mk as a sperate currency, there could be a cooldown on how many times you kill the same player and obtain coins, Or a player can drop a trophy with their name on it that can be sold to the npcs on that island. If all of this is scratched  a fame system could be added and resets each season, seasons could be a month long always reseting the 1st of the next month and the rewards the npcs sell can change each season randomized. Add blue print previews to the discord as it's own channel or in game so players can see what something looks like before committing to it.
**Describe alternatives you've considered**

**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented & linked to suggestion forum
