### ISSUE TITLE
House teleportation 

### ISSUE THREAD

**Issue by jueIz** [Uuvana-Studios/longvinter-windows-client#545]
**Describe the bug**
My own house got upgraded, but my friend who has the code cant see the changes made ingame. The house looks the same inside. So when he goes to the far edge he gets teleported to a outpost, in this case sgt. lake.

**To Reproduce**
1. Enter your friends house
2. Go to the far edge if you cant see the upgrade
3. Gets into the void and gets teleported to an outpost

**Expected behavior**
That the house is upgraded for both of us. 

**Screenshots**
My friends pov: https://gyazo.com/1bebb28098b22ba51e24e36b4a59601c
https://gyazo.com/a91517131c974ea353a1529fad0eb8fe
My pov: https://gyazo.com/d34130e8ee8aa3e4d908700cc5a75f9c

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Game Version 1.0.1
 - Steam Version 1647446817

**Comment by faketucker** [comment]
Did your friend try to relog the server? Did he see the house upgraded properly after that?
