### ISSUE TITLE
Bugged inside of Tent

### ISSUE THREAD

**Issue by FistyDotMe** [Uuvana-Studios/longvinter-windows-client#546]
**Describe the bug**
The inside of my tent is shifted upwards or something like that

**To Reproduce**
1. Place house
2. house is ####

**Expected behavior**
house is not #######

**Screenshots**
https://imgur.com/NAWMBCC

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.1
 - Steam Version: 1.0.1

**Additional context**
Tent was placed near river

**Comment by faketucker** [comment]
Do you still face this bug? Do you have more information or a way to replicate this?

**Comment by faketucker** [comment]
Since there is not enough info and no steps to replicate this, I'm going to close this issue
