### ISSUE TITLE
Remove the resolution change keybinds that are on 1 and 2

### ISSUE THREAD

**Issue by Serianni** [Uuvana-Studios/longvinter-windows-client#548]
Hitting 1 or 2 changes your resolution settings. This is annoying since they are so close to the WASD and Tab keys.
Please either add a key mapping screen where we can customize key bindings, or remove 1 and 2 asap

**Comment by Bunnbunnnn** [comment]
Documented on forum as "- Have more options to cutomize keymapping for everything"
