### ISSUE TITLE
Increase the limit of ⛺ 

### ISSUE THREAD

**Issue by thomasbnt** [Uuvana-Studios/longvinter-windows-client#549]
**Is your feature request related to a problem? Please describe.**
Yes, limits of tents.

**Describe the solution you'd like**

Add to possibility to **increase the limit** of ⛺ per user in `Game.ini`

**Describe alternatives you've considered**
/

**Additional context**
Nope.

**Comment by sirNugg3ts** [comment]
Please don't use emojis while suggestions ideas, be clear and concise.
