### ISSUE TITLE
Unable to see my own server on LAN

### ISSUE THREAD

**Issue by g2bb** [Uuvana-Studios/longvinter-windows-client#550]
**Describe the bug**
I've got a server set up that I can see in the server list from a friends house but when I'm on my local LAN where the server is hosted it doesn't show up in the list, I have to type in the server ID

**To Reproduce**
1. Launch server on the same LAN as your desktop
2. Search for server in server list

**Expected behavior**
The server should show up in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/15370969/159372682-0b600846-5969-43ef-b5e9-3179955ba20e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - Game Version: 1.0.1
 - Steam Version: 1647446817

**Comment by sirNugg3ts** [comment]
Please put this issue in [The Server Repo](https://github.com/Uuvana-Studios/longvinter-linux-server/issues)
