### ISSUE TITLE
haker el el juego tengo 4 dias en el juego y ya me an atacado 2 haker  es increible que un juego de 15 dias comoi mucho de haber salido ya tenga este poroblema jugadores con super velocidad que te matan con motosierra  y otros que destruyen tus paardes si es asi este juego esta muerto antes de comenzar que tristeza con tanto futuro espero que alguen le interece

### ISSUE THREAD

**Issue by ajaxh28** [Uuvana-Studios/longvinter-windows-client#551]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
