### ISSUE TITLE
Got stuck in one place after server crash.

### ISSUE THREAD

**Issue by SlicedBreadBoi** [Uuvana-Studios/longvinter-windows-client#552]
**Describe the bug**
When the game crashed I was walking through the water next to some rocks on the east side of the island above Filemon's Outpost. When I joined back into the game (uuvana 4 US) all it let me do was spin.

**To Reproduce**
Cant reproduce. This is a personal bug and every time that I leave and rejoin I get the same issue.

**Expected behavior**
I expected to be able to move when I got back in the game

**Screenshots**
![Longvinter bug 4](https://user-images.githubusercontent.com/102109287/159377047-4b5296cb-48ee-45e0-888e-3e3ac1a4223c.PNG)
![Longvinter bug 3](https://user-images.githubusercontent.com/102109287/159377049-1668d621-29c3-43f4-ad1d-b67da550531c.PNG)
![Longvinter bug2](https://user-images.githubusercontent.com/102109287/159377053-f59bfb84-fe20-40d7-9410-45d9cbdfe0d6.PNG)
![Longvinter bug1](https://user-images.githubusercontent.com/102109287/159377054-e8bb249c-4b6d-4cc3-9dc8-21f35f2ca6b0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.1
 - Steam Version ?

**Additional context**
None

**Comment by SlicedBreadBoi** [comment]
Someone please come kill me so that I respawn...

**Comment by sirNugg3ts** [comment]
Use alt+k to respawn
