### ISSUE TITLE
House was reverted back to a tent

### ISSUE THREAD

**Issue by Wolfwraith** [Uuvana-Studios/longvinter-windows-client#554]
**Describe the bug**
Describe the bug
The server crashed, I restarted, and my house was reverted back to a tent with one of my 4 chests in it.

To Reproduce
Server crash and reload?

Expected behavior
House to stay the same after the game has crashed. It had crashed multiple times and when I signed one the house was fine. Just this time it wasn't.

Screenshots:
https://steamcommunity.com/profiles/76561198021981336/screenshots/

Desktop (please complete the following information):

    OS: Windows 10
    Game Version: 1.0.1
    Steam Version: Longvinter Beta 1.0.1

**Comment by ComradeSmol** [comment]
I had the same issues too, my buddy's house reverted into tent after a server crash/lag. The chest in the base was also wiped, we had to grind back the 100 wood.

**Comment by sirNugg3ts** [comment]
servers crashing can stop the saving system from recording your upgrade. Has everything else related to a crash, it's not possible to record information in a crash. We will improve the saving system but for now there is nothing we can do
