### ISSUE TITLE
Stuck in chest menu

### ISSUE THREAD

**Issue by Umadd** [Uuvana-Studios/longvinter-windows-client#555]
**Describe the bug**
Opened a chest and got stuck in the chest menu and couldn't escape it

**To Reproduce**
Had to exit the game 

**Expected behavior**
exit outta chest normally

**Screenshots**
 
![Capture](https://user-images.githubusercontent.com/102141362/159433671-8255b7ad-750c-45a4-ad8e-c4a82a482ccd.PNG)

**Desktop (please complete the following information):**
OS: Windows 10
Game Version: 1.0.1
Steam Version: Longvinter Beta 1.0.1

**Comment by sirNugg3ts** [comment]
Same problem that #410
