### ISSUE TITLE
Increase the limit of tents

### ISSUE THREAD

**Issue by thomasbnt** [Uuvana-Studios/longvinter-windows-client#556]
**Is your feature request related to a problem? Please describe.**
Yes, limits of tents.

**Describe the solution you'd like**

Add to possibility to **increase the limit** of ⛺ per user in `Game.ini`

**Describe alternatives you've considered**
/

**Additional context**
Nope. From #549

**Comment by cmod31** [comment]
Also disabling the tent decay with the Game.ini would be nice

**Comment by faketucker** [comment]
You can now do it now by putting this in the Game.ini

[/Game/Blueprints/Server/GM_Longvinter.GM_Longvinter_C]
TentDecay=false
MaxTents=2
