### ISSUE TITLE
Constant Game Crash

### ISSUE THREAD

**Issue by pukegunk** [Uuvana-Studios/longvinter-windows-client#558]
**Describe the bug**
The game freezes then crashes every 5 minutes or so. It starts with not being able to access the inventory or have my name pop up when I wave. Then I get disconnected from the server. Sometimes the servers load when I click "Play" after, but I can't load back into a server without restarting the game and it starts all over.

**To Reproduce**
Play the game.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Current
 - Steam Version: Current
 - Game Settings: Default
 - Location: Eastern US

**Additional context**
This is on any server, but I primarily play on the [US] Uuvana 2 server. There are many bots in the server which may contribute?

**Comment by pukegunk** [comment]
What information can I provide? Sorry, this is my first bug report.

**Comment by PlannjaRikard** [comment]
I have the same issue.
Attached is my system information:
[DxDiag.txt](https://github.com/Uuvana-Studios/longvinter-windows-client/files/8348928/DxDiag.txt)

**Comment by pukegunk** [comment]
Gladly!

Can I get some questions to be answered? I'll fill in the blank.

pukegunk
