### ISSUE TITLE
Re-Spawned In Another Player's House

### ISSUE THREAD

**Issue by ExhaustedPige0n** [Uuvana-Studios/longvinter-windows-client#562]
While it was a lovely house I respawned in, it was not mine. I couldn't leave the fenced in area due to the fences being locked. I died again hoping to spawn somewhere else, but I did not. Dying seems to respawn me in a house not my own. I was hoping upon death I would respawn in my home or at the starting docks. Currently playing Beta 1.0.1. on [EU] us server 7.

![20220323132552_1](https://user-images.githubusercontent.com/102249822/159762531-e026c34f-c8dd-48da-b653-ab82371b59ae.jpg)
![20220323132659_1](https://user-images.githubusercontent.com/102249822/159762533-b2cb5305-a4b3-4c86-9e7b-2f2bef649eb3.jpg)

**Comment by Yukita7** [comment]
yes, there are people appearing inside my house, and they ateal my chests. please fix it this :/

**Comment by faketucker** [comment]
Since the latest stable version update, players should no longer respawn in other people's houses.
