### ISSUE TITLE
if you disconnect from server when your in the water, when you log back on you're unable to move.

### ISSUE THREAD

**Issue by GoogalyMoo** [Uuvana-Studios/longvinter-windows-client#565]
the bug is when you log out or get disconnected when your in water, once rejoined you're no longer able to move. I found this bug when the server crashed on me as I was doing a loot run back to my base. once I got to my base the server disconnected me. when I logged back in I was re-winded back to when I was standing in a shallow part of water. I was unable to move so I had to  /kill , ran back and only retrieved item that were in my bag. This is the second time I have encountered this bug 
d
**To Reproduce**
1. stand in water, or be in water when the server randomly disconnects you.
2. relog back into server
3. player is unable to move but spins in spot.
4. /kill to load back at base

**Expected behavior**
if your player is standing in water when joining server, you could be free to move.

**Screenshots**
i was just standing in the water lol

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0.1]
 - Steam Version [e.g. 1.0.1]

**Additional context**

**Comment by faketucker** [comment]
Tested. You can reproduce this by just standing in the water, then disconnecting and logging back in again, or you can try Alt + F4 while you are standing in the water.

**Comment by Yukita7** [comment]
this happened to me yesterday!

**Comment by Mikooboy** [comment]
Added a check if the player is in water when spawning. Should be more reliable in the next update
