### ISSUE TITLE
Experimental Server No Health Bar

### ISSUE THREAD

**Issue by J2HPHIRE** [Uuvana-Studios/longvinter-windows-client#567]
**Describe the bug**

Experimental Server at the moment has a bug where you cannot see the health bar and you can also not see the amount of ammo you currently have. Seems like this bug is only on this server at the moment

**Comment by Mommainspired** [comment]
This same thing is happening to me. You can't see if you need to eat or stand by a campfire. It is horrible if you are trying to go get loot in the winter area. Also, we died because of this in the water and we could not pick up our loot.

**Comment by sirNugg3ts** [comment]
Do not report bugs on the experimental server, since the experimental is changing everyday. Anything ask on discord about this branch so that the devs can hear you. Here we only log bugs with the public branch

**Comment by Mommainspired** [comment]
Thank you. Wasn’t sure. I had seen the link on discord asking to report
bugs on GitHub and followed the link there. Thanks for the clarification.
