### ISSUE TITLE
Trees

### ISSUE THREAD

**Issue by lrogier** [Uuvana-Studios/longvinter-windows-client#569]
**Is your feature request related to a problem? Please describe.**
It is very frustrating to be chopping down large trees for extended periods of time only to receive less wood than that of a small tree.

**Describe the solution you'd like**
Smaller trees should provide less wood because they are quicker to chop down, while larger trees should give more wood.

**Describe alternatives you've considered**
It is potentially because I am using a hatchet and not a chainsaw that I am frustrated. Perhaps the efficiency increases when you use the chainsaw so you get more wood out of either tree? I don't have a lot of experience yet with the chainsaw.

**Additional context**
I do however love the variety of trees. They are pretty. It would always be neat to see more.

**Comment by Bunnbunnnn** [comment]
Documented on forum already as "- make wood grinding be easier / large trees drop more than small"
