### ISSUE TITLE
EXPIREMENTAL SERVER UNIVERSAL HOUSE CODE! MAJOR ISSUE!

### ISSUE THREAD

**Issue by J2HPHIRE** [Uuvana-Studios/longvinter-windows-client#570]
If you type in this code it works on all houses and the people can pick up your entire base. I have tested this on a house north of me and it let me in. Im not going to putthe code in this report but I need a mod to message me on the discord as soon a possible!

**Comment by aidannnd** [comment]
I also had this issue, but people could pick up turrets and fences without entering into the house, picking up at a longer range than the turrets can shoot.

**Comment by sirNugg3ts** [comment]
> Im not going to putthe code in this report but I need a mod to message me on the discord as soon a possible!

Then open a ticket on discord. Since this post does not have any information on the bug im closing the issue

**Comment by Jalsson** [comment]
This issue is now fixed :)
