### ISSUE TITLE
dun go this server US NYC FLUSHING MEADOWS PVP-WIPED 3/18

### ISSUE THREAD

**Issue by bibiangel** [Uuvana-Studios/longvinter-windows-client#571]
THIS SERVER PPL HAVE PROBLEM , PLAY ALREADY 3 TIME , NOW CANNOT GO IN , SAY GIVE BLOCK ????
WHAT?????? I PLAY FULL UPDATE HOUSE 2 ALREADY , SAY CANNOT GO IN THIS SERVER?

**Comment by bibiangel** [comment]
THIS PPL INSIDE KEEP DISTURBING AND TEARING DOWN YOUR HOME

**Comment by faketucker** [comment]
This is not an enhancement, and it's not an official server, so we can't give you a reason why you were banned.
