### ISSUE TITLE
lost many items and my house become a tent again

### ISSUE THREAD

**Issue by chavis91** [Uuvana-Studios/longvinter-windows-client#573]
**Describe the bug**
lost many items and my house become a tent again, i disconected and had 5 chests, when i reconeccted i only had 2 and my house became a tent again, also lost many fences

**Desktop (please complete the following information):**
 - OS:windows 
 - Game Version 1.0.1
 - Steam Version  1..0.1

**Comment by faketucker** [comment]
Duplicate of #508
