### ISSUE TITLE
Duplicate item bug

### ISSUE THREAD

**Issue by Guardiansp22** [Uuvana-Studios/longvinter-windows-client#574]
**Describe the bug**
When placing an item down such as a lamp post or a turret if you left click mutliple times quickly it will duplicate the item.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
You can duplicate any placable thing by spamming right click to pick it up, and it will go to the equipment slot and drop as a bag.

**Comment by faketucker** [comment]
Both fixed. You can no longer spam left click to place items at the same spot and can't duplicate by spamming right click to pick them up.
