### ISSUE TITLE
cant take my food from the fire

### ISSUE THREAD

**Issue by Sky0ver21** [Uuvana-Studios/longvinter-windows-client#577]
**Describe the bug** 

**To Reproduce**
1. Go to 'fire place' our 'oven' 
2. Click on 'the iten you want to cook'

**Expected behavior**
when the food is finished you cant take it from the oven our fireplace

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0.1]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by moatib** [comment]
same for me

**Comment by faketucker** [comment]
Sven has already released a hotfix for this.
