### ISSUE TITLE
Boxes dissapeared after server/client update 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by fheinis** [Uuvana-Studios/longvinter-windows-client#578]
![image](https://user-images.githubusercontent.com/11536744/160149012-1a98409e-bce0-4a72-bbdb-cd1e99980161.png)

Updated both client and server to latest version and some boxes disappeared in my house as you can see 1 is now floating

**Comment by faketucker** [comment]
Duplicate of #527
