### ISSUE TITLE
 beta 1.0.2 - new server messages can get stuck

### ISSUE THREAD

**Issue by cheerp** [Uuvana-Studios/longvinter-windows-client#579]
The freshly introdoced (and great!) server admin messages can stay stuck on the screen.

**To Reproduce**
1. send a message
2. send a second message before the first disappears
The two messages are both displayed on screen, but only the second vanishes after a few seconds.
The system forgot the old one, it stays on screen for all players.

**Expected behavior**
Plan for multiple messages: all non-expired messages appear on the screen, one below the other
Messages expire after a few seconds and disappear.

**Desktop (please complete the following information):**
Win 10 
LV beta 1.0.2
fresh updated steam

**Additional context**
Great feature! Thanks

**Comment by faketucker** [comment]
Tested. If you send the second message before the first one vanishes, the first one will stay on the screen and disappear when you rejoin the server.

**Comment by Jalsson** [comment]
Fixed this issue and it will be fixed in next update
