### ISSUE TITLE
Uuvana 1 (for hongkong server probably) can't connect to the server

### ISSUE THREAD

**Issue by SaeSHD** [Uuvana-Studios/longvinter-windows-client#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

AFTER TRYING TO CONNECT TO THAT SERVER IT BRINGS ME BACK TO THE MAIN MENU, THERE ARE 0 PEOPLE CONNECTED TO IT SO IT'S PROBABLY HAPPENING TO OTHER PLAYERS PLAYING ON THAT SERVER.

**Comment by sirNugg3ts** [comment]
1st, please follow the template for a bug.
2nd, is this still happening? Seems like a version mismatch only

**Comment by sirNugg3ts** [comment]
No answer was given. Closing issue
