### ISSUE TITLE
NO VEO EL AGUA

### ISSUE THREAD

**Issue by freedharmony** [Uuvana-Studios/longvinter-windows-client#581]
No veo nunca el agua.

Otra opción es que añadáis que se pueda guardar los servidores en los que entras, ya que si no te acuerdas del nombre perderas tu progreso

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
