### ISSUE TITLE
Bug with object

### ISSUE THREAD

**Issue by Manuel13112002** [Uuvana-Studios/longvinter-windows-client#583]
Interaction with object
When I connect to a server, when I open a chest to take an item, once selected it disconnects me from the server, so impossible to play

To Reproduce
1. go to your inventory or chest 
2. click on an item
3. you have been disconnected from the server

Expected behavior
you will need some items and a box to realize the problem

Desktop (please complete the following information):
 - OS: windows 10
 - Game Version : longvinter beta 1.0.2
 - Steam last version

Additional context
thanks !

**Comment by sirNugg3ts** [comment]
Server is not updated
