### ISSUE TITLE
Again, we have a copy bug

### ISSUE THREAD

**Issue by tom4712** [Uuvana-Studios/longvinter-windows-client#584]
**There is a bug that sets up a workbench in the tent and copies the tent and workbench when hitting the tent.
After the bug, they said they installed two tents even if they hit the tent
Only the general tree is used for house upgrades and the scent tree is gone**

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
