### ISSUE TITLE
Glitching after glitching into an area I couldn't get out ot 

### ISSUE THREAD

**Issue by jldurham6** [Uuvana-Studios/longvinter-windows-client#589]
I glitched into a bench of bushes.  Ever since then I glitch ever 15 or 20 seconds and rubberband  to different areas.

**Comment by faketucker** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
