### ISSUE TITLE
Reset everytime I rejoin

### ISSUE THREAD

**Issue by Bellatrix8377** [Uuvana-Studios/longvinter-windows-client#59]
**Describe the bug**
Everytime I join a server, my money, compendium and inventory resets; I come off to have a break and come back and its been wiped on multiple servers

**To Reproduce**
1. disconnect from the server
2. reconnect to a server

**Expected behavior**
My inv, comp' and money saves not losing over £35k :(

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
please give us a recording of this happening, with information about which server this is happening in

**Comment by Plant2** [comment]
I am having this same issue on [US] uuvana6. I played for a few hours without this issue and then lost all player progress when i relogged. I have also had an issue with randomly being teleported to different locations on the map.

**Comment by zidoss** [comment]
happened to me on (US) uuvana6. also couldn't place my tent down

**Comment by Bellatrix8377** [comment]
I dont have a software to show a video but everytime I die or join a server ive been on, its as if the game see's me as a new player and resets me constantly. I don't even spawn at my house, just at the starting dock.

This has happened on Blue Storm 1, EU 1 and Biffots server

**Comment by Grips001** [comment]
Same issue Uuvana 5 US server. My house is still here, but money and progress have completely disappeared. Disconnect/Reconnect spawns me at the dock with nothing.
