### ISSUE TITLE
URGENT - UUVANA 4 HACKER "HELLO FROM NOOB" GLOBAL MESSAGE, SPAWNING IN HOUSE, KILLING

### ISSUE THREAD

**Issue by feedmeimstoned** [Uuvana-Studios/longvinter-windows-client#590]
**Describe the bug**
Noob is hacking, spawning in my house, killing me, I can't kill him. When I leave my house, he kills me from inside. Stealing all my stuff. I don't know how to get rid of him, and he's spawn killing me. He's sending global messages saying "HELLO IM NOOB"

![20220325_200242](https://user-images.githubusercontent.com/100816131/160222459-26d4f3cf-2ace-4f2c-90a0-146c814ec460.jpg)

Red shirt, won't leave my house.

**Comment by feedmeimstoned** [comment]
every time i try to load ammo, it eats it. doesn't load. and when i try to chainsaw him, he doesnt die.

**Comment by feedmeimstoned** [comment]
![Uploading 20220325_200900.jpg…]()

**Comment by feedmeimstoned** [comment]
![20220325_201352](https://user-images.githubusercontent.com/100816131/160222791-b970d2c1-da0e-4612-8b83-2b8729e9033e.jpg)

**Comment by faketucker** [comment]
This GitHub issues page is for reporting bugs, and this is not a bug.

If you want to report a hacker please use the ticket system in our Discord server. To open one follow the instructions:
1. Go to #☎-contact;
2. React to 👮 which is referent to Bot Reporting;
3. Inform which server you were playing on (Official only);
4. Post all images/videos and any information you have on the hacker.
https://i.imgur.com/NvIrIHX.png
