### ISSUE TITLE
Compendium List not updating.

### ISSUE THREAD

**Issue by AriaChantley** [Uuvana-Studios/longvinter-windows-client#592]
Encountered the bug during my peacock hunting session. It was my first time hunting peacocks and was able to get the normal and pristine feathers of it. I sold the feathers after gathering it, but when I checked the compendium it was updated.

 - OS: Windows
 - Game Version: Current
 - Steam Version: Current

**Additional context**
It was my first time playing on a new server and other things on the compendium except for the peacock feathers are updated on the compendium, will try and hunt peacocks again to see if it will register or not.

**Comment by faketucker** [comment]
What server are you playing on? Did you disconnect before you sold the feathers?

**Comment by AriaChantley** [comment]
This issue was okey now, although unlocking it was delayed? It didnt popped
of when i got the last feather and fishes. But later when I was playing if
unlocked, but it was like after an hour when I last picked it up.

**Comment by faketucker** [comment]
It seems to be an issue with the server, not the game. Thanks for the info!
