### ISSUE TITLE
stuck in safezone

### ISSUE THREAD

**Issue by chavis91** [Uuvana-Studios/longvinter-windows-client#595]
**Describe the bug**
i fall in water in a safezone , i cant move because of rocks, also cant die or whatever
**To Reproduce**
1. Go to 'the place with many vending machines'
2. fall near rigth lamp
3. got stuck between rocks
4. cant move or even cant die
**Expected behavior**
cant move, die or even play also cant use weapor or something to get shot by turrets

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2785014238
**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Game Version  1.0.2
 - Steam Version  1.0.2

**Additional context**
plz help i cant even play

**Comment by faketucker** [comment]
You can type /kill in the chat or use Alt + K to get out of there
