### ISSUE TITLE
screen zooms in and out when clicking?

### ISSUE THREAD

**Issue by ambercarver160** [Uuvana-Studios/longvinter-windows-client#596]
whenever i go to inventory and click on items or if i click anything below the bottom half of my screen it will just not allow me to do what i wanted with the click and will also make my screen go black and zoom in super close then when i click the screen anywhere again it zooms back out like normally and i try to proceed and it keeps happening

**Comment by faketucker** [comment]
Weird. I can't replicate this. There might be some problems with your PC or your input devices. Can you provide me with a video?

**Comment by Mailyr** [comment]
Hi Amber,

I'm having the same problem as you but only happened to me in the Menu.
I "fixed" it by pressing ALT+ENTER and changed the settings I needed, I don't know if this tip could help you.

**Comment by faketucker** [comment]
I'll close this issue since there's not enough info.
