### ISSUE TITLE
Cannot update tent to hosue

### ISSUE THREAD

**Issue by remmath16** [Uuvana-Studios/longvinter-windows-client#598]
**Describe the bug**
I am not able to upgrade my tent to a house

**To Reproduce**
1. placed tent
2. placed work bench
3. harvested and deposited 100 wood required
4. selected update
5.  typed in 4 number code and selected a color (i tried all 4 colors and multiple passwords)
6. Update button remained greyed out i could not upgrade house 
7. tried all again on 3 total servers for 2 days

**Expected behavior**
I expeted the tent to update and change into the small house

**Screenshots**
I do not have screen shots

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version [ most recent (just downloaded yesterday 3/25/2022)
 - Steam Version [e.g. 1.0]

**Additional context**
none

**Comment by faketucker** [comment]
The house needs a 5-digit code.
