### ISSUE TITLE
Arena Bug

### ISSUE THREAD

**Issue by AllenJamesS** [Uuvana-Studios/longvinter-windows-client#599]
**Describe the bug**
When near the southern wall of the arena and aim in with a weapon the turrets will shoot through the wall.

**To Reproduce**
1. Go to 'Arena'
2. Click on 'right-click/right mouse button'
4. See error - being shot through the wall by turret 

**Expected behavior**
shot by turrets surrounding the arena 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Game Version [1.0.2]
 - Steam Version [1.0.2]

**Additional context**

**Comment by faketucker** [comment]
Tested. Turrets should only be active on the top platform, not in the arena.
