### ISSUE TITLE
Features for Tents/Homes

### ISSUE THREAD

**Issue by sirNugg3ts** [Uuvana-Studios/longvinter-windows-client#6]
- Interacting with a tent/home brings up a menu which displays information about who owns the home/how old the home is. This could also be used as a way to allow players to destroy unwanted homes/tents by having the option in that menu.

- For public servers there may need to be a tent limit in place (2) and make it a customizable option for custom servers so we can allow as many as we want.

- Mailbox which can notify the player when a player leaves them mail? Display an "!" symbol above the box when it contains item(s). Be sure to Include a way to mute notifications from the mailbox.

[Discord Message](https://discord.com/channels/846308806870695967/873486241482559508/946767178668060702)

**Comment by sirNugg3ts** [comment]
House customisation like:
- Modify the outside of the house (Shape, color, etc.)
-  Modify the inside of the house using upgrades or building (Size, shape, (functional) furniture)

[Discord Message](https://discord.com/channels/846308806870695967/873486241482559508/946782966967853126)

**Comment by Bunnbunnnn** [comment]
> * Interacting with a tent/home brings up a menu which displays information about who owns the home/how old the home is. This could also be used as a way to allow players to destroy unwanted homes/tents by having the option in that menu.
Already documented "- Interacting with house gives information about owner "


> * For public servers there may need to be a tent limit in place (2) and make it a customizable option for custom servers so we can allow as many as we want.

Already implemented 

> * Mailbox which can notify the player when a player leaves them mail? Display an "!" symbol above the box when it contains item(s). Be sure to Include a way to mute notifications from the mailbox.

Mail already documented "- ingame mail w/ notification system for it"

> [Discord Message](https://discord.com/channels/846308806870695967/873486241482559508/946767178668060702)

**Comment by Bunnbunnnn** [comment]
> House customisation like:
> 
> * Modify the outside of the house (Shape, color, etc.)
> * Modify the inside of the house using upgrades or building (Size, shape, (functional) furniture)
> 
> [Discord Message](https://discord.com/channels/846308806870695967/873486241482559508/946782966967853126)

Already documented as "- More house variation / customization / sizes, shapes , color, more rooms "
