### ISSUE TITLE
Stuck between rocks

### ISSUE THREAD

**Issue by Hilolen** [Uuvana-Studios/longvinter-windows-client#601]
Moved in between 4 rocks, and was unable to get back out. Tried disconnecting, going into a different server and then back into original server, and restarting the game. Whenever I enter the server, I respawn between the rocks.

Go to server [US] uuvana 1
Go to Heimo & Rose
walk down and to the left to the yellow house by the water. Water will be below you. 

Just stuck between a rock and a hard place. 
![stuck](https://user-images.githubusercontent.com/97799466/160268109-6a712de9-7a1e-4d59-8f39-c72278b81f9c.PNG)

**Comment by Hilolen** [comment]
If someone could kill me so I can respawn, I'd be forever grateful!

**Comment by faketucker** [comment]
You can type /kill the chat or use Alt + K

**Comment by Hilolen** [comment]
Thank you so much!
