### ISSUE TITLE
can't interact with my bonfire

### ISSUE THREAD

**Issue by isazzel** [Uuvana-Studios/longvinter-windows-client#602]
**Describe the bug**
I placed a bonfire inside my tent, since then it was already bugged. Now I developed the tent to a house and it's still bugged; it gives me energy but I can't cook or move it. Then I bought one more bonfire and it works fine, but that one it's bugged

**To Reproduce**
1. Go to the house
2. Click on the bonfire
3. See error

**Expected behavior**
I expect to interact with the bonfire when I click it (cook with it, move it...)

**Screenshots**
In this case I don't think this is applicable, the bonfire it's juts inside the house 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Game Version 1.0.2
 - Steam Version: I don't know :( but I bought it on steam online 

**Additional context**
Don't know what else to say

I hope it helps. Thanks!

**Comment by faketucker** [comment]
Pretty sure it's the same bug as #354. Thanks for reporting!
