### ISSUE TITLE
House and everything within disappeared overnight :(

### ISSUE THREAD

**Issue by Chey1303** [Uuvana-Studios/longvinter-windows-client#603]
**Describe the bug**
Just logged in today to one of my houses being completely gone, but while I'm in the other one beside it I can still see the items in my other house? It's so confusing. Worst part is I had all of my good loot in that house and had almost upgraded the electric. The servers need a hard fix, way too many bugs and crashes. I was playing on two other servers and every time I would try placing a house in this one area I would be slingshotted back to the outpost and the tent would be gone. It's things like this that make me not even wanna play this game anymore, if I have to start from square one every day I load back in. I understand it's in beta and there's bound to be issues but It's really frustrating. The server this happened on is BaconLife - US East - Updated 3/18 

**To Reproduce**
1. Put a house or tent down
2. Wait a day
3. Log back in
4. Your house and belongings will no longer be there

**Expected behavior**
I expected my house and storage containers within to still be there. 

**Screenshots**
![Longvinter problem 1 ](https://user-images.githubusercontent.com/102265564/160298537-d1855b99-bff5-4479-b345-1bfa9870c0be.jpg)
![Longvinter problem](https://user-images.githubusercontent.com/102265564/160298539-a076df7b-6b81-4326-821f-f71ba8896636.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.2
 - Steam Version Latest Update

**Additional context**
I would like to know if I'll be able to get my things back.

**Comment by sirNugg3ts** [comment]
Unfortunatly we cannot offer support on non-official servers. If you can replicate this on an Official server please let us know !
