### ISSUE TITLE
Extension to issue #600 

### ISSUE THREAD

**Issue by isnowcloud** [Uuvana-Studios/longvinter-windows-client#604]
**Describe the bug**
Lost all houses/ everything on server uuvana 7. 
Lost cause at this point because other players have already settled into the spot fully built houses were built on. 
Also have lost half of the containers full of items and items in the boxes that did not disappear. 
While setting things down in a fenced in area where "only players are able to pick them up" they continue to go missing after logging in and out of the game. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Thanks for the info! I'll put this as a comment there. If you have any more info, please comment there to reduce the duplication.
