### ISSUE TITLE
Unable to zoom in/out after opening Admin panel

### ISSUE THREAD

**Issue by ewrogers** [Uuvana-Studios/longvinter-windows-client#606]
**Describe the bug**
The zoom in/out functionality via mouse wheel does not seem to work after opening the Admin panel and closing it.

**To Reproduce**
1. Zoom in and out normally
2. Open the in-game server Admin Panel
3. Click on "Show names"
4. Close the window via the X button
5. Wave to stop showing names
6. Try to zoom in/out again

**Expected behavior**
Zooming in and out should work properly even after closing the Admin panel

**Desktop (please complete the following information):**
 - OS: SteamDeck via Proton 7.0
 - Game Version 1.0.2
 - Steam Version Latest

**Comment by faketucker** [comment]
Tested. You can't zoom in/out after opening the admin panel. This might happen because the game wants us to be able to scroll through the log without zooming in/out.

**Comment by Mikooboy** [comment]
Allowed the scroll to control zoom again after closing the admin panel. Should be fixed in the next update.
