### ISSUE TITLE
turret bug No harm

### ISSUE THREAD

**Issue by ncezj** [Uuvana-Studios/longvinter-windows-client#607]
![940{_SC6)_HVC@U 3(ELTIP](https://user-images.githubusercontent.com/102506850/160342387-c4e1a1bf-7707-42f8-b438-38e69418c09f.png)
![940{_SC6)_HVC@U 3(ELTIP](https://user-images.githubusercontent.com/102506850/160342401-b5563c86-d641-4546-8228-f56d6b1a136b.png)
@

**Comment by faketucker** [comment]
Duplicate of #377
