### ISSUE TITLE
Drinking Energy Drink Changing Swim Speed

### ISSUE THREAD

**Issue by qweekertom** [Uuvana-Studios/longvinter-windows-client#61]
**Describe the bug**
When drinking an energy drink, while swimming, the player will swim as fast as the boosted land running speed.

**To Reproduce**
1. Swim in the water
2. Drink an energy drink

**Expected behavior**
Increase swim speed by x% or possibly not affect swim speed.

**Additional context**
This may be an intended feature, but it just seems like a bug.

**Comment by sirNugg3ts** [comment]
Duplicate of #11
