### ISSUE TITLE
Tents that had already decayed reappeared

### ISSUE THREAD

**Issue by Ksenia2703** [Uuvana-Studios/longvinter-windows-client#613]
someone put up their tent after the construction of my house
![WhatsApp Image 2022-03-28 at 23 01 44](https://user-images.githubusercontent.com/90321080/160439872-9a8a83d0-c0ef-4201-a20c-ee42a694eb42.jpeg)
![Screenshot_2](https://user-images.githubusercontent.com/90321080/160439909-948004a7-a678-4503-b1fc-a74858ad8551.png)

**Comment by Luxembourg89** [comment]
![insidelongvinter](https://user-images.githubusercontent.com/102540175/160442707-5e62de0e-71e5-404d-814e-1c55d4cde33a.jpg)
![outsidelongvinter](https://user-images.githubusercontent.com/102540175/160442801-e9b42f89-248b-4cb2-a2a9-67124fb94ba4.jpg)
half my base is gone, older section

**Comment by faketucker** [comment]
Tents that are already decayed seem to glitch and be visible.

**Comment by CachorroQuente17** [comment]
Same here
South America 1

![prove 2](https://user-images.githubusercontent.com/75539740/160490048-8475b58f-69cf-4905-826a-a21adffef95a.png)
![prove 3](https://user-images.githubusercontent.com/75539740/160490055-c5195acb-7498-499b-a66f-c6070deeb314.png)
![prove1](https://user-images.githubusercontent.com/75539740/160490057-d4050f87-5b7e-481d-809d-2986f2eb7aab.png)
re
