### ISSUE TITLE
turretts disappeared upon placing 

### ISSUE THREAD

**Issue by gracenlee940** [Uuvana-Studios/longvinter-windows-client#614]
Thank you for fixing the issue where turrets do not work between 2 houses. 

However, I gave my turret to other players to place on their property, which I already entered his house with a password and so did he, it suddenly disappeared. We tried to reenter the server and restarted the game, it was gone. Is there a glitch that turrets from other ppl vanish if a player tries to place it?

**Comment by gracenlee940** [comment]
Also when 2-3 people try to fish in the same fish spawning, one of them randomly fly off from the screen toward the ocean (it looks ridiculous lol) and won't be able to fish for few mins after.

**Comment by faketucker** [comment]
> Also when 2-3 people try to fish in the same fish spawning, one of them randomly fly off from the screen toward the ocean (it looks ridiculous lol) and won't be able to fish for few mins after.

The telescopic rod somehow still has a collision. The devs are already aware of it and might fix it soon.
