### ISSUE TITLE
cant close popup (ex. vending machine, backpack)

### ISSUE THREAD

**Issue by koreayoutuber** [Uuvana-Studios/longvinter-windows-client#615]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #410
