### ISSUE TITLE
Backpacks in areas keep refilling with rifles and ammo.

### ISSUE THREAD

**Issue by AlmondSlinky519** [Uuvana-Studios/longvinter-windows-client#619]
On the server uuvana 4 at sgt. lakes outpost there are backpacks that keep refilling with ammo and rifles which you can in turn sell and get unlimited money as well as ammo and guns. I am not sure if this is meant to be in the game but it seems like a bug.

**Comment by faketucker** [comment]
Might be a hacker messing up with the server, and I can't find those backpacks you said. I'm going to close this since it's probably not a bug
