### ISSUE TITLE
Haddock either can't be caught or is way too rare.

### ISSUE THREAD

**Issue by Harnar** [Uuvana-Studios/longvinter-windows-client#62]
**Describe the bug**
Nobody has been able to find the Haddock yet. Catfish, Arctic Char, and Cod are rare but still have been relatively easy to find, but Haddock has suddenly somehow become mythical.

**To Reproduce**
1. Try to catch a Haddock
2. Fail to ever catch a Haddock

**Expected behavior**
Haddock, as a common and very cheap fish should be easy to find, whether it be in the snowy north or the normal fishing spots.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version 1.0.0
 - Steam Version 1.0.0

**Additional context**
It's the last thing needed to complete my compendium!

**Comment by sirNugg3ts** [comment]
Fixed on last update
