### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by sote15** [Uuvana-Studios/longvinter-windows-client#626]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
I'm trapped. I can't move. I can't even die. Get me out of here.
![DIE](https://user-images.githubusercontent.com/102611583/160654545-2a869a53-7a31-4259-bbaa-c2795e5fe314.PNG)

**Comment by faketucker** [comment]
You can type /kill in the chat or use Alt +K
