### ISSUE TITLE
I have found Unlimited electric power without house   bug.

### ISSUE THREAD

**Issue by monkeycheatcom** [Uuvana-Studios/longvinter-windows-client#627]
1. build 2 houses stay together as screen shot.
2. upgrade 1st house as wind & sun.
3. upgrade 2nd house as fuel house.
4. put fuel in house. so let 2nd house generate electirc.
5. set ur machine gun. as many as u can. (like 6 or 7 turret)
6. dismantle ur 2nd house(fuel house) during daytime
7. now you will see all turrets are still working with powered  even you dont have house!!

what a cool unlimited power without house 😮

i think dev didn't set condition for 'when player dismantle house, how will calculate power level'

**Comment by faketucker** [comment]
Tried many times. I really can't find a way to replicate this. Yes, the turrets are working, but only visually. Maybe when the server restarts, they'll be disabled.
