### ISSUE TITLE
Lootable containers are able to be picked up

### ISSUE THREAD

**Issue by woorim00** [Uuvana-Studios/longvinter-windows-client#629]
There is a bug where you can get the box itself before the supply box disappears. Please check.

**Comment by faketucker** [comment]
Tested. You can right click to pick up the lootable container before it disappears.

![image](https://i.imgur.com/SyBg7S1.png)

**Comment by natamru** [comment]
Can't this be a feature instead, you can loot the container itself, it doesn't really become game breaking.
