### ISSUE TITLE
Setting name, password, and player count in Game.ini not working

### ISSUE THREAD

**Issue by bearlystraight** [Uuvana-Studios/longvinter-windows-client#63]
**Describe the bug**
The server I'm running shows up in LAN and in game. However even when the Game.ini says what I need it to it does not effect the defaults of the server. The server will show up in LAN and in game as uuvana 1, without a password.

**To Reproduce**
1. Go to Game.ini
2. Change to your liking
3. Start your server

**Expected behavior**
I expected to see my named, private server in the list. But I had a random person join.. which is when I realized the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/93161931/155903802-352dbbaf-cc75-41c7-b359-2abe80536ebf.png)
![image](https://user-images.githubusercontent.com/93161931/155903770-489847ff-f154-4967-bd7f-4e081cb22b7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version v020

**Comment by koutetsusteel** [comment]
Are you 100% sure that the Game.ini that you changed is the same one in the subfolder of the server?

**Comment by bearlystraight** [comment]
@koutetsusteel Yes, you have to make the Game.ini file manually and I made it exactly as it's shown in the tutorial on how to run the server.

**Comment by sirNugg3ts** [comment]
Are you sure its in the right folder?

**Comment by bearlystraight** [comment]
@sirNugg3ts Yes

**Comment by couquino** [comment]
Same here for me, I tried different values and it keep getting the same logs as the author

**Comment by sirNugg3ts** [comment]
I've setup a couple of servers and this has never happened, the odds of a misconfiguration are higher than a bug in the server. If you can give steps on how to do this after following exactly what the guide says open a new issue
