### ISSUE TITLE
can't type password

### ISSUE THREAD

**Issue by garqm** [Uuvana-Studios/longvinter-windows-client#630]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![unknown (5)](https://user-images.githubusercontent.com/100501981/160828236-1b67a6fd-1319-472b-a47a-e1d87ac757df.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #164
