### ISSUE TITLE
tent wont upgrade

### ISSUE THREAD

**Issue by PokeyGhost** [Uuvana-Studios/longvinter-windows-client#632]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
tent would not let me upgrade after wood was collected tried 4 different times in different locations still nothing

**Comment by PokeyGhost** [comment]
when i place my tent down and put the workbench inside, i collect the 100 wood required and it says ready for upgrade. Then the option for a code lock and house color comes up, but the other options are grey and not available

**Comment by faketucker** [comment]
You have to fill in a 5-digit code in order to upgrade your house.

**Comment by PokeyGhost** [comment]
i did that and it still doesnt work, ive tried numerous times and the options are still grey

**Comment by faketucker** [comment]
Make sure your password is 5-digits, not less. And if it's not working, please send me a screenshot.
