### ISSUE TITLE
Sea Glitch Cannot Fish

### ISSUE THREAD

**Issue by piakjummpy** [Uuvana-Studios/longvinter-windows-client#634]
![Screenshot (45)](https://user-images.githubusercontent.com/102721716/161003941-44804ff5-a731-40db-9aca-54867df96b8c.png)
**Describe the bug**
I cannot fish at all because the sea/lake is completely blank (just white blank) on every server I've tried, I can swim in it but there's no water animation just white blank, with no fishing zone anywhere.

**To Reproduce**
1. Go to any server
2. Click on any server
3. Scroll down to near the sea area
4. See an error

**Expected behavior**
I was expecting to see blue sea water animation with fishing zones for me to fish.

**Screenshots**
![Screenshot (45)](https://user-images.githubusercontent.com/102721716/161003395-da7a9f6e-0161-47eb-bc70-c3d3187eceac.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version 1.0.2
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Have you tried toggling DX11 water in the settings?
![image](https://user-images.githubusercontent.com/28383557/161004854-0907c9b5-0c2c-4db0-b4f1-0382f9660ca9.png)

**Comment by piakjummpy** [comment]
Thanks, that fixed it!! My bad, I didnt know about the toggle DX11 water, but it does make the game more laggy when i turn it on, it is my own end's problem?

**Comment by faketucker** [comment]
> Thanks, that fixed it!! My bad, I didnt know about the toggle DX11 water, but it does make the game more laggy when i turn it on, it is my own end's problem?

Could be on your end. Can I have your PC specifications?

**Comment by piakjummpy** [comment]
my specs:
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.85 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by faketucker** [comment]
How about your graphics card? Seems like your PC might only meet the minimum requirements. I suggest you turn these options down. It may help you.

![image](https://user-images.githubusercontent.com/28383557/161046749-1ab9c9b6-0619-4e48-8dee-e337eafc405b.png)

**Comment by piakjummpy** [comment]
Ahh I see I've lowered them but it's still pretty laggy and I can fish now but the weird thing is i cant seem to catch any fish (i was pressing E). My graphics card is UHD Graphics 620 or GeForce MX150 w/ 2 GB GDDR5 VRAM and Optimus. (Sorry for asking so many things.)

**Comment by faketucker** [comment]
> Ahh I see I've lowered them but it's still pretty laggy and I can fish now but the weird thing is i cant seem to catch any fish (i was pressing E). My graphics card is UHD Graphics 620 or GeForce MX150 w/ 2 GB GDDR5 VRAM and Optimus. (Sorry for asking so many things.)

Oh, your graphics card does not meet the minimum requirements. You can see the comparison between your graphics card and the minimum requirements for graphics cards [here](https://gpu.userbenchmark.com/Compare/Nvidia-MX150-0-vs-Nvidia-GTX-950/m332822vs3510) and [here.](https://gpu.userbenchmark.com/Compare/Nvidia-MX150-0-vs-AMD-HD-7970/m332822vs2163) And you have to press E repeatedly (spamming the E) to catch the fish :)

**Comment by piakjummpy** [comment]
> > Ahh I see I've lowered them but it's still pretty laggy and I can fish now but the weird thing is i cant seem to catch any fish (i was pressing E). My graphics card is UHD Graphics 620 or GeForce MX150 w/ 2 GB GDDR5 VRAM and Optimus. (Sorry for asking so many things.)
> 
> Oh, your graphics card does not meet the minimum requirements. You can see the comparison between your graphics card and the minimum requirements graphics cards [here](https://gpu.userbenchmark.com/Compare/Nvidia-MX150-0-vs-Nvidia-GTX-950/m332822vs3510) and [here.](https://gpu.userbenchmark.com/Compare/Nvidia-MX150-0-vs-AMD-HD-7970/m332822vs2163) And you have to press E repeatedly (spamming the E) to catch the fish :)

I see, can't do much about that then but thanks for the fishing tip! I really appreciated the help since I don't know much about these things, thanks again faketucker!! 👍
