### ISSUE TITLE
Shop Window Wont close

### ISSUE THREAD

**Issue by Siykitkat** [Uuvana-Studios/longvinter-windows-client#635]
![image](https://user-images.githubusercontent.com/47679649/161008991-62c15a40-64df-438c-afe0-7827d0a618b6.png)
well im kinda far from a shop/vending machine and its still showing up
hitting the cross or escape hasn't done anything so. this is my life now

**Comment by faketucker** [comment]
The only way is to close the game and reopen it again.

**Comment by Siykitkat** [comment]
Hitting the cross even brings up the "pause screen"

**Comment by faketucker** [comment]
Duplicateion of #410
