### ISSUE TITLE
I'm trapped

### ISSUE THREAD

**Issue by nikonyanya** [Uuvana-Studios/longvinter-windows-client#638]
**Describe the bug**
I had placed a tent the day before yesterday. I didn't log in yesterday. Today the tent was gone and someone had built a house where it was. I figured it was just gone due to a bug with timing or something. However once I died, I respawned in what I thought was my house and that most of the containers disappeared again, however I think that I maybe spawned inside the house where my tent was. I didn't spawn in the correct place, i was in the containers that were on the wall so I can't move. I was able to open a container and remove the items and it, however the things in the container were not things that I had in my containers. I can't seem to do anything about the other container so I am still stuck

**To Reproduce**
1. I'm still stuck

**Expected behavior**
I would like to not be trapped in a random house? 

**Screenshots**

**Desktop (please complete the following information):**
windows 10 current version

**Additional context**

**Comment by faketucker** [comment]
You can try type /kill in the chat or use Alt +K. Let me know if it works or not

**Comment by nikonyanya** [comment]
> You can try type /kill in the chat or use Alt +K. Let me know if it works or not

I logged in to try it, but when I logged in, I spawned back in the house, tried walking, managed to move this time and then was effectively teleported to the outpost. I logged out and back in and I am definitely at the outpost now it seems

**Comment by faketucker** [comment]
Yeah, your tent may have decayed. And someone built a house at that spot, so the server remembers that you're still at that spot.

**Comment by faketucker** [comment]
Yeah, it's weird. Your tent is not supposed to decay if it's not been two days yet. But since we can't find a way to replicate it, we cannot know what caused it.
