### ISSUE TITLE
Can't exit vendor menu

### ISSUE THREAD

**Issue by MondayMourning** [Uuvana-Studios/longvinter-windows-client#641]
**Describe the bug**

**To Reproduce**
1. Go to Vendor
2. Click on Vendor
4. See an error: If you walk away vendor menu stays stuck and takes you to esc button menu if you click out of it.

**Expected behavior**
If you walk away vendor menu stays stuck and takes you to esc button menu if you click out of it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Latest version
Latest version. Day one purchase

**Comment by faketucker** [comment]
The only way now is to close the game and reopen it again.

**Comment by faketucker** [comment]
Duplicate of #410
