### ISSUE TITLE
be suspected of infinite range/bullet infinity He fired a series of guns at a crossroads where I couldn'

### ISSUE THREAD

**Issue by bonobono11223** [Uuvana-Studios/longvinter-windows-client#644]
**Describe the bug**

be suspected of infinite range/bullet infinity He fired a series of guns at a crossroads where I couldn'

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0] 1.02
 - Steam Version [e.g. 1.0] 1.02

**Additional context**

**Comment by faketucker** [comment]
This GitHub repository is for reporting and tracking bugs. If you want to report a hacker please use the ticket system in our Discord server. To open one follow the instructions:

Go to #☎-contact;
React to 👮 which is referent to Bot Reporting;
Inform which server you were playing on (Official only);
Post all images/videos and any information you have on the hacker.

![image](https://user-images.githubusercontent.com/28383557/160378547-be55a138-9827-4c55-8581-b9b2fc2d8509.png)
