### ISSUE TITLE
NON-PVP server very very serious bug

### ISSUE THREAD

**Issue by monkeycheatcom** [Uuvana-Studios/longvinter-windows-client#645]
**Describe the bug**
I have found some serious bug in NON-PK server setting.

i have set my server as PVP=false

so my server should not able to kill each other and should indestroiable other player's stucture
and I have found the way to destroy other player's structure in PVP=false  server setting.

1. unequip weapon
2. go to other player's house( not belongs to mine )
3. try to right click on any of other player's stuctures as screenshot.
4. normally u will unable to disassemble other user's structure with 'you are trying to pick up an item on someone elses property' message ( yeah it is normal )
5. but dont give up! just look around keep try to disassemble other player's structure nearby (without weapon)
6. you will successfully disassemble (some times can , but sometimes can not just keep try to right click it with any items. you will easily destroy huge size of town in few minute in NON-PVP server ! now you are good troller!!

7. this is very serious bug. server is  PVP=false  setting so user cant even kill troller  just follow and watch behind troller break all town 

what a mess

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window
 - Game Version 1.0.2 beta
 - Steam Version [e.g. 1.0]

**Additional context**
![20220402011035_1](https://user-images.githubusercontent.com/102656991/161303110-b373253c-2999-4547-8498-4a0c2adea0c1.jpg)
![20220402011042_1](https://user-images.githubusercontent.com/102656991/161303119-5dd4679d-d985-4ca3-a210-aafb7b7b8a41.jpg)
![20220402011103_1](https://user-images.githubusercontent.com/102656991/161303124-ed69ac7a-f37e-4f51-b240-8966d1d98626.jpg)

**Comment by faketucker** [comment]
I'm pretty sure you can pick that up because it's not in the house areas.
