### ISSUE TITLE
me and my 5 friends quitting this game because of the hacker or serious bug that our turret didn't give any damage. 

### ISSUE THREAD

**Issue by gracenlee940** [Uuvana-Studios/longvinter-windows-client#646]
US channel 5. We're enjoying this game so much since its release. We found a perfect spot to put down our 10 houses and were dedicated to upgrading the house for turrets so we can protect our properties. However, a player named nathan- something tried to break in which was common, but we didn't worry since we had 15 turrets and 2 mutual turrets at the entrance. however, he didn't take any damage from all the turrets and destroyed every single thing we build up for playing for so many hours. He SERIOUSLY wasn't taking any damage from even mutual turrets and gunfights. Also, he was able to build benches in our houses so he built stairs into our property. He was teasing and constantly destroyed what we had, so we decided to quit this game. We really want to like this game a lot, but can't handle the hackers and bugs that bullet doesn't go through any object even a dropped item bag. This person built planting pot on the top of his house, so no way for us to shoot him as well. The community we built with 5 other ppl in our West fall island (+ 6 us) are all quitting because of this person abusing the bug and using the hack. We may check out when you release the official version, but as far as now, we are done... I feel so sad that the time I put into this game was nothing... good luck on the other players...

**Comment by faketucker** [comment]
That is not a bug, it's definitely hacker. If you want to report a hacker please use the ticket system in our [Discord server](https://discord.com/invite/Longvinter). To open one follow the instructions:
1. Go to #☎-contact;
2. React to 👮 which is referent to Bot Reporting;
3. Inform which server you were playing on (Official only);
4. Post all images/videos and any information you have on the hacker.

![image](https://user-images.githubusercontent.com/28383557/160378547-be55a138-9827-4c55-8581-b9b2fc2d8509.png#gh-dark-mode-only)
![image](https://user-images.githubusercontent.com/28383557/160378390-fcdc4442-b176-4a5d-9b84-f2566ce5a69e.png#gh-light-mode-only)
