### ISSUE TITLE
lmb and spacebar press kick me from the game

### ISSUE THREAD

**Issue by himan1372** [Uuvana-Studios/longvinter-windows-client#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by himan1372** [comment]
anytime i press the LMB or space bar the game auto kicks me from the island im on just load into us uvana 1 and try to interact with anything windows 11 steam and game version are up to date

**Comment by sirNugg3ts** [comment]
Please open a new issue and fill out the bug report correctly instead of giving just a title. 
Also we need repeatable steps to test this and possibly a screenshot or recording of this happening

**Comment by Areapalm** [comment]
Same issue.
