### ISSUE TITLE
Game does not launch

### ISSUE THREAD

**Issue by typicalchicken** [Uuvana-Studios/longvinter-windows-client#650]
I bought the game from steam and installed. When I click "Play" it says "running" for a second or two but then goes back to a green play button and the game does not launch.

When I try to launch the .exe there are error messages: 
![image](https://user-images.githubusercontent.com/102834155/161345569-b18e2430-a015-433a-a052-4a60bb321634.png)
![image](https://user-images.githubusercontent.com/102834155/161345616-556dacbe-9fa1-4df7-ad32-e7dc3c011c60.png)
![image](https://user-images.githubusercontent.com/102834155/161345625-953a0f07-8b14-4883-a097-c751945c152b.png)

I have uninstalled and reinstalled multiple times with no success.

**Comment by faketucker** [comment]
Install the latest version of DirectX might fix this

**Comment by sirNugg3ts** [comment]
Installing DirectX will fix this
