### ISSUE TITLE
Containers in house shifted slightly

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#651]
**Describe the bug**
I have containers in my house stacked up around. The issue is that the containers shifted so that I could not pass through. There are 2 stacks of 3 containers in the back of the house. The stack on the right of the two stacks in the back shifted down just slightly so that I could no longer walk between them. I had to remove everything from the containers to remove the containers and restack them. The shifting was so slight it prevented me walking between the two rows.

**To Reproduce**
The only think I can think of is stack containers like I have and go in and out of the house. This is the first time it has done it as I have had them there for a couple days and no issue until now when I went into the house.

**Expected behavior**
containers shouldn't move position

**Screenshots**
This is so you can see how I have the stacks set up. Where I am standing the top two containers shifted forward.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/29164981/161350917-47d71d3d-3223-4749-ba34-6024c03350b2.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.2
 - Steam Version 1647446817

**Additional context**
I know when I first go into the house the containers appear slightly delayed and bounce down on top of each other.

**Comment by faketucker** [comment]
Tried many times but could't replicate this. I'm going to close this for now. If this happens to you again or you find an exact way to replicate this, feel free to reopen this issue.
