### ISSUE TITLE
House update merged houses

### ISSUE THREAD

**Issue by Wolfwraith** [Uuvana-Studios/longvinter-windows-client#653]
**Describe the bug**
when upgrading the interior of the house, if you are too close to the "inside the house" instance where you can see your neighbors house in the void, accidentally upgraded the house _into_ my neighbors house. i can access his chests and workbench (i didnt take anything)

**To Reproduce**
1. upgrade interior of house
2. within "x" amount of space of neighbor
3. house space upgrades and melds into neighbors house

**Expected behavior**
each house gets its own space of "x by y" to prevent houses from merging

**Screenshots**
https://imgur.com/a/bS7xGTK

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version 1.0.2
 - Steam Version1.0.2?

**Comment by faketucker** [comment]
How close were you to another base? I'm pretty sure you can't place two bases that close.

**Comment by Wolfwraith** [comment]
the house that merged is further away than my neighbor who is about 10 fences away

**Comment by faketucker** [comment]
> the house that merged is further away than my neighbor who is about 10 fences away

But from the screenshot seems like your inside house are pretty close?
