### ISSUE TITLE
I ate a water canister

### ISSUE THREAD

**Issue by YWainczak** [Uuvana-Studios/longvinter-windows-client#654]
**Describe the bug**
I clicked on a water canister and my character ate it.

**To Reproduce**
1. Pick up a water canister.
2. Click on it.
3. Your character consumes the water canister like their stomach is made of steel and their teeth are chainsaws.

**Expected behavior**
You should not be able to eat water canisters.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Longvinter Beta 1.0.2

**Comment by faketucker** [comment]
It's not a bug. You drink and throw away the canister :)
