### ISSUE TITLE
Game issue (buying from general store)

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#658]
Conditions:
-two players use the store at the same time
-player A either buys or sell
-player B buys

Issue:
When player B buys and player A sells the items will "move forward" so player B will get the wrong item costing money on something player B does not need. When player B buys and player A buys the items will "move backward" so player B will get the wrong item costing money on something player B does not need. This "movement" does not reflect on player B. This is even more of a problem when the server is full.

Suggested resolution:
Add a confirm buy dialogue and show the item being bought.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment]
Tested. When A buys something from James' General Store and B tries to buy something after, B will get the wrong item.
