### ISSUE TITLE
Turrets not working even though electricity needs are met

### ISSUE THREAD

**Issue by jovenile** [Uuvana-Studios/longvinter-windows-client#661]
**Describe the bug**
Turrets not working even though electricity needs are met.

**To Reproduce**
1. Fully upgrade house down sustainability path.
2. Install one turret. 
4. Turret does not work during night. 
5. Install second turret. 
6. Second turret does not work during the day. 

**Expected behavior**
Meeting electricity requirements would mean that turrets work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/102885424/161407476-e4dc9db6-b14d-4bb3-9fcb-d18c31dd0cb8.png)
Fully upgraded sustainable power path

![image](https://user-images.githubusercontent.com/102885424/161407487-79ae3152-1058-4b6a-a04f-69c4bfd3b21e.png)
Turrets stop working at night

![image](https://user-images.githubusercontent.com/102885424/161407494-adbb0f09-fcec-462a-88c3-3930bc2ddcbe.png)
One turret on, one turret off. Why?

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.2
 - Steam Version 

**Additional context**
Other solar powered houses have multiple fully working turrets.

**Comment by faketucker** [comment]
With a sustainable path, you'll get 80 electricity during the day and 60 at night. There might be something wrong with calculating the electricity usage or house areas overlapping each other. Can I have a screenshot of the house below your house?

**Comment by jovenile** [comment]
![image](https://user-images.githubusercontent.com/102885424/161407672-51bcbcc4-c55e-4501-b08a-50f75963a219.png)
House below

I understand the electricity nee changes, but I have seen another sustainable house that has 3 full working turrets at night and neither of mine work. Please advise—thanks!

**Comment by faketucker** [comment]
I'm not sure what happened here. As I said, there might be something wrong with calculating the electricity usage or house areas overlapping each other. And the electricity usage doesn't display correctly. Please be patient and wait until the devs look into it. Thanks for your understanding.

**Comment by faketucker** [comment]
This should be fixed by now. If you encounter this again, feel free to reopen this issue.
