### ISSUE TITLE
Container at the back wall of house won't open from the side

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#665]
Conditions:
-container must be next to the back wall of the house OR container must be right next to another container (close on short side of the container)
-container must be opened from the side

Issue:
The container next to the back wall of the house can't be opened from the side.

https://user-images.githubusercontent.com/16938875/161437721-ed6566cd-6d03-4c95-9a11-8c4ec17419f9.mp4

Expected behavior:
Player should be able to open container from the side like container in other location.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

Additional context
Player won't be able to get items in case they did this (see image) and would cost them a lot of time moving items back and forth just to access the container near the back wall.

![Untitldsadsasded](https://user-images.githubusercontent.com/16938875/161438082-3d6b42c3-5fe3-43e6-868e-d47fbaa0d881.png)

**Comment by Jalsson** [comment]
As of today when I tested this, I cannot no longer replicate so this issue seems to have been solved.
