### ISSUE TITLE
Boat not working.

### ISSUE THREAD

**Issue by MediocrePig** [Uuvana-Studios/longvinter-windows-client#666]
**Describe the bug**
*On Server Uuvana 6*
When attempting to travel from Heimo & Rose's to Sgt. Lake's, the boat's travel pop up will open and allow you to click on the destination (Sgt. Lake's), but the pop up will close after selecting the destination and nothing will occur. No money appears to be removed from inventory either.

**To Reproduce**
1: I begin at Artur's outpost and take a boat to Sgt. Lake's Outpost.
2: I then take a boat from Sgt. Lake's to Heimo & Rose's.
3: Once I finish traveling to the arena on the north island, I return to Heimo & Rose's.
4: I attempt to use the boat to return to Sgt. Lake's.

**Expected behavior**
I would expect the boat to behave properly and to transport me to Sgt. Lake's. Instead, I have to disconnect and close out of the game, reopen the application, and reload into the server in order to get the boat to behave properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows.
 - Game Version: Beta 1.0.2
 - Steam API: v020
 - Steam Package Versions: 1647446817

**Additional context**

**Comment by faketucker** [comment]
Tried many times but couldn't replicate this. But there are many report about this, so I'm gonna leave this for the devs to look into

**Comment by jaschr** [comment]
I keep having this same bug.

**Comment by natamru** [comment]
I have an issue where the boat menu doesn't open at all, I even swam to all docks just to see, needed to restart game to resolve.

**Comment by Jalsson** [comment]
There has been improvements to boat travel and since this issue has not been a problem in a while I'm closing this
