### ISSUE TITLE
Birds respawn instantly inside fence after going inside and coming out

### ISSUE THREAD

**Issue by Bunnbunnnn** [Uuvana-Studios/longvinter-windows-client#669]
**Describe the bug**
You can kill birds by their spawn location and if you fence in the area, go inside a house by the location then come back out, they instantly respawn and can be trapped quickly harvested with a chainsaw. 

**To Reproduce**
1. Fence birds in close to their spawn point 
2. Kill them, then go inside your house that is next to the spawn point / fenced in area
3. Stay in house for a few secs then come out 
4. Birds have already respawn and are trapped inside fence area 

**Expected behavior**
Birds would take longer to respawn & to respawn more random to not get trapped so easily 

**Screenshots**
[Video of bug supplied by discord usesr 성현#8056 ](https://www.youtube.com/watch?v=0jMr-fESKYA)

**Desktop (please complete the following information):**
 - OS: windows 
 - Game Version 1.0.2

**Comment by Bunnbunnnn** [comment]
Posting on behald of Discord user 성현#8056

They mentioned it not only happened with the house, but if you leave the area and the fence area goes out of screen, then the birds are back again as well.

**Comment by faketucker** [comment]
Yep, not sure if this is a bug or if it was intended. I'm goona leave it to the devs

**Comment by guneyarslan** [comment]
Well it should be bug, because if every house owner do this trick other players can't reach birds. Maybe they should spawn in radius not in spesific point.

**Comment by Jalsson** [comment]
Bird spawning area is now building blocked zone so birds should no longer spawn inside items
