### ISSUE TITLE
put the plant box away after planting crops in the plant box

### ISSUE THREAD

**Issue by petically** [Uuvana-Studios/longvinter-windows-client#67]
First plant crops in the plant box
Then put the plant box away
You can see the crops grow in the air
![20220228133913_1](https://user-images.githubusercontent.com/53294917/155931444-19c2fe40-11ac-4961-883d-e69378663315.jpg)
![20220228134242_1](https://user-images.githubusercontent.com/53294917/155931452-1ddfdb52-0acf-40af-9494-4ac4f90f4fd1.jpg)
I guess it's a logical error
By the way, is it possible to upload multiple updates in a package, so that the player's personal server can avoid frequent updates. You know, server update is a very slow thing, which greatly affects our gaming experience.
Thanks.

**Comment by sirNugg3ts** [comment]
> By the way, is it possible to upload multiple updates in a package, so that the player's personal server can avoid frequent updates. You know, server update is a very slow thing, which greatly affects our gaming experience.

This first weeks are going to be always hotfixes until the game is somewhat stable

**Comment by Jalsson** [comment]
This issue has been fixed. If the planter box is dismantled it will also drop dismantle the plants
