### ISSUE TITLE
compendium not saved

### ISSUE THREAD

**Issue by bstickk** [Uuvana-Studios/longvinter-windows-client#671]
**Describe the bug**
So I was doing my compendium last night for plants and after I got all 12 I left the game, the next day it reset back to what it was like before I did my compendium for that day 
**To Reproduce**
Not sure, maybe get compendiums and log out?

**Expected behavior**
Compendiums to save and me being able to wear my farm hat
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 11 
 - Game Version [e.g. 1.0] Beta 1.0.2
 - Steam Version [e.g. 1.0] Latest as of April 3rd, 2022

**Additional context**
N/A

**Comment by faketucker** [comment]
Duplicate of #600

**Comment by faketucker** [comment]
Duplicate of #745
