### ISSUE TITLE
gets stuck in vendor menu 

### ISSUE THREAD

**Issue by hunterbun** [Uuvana-Studios/longvinter-windows-client#673]
**Describe the bug**
If you open the vendor menu, you will randomly get stuck in it. The only way to get out of it is to disconnect. Hitting escape does not take you out of it. 

**To Reproduce**
1. Go to vendor
2. Click on vendor
3. get stuck

**Expected behavior**
not get stuck.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #410
