### ISSUE TITLE
I didnt ban anyone but when I check my ban list, there is always full of stranger

### ISSUE THREAD

**Issue by monkeycheatcom** [Uuvana-Studios/longvinter-windows-client#674]
![20220404121456_1](https://user-images.githubusercontent.com/102656991/161468005-a8ea373d-4184-474d-9e3e-32267ab4f888.jpg)

whats wrong with ban system?? who are they??  I didnt ban anyone. why those people are in my ban list?

**Comment by faketucker** [comment]
That's a [global ban list](https://discord.com/channels/846308806870695967/847462012614082560/953313664214138940)
