### ISSUE TITLE
Player gets stuck inside house after getting killed.

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#679]
Conditions:
-player gets killed (not just shot but killed) by two or more players (can be two enemy or one enemy and one turret) at the same time
-player gets sent inside their house after dying

Issue:
When player gets killed by two or more enemy and gets sent inside their house the player gets stuck and is unable to move.

Expected behavior:
The player should be able to move normally

System tested:
Windows 8
Windows 8.1
Windows 10 21H2
_____________________________________________________________________________________________________________________________________________

Random behavior hard to reproduce, not much of an issue:
If the above happens and the player closes the game and restarts it (player is still inside house which is normal), when player steps outside his house he gets teleported to a random safe zone like sgt. lake outpost.

**Comment by faketucker** [comment]
I've tried many times, but I can't seem to replicate this. This might have happened due to server lag.
