### ISSUE TITLE
Cannot place seeds in planter box.

### ISSUE THREAD

**Issue by Plant2** [Uuvana-Studios/longvinter-windows-client#68]
**Describe the bug**
Cannot place seeds in planter box when it is placed next to house.

**To Reproduce**
place planter box next to house.
attempt to place black lotus seeds

**Expected behavior**
seeds should have been planted in planter box

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - 1.0
 - Steam Version Current

**Additional context**

**Comment by sirNugg3ts** [comment]
give us screenshots or a recording of the error

**Comment by sirNugg3ts** [comment]
No information was given about this issue, closing it
