### ISSUE TITLE
시작 하는데 원래 있던템들이 없어짐 (없어진것 자동포탑2개 산타총1개 돌격소촌1개 금속부품3개 작업대 )를 잃음

### ISSUE THREAD

**Issue by Baejihoon02** [Uuvana-Studios/longvinter-windows-client#684]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by cherryblossom2020** [comment]
Please write bug report as English. Check Discord Q & A for missing items.
