### ISSUE TITLE
Random teleportation

### ISSUE THREAD

**Issue by Plant2** [Uuvana-Studios/longvinter-windows-client#69]
**Describe the bug**
Random teleportation

**To Reproduce**
1. run around map until teleported

**Expected behavior**
player should remain on path and not be teleported

**Screenshots**

**Desktop (please complete the following information):**
 -Windows 10
version 1.0

**Additional context**

**Comment by sirNugg3ts** [comment]
that's the server rubberbanding and we are already working on it <3
