### ISSUE TITLE
Item disappears in inventory

### ISSUE THREAD

**Issue by Stellet** [Uuvana-Studios/longvinter-windows-client#690]
Sometimes when placing an item in the container, an item is not displayed in the inventory and is replaced by a white block.
When returning it to the player's hand, it remains white, but if you place an item after it, it disappears.

**Screenshots**
![image](https://user-images.githubusercontent.com/15570848/161850831-a04d4ee8-f208-4c4c-87bf-56f9885aba77.png)
Image does not appear.

![image](https://user-images.githubusercontent.com/15570848/161851514-a74ca80c-4a4e-43ab-bb08-faa77d669fe1.png)
Empty item description

 - OS: Windows
 - Game Version 1.0.2

**Comment by Stellet** [comment]
![image](https://user-images.githubusercontent.com/15570848/161855911-a57ff913-99ee-4347-bd97-7d8a6ed66c19.png)
Apparently this item is hidden and then appears listed as an extra item

**Comment by faketucker** [comment]
It's a null item, it doesn't exist, and it's due to the server lag.
