### ISSUE TITLE
vending machine window doesn't closes if I double click to interact with it 

### ISSUE THREAD

**Issue by chltjrwns1gh** [Uuvana-Studios/longvinter-windows-client#695]
**Describe the bug**
1. vending machine window doesn't closes if I double click to interact with it
2. When I pick up flowers(maybe berries) sometimes it gives two items

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See an error

**Expected behavior**
After opening a private server by myself for the 1st time,
I tried to pick up some flowers(maybe berries) near the spawned area and sell to vending machine that sells fishing rod and bullets, etc.
Maybe this happend because my computer is so slow and gets easily lagged.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Game Version [e.g. 1.0]  1.0.2
 - Steam Version [e.g. 1.0]  latest(22.04.06 21:31 GMT+9)

**Additional context**

**Comment by faketucker** [comment]
Duplicate with #410

**Comment by faketucker** [comment]
Duplicate with #319
