### ISSUE TITLE
I want to play PVE

### ISSUE THREAD

**Issue by Humoculos** [Uuvana-Studios/longvinter-windows-client#696]
All of server have many people , their house is all over the ground , or can we play stand-alone games ourselves ?

**Comment by faketucker** [comment]
We don't have any PvE official servers right now but there are many unofficial ones in the game. You can host the server by yourself by following this [guide.](https://docs-server.longvinter.com/)

**Comment by Humoculos** [comment]
您好,我已收到您的来信,查阅之后会尽快回复予您。This is an automatic reply, confirming that your e-mail was received.Thank you.
