### ISSUE TITLE
I opened a chest inside my house and it sent me to SGT Lake's outpost

### ISSUE THREAD

**Issue by Queso924** [Uuvana-Studios/longvinter-windows-client#698]
**Describe the bug**
I opened a chest, the sound of leaving home played and I appeared at Lake's outpost

**To Reproduce**
I don't know, it happened very fast;
i opened a chest and it sent me to lake's outpost

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: Beta 1.0.2
 - Steam Version: I don't know
**Additional context**
Very rare, it only happened to me once

**Comment by natamru** [comment]
same thing happened to me here but steps to reproduce #679
