### ISSUE TITLE
Chat upgrades

### ISSUE THREAD

**Issue by sirNugg3ts** [Uuvana-Studios/longvinter-windows-client#7]
- Chat history is 100% needed. There are times where someone says something and wants to respond to something you said, so they reply right away and their initial message disappears and then they have to restate what they had said if you missed it.

- Global chat would be a great option for private servers at least if there are good reasons for why it wouldn't be welcome in public servers. Otherwise, global chat would be very helpful.

- Smart stacking chat bubbles. Currently when players stand next to each other their chat bubbles will overlap and make it difficult to read. There should be a system which will move around the chat bubbles so they are always visible and never overlap.

- I might also suggest having up to 2 chat bubbles active above a player, as it could help with those situations I mentioned previously where a player might talk too fast and lose out on their previous message.

[Discord Message](https://discord.com/channels/846308806870695967/873486241482559508/946767178668060702)

**Comment by Bunnbunnnn** [comment]
Yes, agreed - I almost missed what people were saying to me ingame and was looking for a history so I could look back and see. 

Also, I forget who it was that said something to me, so logging their username would be helpful

**Comment by Bunnbunnnn** [comment]
Also was thinking, when you have a message above your head, then you cannot see a name when waving. 

Would be nice if name always knew to be on top or bottom of the message so the name could be shown at all times when a wave is active. 

![image](https://user-images.githubusercontent.com/100467604/156053103-5daaf9ab-976a-48e8-a4a8-cfc12e6196fc.png)

**Comment by Bunnbunnnn** [comment]
Here is an prototype click-able of a proposed chat upgrade 

https://www.figma.com/proto/lA3wh0eu8jc7OlT959uEym/Design-File?node-id=22%3A187&scaling=contain&page-id=5%3A2&starting-point-node-id=22%3A187

Included show: 
- Area chat log 
- Group chat 
- Option to join group / manage group 
- Chat settings 
- how to report user

**Comment by Bunnbunnnn** [comment]
Added to forum
