### ISSUE TITLE
autosave feature after looting a container

### ISSUE THREAD

**Issue by JonnyTwoTimez** [Uuvana-Studios/longvinter-windows-client#70]
**Is your feature request related to a problem? Please describe.**
I was running around the map looting containers and finals after 13 hours of gameplay I finally find metal parts, and then the game freezes after 15 seconds, after starting the game back up i checked my inventory and the metal parts were gone..... and yesterday my character was wiped on uuvana 1.... we need better autosave features and the ability to get our characters back.
**Describe the solution you'd like**

**Describe alternatives you've considered**
I would love an autosave feature after looting containers to avoid this issue
**Additional context**

**Comment by sirNugg3ts** [comment]
The saving method of the game was altered to fix some save issues. Autosaving shouldn't be an issue now
