### ISSUE TITLE
the range problem of a bullet

### ISSUE THREAD

**Issue by ssmedison** [Uuvana-Studios/longvinter-windows-client#700]
**Describe the bug**

**To Reproduce**
Symptoms that occur when pressed continuously
Can't use up 100 bullets at once.

**Expected behavior**

the range problem of a bullet

The bullet seems to have a certain rangeten thousand

It doesn't go out exactly as far as that range, and when you use bullets, you get a stop.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
You can you find bugs if you are banned ?
