### ISSUE TITLE
Get stuck on house door when entering while someone else input code

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#703]
Condition:
-two players stand in front of door
-player A is house owner
-player A tries to go in house while player B is entering code

Issue:
Player A gets stuck if player A tries to enter while player B is entering code, player A is stuck even after player B gets in. In some cases both player gets stuck. In the rarest of cases both player gets stuck and the code UI also gets stuck. Players can get unstuck by restarting the game or using /kill.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment]
Can't replicate this. This might have happened due to server lag.
