### ISSUE TITLE
9 berry seeds cannot be planted in an angled Planter Box 3x3

### ISSUE THREAD

**Issue by ducbenho** [Uuvana-Studios/longvinter-windows-client#704]
**Describe the bug**
9 berry seeds cannot be planted in an angled Planter Box 3x3

**To Reproduce**
1. Pick a Planter Box 3x3 from your inventory
2. Press R 1 (or 2 or 3) times to rotate it 1 (or 2 or 3) times
3. Place it on the ground so it is angled and not straight to the view
4. If you try to plant a berry seed near 1 of the 4 corners of the Planter Box 3x3, there is a message saying it is overlapping something.
5. Therefore you can't plant 9 berry seeds in such Planter Box 3x3, only 5 is possible.
6. This bug does not happen if the Planter was not rotated before placing, or the seeds being planted are of flowers or sugar beets.

**Expected behavior**
You should be able to plant 9 berry seeds in a Planter Box 3x3 no matter how it was rotated before placing.

**Screenshots**

Step 4:
[https://cdn.discordapp.com/attachments/934069436216918017/961517206296985600/20220407_134516.jpg](https://cdn.discordapp.com/attachments/934069436216918017/961517206296985600/20220407_134516.jpg)

However I could plant 9 seeds if they are of beets or if the Planter is straight
[https://cdn.discordapp.com/attachments/934069436216918017/961607991554109470/20220407_185908.jpg](https://cdn.discordapp.com/attachments/934069436216918017/961607991554109470/20220407_185908.jpg)
[https://cdn.discordapp.com/attachments/934069436216918017/961646970961801236/20220407_221938.jpg](https://cdn.discordapp.com/attachments/934069436216918017/961646970961801236/20220407_221938.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: Beta 1.0.2

**Comment by faketucker** [comment]
Great that you figured out what caused it

**Comment by ducbenho** [comment]
May be the collision box of berry seed is bigger compared to flower seed?

**Comment by Jalsson** [comment]
It was indeed very hard to plant items into an angled. I smallered the collision box 20% so its now easier
