### ISSUE TITLE
Containers are duped in overlapping areas of the house

### ISSUE THREAD

**Issue by BugSecret** [Uuvana-Studios/longvinter-windows-client#706]
Bugs run in overlapping areas of the house
![Honeycam 2022-04-08 05-44-49](https://user-images.githubusercontent.com/103220027/162299146-dbf397de-cb57-44af-ad64-1ba6a885bbae.gif)
![Honeycam 2022-04-08 05-45-56](https://user-images.githubusercontent.com/103220027/162299210-00f484ab-fb77-4913-9486-0c2e81fcf4c7.gif)
![z1](https://user-images.githubusercontent.com/103220027/162299288-808e6cc7-30b0-43e6-83e3-5065f40ec8c3.png)

**Comment by faketucker** [comment]
Tested. When you pick up a container in house areas that overlap with other houses/tents, it will drop two containers instead of one
