### ISSUE TITLE
unable to place tent and steam achievements issue

### ISSUE THREAD

**Issue by MarkYoaa** [Uuvana-Studios/longvinter-windows-client#708]
I was trying to place a tent. Ran across the whole map without success. The tend was always red.
I did a quick restart of the game and recieved immediately the "Happy camper" and "Constructor" achievement without actually placing anything succesfully.

 - OS: win11
 - Game Version 1.0.2

**Comment by faketucker** [comment]
Most official server maps are kinda full right now. You should try to find a place in the winter biome or a new biome. They might have some space left there. And yes, Steam achievements are bugged, and we are aware of it.

**Comment by faketucker** [comment]
Duplicate of #421
