### ISSUE TITLE
Lets have some more rules around the use of turrets. 

### ISSUE THREAD

**Issue by aaaaaaaaaaaavm** [Uuvana-Studios/longvinter-windows-client#71]
it's basically impossible for all the other players including the new one to travel around the maps without being shot with a turret even if they aren't in the close space of another player's house

How about having the turrets work only if they are placed inside a close fence or something similar 

**Describe alternatives you've considered**

**Additional context**

**Comment by Jalsson** [comment]
- Player based Turrets can now only be placed near houses. They will not work when placed near your own tent, needs to be upgraded first.
- Turrets that are not near a house will not shoot people anymore. 
- Made player placed turrets shoot radius 38% smaller

**Comment by aaaaaaaaaaaavm** [comment]
On the same subject, I cant cross a lot of areas on the map without getting killed. I know it's about protecting your area, but it makes it difficult for anyone to live around farms with turrets. 

[Example 1](https://vimeo.com/683446412), me trying to cross to the vendor's area without wanting to swim to it or crossing someone else's property


A lot of places on the map have become a sort of graveyard. With everyone's bags left behind, full of whatever they have been farming, bringing back from an adventure or something of the sort. It's truly sad to see it after all the work they have done. A lot of players intentionally place turrets in such a way so that they can target those previously mentioned people and loot their stuff. 

[Example 2](https://ibb.co/ZT39Qb3) and [example 3](https://ibb.co/MPFsKrR) are of such graveyards where players have lost a lot of their stuff to turret owners who then loot them.

[Example 4](https://vimeo.com/683448201): Me trying to cross a river also trying to avoid all the placed turrets in the area.


I play on the Official Singaporean server btw and all the screenshots/videos are from there.
