### ISSUE TITLE
When respawning in a warehouse, it didn't show indoor view

### ISSUE THREAD

**Issue by mezzo19** [Uuvana-Studios/longvinter-windows-client#711]
**Describe the bug**
I disconnected while in a warehouse, when I relaunched and spawned back in the warehouse, the game didn't show the indoor view. Instead, it showed the outside of the warehouse. I had to navigate out of the warehouse with the roof in view rather than the indoor view. 

**To Reproduce**
1. Disconnect while in a warehouse. (I was in the one in the middle of the large far right island)
2. Reenter the same server
3. I didn't fully exit the game, just disconnected and reconnected into the server.

**Expected behavior**
Warehouse indoor should be in view when relaunching server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version Beta 1.0.2
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Tested

**Comment by Mikooboy** [comment]
Added a check to see if a player is inside when spawned which should make the indoor view more reliable in the next update
