### ISSUE TITLE
Unable to place a tent.

### ISSUE THREAD

**Issue by xr0nin** [Uuvana-Studios/longvinter-windows-client#714]
I got on the game, a friendly player bought me a tent to place. We went around the map, but no matter where, it would always say I was "trying to build on someone else's property". This would appear anywhere- near other bases, far from other bases, middle of nowhere...

We thought it could be a bug with them giving me a tent, so I bought one myself and had the same issue. It just wouldn't let me place it anywhere in the world. I gave the same tent to the other, experienced player and they had the same issue.

This is an urgent bug- the game, at least for me right after buying it, is un-progressable.

**Comment by faketucker** [comment]
Most official server maps are kinda full right now. You should try to find a place in the winter biome or a new biome. They might have some space left there.
