### ISSUE TITLE
I cant place my tent

### ISSUE THREAD

**Issue by MaroonPopsicle438** [Uuvana-Studios/longvinter-windows-client#715]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Most official server maps are kinda full right now. You should try to find a place in the winter biome or a new biome. They might have some space left there.
