### ISSUE TITLE
I stuck in the water!

### ISSUE THREAD

**Issue by CodezTree** [Uuvana-Studios/longvinter-windows-client#717]
**Describe the bug**
I stuck in the water...! (Between rocks)

**To Reproduce**
1. Go to Sgt. Lake Outpost
2. Jump off from the cliff exactly left of stucking place.

**Screenshots**
https://imgur.com/a/KCEbLj8

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.2

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt + K but you will lose all your stuff
