### ISSUE TITLE
Ban function doesn't work 

### ISSUE THREAD

**Issue by KoalaBoy** [Uuvana-Studios/longvinter-windows-client#72]
**Describe the bug**
Ban function doesn't work I can't ban anyone

**To Reproduce**
1. Go to 'Admin Panel'
2. Click 'Ban' someone
3. Nothing happenned

**Expected behavior**
Able to ban people and able to see who own turrets and house and able to remove their stuff because admin should have authority to control people, otherwise admin is useless

**Desktop:**
 - OS: Windows 11
 - Game Version 1.0.0
 - Steam Version Lastest

**Comment by Jalsson** [comment]
Ban function does not work if the player has logged out.

**Comment by KoalaBoy** [comment]
> Ban function does not work if the player has logged out.

Does not work when players are online too just tried it with my friends

**Comment by sirNugg3ts** [comment]
Fixed on the last update
