### ISSUE TITLE
 Multiple vendor menus appearing and not disappearing

### ISSUE THREAD

**Issue by today1212** [Uuvana-Studios/longvinter-windows-client#720]
**Describe the bug**
If you press the space bar key consecutively in vendor, the vendor menu window appears continuously and does not disappear.

**To Reproduce**
1. Go to vendor
2. Press the spacebar key consecutively on vendor.
3. The vendor menu is moved enough to automatically disappear.
4. See an error
**Expected behavior**
Multiple vendor menus appear and do not disappear

**Screenshots**
![1](https://user-images.githubusercontent.com/53577780/162585087-7cab4b33-008b-4fd5-ac52-d98f82afc03b.png)
![unknown](https://user-images.githubusercontent.com/53577780/162585089-51422180-53bf-4723-bac0-4cb527a38ea6.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro 21H2 Build 22000.593]
 - Game Version [Beta 1.0.2]

**Comment by faketucker** [comment]
Fuplicate of #410
