### ISSUE TITLE
lose ammo from autocannon death

### ISSUE THREAD

**Issue by L0574u5513** [Uuvana-Studios/longvinter-windows-client#721]
Whenever killed by autocannon I lose my ammo and get berries instead

**To Reproduce**
get killed by autocannon

**Expected behavior**
dont lose ammo

**Desktop (please complete the following information):**
 - OS:  Windows
 - Game Version 1.0.2
 - Steam Version 1.0?  updated

**Comment by faketucker** [comment]
Duplicate of #328
