### ISSUE TITLE
Accidental dismantling house 

### ISSUE THREAD

**Issue by lukejroberts1997** [Uuvana-Studios/longvinter-windows-client#722]
**Describe the bug**
Basically lost around 18 hours of progress because if you press the dismantle button and and then press w it auto accepts the dismantle and instantly teleports you to Sgt lake.

**To Reproduce**
1. Go to 'house' and then after the message pop up
2. Click on 'click dismantle on workbench followed and then after the message pop up press "w" or maybe "s" '
3. Dismantles house and sends you to Sgt lake.

**Expected behavior**
I expect it to do nothing. You should only dismantle houses if you click yes or whatever.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version latest
 - Steam Version latest

**Comment by sirNugg3ts** [comment]
This is not a bug, it's more of a suggestion. For that use the forum

**Comment by lukejroberts1997** [comment]
Of course its a bug? Are you saying that pressing a directional button when reading the dismantle message on the workbench should confirm the message and teleport you elsewhere? It's a bug.
