### ISSUE TITLE
get stuck between tree and rock

### ISSUE THREAD

**Issue by Jarno-V** [Uuvana-Studios/longvinter-windows-client#725]
**Describe the bug**
get stuck between rocks and tree

**To Reproduce**
1. go to this location
2. walk from the left side of tree to the rock and get stuck
![Schermopname (2)](https://user-images.githubusercontent.com/54915026/162593669-1c5aada3-415b-41da-8db4-20cd5bc803ce.png)

**Expected behavior**
just walk out the same way i walked in to this spot.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.2

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt + K
