### ISSUE TITLE
Vending Machine Window Does Not Close

### ISSUE THREAD

**Issue by marianettie** [Uuvana-Studios/longvinter-windows-client#727]
**Describe the bug**
When I try to leave the vending machine, the window does not close. Even if I walk far away, it does not go away. The only way to remove the window is to disconnect and reconnect to the game. This does not happen every time, however, it happens enough times to make the game feel frustrating. 

**To Reproduce**
1. Go to vending machine
2. Click on vending machine
3. Vending machine window does not close.

**Expected behavior**
I expected the window to close.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.2
 - Steam Version 1

**Comment by faketucker** [comment]
Duplicate of #410
