### ISSUE TITLE
The game that worked yesterday doesn't open today

### ISSUE THREAD

**Issue by klamet121** [Uuvana-Studios/longvinter-windows-client#729]
The game I played well yesterday doesn't open today
I played the game for a day and made a turret
It doesn't open on all servers
I'm so angry ㅠㅠ.;

**Desktop (please complete the following information):**
 - OS:  Windows
 - Game Version  1.0.2
 - Steam Version  Latest
**Additional context**

**Comment by klamet121** [comment]
After starting, the server list appears, and when you press the list, the loading screen appears and returns to the first screen

**Comment by sirNugg3ts** [comment]
This sounds like you got a version mismatch. Did you in any case switch to experimental branch? Also I don't know in which server you were but you might have been banned from that server

**Comment by AZBASS9** [comment]
Hello I am also having the same issue.  My server did not have anyone else in it, so it wasn't a ban.  It was one of the Uuvana 1 servers.

**Comment by klamet121** [comment]
I'm sorry. I think it happened because I accidentally pressed the beta Now I'm playing a best game
 Thank you
