### ISSUE TITLE
Chat Freezes Character if you Press Escape

### ISSUE THREAD

**Issue by mozameeza** [Uuvana-Studios/longvinter-windows-client#732]
When you go to chat and try to close the bubble by typing the Escape button, the character will be stuck in place. Everything still moves around besides the character. The only way to fix the issue is by 'Alt + F4' or (as I've recently tested) by pressing the Windows Key. The chat bubble stays up (though you can't type) and the cursor within the box disappears.

**Comment by faketucker** [comment]
I believe it is the same bug as #402. You write something and don't exit the chat properly, so it freezes
