### ISSUE TITLE
Can't connect to Server I was playing on yesterday.

### ISSUE THREAD

**Issue by AZBASS9** [Uuvana-Studios/longvinter-windows-client#734]
Hello! I just started playing this yesterday and I am curious about servers. I joined an empty uuvana 1 server and now I can't find the one I was playing in, even when I use the 17-digit session ID. I then realized that there are a ton of servers named "Uuvana 1" and it's almost impossible to find the server I was playing on.   When I enter the code for "connect to server" the loading screen pops up, as if it's loading in, and then the main game screen appears.

 - OS: Windows
 - Steam Version 1.0.2

**Comment by faketucker** [comment]
The Server ID will be changed every time it (re)starts
