### ISSUE TITLE
Player dies and has their body cloned

### ISSUE THREAD

**Issue by N-E-M-A-N** [Uuvana-Studios/longvinter-windows-client#736]
**Describe the bug:**

I was afk in my house and when i came back i was "naked" (all my gear and inventory is gone but i still have my money and access to my house and all the things inside and outside my house. It shows the ammount of ammo i had on the bottom left corner but i dont have it in my inventory anymore. The ammo part got fixed after rejoining).
And another "Player" with the exact gear i had on me before is standing in my house with me (presumably myselfe).

Since this happened my game is gtliching out when i am entering my house or rejoining the game, i for example joined the server and was in my house but then out of nowhere i got teleported to Sgt. Lakes Outpost and when i died i respawned inside my house but then immediatly left the house without doing anything and when i entered the house again my Screen was flickering (it never did that before).

Server: [EU] uuvana 3

UPDATE:

After rejoining the house multiple times the old me spawned in the floor so i killed him and got all my stuff except the ammo back and he is gone.

**To Reproduce:**

I have no clue.. i was just afking and when i came back it already was as discribed.

**Expected behavior:**

Nothing i guess.

**Screenshots:**

https://prnt.sc/aktdQCvDvPpu

The one on the Floor (in the middle of the house) is the current me which i can controll the other one floating is my old me which started floating after i rejoined the server.

**Desktop:**

 - OS: Windows 11 Insider 22000.593 (co_release)
 - Game Version: Longvinter Beta 1.0.2
 - Steam API: v020
 - Steam-Paket-Version: 1647446817

**Additional context:**

I think the same thing might have happened to a guy at Sgt. Lake Outpost a couple days ago.. there is a player standing on a bench there for like 3 or 4 days now i thought he might just afk there but now i think the same might have happened to them aswell.

**Comment by faketucker** [comment]
This seems to happen when people go AFK, but I'm not sure how it happens

**Comment by Jalsson** [comment]
We have added a code that deletes any character that does not have a controller. This should prevent ghosts from appearing
