### ISSUE TITLE
someone killed me and took all my stuff

### ISSUE THREAD

**Issue by sarahbarah96** [Uuvana-Studios/longvinter-windows-client#737]
**Describe the bug**
I was running around and someone shot me and stole my stuff. I had a workbench that someone gifted me and several fish I planned to sell. My inventory is gone.

**To Reproduce**
1. Run around
2. Get killed
3. Lose inventory

**Expected behavior**
I expect to have my inventory back when I respawn.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
That’s not a bug
