### ISSUE TITLE
Attempting to connect to a password locked server provides an interesting result.

### ISSUE THREAD

**Issue by TrilliASF** [Uuvana-Studios/longvinter-windows-client#738]
An odd issue with the U.I. makes the password locked server screen look interesting.
>> https://gyazo.com/ad273babbf20d3c81f2b5eecf0ea3af6 <<

A friend says it looks nothing like that. I have redownloaded it twice, verified the game file's integrity, and messed with the resolutions, nothing works.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.2

**Comment by faketucker** [comment]
Duplicate of #164
