### ISSUE TITLE
Turrets Shooting Me

### ISSUE THREAD

**Issue by choppa123** [Uuvana-Studios/longvinter-windows-client#74]
**Describe the bug**
I logged in and my turrets are shooting me. I am unable to get into my house now. I don't believe I was griefed because all of the turrets are within a fence inside of my build locked area.
**To Reproduce**

**Expected behavior**
Until logging in today my turrets have worked correctly and not shot at me.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
We need a explicit way to replicate the bug with (if possible) screenshots and recording, otherwise we don't have anyway to fix it. Please create a new bug report with the appropriate steps.
