### ISSUE TITLE
House over tent

### ISSUE THREAD

**Issue by Stellet** [Uuvana-Studios/longvinter-windows-client#741]
The tent has the walls of the house showing.

![image](https://user-images.githubusercontent.com/15570848/162854105-95c166f7-68a4-417a-8967-e58d966dd3fc.png)

Desktop
 - OS: Windows]
 - Game Version 1.0.2

This happened after the server reset on 04/11/2022, where I lost all my items and apparently all the houses were deleted.

**Comment by faketucker** [comment]
Duplicate of #625
