### ISSUE TITLE
Mouse does not work right (After Server Wipe) 

### ISSUE THREAD

**Issue by isnowcloud** [Uuvana-Studios/longvinter-windows-client#742]
**Describe the bug**
While trying to click on anything ('X' exit icon out of market menus, loot boxes, vending machines) I find myself clicking a bunch of times everywhere to trigger the item. Not as flawless as before. GL! 

**To Reproduce**
1. Go to any loot box, vending machine, etc
2. Click on them
3. Does not popup the first try, you'll have to click around until it pops up.
4. The mouse was spot on before 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
How about changing the resolution? Maybe try to verify or re-download the game.

**Comment by faketucker** [comment]
Change the resolution. It works for #803
