### ISSUE TITLE
Compendium gets deleted

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#745]
Conditions:
-join a server you have never joined before (which means it also works on freshly wiped server)
-collect some stuff
-die (must be first death)

Issue:
Compendium gets deleted on first death, its fine after that, really game breaking if you completed it before your first death.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment]
Tested. If you die before the servers auto-save all your progress, you'll lose the compendium you got at that time

**Comment by MollyTeaaa** [comment]
I had this same issue happen to me. I died then lost my progress. Also I left the server I was in and got on the next day to find that half of my progress on the compendium was gone. Once I finished one of them the finished one didn't disappear but my 3/8 feathers is now 0/8 and I cant complete the feathers.

**Comment by faketucker** [comment]
I believe this has been fixed. If you encounter this again, feel free to reopen this issue.
