### ISSUE TITLE
Game has been reset i.e. every has just disappeared.

### ISSUE THREAD

**Issue by PhoebyLee** [Uuvana-Studios/longvinter-windows-client#746]
As mentioned in the title, the game has been reset.
All has disappeared e.g. my character has been set to where i started, now with only 100 MK, All items i gained are not there in the bag, houses disappeared, Fish/plants/feathers we found have all disappeared as well etc.
Have been experiencing this issue twice- once in Japan server and the other in Korean server respectively.
Hope to hear back to solve the issue.

**Comment by faketucker** [comment]
The servers have been [wiped](https://discord.com/channels/846308806870695967/847462012614082560/963031709840986172)

**Comment by PhoebyLee** [comment]
Is it normal for the servers to be wiped or is this an error?
If it is normal, are the servers being wiped frequently/regularly?
