### ISSUE TITLE
stuck between tree and cliff

### ISSUE THREAD

**Issue by fabselwesen** [Uuvana-Studios/longvinter-windows-client#749]
I went along the cliff and fell between the tree and the cliff and am now stuck there.

**To Reproduce**
1. Go to a cliff.
2. Fall between tree and cliff.
3. Stuck in the air between tree and cliff. 
4. You can´t move away

![Screenshot (15)](https://user-images.githubusercontent.com/103567045/163140409-27553068-14a7-4d33-ad4d-6268423144a2.png)

**Desktop:**
 - OS: Win 10 Home
 - Game Version 1.0.2
 - Steam Version 1647446817
 - Server: [EU] Uuvana [3]

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt+K
