### ISSUE TITLE
Players Logging out during gun fights

### ISSUE THREAD

**Issue by shaymoe2** [Uuvana-Studios/longvinter-windows-client#752]
Players are easily logging out during a gun fight, really unfair and frustrating to play. If a player takes damage/shoots their gun, they shouldn't be able to just log out. Maybe a 30 second cooldown need to be put in place to avoid this situation. It has happened to me several times. Getting tired of playing against this.

Please see video for example:

https://www.youtube.com/watch?v=MFE-R8PDzz8

**Comment by sirNugg3ts** [comment]
Not a bug but a sugestion. Post suggestions in our forum at https://forum.uuvana.com/
