### ISSUE TITLE
hacker in this game

### ISSUE THREAD

**Issue by liuanming1999** [Uuvana-Studios/longvinter-windows-client#754]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by liuanming1999** [comment]
there was a hacker in my base Infinite HP and AMMR and I cant get out to the door

**Comment by sirNugg3ts** [comment]
hacker reports are on discord, not here
