### ISSUE TITLE
Hackers

### ISSUE THREAD

**Issue by TaanKeD** [Uuvana-Studios/longvinter-windows-client#755]
**Describe the bug**
Player is invisible. Using chainsaws as guns with no range and can shoot through anything. Players also have insane speed boost that is obviously not natural to the game.

**To Reproduce**
Server Uuvana 1 (US)

https://user-images.githubusercontent.com/103089215/163457310-7a0593a9-9389-428c-8b32-86e4b9fd1fa3.mp4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 -Windows 11
 - 1.0.2

**Additional context**
Game is unplayable and for the moment ruined.

**Comment by TaanKeD** [comment]
This has happened several times in the last few days. Several players were able to dismantle my entire house within minutes. At least 2 looked invisible. while one was not but still appeared to be killing me with chainsaw.

**Comment by yone111** [comment]
YEAH two hacker they move so fast and kill me with chainsaws in 1s!!!WTF in this situation.

**Comment by sirNugg3ts** [comment]
Hackers reports are on discord, this is to report bugs.
