### ISSUE TITLE
Character runs in circles no matter the input

### ISSUE THREAD

**Issue by ManiacalZ** [Uuvana-Studios/longvinter-windows-client#758]
**Describe the bug**
Whether it's WASD or controller, my character will consistently run in a wide circle, until a new input, in which he'll run in a new circle.

**To Reproduce**
I was able to "fix" it last night by quitting/restarting a few times, but today it doesn't seem to be wanting to fix. Remains persistent between servers.

**Expected behavior**
Normal movement

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Game Version [e.g. 1.0] 1.0.2
 - Steam Version [e.g. 1.0] 1647446817

**Additional context**
~~Add any other context about the problem here.~~

**Comment by ManiacalZ** [comment]
[Here is a google drive link](https://drive.google.com/file/d/1SWMRJ9ts52DwBAuKEIQvezjBzUVLz1iN/view?usp=sharing) with an .mkv of it happening

**Comment by faketucker** [comment]
Do you use a gamepad or have any emulation software for input?

**Comment by faketucker** [comment]
The same happened in #369

**Comment by faketucker** [comment]
Unplugging any gamepad or controller will fix this
