### ISSUE TITLE
lost all my stuff

### ISSUE THREAD

**Issue by picklefritz375** [Uuvana-Studios/longvinter-windows-client#759]
I logged in and was playing was sitting in my cabin and i got kicked and when i was able get back in my cabin and all of my stuff was gone

**Comment by faketucker** [comment]
Are you playing right before the update?

**Comment by picklefritz375** [comment]
Yes I got kicked and had to updateSent from my T-Mobile 5G Device
-------- Original message --------From: tucker ***@***.***> Date: 4/15/22  12:08 PM  (GMT-05:00) To: Uuvana-Studios/longvinter-windows-client ***@***.***> Cc: picklefritz375 ***@***.***>, Author ***@***.***> Subject: Re: [Uuvana-Studios/longvinter-windows-client] lost all my stuff (Issue #759) 
Are you playing right before the update?

**Comment by faketucker** [comment]
That’s the reason. The update rollbacked your progress a bit. There’s no way to get your stuff back, sorry.

**Comment by picklefritz375** [comment]
a bit you took my house my cash and my stuff you left me with nothing. Why?
    On Friday, April 15, 2022, 12:29:29 PM EDT, tucker ***@***.***> wrote:  
 
 


That’s the reason. The update rollbacked your progress a bit. There’s no way to get your stuff back, sorry.

**Comment by faketucker** [comment]
You lose all your progress or just some stuff?

**Comment by picklefritz375** [comment]
progress is still there but my house all my money only about 4k but all my crates 
    On Friday, April 15, 2022, 01:13:55 PM EDT, tucker ***@***.***> wrote:  
 
 


You lose all your progress or just some stuff?

**Comment by sahamil** [comment]
i have the same or near it bug. When i log this morning i lose all stuff i have on me (item/cash) and reset my collection for spécial shop. but all building and chest was remain ok. 

When i connect i roll back when start the game

**Comment by faketucker** [comment]
As I said, the update can rollback your progress a bit. Comment with all the information about what you've encountered on #600
