### ISSUE TITLE
After the update I can't access the game server. 

### ISSUE THREAD

**Issue by 97seokhwankim** [Uuvana-Studios/longvinter-windows-client#760]
After the update I can't access the game server. After clicking game start and selecting the server it just pops back to the intro screen. Help. I just bought the game and this happens...

**Comment by faketucker** [comment]
The server might not be updated yet

**Comment by PadoPool** [comment]
Same here. Can't join the game servers.

**Comment by faketucker** [comment]
> Same here. Can't join the game servers.

If it’s not the official servers, the server owner night not update their server yet

**Comment by Credo1911** [comment]
All official servers have been removed, not wiped.

**Comment by faketucker** [comment]
> All official servers have been removed, not wiped.

This is not related to this issue, please avoid making any further comments. Today, the official servers are down for maintenance. You can look at the devlog on the Steam to see what is going on.
