### ISSUE TITLE
Tent exit zone bug

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#761]
Conditions:
-walk to the wall near exit
-walk away from wall

https://user-images.githubusercontent.com/16938875/163589013-1dc64daa-34ab-4cae-869e-a058ed815ed9.mp4

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by Mikooboy** [comment]
Adjusted collisions so this should not happen in the next update
