### ISSUE TITLE
No fire damage

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#762]
Conditions:
-walk to fire
-you can move or stay still

https://user-images.githubusercontent.com/16938875/163589914-ebc6938f-0b5f-439f-bae1-39f503be1179.mp4

Issues:
Player don't get fire damage.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment]
It can happen sometimes. Walk away and walk on the fire again. You'll get the damage

**Comment by Jalsson** [comment]
Found a cause for this and fix will be applied in next update
