### ISSUE TITLE
Demolish and rebuild bug (this is not tent decay bug)

### ISSUE THREAD

**Issue by natamru** [Uuvana-Studios/longvinter-windows-client#764]
Conditions:
-demolish house
-rebuild tent on the exact position of the house

![Screenshot (98985)](https://user-images.githubusercontent.com/16938875/163590949-03b4602d-6a0e-48f4-8587-d57b0eb905f0.png)

Issues:
The house still exist (you could still get items if there were any left as well)

Expected behavior:
The house should no longer exist after demolishing

Context:
I demolished my house to realign with my other house and then I placed a tent.

System tested:
Windows 8
Windows 8.1
Windows 10 21H2

**Comment by faketucker** [comment]
Duplicate of #625
