### ISSUE TITLE
Loss of Progress on Server

### ISSUE THREAD

**Issue by JohnPizzaCrust** [Uuvana-Studios/longvinter-windows-client#765]
so this is what happened
1. my position was completely wonky
2. compendium was near empty
3. no more house
4. cash was different then when i logged out
I dont know what happened. My router didnt go out while I was playing, and I gathered wheat about 2 days ago, and it didnt show up.

**Comment by faketucker** [comment]
The server rolled back your progress a bit when you were playing right before the update. Comment with all the information about what you've encountered on #600
