### ISSUE TITLE
Autumn Isle Vendor Issues in build 1.0.3 (misspelled vending unit name & low price on item for sale)

### ISSUE THREAD

**Issue by Erukani** [Uuvana-Studios/longvinter-windows-client#766]
Image: https://steamuserimages-a.akamaihd.net/ugc/1861684358566157797/1AADAD038DA908BB55FEB1E19A6720CF2AA0C701/
Build: 1.0.3

Description:  At the large northern base POI on the autumn islands, there was a new vending machine put up called Julia's Mysterious Shop at 17°N, 35°W, with a rotating stock of sold items. There is currently 2 issues present with this vending machine:

1) The name has a typo, it is listed as "Julia's Mysterios Shop", with the 'u' in 'Mysterious' missing.
2) In any rotation involving 'Mysterious Bag' for sale, it is listed for a sale price of just 15mk. This amount is absurdly low, as Mysterious Bags are easily tradable for items on Pix's Island that would easily go for 400-500mk elsewhere. The price of the bags from this vendor should be drastically increased, to at least 250-300mk apiece, or else somehow limit the amount of bags that can be purchased by one person.

**Comment by faketucker** [comment]
You can make suggestions on our [forum](https://forum.uuvana.com/)

**Comment by Jalsson** [comment]
The mysterious bag does not spawn in Julia's Mysterious Shop any more. Also spelling is now corrected
