### ISSUE TITLE
Property Disappearing

### ISSUE THREAD

**Issue by Beeg-Ian** [Uuvana-Studios/longvinter-windows-client#768]
First of all, LOVE the game and hyped to see what it becomes. 

The issue is that a lot of items WITHIN my property lines keep disappearing. This so far includes a stone garden fireplace, two full chests of seeds and produce, two lampposts, and multiple growing crops.

This either means someone other than me (I play alone, no friends with codes) is able to pick up things off of my property, or items are despawning.

Also, the pickup buttons (space and left click) have what seems to be a 25% chance of working on grown crops.

Excited to see this game grow!

**Comment by faketucker** [comment]
Players can destroy your stuff by chainsawing it. It is kinda hard to pick up things because you have to pick them up at the right angle.
