### ISSUE TITLE
텐트위에 다른 집이 보임

### ISSUE THREAD

**Issue by bignaughty22** [Uuvana-Studios/longvinter-windows-client#770]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**
A clear and concise description of what
![HighresScreenshot00001](https://user-images.githubusercontent.com/103818187/163667778-e1b8d945-2de4-474a-9c85-d57cbf755c77.png)
![HighresScreenshot00002](https://user-images.githubusercontent.com/103818187/163667781-b392ccf4-48e2-4f18-94a5-0b2c570b0508.png)
![HighresScreenshot00000](https://user-images.githubusercontent.com/103818187/163667783-15452b75-08db-4239-8cc3-5d6e63a4fcb8.png)
 you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
