### ISSUE TITLE
다양한 버그발생 (총이 장착되지않음,장착한 물건을 벗을수없음,거래소 사용후 거래소 창이 계속뜨는현상 등)

### ISSUE THREAD

**Issue by qkdlzm38** [Uuvana-Studios/longvinter-windows-client#771]
확인한 버그 여러개를 보고드려요 
제발 고쳐주세요 원활한게임진행이 어렵습니다. 

제 캐릭만 그런진 모르겠으나 
갑자기 다양한 버그가 발생하여 
게임을 제대로 하고있지 못합니다.

1.총이 나 아이템이 캐릭터에 장착되지않음
2.이미 착용한 아이템을 벗을수가없음
3.거래소 사용후 거래소 창이 계속뜨며, 거래소 위치를 벗어나도 게임을 끄지않는이상 창이 사라지지않음
4.게임도중 초록색 동그라미가 계속 떠있음
5.거래창 오류로 게임에 나갔다 들어오면 집아닌 항구에서 젠됨
6.죽으면 총알이 다 사라짐

**Comment by cherryblossom2020** [comment]
**Please use English here**. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
