### ISSUE TITLE
Lost Compendium progress and money

### ISSUE THREAD

**Issue by HammersBros1711** [Uuvana-Studios/longvinter-windows-client#773]
**Describe the bug**
I played last night on 4-15 and logged off with 70k money and all my compendium complete. Log in today 4-16 with progress set back and only 7k money.

**Desktop (please complete the following information):**
 - OS: window 10 
 - Game Version 1.0.3

**Comment by faketucker** [comment]
The server rolled back your progress a bit when you were playing right before the update. Comment with all the information about what you've encountered on #600

**Comment by HammersBros1711** [comment]
im not sure what you mean by that. if you are asking what i lost i could
give you an idea but i couldnt tell you exactly the amount of money
