### ISSUE TITLE
Boat not working. [Snow's outpost bug]

### ISSUE THREAD

**Issue by Himgirish** [Uuvana-Studios/longvinter-windows-client#774]
**Describe the bug**
If you travel to snow's outpost from a boat then you cannot use any boat from anywhere unless you restart the game or reconnect.
Since Snow's outpost is an important outpost from selling fish it is causing a major issue for me.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ' any outpost'
2. Click on 'Travel to snow's outpost'
3. Try 'use any boat it won't work'
4. See an error

**Expected behaviour**
Nothing happens when you click on travel to... any outpost.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #666

**Comment by Himgirish** [comment]
That issue was not replicable this one is.
