### ISSUE TITLE
게임이 안들어가지는 버그

### ISSUE THREAD

**Issue by asmr21** [Uuvana-Studios/longvinter-windows-client#775]
섬을 들어갈려고 하는데 홈 화면은 되는데 섬이 안들어가저요

**Comment by kbs4674** [comment]
server master should upgrade server.
1. if you admin, please upgrade server refer to [offical document](https://docs-server.longvinter.com/linux/setup-docker/)
2. if you admin & server is linux&docker based, please refer [this document(kor&eng version)](https://longvinter-kr.notion.site/HOTFIX-4-15-v1-0-3-1879ac0cf7b54daba0eb0d215c9cbebe)
3. if you are not admin, please contact admin for update server

I know you are Korean, but this is a platform that people all over the world see, so I answered in English.
님이 한국인인건 알겠으나, 이곳은 전세계 사람들이 보는 플랫폼이어서 영어로 답했습니다. 참고부탁드립니다.

**Comment by kbs4674** [comment]
or, check your game client version.
latest game version must `1.0.3`

![2](https://user-images.githubusercontent.com/19690475/163686581-d8e98212-8b3f-4b5c-9f98-dedcc0c90a7a.png)

**Comment by cherryblossom2020** [comment]
Ask server owner to update server
And use English next time
