### ISSUE TITLE
i cant understand your 'duplicated'

### ISSUE THREAD

**Issue by NaOH-H2** [Uuvana-Studios/longvinter-windows-client#777]
**Describe the bug**
Water is whole white, so i cant see fish.
I did reinstall and deleted file in appdata
but it still white

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101209612/163692093-9a20c429-02c9-478a-a171-47ddedce21fd.png)
z
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0] beta 1.0.3
 - Steam Version [e.g. 1.0] 

**Additional context**
pls say me some solution for solve this problem, not a 'duplicated'

**Comment by faketucker** [comment]
Try toggle DX11 water in the setting
