### ISSUE TITLE
Drowning causes your bag to sink to the bottom

### ISSUE THREAD

**Issue by Dyslooxia** [Uuvana-Studios/longvinter-windows-client#778]
**Describe the bug**
When you drown your bag sinks to the bottom
for example my friend drowned at 17s / 8w and his bag is unobtainable
**Reproduce**
1. Go to 17s / 8w
2. Drown

**Expected behavior**
was expecting the bag to float on the surface of the water

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version: Beta 1.0.3
 - Steam Version: Live/ Most recent update

**Additional context**

**Comment by faketucker** [comment]
This is more of suggestion not a bug. For suggestions do it on our [forum](https://forum.uuvana.com)
