### ISSUE TITLE
houses are not loading in

### ISSUE THREAD

**Issue by AppleSauce187** [Uuvana-Studios/longvinter-windows-client#78]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Fill the bug report correctly with evidence of the bug and steps to reproduce

**Comment by AppleSauce187** [comment]
pay me then
