### ISSUE TITLE
Can't craft 

### ISSUE THREAD

**Issue by gh0stlyn** [Uuvana-Studios/longvinter-windows-client#784]
**Describe the bug**
I have a fully upgraded sustainable home but I cannot craft assault rifles, auto turrets. etc. . Energy always says 0/80. Not sure if there's an extra step I've missed. I can still craft fences and things like that.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0] 1,0,3
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Make sure you use a long barrel for an assault rifle
