### ISSUE TITLE
Stuck in Water

### ISSUE THREAD

**Issue by Leesa2594** [Uuvana-Studios/longvinter-windows-client#785]
I am stuck in the water at Sgt. Outpost.  I cannot go anywhere, and noone can kill me because they get killed by the turrets at Sgt. Outpost.  I was "slingshotted" into the water as it has been really glitchy this evening - and was pretty much unplayable.  But now, like I said I can't move and my health will not go down, so I can't do anything.

I am on Uuvana 5
My name is Leesa2594

Please help!

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt+K
