### ISSUE TITLE
Rapidly de-equipping items with weapon swap duplicates 3rd equip slot

### ISSUE THREAD

**Issue by Taliesin42069** [Uuvana-Studios/longvinter-windows-client#787]
Spam clicking equipment to de-equip and then switching weapons causes item duplication of the third removed(equipped) item.
I believe this is the cause of my other issue submitted which causes items to become stuck in your hands.
![image](https://user-images.githubusercontent.com/103878216/163707609-f2be4c28-7e00-4dac-8e0f-edfdddd4f93b.png)
![image](https://user-images.githubusercontent.com/103878216/163707616-595a7739-23f1-4476-a974-c76443c8ca14.png)
![image](https://user-images.githubusercontent.com/103878216/163707637-8a8c83c1-7cb5-432e-88a8-b33378668e5a.png)

**Comment by faketucker** [comment]
Have you tried to relog?

**Comment by Taliesin42069** [comment]
Re-logging doesnt solve the issue,-- this is a GUI bug that causes duplication.

**Comment by faketucker** [comment]
Tried many times to replicate this, but I can't seem to find a way. This might happen due to server lag, but I've still got to leave it for the devs to look into.

[https://youtu.be/mPas3HHuOpE](https://youtu.be/mPas3HHuOpE)

**Comment by Mikooboy** [comment]
Reworked how inventories handle item transfers so this should be fixed in the next update
