### ISSUE TITLE
나무사이에 끼여서 나올수가 없습니다.

### ISSUE THREAD

**Issue by feda1004** [Uuvana-Studios/longvinter-windows-client#788]
나무사이에 끼여서 나올수가 없어요..빼주세요.

![끼임](https://user-images.githubusercontent.com/103879970/163709040-7880a6d7-3afc-4316-825e-42fe778f00ba.png)

**Comment by faketucker** [comment]
**Please use English here.** Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.

**Comment by faketucker** [comment]
Type /kill in the chat or use Alt + k
