### ISSUE TITLE
모든 상자 그리고 제작대가 사라졌습니다

### ISSUE THREAD

**Issue by ass1234568** [Uuvana-Studios/longvinter-windows-client#790]
해커 유저에게 당한 것 같습니다. 모든 상자와 그 안에 있던 아이템들(총알,총,음식,라즈베리 잼,에너지드링크 등등 ......)
원거리 전기톱 공격을 하는 사용자와 싸움이 있었고 그가 저의 집을 확인하고 죽은 후 화면 확대 버그를 해결하기 위해 재접속을 하고 돌아오니 모든 아이템이 사라져있었습니다.
os 버전: Windows 10 Pro 64bit
게임 버전: beta 1.0.3
![unknown](https://user-images.githubusercontent.com/103885769/163714618-9ca23ae6-4653-4350-a000-3e0181e5624c.png)

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
