### ISSUE TITLE
hackers in safe zones ( aiming and shooting with out safe turrets noticing) 

### ISSUE THREAD

**Issue by GoogalyMoo** [Uuvana-Studios/longvinter-windows-client#792]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #793
