### ISSUE TITLE
hackers ( no health and aiming in safe zone )  killing and shooting and no damage taken at all by turrets in safe zones ( huge problem )

### ISSUE THREAD

**Issue by GoogalyMoo** [Uuvana-Studios/longvinter-windows-client#793]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
If you want to report a hacker please use the ticket system in our [Discord server](https://discord.com/invite/Longvinter). To open one follow the instructions:
1. Go to #☎-contact;
2. React to 👮 which is referent to Bot Reporting;
3. Inform which server you were playing on (Official only);
4. Post all images/videos and any information you have on the hacker.

![image](https://user-images.githubusercontent.com/28383557/160378547-be55a138-9827-4c55-8581-b9b2fc2d8509.png#gh-dark-mode-only)
![image](https://user-images.githubusercontent.com/28383557/160378390-fcdc4442-b176-4a5d-9b84-f2566ce5a69e.png#gh-light-mode-only)
