### ISSUE TITLE
Longvinter new update 

### ISSUE THREAD

**Issue by DatBoyJa** [Uuvana-Studios/longvinter-windows-client#797]
**Describe the bug**
Sorry i messed it up the first time submitting, the bug is one of the electrical upgrades dosnt work sometimes, at one point i will have 60 power then go to 80 and this results in one my turrets going online and offline. It’s annoying i lost a couple planters and i hvant seemed to figure out a fix for it

**Comment by N-E-M-A-N** [comment]
You know how Solarpower works right? (hint it doesnt without light) assuming you choose the Sustainable path ofc.

**Comment by faketucker** [comment]
Sustainable Path has Solar Panels which provide +20 electricity during the day.
