### ISSUE TITLE
Loosing Items trough the Workbench

### ISSUE THREAD

**Issue by N-E-M-A-N** [Uuvana-Studios/longvinter-windows-client#798]
Description:

Deposited wood to upgrade my house and Immediatly after i closed the workbench window and when i reopened it the wood i just deposited was gone. ( not in the workbench anymore and neither in your inventory.)

To Reproduce:

1. Deposit mats to your workbench.
2. Close the workbench window immediately after.
3. When you reopen your workbench your just deposited mats are gone.

Desktop:

 - OS: Windows 11
 - Game Version 1.0.3

**Comment by faketucker** [comment]
Tried many times but can't replicate this. Sometimes when I close the window immediately, it appears as if I didn't put materials in there, but when I reopen it, it appears normal. If you encounter this problem again or can provide us with a video, feel free to reopen this issue
