### ISSUE TITLE
Left clicking doesn't trigger anything in a post

### ISSUE THREAD

**Issue by sirNugg3ts** [Uuvana-Studios/longvinter-windows-client#8]
**Describe the bug**
Left clicking the Interact in a post does nothing

**To Reproduce**
1. Go to the post on the image
2. Click on Interact

**Expected behavior**
Open a shop or the door.

**Screenshots**
![image](https://user-images.githubusercontent.com/28486181/155728081-895a6d31-4da1-48ca-88c8-3c790f3228d5.png)

**Desktop :**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version 1.0

**Comment by Jalsson** [comment]
Problem with the map. Fixed now
