### ISSUE TITLE
uuvana6 is just a black world

### ISSUE THREAD

**Issue by pizzadreams6** [Uuvana-Studios/longvinter-windows-client#80]
**Describe the bug**
The world is black. I can see myself and  inside other houses. Everything else is black. 

**To Reproduce**
1. Log into uuvana6

**Expected behavior**
I expected to be able to play the game, in a non black/darkened world

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by pizzadreams6** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/100520793/156032069-159030bf-3346-4c99-83c1-4730e5c8dc8b.jpg)

**Comment by Plant2** [comment]
all the houses dissapeared so youre stuck in the void. i lost my house too

**Comment by pizzadreams6** [comment]
Are you in uuvana6? Of course this happens when I have all morning and afternoon free.

**Comment by pizzadreams6** [comment]
I did /kill and now Im back. Hopefully I can find my items

**Comment by sirNugg3ts** [comment]
use alt+k or /kill.
Just entered the server with no issue
