### ISSUE TITLE
Mouse Gap

### ISSUE THREAD

**Issue by WhiteJedii** [Uuvana-Studios/longvinter-windows-client#803]
I'm having an issue where there's a gab between my mouse and where it's actually clicking. I've reinstalled, reloged, also used my ps4 controller. I can't access anything in the inventory either

1 : load longvinter up
2 : move mouse 
3 : try to click on something but it goes to the one below what you want.

**Comment by faketucker** [comment]
Have you tried to change resolution?

**Comment by WhiteJedii** [comment]
I did and it worked. Silly me

**Comment by faketucker** [comment]
Thanks for letting me know. Someone has faced this problem before, and I'm going to tell them this!
