### ISSUE TITLE
Issues with turrets/electricity

### ISSUE THREAD

**Issue by ForsakenDabss** [Uuvana-Studios/longvinter-windows-client#808]
I fully upgraded my house with all the electricity but it shows only 60 electricity in sustainable upgrades. Sometimes the game will be buggy and only turn on 2 turrets and sometimes it will let me do 3. Don't know how to fix it. Keeps happening randomly
![Screenshot (74)](https://user-images.githubusercontent.com/104035563/164103494-55771cce-a7c6-43c2-b420-c3eddf9dd5cd.png)
![Screenshot (75)](https://user-images.githubusercontent.com/104035563/164103508-f889ba2f-db4b-4f7e-89e5-c7806318f38f.png)

**Comment by faketucker** [comment]
Solar panels will only give you +20 electricity during the day
