### ISSUE TITLE
Electricity Bug

### ISSUE THREAD

**Issue by BeepPeep001** [Uuvana-Studios/longvinter-windows-client#809]
**Describe the bug**
Despite fully upgrading house and having a total of 80 energy and allowing 3 turrets. The electricity amount always changes back down to 60 and deactivating a turret as a result.

**Screenshot**
![Untitled](https://user-images.githubusercontent.com/104050071/164147437-123eda02-db69-4f53-b614-019ca81666e9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.3
 - Steam Version 1.0.3

**Comment by faketucker** [comment]
Solar panels will only give you +20 electricity during the day
