### ISSUE TITLE
Can't enter the house 

### ISSUE THREAD

**Issue by DonDonuWu** [Uuvana-Studios/longvinter-windows-client#810]
**Describe the bug**
When the entrance of the house is blocked by blocks(e.g Workbench, fireplace, container) you get kick out of the house out of will exiting the house and entrying and causes to stuck outside the house. In the end stuck outside the house.

**To Reproduce**
1. Go into the house and filled up the house with containers and workbench till the entrance,
2. Leave the house
3. Try to re-enter the house
4. You will get lock out of the house entering n exiting immediately no on own will
5. Stuck outside your house

**Expected behavior**
Entering and exiting the house out of own will and stuck outside the house. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - LongVinter Beta 1.0.3
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Yeah, this can happen

**Comment by leeeeeeeeeeeeeeeeeeeeeeeeeee** [comment]
same issue...

![image](https://user-images.githubusercontent.com/104214596/164740122-9122c19a-d64f-42ac-b05a-6e1e9656bea2.png)

can't enter the my house   :(

**Comment by Jalsson** [comment]
Increased the size of the spawn area inside the house so spawning inside should be more reliable in next update
