### ISSUE TITLE
water not loading in. invite message not disappearing

### ISSUE THREAD

**Issue by RustyTeacup** [Uuvana-Studios/longvinter-windows-client#812]
**Describe the bug**
for some reason whenever i log into the game my water is completely white and i cannot see it. I can't see the fish either. I have to go into settings and press "toggle water "in order to see the fish and progress but it isn't nearly as pretty as the water other people are seeing in game. another thing that is happening is that the message at the top of the screen saying that a person wants to invite me to their team does not go away after pressing the x multiple times. it will only go away once i leave the game and come back.

**Expected behavior**
I just expected the water to be sparkly like I was seeing in other videos

**Screenshots**
![2022-04-20 (1)](https://user-images.githubusercontent.com/104100342/164310559-5f4ad3b1-2740-4efa-a24c-bb5b24fa7723.png)
![2022-04-20 (2)](https://user-images.githubusercontent.com/104100342/164310005-49c9ee27-d583-4a29-be99-8b288d168952.png)

**Desktop (please complete the

 following information):**
 - OS: Windows 11
 - Game Version: 1.0.3

 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
If toggle water doesn't help, try this

![image](https://user-images.githubusercontent.com/100423371/156272550-c1f1bf96-e1b8-4ce8-8853-4fb964ffe403.png)
