### ISSUE TITLE
Sign placement bug

### ISSUE THREAD

**Issue by kaihart** [Uuvana-Studios/longvinter-windows-client#813]
**Describe the bug**
You can place a sign on your character's head which then locks you in place without being able to get out.

**To Reproduce**
1. Select the sign
2. Enter caption
3. attempt to place as close as you can without hovering the mouse on yourself
4. clip as soon as sign turns green

**Expected behavior**
The sign will be placed on your characters head and you will be locked in place

**Comment by faketucker** [comment]
Just right-click to pick up the sign
