### ISSUE TITLE
THIS GAME IS DEAD

### ISSUE THREAD

**Issue by a118326** [Uuvana-Studios/longvinter-windows-client#816]
User: Slashnine is able to remove my fence on Uuvanna 6. WHAT THE FK IS THIS. YOU MOTHERFKERS NEED TO BAN THIS GUY AND FIX THE BUG. I PLAY THIS GAME FOR A FEW HOURS, AND THIS MOTHERFKER IS REMOVING ALL MY FENCE BY HAND AND HUNTING ME ALL THE TIME. WHAT A SHITTY GAME. 

1. REMOVING FENCE BY HAND
2. HE LOGGED OFF AND TELEPORT TO ANOTHER PLACE.  I WAS TRYING TO KILL HIM WHEN HE GET ONLINE, BUT HE TELEPORT TO ANOTHER LOCATION AND AMBUSHED ME.
3. THIS GAME IS NOT ENJOYABLE AT ALL. TOTALLY A FAILURE

**Comment by cherryblossom2020** [comment]
It’s not a bug. Players can pick up fences that aren’t in house area.

**Comment by a118326** [comment]
The map is freaking small, there is no way to run.

**Comment by faketucker** [comment]
Watch your language next time

**Comment by a118326** [comment]
Without indicator or anything and you are telling me it is not a bug. What a joke. Even it is not a bug in the backend, and you expect all players to figure it out without any visual help?

**Comment by a118326** [comment]
W

> Watch your language next time

Watch your game development progress going forward. Nobody is going to pay for a buggy game. Mixed reviews on steam means something. If you guys don’t give a damn about this game, then it is not going anywhere in the future
