### ISSUE TITLE
전기톱을들고 총을 같이쓰는행위(전기톱을사용하면서 샷건이쏴지는핵)

### ISSUE THREAD

**Issue by koreacider** [Uuvana-Studios/longvinter-windows-client#817]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by koreacider** [comment]
>

**Comment by cherryblossom2020** [comment]
Please use English

**Comment by evgaming88** [comment]
Translates roughly too: The act of using a gun with a chainsaw (a shotgun is fired while using a chainsaw)
