### ISSUE TITLE
It’s not a bug. Players can pick up fences that aren’t in house area.

### ISSUE THREAD

**Issue by a118326** [Uuvana-Studios/longvinter-windows-client#818]
It’s not a bug. Players can pick up fences that aren’t in house area.

_Originally posted by @cherryblossom2020 in https://github.com/Uuvana-Studios/longvinter-windows-client/issues/816#issuecomment-1107182125_

**Comment by a118326** [comment]
How do you define house area. Indicator? Or just pure backend data which players aren’t allow to see?

**Comment by biffotmc** [comment]
use the key on the side of you screen when you are placing things it will tell you if it’s able to be picked up by everyone or only you.

**Comment by evgaming88** [comment]
Red- can’t place 
Blue- anyone can pick up
Green- only you can pick up
