### ISSUE TITLE
자동포탑 상자에서 발견했는데 집가는길에 얼어서 죽었는데 자동포탑 없어졌어요

### ISSUE THREAD

**Issue by sexonthebeachh** [Uuvana-Studios/longvinter-windows-client#820]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Reports not written in english won't be taken into account
