### ISSUE TITLE
Cosmetic Windmill Models are Bugged

### ISSUE THREAD

**Issue by Hunstagamez** [Uuvana-Studios/longvinter-windows-client#821]
To the south point of the map these windmill models are a bit weird.
![image](https://user-images.githubusercontent.com/95254703/165021064-aaf72d5c-349d-4b0a-889c-9306ca2962ff.png)

**Comment by faketucker** [comment]
what's weird about it?

**Comment by faketucker** [comment]
Oh yeah, I've just realised

**Comment by Mikooboy** [comment]
Adjusted the location for the blades
