### ISSUE TITLE
Vending machine Interface opens twice and closes once.

### ISSUE THREAD

**Issue by whygelt** [Uuvana-Studios/longvinter-windows-client#824]
After clicking on the vending machine the window may open twice and won't close at all 

1.Go to a vending machine
2. leftclick the machine
3. close the interface 
4. enjoy needing to restart 

**Expected behavior**
I expected the window to close 👍 

**Screenshots/Gif**
https://gyazo.com/ca69241ea6fa21b0c6b5cfd20faf3a3b

**Desktop (please complete the following information):**
 - Windows 
 - Game Version: Beta 1.0.3
 - Steam Version: Latest 

**Additional context**
Nothing except relog/restart will close the window

**Comment by faketucker** [comment]
Dullicate of #410
