### ISSUE TITLE
Despite the fact that I cracked the game, I can't play it. When will this bug be fixed?

### ISSUE THREAD

**Issue by ICANTTAKEIT** [Uuvana-Studios/longvinter-windows-client#826]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by evgaming88** [comment]
Loooooool
