### ISSUE TITLE
핵 언제까지 두고보실건가요

### ISSUE THREAD

**Issue by thdgus90** [Uuvana-Studios/longvinter-windows-client#828]
[KR] UMS 서버 
총으로 30발이상 맞췄으나 죽지않는 버그좀 해결해주세요. 음식먹을 겨를도없이 뒤에서 쐈습니다.

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
