### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by R0rd3n** [Uuvana-Studios/longvinter-windows-client#829]
**Describe the bug**
When you die while trying to pick up stuff from a player's backpack, the window stays open and cannot be closed

**To Reproduce**
go pick stuff from a player's backpack, don't close the window and die

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Game Version 1.0.3

![image](https://user-images.githubusercontent.com/104520553/165579213-a22f62b0-e34a-47e8-beed-16058d43a7d9.png)

**Comment by HaikozReal** [comment]
i have tested this bug : https://youtu.be/9Mnbew2-MZ0

**Comment by faketucker** [comment]
Can't replicate. This might happened due to the server lag.
