### ISSUE TITLE
Getting sent back to home screen

### ISSUE THREAD

**Issue by masonnjayy** [Uuvana-Studios/longvinter-windows-client#83]
**Describe the bug**
After loading into my server that I have been playing on, trying to pick things up/ eat things, kicks me back to the menu.
**To Reproduce**

1. Load into server
2. Walk up to berry bush or right click berry
3. Sent back to home screen.

**Expected behavior**
I expect to either eat the berry or be able to pick it up.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]
Steam Version
**Additional context**

**Comment by masonnjayy** [comment]
let me know if this has happened to anyone else and if it is a fixable thing. Love this game and trying to play more!

**Comment by mynamejolt** [comment]
On my end this isn't just applicable to Berry Bushes, this is happening when picking up/dropping any item. See gif below, also renders my boxes useless if trying to move something to/from them.

https://gfycat.com/dapperneighboringeider

**Comment by Banbee168** [comment]
> On my end this isn't just applicable to Berry Bushes, this is happening when picking up/dropping any item. See gif below, also renders my boxes useless if trying to move something to/from them.
> 
> https://gfycat.com/dapperneighboringeider

same problem

**Comment by sirNugg3ts** [comment]
Be sure that the server is indeed updated. When the player is kicked out 9/10 times is because the server is not updated or vice-versa

**Comment by masonnjayy** [comment]
can i update the server if i do not run it, how would I go about doing so.

**Comment by sirNugg3ts** [comment]
You cannot update a server you dont own
