### ISSUE TITLE
Went to my base today and my energy dropped from 80 to 65 shutting off one of my auto defenders leading to my base being raided. I have 30 from transmitter, 20 from solar panels, and 30 from windmill. I know it lets you have 1 auto defender from the go just from house. I had all 4 running fine just started today where my power went down from 80 to 65.

### ISSUE THREAD

**Issue by OGPDTHUMS** [Uuvana-Studios/longvinter-windows-client#831]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Solar panels will only give you +20 electricity during the day, so at night you will only have 60 electricity
