### ISSUE TITLE
money not spend for buying items(can buy items free and can sell those for earn money again and again)

### ISSUE THREAD

**Issue by pFour420** [Uuvana-Studios/longvinter-windows-client#832]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
update the game
