### ISSUE TITLE
Where did the official servers go?

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#834]
![Screenshot_2](https://user-images.githubusercontent.com/69962198/166085653-e6c97e5c-2d1f-4c8b-9b8b-f9b799baf9e2.png)

where is [EU] Uuvana 1, [EU] Uuvana 2, [EU] Uuvana 3 and etc...

**Comment by faketucker** [comment]
Don’t file an issue here if it’s not a bug. Please check the [devlog](https://store.steampowered.com/news/app/1635450/view/3190247426146460829) about this. If you got any further questions, use our [Discord.](https://discord.gg/longvinter)
