### ISSUE TITLE
A tent can be placed inside an upgraded house. 

### ISSUE THREAD

**Issue by Baulder87** [Uuvana-Studios/longvinter-windows-client#835]
**Describe the bug**
When a house is upgraded to a larger interior size, a tent can be placed inside trapping the people inside until the tent disappears. 

**To Reproduce**
Upgrade House
Place Tent Inside
Get Stuck

**Expected behavior**
Get locked out of the game until the tent disappears. *Still testing, have not despawned tent*
Can kill yourself to get out of house, but then are locked out of house and lose inventory 

Longvinter Beta 1.0.4
Steam package version 1647446817

**Additional context**
Shout out to Pushyleaf for trapping 4 people in our house

![Tent in House](https://user-images.githubusercontent.com/104665938/166091291-c9b0d208-31c3-48b5-a75d-d70bc8eb04b7.png)

**Comment by Pushyleaf9002** [comment]
To be fair though, this is what makes me a good beta tester :)

**Comment by faketucker** [comment]
[Fixed.](https://discord.com/channels/846308806870695967/946785267984003072/974562814171693116)
