### ISSUE TITLE
Turret attacks me even I placed turret

### ISSUE THREAD

**Issue by PP0074** [Uuvana-Studios/longvinter-windows-client#836]
**Describe the bug**
Turret attacks me.

**To Reproduce**
1. Make your home in Longvinter 1.0.3
2. Update to 1.0.4
3. (?)
4. You spawn like new player then Done

**Expected behavior**
Replace turret then working properly

**Screenshots**
([https://streamable.com/pfpv7w](https://streamable.com/pfpv7w))
just added video.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.4
 - Steam Version Newest version

**Additional context**
When I updated to 1.0.4 without wipe then some user happens like this

**Comment by faketucker** [comment]
Devs will look into this

**Comment by OGPDTHUMS** [comment]
YES WHY DO MY TURRETS SHOOT ME AND WHEN PEOPLE GET CLOSE TO MY TURRETS THEY DONT SHOOT THEM?

**Comment by faketucker** [comment]
> YES WHY DO MY TURRETS SHOOT ME AND WHEN PEOPLE GET CLOSE TO MY TURRETS THEY DONT SHOOT THEM?

Turrets only shoot hostiles outside your house area
