### ISSUE TITLE
my character got wiped 

### ISSUE THREAD

**Issue by Yuuka-666** [Uuvana-Studios/longvinter-windows-client#84]
![Bild_2022-02-28_180507](https://user-images.githubusercontent.com/100610800/156026215-4f9e9f41-2da6-4deb-b754-a8b40e8baea9.png)

i lost all my stuff and knowledge..I don't care about the stuff but not the knowledge! I spent 5 hours on the arctic and catfish and I don't want to waste my time on them again. i had fishes 9/10 , feathers 8/8 & flowers 11/11.  

i want it back ..PLS

**Comment by Plant2** [comment]
happened to me as well

**Comment by sirNugg3ts** [comment]
At the moment there is no way to get stuff back. This is most likely because of the server updating and removed saves or didnt save correctly. There is no fix to this event
