### ISSUE TITLE
Server appears in the server list

### ISSUE THREAD

**Issue by chaoskometGP** [Uuvana-Studios/longvinter-windows-client#840]
Hello, 

the server I rented does not appear in the server list. Only 100 servers are listed in the server list. According to info from the hoster, they already have well over 100 servers in their inventory. 

Is it possible to extend the server list or enable joining via IP address with port?

**Comment by faketucker** [comment]
Devs will look into it

**Comment by sirNugg3ts** [comment]
Sven has fixed this on the 1.0.5 update with the new server browser
