### ISSUE TITLE
My house is gone

### ISSUE THREAD

**Issue by SimplyMrMatt** [Uuvana-Studios/longvinter-windows-client#841]
**Describe the bug**
I upgraded my tent to a house and logged off. When I logged back in, I was at the southern-most port and my house was gone
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
When was the last time you play? Before the wipe?

**Comment by sirNugg3ts** [comment]
No information was given. Closing the issue
