### ISSUE TITLE
GameThread timed out waiting for RenderThread after 120.00 secs

### ISSUE THREAD

**Issue by ThatOneAlexDev** [Uuvana-Studios/longvinter-windows-client#846]
**Describe the bug**
An error saying "GameThread timed out waiting for RenderThread after 120.00 secs" pops up after i try to join any server. It loads a few seconds until i believe the rendering should start, but the render thread does not reply. This happend after a casual restart like i did it many times before.

**To Reproduce**
Not reproducable | Seems to have happened randomly

**Expected behavior**
A start of the render-sequence and loading into the world afterwards

**Screenshots**
[Error message](https://i.imgur.com/kTNFfXa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.4 (Normal and Experimental Branch)
 - Steam Version [Screenshot](https://i.imgur.com/3YOHbqh.png)

**Additional context**
Discord: AlexDev#0001 (965551856682151956)

Things i already tried:
Restarting the game
Restarting the PC
Reinstalling the game
Deleting the local AppData files
Deleting my GPU cache
Deleting and disabling Steam shadercache

**Comment by faketucker** [comment]
Can you try to update your graphics card driver or maybe do a [clean boot](http://bit.ly/Clean_Boot)?
