### ISSUE TITLE
Faster Walking/Running

### ISSUE THREAD

**Issue by masonnjayy** [Uuvana-Studios/longvinter-windows-client#85]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...

Being that my house is not that close to the planter's vendor, I have to walk all the way to him to sell my lotus.

**Describe the solution you'd like**

I would like a way to get around faster without having to make and use an energy drink that only last a limited amount of time. 

**Describe alternatives you've considered**

I think it would be very cool and also efficient if there were some sort of running shoes you could unlock or rollerblades or something like that to make you permanently run faster. 

**Additional context**

**Comment by Bunnbunnnn** [comment]
Documented on forum already as 
 have a faster speed than base walking - running shoes/rollerbaldes to unlock
