### ISSUE TITLE
Not enough money to get back to islands

### ISSUE THREAD

**Issue by pixle01** [Uuvana-Studios/longvinter-windows-client#850]
**Describe the bug**

**To Reproduce**
1. Go to 'boat at spawn at Sgt. Lake Outpost'
2. Click on 'Pix's Island for $99'
3.Cannot travel back to Sgt. Lake Outpost or original outpost because of insufficient funds

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
It only costs $99 to get to Pix's Island from Sgt. Lake Outpost, but to travel back from Pix's island to Sgt. Lake Outpost, it cost $199. Also no way to get back to original island.

**Comment by faketucker** [comment]
This is not a bug. You can swim back to other islands. Check the map [here](https://i.imgur.com/Plpq2yJ.jpeg)
