### ISSUE TITLE
My house disappeared 20 minutes after I left it

### ISSUE THREAD

**Issue by EclipseSkye** [Uuvana-Studios/longvinter-windows-client#853]
**Describe the bug**
I was traveling to the other vendors to buy stuff and catch fish and 20 minutes later, I return to my house to find it missing and surrounded by other houses. I spent the day upgrading all the electricity stuff, and gotten 2 turrets and a full flower bed going on.

Now when my character dies, he teleports into the void, then to Sgt Lake Outpost.

I built the house yesterday 02/05/2022.

Is there a function to destroy houses and steal the stuff that Im not aware of?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
Didn't know my house was going to disappear so no screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
N/A

**Comment by faketucker** [comment]
May I know which server are you playing on?

**Comment by EclipseSkye** [comment]
Hi, this was the person asking on Discord. it fixed itself after a relog. Thanks again.
