### ISSUE TITLE
No Serverlist

### ISSUE THREAD

**Issue by DonPommes** [Uuvana-Studios/longvinter-windows-client#854]
Server list completely empty and when displayed only 100 servers!

If you are looking for your own server, it will unfortunately not be found.

**Comment by faketucker** [comment]
Press "show more" and try to refresh the list until your server appears

**Comment by DonPommes** [comment]
I have already done that, but it is not reloaded and no server is found again and again

**Comment by faketucker** [comment]
You mean there’s no server showing at all? Can you record a video for me?

**Comment by DonPommes** [comment]
https://user-images.githubusercontent.com/104854302/166506418-7196c664-8c98-4dc6-bec0-3dc013c83f35.mp4

**Comment by faketucker** [comment]
Can you try to verify the game files or restart your pc/network?

**Comment by DonPommes** [comment]
When I reload the game, the list is displayed to me, but it doesn't find all the servers, for example. from my colleague and the server from me.
And as soon as I go to the X in the server list and go there again, it says that it didn't find any servers.

**Comment by faketucker** [comment]
Epic Online Service limits 200 servers per search. Let's see if the devs can find a way around this

**Comment by DonPommes** [comment]
I really hope so because otherwise it makes no sense to offer servers from providers and they cannot be found at the end.

**Comment by sirNugg3ts** [comment]
Sven has issued a region and search by tag feature to fix this issue in 1.0.5 update
