### ISSUE TITLE
People still able to steal placed structures inside my Houses property lines

### ISSUE THREAD

**Issue by BalinP** [Uuvana-Studios/longvinter-windows-client#855]
I Placed all my fences and structures inside my Houses property lines. I made sure the structures were green (meaning they can be picked up by others) yet when I log off and get back on the next day. 1 fence is gone and my flower beds are missing. I've tried doing this at other players bases, but i get the error code that I can't pick something up in someone elses property.

**Comment by Lols0827** [comment]
for the fence, its possible that someone/a turret broke it. flowers, as well as any item on the ground can be taken even while in property bounds. make sure to place your turret on top of a fence so that it can shoot over.
