### ISSUE TITLE
Exit Bug

### ISSUE THREAD

**Issue by IceTrue0013** [Uuvana-Studios/longvinter-windows-client#857]
**Describe the bug**
Upon entering the server, no error message is displayed and the game shuts down after a few minutes

**To Reproduce**
1. Go to 'Longvinter'
2. Click on 'Play'
3. Scroll down to '[KR] GyulChan'
4. See an error

**Expected behavior**
A bug that occurs when entering the server

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Game Version 1.0.4
 - Steam Version (package version:1647446817)

**Additional context**
NO

**Comment by sirNugg3ts** [comment]
We cannot provide support on non-official servers
