### ISSUE TITLE
Getting sent to title screen

### ISSUE THREAD

**Issue by Manofixe** [Uuvana-Studios/longvinter-windows-client#86]
**Describe the bug**
Whenever i try to unequip my chainsaw, i get sent back to the title screen.

**To Reproduce**
1. Go to 'Inventory, the equipped tab'
2. Click on 'Equipped tool or weapon'
3. Get sent to title screen

**Expected behavior**
I expected to unequip my chainsaw

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by masonnjayy** [comment]
This happens to me too. Even trying to put something into my container I just automatically get sent to the menu. Also, if I try to eat berries. I'm pretty sure it kicks you for anything you push space or right click on.

**Comment by sirNugg3ts** [comment]
Is this on an official server?

**Comment by masonnjayy** [comment]
no it is a server that me and my freind joineds because it had the lowest ping. The server is "GamerZLanding."

**Comment by sirNugg3ts** [comment]
Then the server is not updated for sure. Please report this kind of bugs by testing on the official servers which are always updated

**Comment by masonnjayy** [comment]
So then I cannot play on the one I have all my progress on, ill have to restart on a new one?

**Comment by sirNugg3ts** [comment]
if you want to play on that server, you need to wait that the host updates their server

**Comment by Manofixe** [comment]
> Is this on an official server?

nope...it was on a private server

**Comment by sirNugg3ts** [comment]
Then the server is not updated.
