### ISSUE TITLE
I don't see the effect of the water shining on the game screen.

### ISSUE THREAD

**Issue by snh3537** [Uuvana-Studios/longvinter-windows-client#860]
**Describe the bug**

**To Reproduce**
4. See an error: I don't see the effect of the water shining on the game screen. Even though everything is turned on in the settings, nothing changes on the screen.
게임화면에 물 반짝이는 효과가 안보여요. 비디오 설정은 다 켜져있었는데 아무 변화가 없어요!

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Toggle DX11 Water in the setting

**Comment by snh3537** [comment]
I've tried that too, but the water color just changes and I don't have a shiny effect.

**Comment by faketucker** [comment]
If it doesn’t work, try what the issue #13 said and try to set eveything on High
