### ISSUE TITLE
Bug with property

### ISSUE THREAD

**Issue by EinsKevinIAM** [Uuvana-Studios/longvinter-windows-client#861]
Hello,
I have an issue on [EU-West] Uuvana 2. Someone build a house on my property and stole my items.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: Beta 1.0.4
 - Steam Version: newest

**Additional context**
I dont understand how this is possible

![Longvinter   04 05 2022 22_41_10](https://user-images.githubusercontent.com/104940608/166822629-1c498016-adf2-4283-8852-34658c31b325.png)

**Comment by sirNugg3ts** [comment]
From what it seems you placed items further from your markers, can you confirm that?

**Comment by EinsKevinIAM** [comment]
Actually i Just fixed it. It was my friend who placed the House. Thank you for your quick answer.

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Mai 4, 2022 at 22:45 schrieb Diogo ***@***.***>:   


From what it seems you placed items further from your markers, can you confirm that?
