### ISSUE TITLE
If you connect to all servers that are not discode problems, it will appear on the main screen during loading

### ISSUE THREAD

**Issue by Mrunda** [Uuvana-Studios/longvinter-windows-client#865]
This is a user with the nickname Mr. Unda who is playing on the Us-West Uuvana server The problem is not the discode problem, but when you try to enter all the official servers, it comes to the main screen while loading the server What should I do?

**Comment by Jalsson** [comment]
Is your client version 1.0.5?

**Comment by Mrunda** [comment]
Yes, but there's no update on Steam

**Comment by Mrunda** [comment]
> 게임 버전 이 1.0.5 ?

네 하지만 스팀업데이트가 더이상 없는데요?

**Comment by Mrunda** [comment]
> 게임 버전 이 1.0.5 ?

Yes, but there is no steam update anymore
