### ISSUE TITLE
Money, Inventory and Compendium lost

### ISSUE THREAD

**Issue by DamienPika** [Uuvana-Studios/longvinter-windows-client#868]
I stopped playing for a few weeks. After I logged back in today I lost all my money (about 150k), my current Inventory + my compendium Progress. My house is still there and I can still access all of it after opening the door with my code. I'm Not really sure, but I feel like I changed outfit colors as well (I swear I was green before and now I'm red..)

**To Reproduce**
I honestly don't know

**Expected behavior**
I expected to log in where I logged off with all my money, compendium and Inventory. The stuff I gathered wasn't even in one Session, so if it wouldn't have been saved right the last time, I still woudn't have been set back to zero

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.5
 - Steam Version: newest 

**Additional context**
It happened on a private server! It wasn't like a server wipe or anything

**Comment by faketucker** [comment]
Your ID has changed since we now use Epic Online Service. That’s why you lose your stuff.
