### ISSUE TITLE
Being able to put a house in a point of interest

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#869]
**Describe the bug**
Being able to put a house in a point of interest and blocking it off?

**To Reproduce**
Please see screen shot

**Expected behavior**
Shouldn't this say too close?

**Screenshots**
<img width="758" alt="image" src="https://user-images.githubusercontent.com/29164981/167178251-33ab72b1-cac5-4abf-b47b-1788ee2b01ff.png">

**Desktop (please complete the following information):**
 - OS: win 11
 - Game 1.0.5
 - Steam Version 1.0.5

**Additional context**
Isn't this a point of interest and now no one has access because they even put a turret inside of it.

**Comment by Mikooboy** [comment]
Should be fixed in the next update
