### ISSUE TITLE
Player can left the Game directly after lose an Attack.

### ISSUE THREAD

**Issue by viaInteritus** [Uuvana-Studios/longvinter-windows-client#872]
**Describe the bug**
Players can safe their Items at fight because they left before they die.

**To Reproduce**
A Player attacks another Player.
One Player is losing and press disconnect, before he dies to safe his loot.
The winning Player have two problems:
First he don´t get the winning loot.
Second if the enemy is inside a Base he don´t have to get over the Basewall again before attacking.

**Expected behavior**
Normaly i would expect, that the players Logout needs 10 or more seconds.
A Player should not left the Game inside a fighting situation.

**Desktop (please complete the following information):**
This part would not help.

**Additional context**
I got this issue most at Team attacking situations. If my enemy lost the fight, he left the game and came back when their buddys are there to help them fighting back.

**Comment by sirNugg3ts** [comment]
That is not a bug and more of a game balancing issue. For that kind of suggestions, refer to discord or our forum
