### ISSUE TITLE
Can't shoot when aiming

### ISSUE THREAD

**Issue by Zunlin0517** [Uuvana-Studios/longvinter-windows-client#873]
**Describe the bug**

Unable to shoot by LMB while aiming sometimes. The last time when I was in a warehouse and trying to shoot other players, my gun cannot shoot when I aiming, and I'm sure that I was armed with enough ammo and used them correctly. 

**To Reproduce**
4. See an error

1. Aiming by RMB
2. Click on LMB to shoot
3. Scroll down to no responses when using LMB
4. See an error

**Expected behavior**
The shooting function should be correctly realized at any time and any place.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Game Version [e.g. 1.0.5] 1.0.5
 - Steam Version [e.g. 1.0.5] 

**Additional context**

**Comment by Mikooboy** [comment]
Most likely caused when aiming while standing close to other objects. Should be more reliable soon.
