### ISSUE TITLE
Sub-machine gun bug

### ISSUE THREAD

**Issue by XaoSid** [Uuvana-Studios/longvinter-windows-client#874]
Describe the bug
i can't make semi-automatic in my workbench but i can build another weapons like submachine, shotgun and etc...

To Reproduce
Please see screen shot

**Expected behavior**
i just want made a new gun

**Screenshots**
![image](https://user-images.githubusercontent.com/88840408/167969317-cee8823c-a7a7-4e09-ada5-d9c52c8c0fd5.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Game Version 1.0.5
 - Steam Version 1.0.5

**Additional context**
i was made the semi-automatic gun for a PvP, but I couldn't build it

**Comment by faketucker** [comment]
You’re not using the right gun barrel
