### ISSUE TITLE
Village lamp turn on when got attack

### ISSUE THREAD

**Issue by MineMy** [Uuvana-Studios/longvinter-windows-client#875]
https://user-images.githubusercontent.com/26472792/168234736-643da546-883c-4634-805c-1e401657ef63.mov

**Comment by faketucker** [comment]
I believe it's already on because it appears to be evening, but it hasn't been updated on your side, so when you attack those lamps, they are updated and turn on.

**Comment by faketucker** [comment]
Oh, I've just tested it. Yeah, it's bugged.
