### ISSUE TITLE
J shop's page UI doesn't fit

### ISSUE THREAD

**Issue by MineMy** [Uuvana-Studios/longvinter-windows-client#876]
**Describe the bug**

<img width="636" alt="스크린샷 2022-05-13 16 34 14" src="https://user-images.githubusercontent.com/26472792/168235082-5db32deb-1768-4e10-9b41-146196b9c608.png">

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
This happens when the sell price is four-digits more than 3 items.

**Comment by Jalsson** [comment]
Made the digits smaller if the price was higher than 3 digits. Will be fixed in next update
