### ISSUE TITLE
Resetserver after 1.0.6..

### ISSUE THREAD

**Issue by oRAVENo** [Uuvana-Studios/longvinter-windows-client#878]
Hello,
While updating, all the servers have been deleted. Is this normal? In addition to that there are some lag from time to time that there was not before. The game is very good however if every time there is an update, you have to start all over again it will be boring ....
Sincerely

**Comment by faketucker** [comment]
Official servers have been wiped. Check out the devlog on Steam or keep up with the latest news in our Discord.
