### ISSUE TITLE
Paintings are not destroyed when Tent is dismatlet

### ISSUE THREAD

**Issue by DustinDEV2more** [Uuvana-Studios/longvinter-windows-client#879]
**Describe the bug**
If you place a painting in a tent and then dismantle it afterwards the paintings that you left inside dont get destroyed. 
You can see this when placing a tent again and go inside

**To Reproduce**
1. Place a tent somewhere
2. Put a painting inside of the tent
3. Dismantle the tent
4. Place a tent again near the original one and go inside

**Expected behavior**
You can see the painting in the void

**Screenshots**
![image](https://user-images.githubusercontent.com/45263590/168279066-ff82b377-232d-4a2f-aebf-aef805285910.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version Beta 1.0.6

**Comment by Mikooboy** [comment]
Adjusted the overlap check so that the paintings will get deleted in the next update
