### ISSUE TITLE
sent to home screen for interacting with anything

### ISSUE THREAD

**Issue by Banbee168** [Uuvana-Studios/longvinter-windows-client#88]
**Describe the bug**

**To Reproduce**
1. Go to 'any item'
2. Click on 'the item or storage'
3. you are automatically sent to home screen

**Expected behavior**
Yesterday the game worked perfectly for me and I had no issue, today as soon as i logged on any item i interacted with sent me to the title screen. i do hope it gets fixed soon the game is really cool and a lot of fun. sad it's unplayable for now.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
Also idk if it helps but i am on the "[US][NYC] Flushing Meadows [NEW PLAYER FRIENDLY]" server. I also upgraded my house if that makes a difference.

**Comment by Jalsson** [comment]
What server you were ob?

**Comment by Banbee168** [comment]
> What server you were on?

nyc flushing meadows

**Comment by sirNugg3ts** [comment]
The server is most likely out of date. Please report this kind of bugs in official servers
