### ISSUE TITLE
I'm stuck on Joining Island screen for more than 20 mins

### ISSUE THREAD

**Issue by Sloffeex** [Uuvana-Studios/longvinter-windows-client#881]
so im trying to join US-WEST Uuvana 1 for more than 20 mins now... just stuck on Joining Island... screen, i cant seem to get in.. please help.. i didnt have this issue before.. i was in the server last night without having any issue..

i have reinstall the game and i have also tried to join another server and im still having the same issue..

**Comment by faketucker** [comment]
You have been banned because of the sign you put up with hate speech. If you believe you were unfairly banned, please submit a ban appeal through our[ Discord](discord.gg/longvinter).
