### ISSUE TITLE
Seems either the server is lagging ... or the hit box on clicking items is having issues. it wasn't like this before i used to be able to click a box and it would open ... now i have to try and hit space bar to open it and sometimes that even is having problems?

### ISSUE THREAD

**Issue by JBenkoLongVinter** [Uuvana-Studios/longvinter-windows-client#882]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
