### ISSUE TITLE
Stuck in water between rocks

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#884]
**Describe the bug**
While swimming trying to go through rocks. I was able to walk over a small rock but then was stuck between rocks and couldn't climb out and ended up dead

**To Reproduce**
1. Go to This was at the top left corner of the middle desert island trying to swim around the corner
4. See an error

**Expected behavior**
was hoping to be able to go around but was able to climb rock from one direction but once over I couldn't move in any direction

**Screenshots**
<img width="997" alt="Longvinter Stuck between rocks in water" src="https://user-images.githubusercontent.com/29164981/168450202-84859ac9-070b-4f59-aa01-92bf9c1f665e.png">

**Desktop (please complete the following information):**
 - OS: win11
 - Game Version 1.0.6
 - Steam Version 1.0.6

**Additional context**
some rock you can walk up and over and this particular one I could walk up one way and then stuck in all directions.

**Comment by faketucker** [comment]
I believe the point of these rocks is to prevent you swimming through. If you get stuck in any places, you can type /kill in the chat or use Alt + K, but remember that all your stuff will drop.
