### ISSUE TITLE
Turrets shooting through houses 

### ISSUE THREAD

**Issue by QTJAZ** [Uuvana-Studios/longvinter-windows-client#885]
**Describe the bug**
Placing a tent/house in front of a turret either in a safe zone or near a teleporting dock. You can shoot the turret since it is in a safe zone. Can not raid the base because the turret will shoot and kill your character through house(s).

**To Reproduce**
1.  Placing your tent/house directly Infront of the turret.
2. Place fences around the yard of the tent/house.
3. Untouchable base due to turrets shooting through the house.

**Expected behavior**
It only makes sense if you was to place a tent/house in front of a turret, in a safe zone or not, I think the turret should be able to shoot through the house(s) and kill you. Basically, the turret's vision would be blocked from the house.

**Screenshots**
![image](https://user-images.githubusercontent.com/105604484/168488052-4dd5e706-d871-4868-8fda-869cb73c2bfd.png)
- The turret is placed behind the yellow house on the left.
![image](https://user-images.githubusercontent.com/105604484/168488107-eb77f8e0-45dd-46ef-8712-1b14325a7d73.png)
- Made an attempt to raid this base, was immediately shot through the house as I thought the turret would not see me due to the house being there.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: LongVinter Beta 1.0.6
 - Steam Version v020

**Additional context**

**Comment by faketucker** [comment]
Should make this area a POI

**Comment by Mikooboy** [comment]
Should be fixed in the next update
