### ISSUE TITLE
When opening LongVinter, Error codes pop up, and it won't let me open the game. (provided below)

### ISSUE THREAD

**Issue by SomeDude5652** [Uuvana-Studios/longvinter-windows-client#890]
I've tried restarting my pc, uninstalling and reinstalling steam, verifying game files and all other common fixes for this issue but it wouldn't help. 

These are the error codes;

![image](https://user-images.githubusercontent.com/106001064/169676421-2b3341b0-1fd6-42e3-b0d6-56a8f45a3b16.png)

![image](https://user-images.githubusercontent.com/106001064/169676417-856c1f5b-2148-43f7-bbf2-632581f814e8.png)

![image](https://user-images.githubusercontent.com/106001064/169676426-85bfdf9a-5190-4668-897f-6bed84aae712.png)

![image](https://user-images.githubusercontent.com/106001064/169676428-179bb8ea-bc6e-474f-b70e-ecb3115d45e8.png)

I enjoyed this game a lot until this happened, I'm past refunding the game so I'm stuck trying to fix this, please help.

**Comment by faketucker** [comment]
Installing the latest version of Microsoft DirectX will fix this

**Comment by SomeDude5652** [comment]
> 

I just checked and I have directx 12, along with my friend who also has directx 12 but his longvinter works. Any other fix?

**Comment by faketucker** [comment]
Reinstall
