### ISSUE TITLE
Houses can be entered from underneath when it is placed at a height

### ISSUE THREAD

**Issue by faketucker** [Uuvana-Studios/longvinter-windows-client#891]
**Describe the bug**
Houses can be entered from under the house when it is placed at a height

**To Reproduce**
1. Place a house at a height
2. Enter the house from underneath

**Expected behavior**
Houses can't be entered from underneath or can't be placed at a height

https://user-images.githubusercontent.com/28383557/169676384-49124e67-e30c-4275-96d8-58aab8703ab3.mp4

**Comment by Jalsson** [comment]
Fixed this issue by preventing houses from being placed on top of placeables. The fix will take effect in update 1.0.9c.
