### ISSUE TITLE
Double-click to deposit materials into the house, you will lose the materials and they will not be deposited

### ISSUE THREAD

**Issue by faketucker** [Uuvana-Studios/longvinter-windows-client#892]
**Describe the bug**
Double-click to deposit materials into the house, you will lose the materials and they will not be deposited

**To Reproduce**
1. Double-click to deposit materials into the house
(more likely to happen when you are on high ping)

**Expected behavior**
Not lose the materials

**Comment by Mikooboy** [comment]
Should be fixed in the next update
