### ISSUE TITLE
turret installation bug

### ISSUE THREAD

**Issue by leejunwon0207** [Uuvana-Studios/longvinter-windows-client#893]
![Longvinter Screenshot 2022 05 22 - 19 04 04 41](https://user-images.githubusercontent.com/69827603/169690215-a910a069-b221-47b6-a05e-28c71b2c6a29.png)

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. Next time, please use the appropriate template that we provided.
