### ISSUE TITLE
Unable to collect items with LMB or Space button

### ISSUE THREAD

**Issue by MrHoTdOg99** [Uuvana-Studios/longvinter-windows-client#894]
**Describe the bug**
When walking over items such as plants I am unable to collect anything when I click my left mouse button or my space button, however I am able to fish with an equipped fishing rod.
I'm using the Steam 1.0.6 version

**Comment by evgaming88** [comment]
Is there a specific action that caused this, or a process to re create it? For me both options work

**Comment by faketucker** [comment]
Not enough info.
