### ISSUE TITLE
Was There a wipe? Also logged into blackness.

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#895]
**Describe the bug**
Logging in took longer than usual. then when I did log in to what should have been my house, I could only see my character and moved around like I was in my house. I have logged in and out multiple times. I see parts of houses when logging in but once logged in there are no houses and my houses are gone. I can't tell if this is supposed to be a wipe or not because my backpack is still filled with the stuff I had previously in it.

**To Reproduce**
1. Go to I'm on Uuvana 2

**Expected behavior**
Game should appear as normal but housing is missing but still have things in my backpack from previously when I logged in my house. Also first log into total blackness.

**Screenshots**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/29164981/169831110-2a77c70e-829e-4785-9a7c-4ae8832d2409.png">

**Desktop (please complete the following information):**
 - OS: Win 11
 - Game Version 1.0.6
 - Steam Version 1.0.6

**Additional context**
I didn't think the wipe was for another 2 weeks.

**Comment by faketucker** [comment]
The servers have used up all the resources, so it's kinda lag. We will try to fix that problem with the next wipe on June 17, 2022
