### ISSUE TITLE
Loading into server takes too long and laggy!

### ISSUE THREAD

**Issue by Demon-Boi** [Uuvana-Studios/longvinter-windows-client#896]
**Describe the bug**
I took very long to load into [SEA] Uuvana 1

**To Reproduce**
1. Go to [SEA] Uuvana 1

**Expected behavior**
Start up normally without lags.

**Screenshots**
![pic1](https://user-images.githubusercontent.com/106092342/169841603-20ceb7a3-4b06-4794-ac26-428735a5a0a2.png)
![pic2](https://user-images.githubusercontent.com/106092342/169841984-54790307-8acf-447c-ad4a-0716363fbff3.png)

**Desktop (please complete the following information):**
- OS: Win 11
- Game Version 1.0.6
- Steam Version 1.0.6

**Comment by faketucker** [comment]
The servers have used up all the resources, so it's kinda lag. We will try to fix that problem with the next wipe on June 17, 2022
