### ISSUE TITLE
Dx11 water toggle isn’t working

### ISSUE THREAD

**Issue by Bellatrix8377** [Uuvana-Studios/longvinter-windows-client#9]
**Describe the bug**
When I click to toggle the dx11 water it doesn’t work; I’ve tried in game, in the main menu and even restarting the game

**To Reproduce**
1. Press esc and options

**Expected behaviour**
The water to appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.0
 - Steam Version unknown

**Comment by sirNugg3ts** [comment]
Hotfix corrects the issue with switching DX11 and DX 12
