### ISSUE TITLE
Water isn't displayed

### ISSUE THREAD

**Issue by sufrd** [Uuvana-Studios/longvinter-windows-client#901]
The water (sea, lake...) doesn't appear, it is just white so players can't see rocks and can't fish at all.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Try to toggle DX11 water in the settings. If it doesn’t work, try what the issue #13 said
