### ISSUE TITLE
 Tent decay process not working

### ISSUE THREAD

**Issue by Neidn** [Uuvana-Studios/longvinter-windows-client#903]
**Describe the bug**

Hello, I'm playing on [KR]Uvana1 server. 

I said, "Decay is not working in KR server. Isn't this a bug?", "All tent marking times are marked as 12h0min. Is this normal?".

I contacted 'Question and help' but did not get any answer from community helpers.

When I go to the [US-West] server, the tent marking time was being activated on other servers.

In [KR] server, Decay does not work the decay process. abandoned houses are left unattended.

I haven't checked all the houses, but I'm sure there's a problem with the 'Decay process' function. Please check all [KR] servers once. 

Thank you.

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.6

**Comment by vkeldh** [comment]
I'm same issue and bug

**Comment by faketucker** [comment]
Decay works fine now.
