### ISSUE TITLE
Hairstyles are buggy while fishing

### ISSUE THREAD

**Issue by libkuza** [Uuvana-Studios/longvinter-windows-client#904]
For some hairstyles the head is looking through the hairs/caps when you fishing.

1. equip any of the new hairstyles
2. start fishing and watch head

Expected behavior
the head should not look through the hairs at any moment

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version 1.0.7 experimental

![longvinter2](https://user-images.githubusercontent.com/76413915/170869435-256559a4-37a0-46d8-b9d4-fe375a41ec1a.png)

**Comment by faketucker** [comment]
Fixed
