### ISSUE TITLE
After Character Customize you can not use Tools, Wepons and other things.

### ISSUE THREAD

**Issue by Dantwire** [Uuvana-Studios/longvinter-windows-client#907]
**Describe the bug**
After Character Customize i can not use Tools, Weapons and other things.

**To Reproduce**
1. Customize your Character
2. Join a Server
3. Try to equip a weapon or something

**Comment by faketucker** [comment]
I tried it and it worked fine. Can you provide us with a video?

**Comment by faketucker** [comment]
I'll close this issue since there's not enough info.
