### ISSUE TITLE
after update 1.0.7 don't enter to my house (EU-WEST Uuvana 1)

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#909]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

https://user-images.githubusercontent.com/69962198/171876868-f33e39c5-fff9-41c3-9039-d409a538bad0.mp4

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Is your house filled with much stuff?

**Comment by faketucker** [comment]
I'll close this issue since there's not enough info.
