### ISSUE TITLE
Player get kicked when Dropping Items

### ISSUE THREAD

**Issue by ZeroOneVBS** [Uuvana-Studios/longvinter-windows-client#91]
**Describe the bug**
Players get Kicked off my Server when they are dropping Items from the Inventory

**To Reproduce**
1. Connect to Server
2. Open Inventory
3. Drop an Item

**Expected behavior**
That the Items get dropped in bags

**Desktop (please complete the following information):**
 - OS: Windows | Server OS: Linux Ubuntu 20.04
 - Game Version Beta 1.0.0
 - Steam Version Latest

**Comment by sirNugg3ts** [comment]
Is this on an official server?

**Comment by ZeroOneVBS** [comment]
Nope, it is Hosted by myself. I want to play with Friends, everything worked, after a restart the bug came

**Comment by JustDalek** [comment]
I had this issue too, have you updated your server? 

That fixed my issue #95

**Comment by sirNugg3ts** [comment]
Update the server and the bug will be fixed
