### ISSUE TITLE
Hair Customization Not Loading

### ISSUE THREAD

**Issue by bexcam** [Uuvana-Studios/longvinter-windows-client#911]
EAST-US Uuvana 5 custom hair is not loading, i also keep rubber banding. when i exit server my original shirt color before update shows and hair is glitched and then few seconds later im back to brown beanie but customized shirt color and backpack comes back. 
Example: 1.0.6 - load in shirt color, Red w/ default beanie. 1.0.7 - I customized my character with new hair, blue shirt, and changed bag color.
the issue is when i load in im red again BUT i have my new hair, then 2 seconds later i load into my blue shirt and new bag BUT im back into default beanie/brown beanie.
This issue has only been happening on (EAST-US) Uuvana 5 server. I've tested all the other NA official servers and have not experienced any custom character issues.
The only time ive been able to get it to work is if i get bugged back into loading to a boat dock OR ive tested if i empty my bag inventory and connect back into server, custom hair finally loads.
Update!!: i found out i have to /Kill in order for hair to work :(

![7bc28e88-fbb3-4d32-ab70-103a4117f4d4](https://user-images.githubusercontent.com/106779081/171934777-505aa923-8459-40e9-a2b9-1c67c7655ad0.png)
![23de0247-5eeb-4cce-816b-98f27384a0c4](https://user-images.githubusercontent.com/106779081/171935592-5d031168-b865-41df-9f9f-dea3499b758c.png)

**Comment by faketucker** [comment]
This might have happened due to the server lag
