### ISSUE TITLE
House upgrade/decay menu not working

### ISSUE THREAD

**Issue by Hilolen** [Uuvana-Studios/longvinter-windows-client#912]
**Describe the bug**
When I click on the workbench, the upgrades and decay are not available. This is only happening in one of my homes.
I am in [US-EAST] Uuvana 6

**To Reproduce**
1. Go to 'workbench'
2. Click on 'workbench'
3. See an error

**Expected behavior**
It is expected to see home upgrade options, as well as a place to deposit wood to avoid home decay. 

**Screenshots**

![Upgrade fail](https://user-images.githubusercontent.com/97799466/171938082-3d24046f-387d-4e25-806a-5df413ddae34.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version 1.0.7
 - Steam Version- Latest version

**Comment by faketucker** [comment]
Have you tried to relog?

**Comment by faketucker** [comment]
I'll close this issue since there's not enough info.
