### ISSUE TITLE
Customized hair not carrying into game

### ISSUE THREAD

**Issue by MJR1972** [Uuvana-Studios/longvinter-windows-client#913]
**Describe the bug**
I've set up my customized character and looks like the hair settings are not carrying into the game

**To Reproduce**
1. Customize your character and change your hair
2. Log into game hair is shown as the default hat

**Expected behavior**
My customized hair should be displayed

**Screenshots**
In game
<img width="138" alt="image" src="https://user-images.githubusercontent.com/29164981/172030999-bd8e5da1-f3ce-41dd-b0c0-ba33cb891a9a.png">

My selected hair
<img width="631" alt="image" src="https://user-images.githubusercontent.com/29164981/172031012-4fd8351a-3e5a-494f-8094-adf86b694fe6.png">

**Desktop (please complete the following information):**
 - OS: win 11
 - Game Version 1.0.7
 - Steam Version 1.0.7

**Additional context**
When this first came out it was working great but suddenly stopped.

**Comment by cheerp** [comment]
Same, latest 1.0.7 patch. other customizations work - Hair is not used, stays the standard cap or whatever hat is used at the moment

**Comment by faketucker** [comment]
I've tested it and it worked fine. This might happen due to server lag. Try to relog or restart the game and test it on the server with low ping
