### ISSUE TITLE
Items disappearing or being stolen

### ISSUE THREAD

**Issue by zigglesbee** [Uuvana-Studios/longvinter-windows-client#915]
I am in the [US-EAST] Uuvana 4 server and certain items are disappearing (solar lights, generator, etc) despite having a fence and code lock. Is there a way players can steal these items that I am unaware of? Fence and code gate are intact. So I do not know how others can get to these items or if they are despawning. Please advise.

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
People can break your stuff with a chainsaw or gun. That's why we have turrets in the game to protect your stuff.

**Comment by zigglesbee** [comment]
Nothing was broken when this happened, just things missing. I logged in today and my teammates turrets are hitting me, and things from inside my house are missing as well as my teammates.
