### ISSUE TITLE
Trading Vendor.my friends bought item from my shop but item is still there and i don't get any money

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#916]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Should be fixed in the latest update
