### ISSUE TITLE
Cannot pick up garden fire pit

### ISSUE THREAD

**Issue by cheerp** [Uuvana-Studios/longvinter-windows-client#918]
After the last emergency patch (second 1.0.7), a placed garden fire pit cannot be taken up again. A normal item like bush can be packed/picked up.
Right-clicking on the pit does nothing. Left-click/space brings up the cooking menu as expected.

**To Reproduce**
1. Go to some free space, place a garden fire pit.
2. left-click or space: brings up the expected cooking dialog
3. right-click (with a non-aiming tool in hand, like the fishing rod) does nothing!

**Expected behavior**
Right-click (without having an aiming tool in hand) should break the item, i.e. place it in a bag on the ground.
Like it does with any other item.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 
 - Game Version 1.0.7 w/ emergency patch

**Additional context**
n/a

**Comment by faketucker** [comment]
Tested

**Comment by Jalsson** [comment]
Fixed in next update
