### ISSUE TITLE
Milky Ocean

### ISSUE THREAD

**Issue by Alannahrose** [Uuvana-Studios/longvinter-windows-client#919]
**Describe the bug**

The Ocean is completely white.

**To Reproduce**
4. See an error

i dont know how to reproduce it. I am currently on us west uuvana 2.

**Expected behavior**

I expected a blue ocean but i got a white one.. probably a broken texture?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g. 1.0] Beta 1.0.7
 - Steam Version [e.g. 1.0] i dont know this..

**Additional context**
![water glitch](https://user-images.githubusercontent.com/26313031/172200401-34d0a51d-9e7b-452c-8ed0-f6358bd1c609.png)

**Comment by faketucker** [comment]
Try to toggle DX11 water in the settings. If it doesn’t work, try what the issue #13 said
