### ISSUE TITLE
Wood for Tent Upgrade disappears 

### ISSUE THREAD

**Issue by Bunnbunnnn** [Uuvana-Studios/longvinter-windows-client#92]
**Describe the bug**
Wood put into the craftbench disappears. For instance, I had 30 logs in the bench then left the house to go get more. I came back and it was at 0 again. I added more logs and it didnt happen again and I was able to upgrade. 

**To Reproduce**
1. Put logs in craft bench
2. Leave house 
3. Come back and check logs 
4. Logs might be gone

**Expected behavior**
To not have logs be disappearing from the total I need to upgrade.  

**Screenshots**
No screenies needed 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] WIndows 
 - Game Version [e.g. 1.0] 1.0
 - Steam Version [e.g. 1.0]1.0

**Additional context**
This happened to me when logs were at 60 total to upgrade, but now they take 200 - but someone again mentioned in discord it just happened to them so its still happening.

**Comment by Xogot** [comment]
Happened to me as well but after disconnecting and reconnecting to the server

**Comment by JackDic** [comment]
This has also happened to me after re-launching the game. Very unfortunate to lose lots of wood which is slow to grind.

**Comment by sirNugg3ts** [comment]
Just tested this and it does happen

**Comment by aiiabon** [comment]
this happened to me yesterday too

**Comment by Jalsson** [comment]
Wood is now saved to the workbench value and this should no longer happen
