### ISSUE TITLE
집에서 튕겨서 나와요 집에 들어 갈 수 없는 문제

### ISSUE THREAD

**Issue by longvinteric** [Uuvana-Studios/longvinter-windows-client#922]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
