### ISSUE TITLE
Stuck in game when using /noclip under the house

### ISSUE THREAD

**Issue by MineMy** [Uuvana-Studios/longvinter-windows-client#924]
**Describe the bug**
There is an error where the game freezes when player go to the floor of the house using the `/noclip` command inside the house.
Shows a blank screen for about 5 seconds and then shows players in the house for 0.5 seconds.
None of the actions, including the Escape key, will work on a blank screen, and will only work for a short time if you're showing a player in the house.
However, the player is unable to leave the house, and is stuck in the house.
Reconnecting the server does not solve this problem. Currently the best workaround is the `Alt` + `K` key combo. This is a command to kill themselves, and when player die, player will be moved to player's home or island.

**To Reproduce**
1. Go to any house and get in... or use /noclip and move under the ground.
2. Use /noclip in house.
3. Goto under the house. More deeper and deeper...
4. See an error

**Expected behavior**
Game is freezing.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version 1.0.7
 - Steam Version -

**Comment by faketucker** [comment]
Yeah, that happens. For now, Alt + K can help you unstuck.

**Comment by Mikooboy** [comment]
Adjusted Kill Z so this should not happen in the next update
