### ISSUE TITLE
like

### ISSUE THREAD

**Issue by shinddochi** [Uuvana-Studios/longvinter-windows-client#925]
good

**Comment by shinddochi** [comment]
모든서버가 안들어가지고
지웠다 깔아도 똑같은 현상입니다
서버를 클릭하면 메인화면으로 돌아옵니다

**Comment by bluemusicbox** [comment]
당신은 한국인 입니까?

오 대박

**Comment by faketucker** [comment]
Don't post stuff that is not related to bugs.
