### ISSUE TITLE
[JAPAN] Uuvana 1 server not working

### ISSUE THREAD

**Issue by toozuuu** [Uuvana-Studios/longvinter-windows-client#928]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
This happened due to an EOS services problem and should be solved by now.
