### ISSUE TITLE
Infinite loading softlock

### ISSUE THREAD

**Issue by LogicologistDev** [Uuvana-Studios/longvinter-windows-client#93]
**Describe the bug**
When loading in underground, for some reason I was spawned in a void where i saw floating structures, and also an area with a small tent in a box. By walking into the box, it effectively softlocks the game and cannot be quit without forcequitting, and you cannot die.

**To Reproduce**
1. Load into the game underground
2. Before loading in completely, start moving your character to an underground box with a tent
3. Walk into area
4. Log out
5. Log in

**Expected behavior**
My game shouldn't softlock, or be able to not reset my character.

**Screenshots**
![image](https://user-images.githubusercontent.com/35440116/156050370-807223c9-c11b-4134-91d6-df7525ff6e0a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: Beta 1.0.0
 - Steam Version: [e.g. 1.0] Latest as of 2/28/2020 (unsure where to find)

**Additional context**
I'm not sure what initially caused me to load in a void in the first place.

**Comment by Jalsson** [comment]
I cannot reproduce this issue. But if you happened to find yourself again in the loading screen you can use alt + k keybinding to commit suicide in the game without opening chat. This seems to work even if the loading screen is on.
