### ISSUE TITLE
I cannot move

### ISSUE THREAD

**Issue by gabbyylouise** [Uuvana-Studios/longvinter-windows-client#932]
**Describe the bug**
Whenever I move, I can't seem to go to where I want to go clearly. For example, I was trying to get off the dock and when I was moving UPWARDS, I was dragged into the ocean like I was moving right, but I wasn't pressing "D", I was pressing "W". I have no controllers or computer mice.

**To Reproduce**
Play on any USA server on a keyboard (ONLY) basically

**Expected behavior**
When I started to play this game, I expected--like many YouTubers who has played this game--that there would be no lag and I could move my character freely.

**Screenshots**
[attachments.zip](https://github.com/Uuvana-Studios/longvinter-windows-client/files/8903749/attachments.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.7
 - Steam Version v020 (I think)

**Additional context**
Why is the water not blue and I cannot see any fish??

**Comment by faketucker** [comment]
Your laptop's specifications may not meet the game's minimum requirements. Lowering things down in the settings might help you with the game lag. Also check your keybindings in the settings to see if every key is set properly.

For the water, try toggle DX11 in the settings.
