### ISSUE TITLE
issue on Uuvanna 3 US

### ISSUE THREAD

**Issue by QueenPookins** [Uuvana-Studios/longvinter-windows-client#935]
Uuvanna 3 US is crashing. it wont load my base. it crashed on me and wouldn't load the game right. than after restarting and having to exit the game 5 times it finally let me. no updates, i checked. I  made a video of the issue. it wont load my base inside and outside. Doesnt load customized character. Been well over an hour and still wont load the server right

**Comment by faketucker** [comment]
There was some problem with our servers that was making them lag. We have migrated our servers to the new operating system with the wipe today, so this should be fixed.
