### ISSUE TITLE
Uuvanna 2 multiple issues.

### ISSUE THREAD

**Issue by homicidalsenpai** [Uuvana-Studios/longvinter-windows-client#938]
**Describe the bug**
Houses and items are not loading in and when they do they are unusable. my house when it finally loads is now empty. I am constantly being rubber banded back into random spots. repeatedly getting trapped in one of the loot depo areas as the interact button is now only working half the time,

**To Reproduce**
log in attempt to walk around/interact with interactables 

**Expected behavior**
items and objects to spawn in and buttons to be responsive.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 1.0.7
 - Steam package Version 1654574690

**Additional context**
a friend and i were playing on stream when this issue started, we had just finished their house and i was cutting down a tree. the tree had dropped like 30 wood and then the game freaked out.

**Comment by faketucker** [comment]
There was some problem with our servers that was making them lag. We have migrated our servers to the new operating system with the wipe today, so this should be fixed.
