### ISSUE TITLE
Black Lotus Texture Error

### ISSUE THREAD

**Issue by ThatRagingKid7** [Uuvana-Studios/longvinter-windows-client#945]
![image](https://user-images.githubusercontent.com/107796286/174581702-359b39c4-ccc8-4de8-bb27-d4dcc80ffa61.png)

Black lotus seeds have different textures on crafting book

game version 1.0.7b

**Comment by ducbenho** [comment]
Yeah that's of cloudberries. The icon is wrong in game too.

**Comment by Jalsson** [comment]
Current build shows the correct icon so closing this issue
