### ISSUE TITLE
The problem has been solved. I don't know how to delete a post

### ISSUE THREAD

**Issue by shinddochi** [Uuvana-Studios/longvinter-windows-client#949]
The problem has been solved. I don't know how to delete a post

**Comment by shinddochi** [comment]
> He built two houses on Urbana, two-seob Fix Island We removed the items from the same house
> I got rid of one
> but
> 
> All the items from the other house have disappeared. I lost all the items in the house because of the bug Please check.

**Comment by MineMy** [comment]
If you do not need more support, please click the `Close issue` button below.

![image](https://user-images.githubusercontent.com/26472792/174978543-3d035d66-ca19-4873-95bf-15ad7555db40.png)
