### ISSUE TITLE
Server not visible

### ISSUE THREAD

**Issue by jomsgseo** [Uuvana-Studios/longvinter-windows-client#951]
**Describe the bug**
There is a bug that you can't see to your friends even if you open a personal server. What should be done to solve this problem?
**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Game Version [e.g. 1.0] 1.0.7b
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
You will need to open port 7777 from your modem so that other players can join.
