### ISSUE TITLE
loot in water

### ISSUE THREAD

**Issue by GTony12** [Uuvana-Studios/longvinter-windows-client#952]
**Describe the bug**
When your swimming and you die or get shot while in water all your loot drops in the water, when you go to pick it up you can't.
**To Reproduce**
4. See an error

**Expected behavior**
When you die in water you can see your loot bur cant grab it?
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Duplicate of #450
