### ISSUE TITLE
내가 플레이하던 서버가  사라졌어요!

### ISSUE THREAD

**Issue by ArcticSamoyed** [Uuvana-Studios/longvinter-windows-client#953]
[TH]서버에서 플레이 중이였는데, 자고 일어나 보니 내가 플레이하던 서버가 갑자기 사라졌어요!
엄청 공들이며 집을 지었는데.. 갑자기 사라지다니!
서버 돌려줘요!!!

**Comment by MineMy** [comment]
Korean is not allowed.
여기서 한국어를 사용할 수 없습니다. 전 세계 사람들이 이용하는 창구인 만큼 영어를 사용해 주세요.

== Original Messages ==
[TH]서버에서 플레이 중이였는데, 자고 일어나 보니 내가 플레이하던 서버가 갑자기 사라졌어요!
엄청 공들이며 집을 지었는데.. 갑자기 사라지다니!
서버 돌려줘요!!!
