### ISSUE TITLE
Bug is when using the chainsaw, it damages me and kills me. I got a new chainsaw and it happened over and over.

### ISSUE THREAD

**Issue by annoyed12** [Uuvana-Studios/longvinter-windows-client#956]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by annoyed12** [comment]
Found out i was too close to a tower. please have a warning pop up explaining why you are dying.

**Comment by faketucker** [comment]
There is a sound that indicates turrets are shooting at you, as well as a tip in the loading screen to avoid pulling out weapons in safe zones.
