### ISSUE TITLE
Fuel Powered houses are not consuming any fuel at all

### ISSUE THREAD

**Issue by ducbenho** [Uuvana-Studios/longvinter-windows-client#959]
**Describe the bug**
Fuel Powered houses are not consuming any fuel at all, at least on US Uuvana 6.

**To Reproduce**
1. Build a fuel powered house
2. Deposit some fuel
3. Check back after a few hours
4. The "Time left" remains the same.

**Expected behavior**
Fuel Powered houses should consume fuel or they will be too OP.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version: 1.0.7b

**Comment by Jalsson** [comment]
This issue has been resolved so closing this issue
