### ISSUE TITLE
Anticheat

### ISSUE THREAD

**Issue by ovm** [Uuvana-Studios/longvinter-windows-client#96]
**Is your feature request related to a problem? Please describe.**
Seeing more and more cheaters

**Describe the solution you'd like**
Add a crude anticheat asap even if it just blocks things such as cheat engine since it seems like most of them are just using CE speed hack

**Additional context**
Example
https://streamable.com/41e48f
https://i.imgur.com/OpKXmUn.jpeg (everything seems clientside?)

**Comment by Bunnbunnnn** [comment]
Already being worked on by dev team, documented on forum as 
Anti cheat
