### ISSUE TITLE
KR Uuvana1 sever is gone

### ISSUE THREAD

**Issue by five535** [Uuvana-Studios/longvinter-windows-client#963]
**Describe the bug**
The KR Uuvana1 server is gone

**To Reproduce**
We can't find the KR Uuvana1 server

**Expected behavior**
Not only me but also Koreans can't find the KR Uuvana1 server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.7b

**Comment by faketucker** [comment]
Should be back now
