### ISSUE TITLE
I found a duplicate bug by chance

### ISSUE THREAD

**Issue by MathAttack4** [Uuvana-Studios/longvinter-windows-client#966]
**Describe the bug**
I had a generator placed outside, I took it in right click on it and picking it up with space and when I entered my house I had in my inventory 2 generator. (I don't know if I had the 2 generators in my inventory before going into my house)

**To Reproduce**
1. right click on the generator
2. click space to have it in the inventory
3. enter in your house or open your inventory
4. See the 2 generators

**Expected behavior**
I expected to have only one generator in my inventory

**Screenshots**
![Longvinter Screenshot 2022 06 27 - 22 34 10 57](https://user-images.githubusercontent.com/108268430/176031889-187fca55-3035-4476-858b-fe080c567123.png)

**Desktop (please complete the following information):**
 - OS: window 10
 - Game Version 1.0.7b
 - Steam Version 1.0.7

**Additional context**
I don't know where the problem may come from

**Comment by faketucker** [comment]
There might be two generators when you first placed it due to high ping, just like in this video.

https://user-images.githubusercontent.com/28383557/176092133-6c446396-c033-4889-acb1-6b98a3c28563.mp4

**Comment by Jalsson** [comment]
This issue should be resolved by making sure the item only spawns one bag after dismantling. Closing this one because no duplicates are founded in a while
