### ISSUE TITLE
is:issue is:open What happened to the South America server? 

### ISSUE THREAD

**Issue by lkzbrandao** [Uuvana-Studios/longvinter-windows-client#967]
**Describe the bug**
- Items inside the house disappearing, door code problem to open and home screen stuck.
- The house was completely fenced in, now some fences are gone
- When I click on objects, I don't collect them in my backpack
- Objects dropped on the ground, cannot be picked up later
- Character making long jumps to other random places on the map
- When trying to enter the house it returns to the main game menu

**To Reproduce**
- Just open the server South America

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.7b
 - Steam Version 2.10.91.91

**Additional context**
The server is a complete mess (I'm sad to be the only one in South America) and even for Brazil. In a single game day I met at least 10 different Brazilians in the game.

**Comment by BrunoCMenna** [comment]
yea the server is unplayable right now

hope they can fix it!

**Comment by faketucker** [comment]
There were some issues with the server. Should be fine now
