### ISSUE TITLE
Some of the Servers not showing ping in the servers list menu.

### ISSUE THREAD

**Issue by MUmairKhan42900** [Uuvana-Studios/longvinter-windows-client#968]
**Describe the bug**
BUG: Some of the Servers not showing ping in the servers list menu. Some of them are showing the realtime ping but some of them aren't showing up. They're showing Ping: Not available.

**To Reproduce**
1. Go to 'Servers list menu'
2. Click on 'info about server (3 dots with the server name)'
3. See an error

**Expected behavior**
Show the real-time ping

**Screenshots**
![image](https://user-images.githubusercontent.com/97685228/176225806-7711ce03-9b0f-494d-9e5c-718e004f28be.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Game Version [1.0.7b]
 - Steam Version [lastest, upto date (june 6 2022)]

**Additional context**
None

**Suggestion**
Please add an option to show real-time ping on the top right corner while playing the game too, not only in the menu option. we will be able to see and monitor our realtime ping and packet loss :)

**Comment by faketucker** [comment]
Those servers are not using the default port. That's why ping is not available. If you want to make suggestions, you can do that on our [Discord](discord.gg/longvinter)!
