### ISSUE TITLE
My item disappears intermittently in the bag

### ISSUE THREAD

**Issue by kimjeend** [Uuvana-Studios/longvinter-windows-client#971]
**Describe the bug**

**Expected behavior**
(Bangkok server) It goes in and out of the tent, picks up items, and intermittently loses my items in the bag

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
