### ISSUE TITLE
Disappearing Bench 

### ISSUE THREAD

**Issue by Niftyyy** [Uuvana-Studios/longvinter-windows-client#973]
Disappearing Bench 

So, I have gotten 2 benches in my playthrough. Both of which have disappeared within 10 minutes of purchase and place. They are gone and I no longer have them in any container or inventory. Neither do any of my party members. This happened directly after using the bench one time. 

![image](https://user-images.githubusercontent.com/108381575/176341699-4741e45f-0f39-4949-86a4-c459fa758348.png)

I have lost over 6,000$ paying for both benches. I no longer have a bench. 

Thanks for reading.

**Comment by faketucker** [comment]
Where do you place the benches? If they are outside your house, they can be chainsawed and stolen.

**Comment by faketucker** [comment]
I'll close this issue since you did not provide us with more info.
