### ISSUE TITLE
[US-WEST] Uuvana 1 is a buggy mess.

### ISSUE THREAD

**Issue by Dlphs** [Uuvana-Studios/longvinter-windows-client#974]
**Describe the bug**
All assets load in way too late, to the point that you could be walking and a house with a fence loads onto you and you become stuck. You can even harvest other's gated and protected plants because their fences don't load in for awhile. On top of this there is frequent rubber banding. This happens even with a low ping, my ping is 19 and the issue persists.

**To Reproduce**
1. Go to server browser
2. Click on [US-WEST] Uuvana 1
3. Realize that the asset loading times are absurdly high, to the point that the game is not playable.
4. Leave

**Expected behavior**
Assets load into the world before you see them. 

**Screenshots**
Upon initial arrival of this random base (I am able to enter and harvest):
![image](https://user-images.githubusercontent.com/108439168/176566743-87119411-7dfa-45c5-a13b-7b16d3155d16.png)

After 1 minute of waiting without moving:
![image](https://user-images.githubusercontent.com/108439168/176566891-5e61b2e0-9312-4b1c-a2fc-b9ddd273cc33.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.07b
 - Steam Version (most recent of July 29th, 2022)

**Comment by faketucker** [comment]
Can you try it now? It should be better now.

**Comment by Dlphs** [comment]
yes the situation has been improved. 👍
