### ISSUE TITLE
Intense Lag

### ISSUE THREAD

**Issue by KittyCatJack** [Uuvana-Studios/longvinter-windows-client#975]
cannot pick up any items such as; berries, flowers, loot bags, feathers, acorns, wheat, etc. Very slow loading player made houses and fencing. Very harsh lag when in a group.

**Comment by faketucker** [comment]
Seems to be a server problem. Can I know which server you are encountering this problem on?

**Comment by faketucker** [comment]
I'll close this issue since there's no info.
