### ISSUE TITLE
longvinter mk bug

### ISSUE THREAD

**Issue by wjstngud** [Uuvana-Studios/longvinter-windows-client#977]
**Describe the bug**

Today July 1st at 6pm
be updated
about 10 minutes passed
I went to Daon 2. However, the spawn location is different from where it was before.
It changed and I had 150,000 mk of money, but it was updated and the goods I had and 100,000 mk were
disappeared.
about this bug
Please restore it again.

 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Lost progression can be caused by the update, and there's nothing we can do to bring your progress back
