### ISSUE TITLE
Invisible gas stove and cabinets turned into containers

### ISSUE THREAD

**Issue by W00denino** [Uuvana-Studios/longvinter-windows-client#978]
After 1.0.8 update, the newly implemented gas stove turned invisible after some minutes, it's still there but you can't see it. Then, after the last fix after 1.0.8, the newly implemented cabinets turned into containers and look bugged as well, but at least I kept all the items I had inside.
![Screenshot (424)](https://user-images.githubusercontent.com/108533243/176906125-19d7e18f-29f9-4695-a57c-6e5f8d207960.png)

**Comment by faketucker** [comment]
Fixed
