### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CarloLongo2** [Uuvana-Studios/longvinter-windows-client#979]
the game has bug, I can no longer find my part I am obliged to recompense another one, those bug is arrive just after the update, how to find his part, the update has made crach all the games. please give me back my part.

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
