### ISSUE TITLE
Fishing Hat cannot be seen while equipped

### ISSUE THREAD

**Issue by Harnar** [Uuvana-Studios/longvinter-windows-client#98]
**Describe the bug**
While trying to wear the fishing hat, it cannot be seen. Still get the fishing buff while wearing it though.

**To Reproduce**
1. Equip fishing hat
2. See no Fishing hat on character while wearing it.

**Expected behavior**
I expect to see my fishing hat.

**Screenshots**
![20220228172452_1](https://user-images.githubusercontent.com/100540730/156068728-ff3b78c2-3f11-4e23-9435-fa0cddda3a91.jpg)

**Comment by sirNugg3ts** [comment]
Is this stil happening?

**Comment by Harnar** [comment]
haven't had it happen since the fix
