### ISSUE TITLE
The houses are disappeared

### ISSUE THREAD

**Issue by ditothe** [Uuvana-Studios/longvinter-windows-client#980]
**Describe the bug**
The houses are disappeared itself even the woods are fully set.
+ my whole team's house

**To Reproduce**
1. Go to 'DAON kr-server'
2. Click on 'Filmon's ourpost'
3. You can see small floating flowerpot
4. Thats where my team's houses were.

**Expected behavior**
If thats possible, I want every houses back with every items in it. NOTHING lost.

**Screenshots**
BEFORE
![BEFORE](https://user-images.githubusercontent.com/108541349/176935965-f6e34ad7-394e-4c6b-aea8-0674791f4966.png)

AFTER
![AFTER](https://user-images.githubusercontent.com/108541349/176935204-9e4b0dbc-be07-4657-915a-a1ebd2d25885.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: BETA 1.0.8
 - Steam Version: Recent Released Version

**Additional context**
Please try your best to fix it, 'cause my teams are so much fraustrating rn.
+ Thank you for your effort.

**Comment by faketucker** [comment]
_Answered in the ticket_
