### ISSUE TITLE
I CAN'T ENTER MY OWN HOUSE LOL.... THAT BUG WHEN U ENTER U GET KICKED OUT ASAP

### ISSUE THREAD

**Issue by huntergc** [Uuvana-Studios/longvinter-windows-client#981]
I CAN'T ENTER MY OWN HOUSE
WHEN I'M GOING IN WILL BE FAST TO KICKED OUTSIDE

**Comment by faketucker** [comment]
Is there anything inside that blocks your doorway?

**Comment by huntergc** [comment]
No, im in my house and only loading and still outsite

Pada tanggal Sab, 2 Jul 2022 12.01, tucker ***@***.***>
menulis:

**Comment by faketucker** [comment]
Duplicate of #943
