### ISSUE TITLE
The house says its not mine. I can not place any items like fences and have to enter the code to get into the house.

### ISSUE THREAD

**Issue by grimmy707** [Uuvana-Studios/longvinter-windows-client#983]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Try to relog

**Comment by grimmy707** [comment]
after a few relogs the problem was fixed..
