### ISSUE TITLE
Unable to join servers of the same network.

### ISSUE THREAD

**Issue by FatalPickle** [Uuvana-Studios/longvinter-windows-client#988]
**Describe the bug**
When joining any server or more importantly, any server on the same network, will produce an infinite loading screen. 

**To Reproduce**
1. Go to unofficial
2. Click on any server
3. Load into server
4. Infinite loading screen

**Expected behavior**
To Load into a server and play with my mom.

**Desktop:**
 - OS: Microsoft Windows 11 Home
 - Game Version 1.0.8.

**Comment by faketucker** [comment]
In LAN, you have to use the direct connect tab and use the local IP. Server browser will not work
