### ISSUE TITLE
World edges

### ISSUE THREAD

**Issue by JustDalek** [Uuvana-Studios/longvinter-windows-client#99]
**Is your feature request related to a problem? Please describe.**
I like to explore and find new land, but sometimes its hard to tell if another island exists after a certain point. I swim and swim, eventually risking death without knowing if ill find land or hit an edge

**Describe the solution you'd like**
Some kind of clear indication of when you are swimming away aimlessly. Maybe an invisible region that triggers a banner that says turn around or the water turns a certain color?

**Describe alternatives you've considered**
An alternative would be a world map, which would allow us to "discover" the landscape maybe

**Comment by Bunnbunnnn** [comment]
Documented on forum
