### ISSUE TITLE
Eject other players while fishing

### ISSUE THREAD

**Issue by o-super** [Uuvana-Studios/longvinter-windows-client#990]
**Describe the bug**
Deploying fishing rode behind another player ejects him on local.

**To Reproduce**
1. Position yourself to have another player between you and a fishing spot
2. Deploy fishing rode
3. The other player is ejected out of your screen

**Expected behavior**
The other player should not collide with your fishing rode.

**Screenshots**
![image](https://user-images.githubusercontent.com/16004081/177018129-c5894a10-c063-41a2-9394-beee6e405e22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 1.0.8

**Additional context**
Only eject the other player on local, it does not affect the server side.
The other player will have his position corrected as soon as he moves.

**Comment by faketucker** [comment]
Somehow, the fishing rod still has a collision

**Comment by Mikooboy** [comment]
Telescopic reel can no longer be used to launch people to space in the next update
