### ISSUE TITLE
after death, the money disappeared

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#991]
after death, the money disappeared and I was thrown out of the team
another team member has me in the team list and shows the original amount of money
![s1](https://user-images.githubusercontent.com/69962198/177023153-1a2aa73b-c5f1-4719-89e0-efd4e72c3ef2.png)
![s2](https://user-images.githubusercontent.com/69962198/177023157-558f85af-0f41-425a-856b-92d1a6719553.png)

**Comment by dimancorporation** [comment]
And all achievements disappeared
![s3](https://user-images.githubusercontent.com/69962198/177023263-b00a6d91-ec50-4a91-9fe4-bbdcfae2dee6.png)
![s4](https://user-images.githubusercontent.com/69962198/177023264-e2d32da6-59fc-4803-972b-518f598ef321.png)

**Comment by faketucker** [comment]
Data could be corrupted in some way

**Comment by faketucker** [comment]
Duplicate of #600
