### ISSUE TITLE
Wood appears in the rock

### ISSUE THREAD

**Issue by TheSalts** [Uuvana-Studios/longvinter-windows-client#992]
**Describe the bug**
when cut down tree wood appears in the rock

**To Reproduce**
1. cut tree beside rock

**Screenshots**
![image](https://user-images.githubusercontent.com/76579116/177027572-fa92d24c-48ee-4990-bfec-286b159c849c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version : 1.0.8
 - Steam Version newest version

**Comment by Mikooboy** [comment]
This should be more reliable in the next update
