### ISSUE TITLE
This is too bad About Serverdown Bangkok2!!

### ISSUE THREAD

**Issue by heajung1** [Uuvana-Studios/longvinter-windows-client#993]
I understand the server may crash because it is under development. But! The new box in my house has been replaced 3 times with the old box. I spent a lot of money to buy a new box to set up to make my home beautiful again. Until my money runs out, I spent more than 100k!! I now have over 80 old boxes. No more storage space. please help At least give me some extra money back or give me the original box.

Best Regards

Server Asia : BANGKOK2
Steamname : Kurokun
My Steam EOS 00025f7abbc34c8f84b41bc522519bd2

**Comment by faketucker** [comment]
Lost progression can be caused by the update or the server crash, and we can't bring you anything back.

**Comment by heajung1** [comment]
But this has happened more than 3 times already. If once is enough.

**Comment by heajung1** [comment]
Every time something like this happens, I have to buy something new every time.

**Comment by faketucker** [comment]
The developers are trying to identify the issue with every update to prevent this from happening again. We are aware of the time some of you are devoting to our game, and we appreciate it. And we are, as you should be aware, in EA and Beta. We ask for your understanding and patience while we work on your next favorite game.

**Comment by heajung1** [comment]
I'll try to accept what happened. But the problem that damages players or items It shouldn't happen over and over, it's too bad.

please consider
