### ISSUE TITLE
Hacker!! plz help

### ISSUE THREAD

**Issue by heajung1** [Uuvana-Studios/longvinter-windows-client#996]
in server BANGKOK 2 Autumm zone have 3 hacker with chainsaw.them not die.i shot him more then 300 HP.them not use food or anything but him not die.he can build wall in my home.

**Comment by faketucker** [comment]
This is not a place to report a hacker. If you want to report a hacker please use the ticket system in our [Discord server](https://discord.com/invite/Longvinter). To open one follow the instructions:
1. Go to #☎-contact;
2. React to 👮 which is referent to Bot/Hacker Reporting;
3. Inform which server you were playing on (Official only);
4. Post all images/videos and any information you have on the hacker.

![image](https://user-images.githubusercontent.com/28383557/160378547-be55a138-9827-4c55-8581-b9b2fc2d8509.png#gh-dark-mode-only)
![image](https://user-images.githubusercontent.com/28383557/160378390-fcdc4442-b176-4a5d-9b84-f2566ce5a69e.png#gh-light-mode-only)

Also already answered in the ticket.
