### ISSUE TITLE
furnaces, workbench and fences just disappeared

### ISSUE THREAD

**Issue by Hallerius** [Uuvana-Studios/longvinter-windows-client#998]
i was off for 4 days. Today i joined again and all my fences i placed around my house just disappeared. Going into my house also all my furnaces and my workbench disappeared. everything is fine in my chest, nothing was taken out of my chests, so noone was inside my house rading me

**Comment by faketucker** [comment]
Progress can be lost when there's an update or the server crashes. The devs are trying to prevent it from happening again.
