### ISSUE TITLE
I am stucked between someone's bonfire, there is also a chair with bush. I cant go out and stuck there forever :,)))

### ISSUE THREAD

**Issue by 10809318a** [Uuvana-Studios/longvinter-windows-client#999]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Type /kill inthe chat or use Alt + K
